- .travis.yml
- conda/install.py
- tests/decorators.py
- tests/helpers.py
- tests/test_install.py
- tests/test_pip.py
This is to ready to merge and will not be ready to merge until all of the changes in `conda/install.py` have been undone.  As noted in 77f65c94579b6fe4d567d888958850ffb3b53e8c, the modifications there are to use this as TDD.  I started with a function that simply returned and have slowly been adding everything back in as each test is added to verify some additional functionality.
I'm pushing and opening the PR in case anyone's interested following along.
> Adding tests to conda.install.rm_rf

- conda/misc.py
Ran into an issue where `conda run ls` doesn't work as expected because it's not explicitly in the environment.  Looking through the code's history I'm not sure why `join(binpath, cmd)` was used here, but it works fines without it.
This has been manually tested on OS X and Windows XP using `conda run ls` and `conda run ipconfig`, respectively.
> Fix run environment

- .travis.yml
- appveyor.yml
- bin/_conda-env-missing
- bin/activate
- bin/activate.bat
- bin/deactivate
- bin/deactivate.bat
- setup.py
This provides a backwards compatible method of moving activation over to [conda-env][].  It requires conda-env v1.2.0 to be installed, but once that's installed everything works as it did + the new activation behavior.
[conda-env]: https://github.com/conda/conda-env
> Move activation into conda-env

- conda/install.py
When installing a package on windows with a pre-link script, I was getting TypeErrors thrown.
```
File "C:\moonbot\tools\env\Scripts\conda-script.py", line 4, in <module>
File "C:\moonbot\tools\env\lib\site-packages\conda\cli\main.py", line 202, in main
args_func(args, p)
File "C:\moonbot\tools\env\lib\site-packages\conda\cli\main.py", line 207, in args_func
args.func(args, p)
File "C:\moonbot\tools\env\lib\site-packages\conda\cli\main_install.py", line 46, in execute
install.install(args, parser, 'install')
File "C:\moonbot\tools\env\lib\site-packages\conda\cli\install.py", line 417, in install
plan.execute_actions(actions, index, verbose=not args.quiet)
File "C:\moonbot\tools\env\lib\site-packages\conda\plan.py", line 500, in …
```
> Fix TypeError from using a unicode string in env var on windows

- conda/config.py
- conda/fetch.py
- conda/install.py
- tests/test_config.py
A directory named `noarch` (alongside `linux-64`, `linux-32`, `osx-64`, etc.) will be looked for, and (if present) used.
> Noarch (sub) directory support

- conda/plan.py
This small change allows conda to be installed into environments which start with an underscore '_'.  This will allow conda-build to build conda itself.
> allow conda to be installed into environments which start with _

- conda/cli/main_clean.py
All other help strings terminate with a period, except the clean one.
> fix missing period

- conda/cli/common.py
There is a list of packages which must never be removed from the root environment: [`conda.cli.common.root_no_rm`][1]
Apparently two more packages (`requests` and `openssl`) should be added to that list.
[1]: https://github.com/conda/conda/blob/master/conda/cli/common.py#L530
For the curious, here are the error messages you'll see if you accidentally remove `requests` or `openssl` from the root environment:
```
$ conda info --env
#
root                  *  /tmp/miniconda
```
```
$ conda remove -y requests > /dev/null 
$ conda list
File "/tmp/miniconda/bin/conda", line 3, in <module>
from conda.cli import main
File "/tmp/miniconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
from conda.cli.main import main
File …
```
> cli: Added 'openssl' and 'requests' to root_no_rm

- conda/fetch.py
This small change adds pip as a Python dependency.  The reason this is done here, and not in the `repodata.json` on the server is because older versions of conda don't handle circular dependencies, and this would `conda update conda` cause to fail.
> add pip as a Python dependency

- conda/history.py
Maybe this is not good behavior, but it fixes the issue where if you cancel a `conda create` at the download stage, the environment is still created with just an empty history file.
> Don't write to the history file if nothing has changed

- conda/cli/install.py
- conda/cli/main_remove.py
- conda/cli/pscheck.py
Previously it always looked for processes from the root environment.
@srossross this should fix the issue you were having at https://binstar.org/conda/conda-env/builds/115/9.
> pscheck: check for processes in the current environment

- tests/test_activate.py
We want them to fail in this case, as we don't want to not notice test
failures.
> Don't skip the activate tests if conda-env is not installed

- conda/cli/activate.py
- conda/install.py
- conda/plan.py
- Use `lexists` instead of `exists`. The former returns True for broken symlinks.
- Don't attempt to symlink conda in the root environment. I believe this can lead to a situation where there is a broken symlink if, e.g., activate does not exist in the root environment, in which case it writes a symlink to itself (which is considered to be a broken symlink). 
I have not fully tested this yet.
> Fixes to symlink_conda issues

- conda/compat.py
- conda/logic.py
- conda/resolve.py
This is required to get the true minimal solution, even if there are a lot of possibilities. Without this, things like `conda create -n test c asmeurer r-survival` produce two possible solutions, neither of which is the minimal one. The changes here only fallback to the slightly slower method when necessary, so the common case should stay exactly the same speed.
> Changes to min_sat

- conda/fetch.py
At some point (probably when switching to using `requests`), the keys `_etag` and `_mod` in the local cache of `repodata.json` had been removed.  This made the local cache useless, because the server would never respond with status 304 anymore.  This PR fixes restores the behavior, and will therefore help minimize bandwidth.
> restore json cache of repodata

- CHANGELOG.txt
- appveyor.yml
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_create.py
- conda/cli/main_install.py
- conda/cli/main_remove.py
- conda/cli/main_update.py
- conda/exceptions.py
- conda/install.py
- conda/instructions.py
- conda/plan.py
- conda/utils.py
- tests/test_exceptions.py
- tests/test_install.py
- tests/test_instructions.py
- tests/test_plan.py
- tests/test_utils.py
Didn't realize that I didn't have the latest code when I was on the plane working on #1273.  This creates a branch off of the latest release so the Windows upgrade changes are isolated and can be release independently.
This supersedes #1273.
* Before installing, create a new environment with pandas 0.16
* Open `python` console and type `import pandas` and `pandas.__version__` to verify the version is as expected
* Leave `python` console open
* In another terminal window, attempt to install `pandas=0.14*`
* When prompted, select `f` to force installation
At this point, you can repeats step 2 and you should receive an error.
To fix this, you have to close all running `python` consoles, then install `pandas` again.
Once you've reset, you can install this code and test -- it shouldn't allow …
> Release branch for 3.11

- runtests.sh
- tests/test_activate.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_logic.py
- tests/test_resolve.py
This makes it easier to isolate the unit tests from the integration and slow tests.
To skip the slower tests:
```console
py.test -m 'not slow'
```
Running without the `-m` flag will run all of the tests the way it always has.
This also adds a simple `runtests.sh` file that uses [watchdog](https://pypi.python.org/pypi/watchdog) to automatically run the tests on any file save.
> Mark slow tests to speed up unit test running

- conda/cli/conda_argparse.py
- conda/cli/main_bundle.py
- conda/cli/main_clean.py
- conda/cli/main_config.py
- conda/cli/main_create.py
- conda/cli/main_help.py
- conda/cli/main_info.py
- conda/cli/main_init.py
- conda/cli/main_install.py
- conda/cli/main_package.py
- conda/cli/main_run.py
- conda/cli/main_search.py
- conda/cli/main_update.py
@tswicegood you'll want to be using `conda.cli.conda_argparse.ArgumentParser` instead of `argparse.ArgumentParser` in conda-env to get these standardized fixes. Let me know if you have any issues with it.
> Automate some things for conda command help

- conda/cli/common.py
- conda/config.py
- tests/test_cli.py
- tests/test_config.py
Here, we merely focus on renaming `binstar.org` to `anaconda.org`.
> Rename binstar.org -> anaconda.org

- conda/cli/activate.py
- conda/cli/main.py
- conda/cli/misc.py
Made some imports local to ensure that the fast path in conda main is
really fast.
This includes processing for all '..XXX' commands (such as ..activate)
> Speed up 'source activate' by ~40%

- conda/fetch.py
Some packages do not have a 'depends' info key, which caused 'conda
search' to fail with KeyError.
> Fix issue when trying to add 'pip' dependency to old python packages

- conda/cli/main_info.py
It's currently impossible to get a list of all of the channels that are unobscured.  This adds the `--channels` option to `conda info` to give you a list of channels without their tokens stripped.  This provides the opt-in behavior described in #1194.
> Provide command for getting unobscured channel list

- conda/signature.py
- tests/test_misc.py
Apart from simplifying the code, this makes the signatures more secure.
See also https://github.com/conda/conda-build/pull/469
> Make use of Crypto.Signature.PKCS1_PSS module

- conda/pip.py
This causes weird console coloring issues on windows.
We could redirect it to STDOUT and just ignore when we parse it, or we can just throw it away from the beginning.
> Throw away stderr when calling pip list

- conda/cli/conda_argparse.py
- conda/cli/main.py
So far this is just a basic proof-of-concept. 
You have to install argcomplete into conda build and conda skeleton for this
to work. It does not yet detect subprocess commands (it hard-codes 'build' and
'skeleton'), and it does not yet complete the subprocess commands themselves.
> Making bash command completion work with subcommands (like conda build)

- conda/cli/main_info.py
That way, packages with versions greater than 9 will be sorted correctly.
> Sort the output of conda info package

- conda/cli/main_config.py
The `message` variable was not defined when not using JSON output which raised an exception when I ran the tests (on Windows 7)
> fix variable scope

- .travis.yml
- appveyor.yml
It would be nice to catch issues with `conda --help` in advance of a release. This is an easy way to do so.
Ultimately, something like this would be good, as well ( https://github.com/conda/conda-build/pull/400 ). Though it may need more work.
> Test help on CIs

- README.rst
- conda/cli/install.py
- conda/config.py
- conda/fetch.py
allow renamed entries in condarc, ie.
```
add_binstar_token -> add_anaconda_token
binstar_upload -> anaconda_upload
```
For backwards compatibility the old names can still be used.
If both are defined in the `~/.condarc` file, the new ones take precedence, e.g.
```
binstar_upload: True
anaconda_upload: False
```
will result in `anaconda_upload` being set to `False`.
Also the readme, and user facing messages are updated.
Internal (in the code) occurrences of binstar are **NOT** renamed.
> Rename binstar -> conda_server

- conda/install.py
When I install a tarball to an env on another mount point from `~/.conda/envs/.pkgs` (e.g. `/tmp/env`, where `/tmp` and `/home` are different mount points), conda install fails silently because it tries to use hard links.
In my opinion, it is awful to check whether hardlinking is available everywhere you want to use `link`, but my previous pull-request #1410 was rejected. Thus, I fix this thing to close the bug that I hit this time, but I'm almost sure there are more related to this somewhere else. Good luck.
P.S. Don't ask me why it fallbacks from hardlinks to copying instead of symlinks.
> check whether hardlinking is available before make a link (second attempt)

- conda/resolve.py
- tests/test_resolve.py
When solving dependencies and listing the installed features, it was
being considered only features present on field "features" and not on
"track-features".
> Fix track-features when there is no installed package with feature yet.

- conda/cli/main_list.py
I moved `sys.exit` from `print_packages` to `execute` where it makes more sense because `print_packages` is also used in `cli/install.py`, where it makes no sense to return exit status 1 when a package was installed successfully, but had no dependencies.
> print_packages breaks installation of a package with no "run" dependencies

- conda/cli/find_commands.py
- conda/pip.py
- conda/plan.py
- tests/mk_index.py
Continuation of the work here ( conda/conda-build#516 ) except with `conda` proper.
> Use `splitlines` to break up multiple lines

- conda/config.py
This is meant to be used only for conda-build when building 32-bit binaries on a 64-bit system.
> add ability to set CONDA_FORCE_32BIT environment variable

- conda/resolve.py
This way, it is properly skipped with conda update --all.
Fixes #1561.
> Add package itself to NoPackagesFound pkgs list

- conda/api.py
- conda/cli/main_run.py
This PR enables the --offline flag for the 'conda run' command, so that commands can be ran in an environment without fetching package information from online channels.
> enable running 'conda run' in offline mode

- conda/fetch.py
> Give a better error when a proxy isn't found for a given scheme

- conda/cli/find_commands.py
The point of this PR is to simplify how sub commands from conda-build handled, and also to only allow sub-commands coming from conda-build (and conda-env for the time being).
> simplify build sub-command handling

- conda/resolve.py
- tests/test_resolve.py
Use case: Imagine a version number convention that contains the version of the compiler used to build the package, such as `mypackage-2.4.vc11` (a convention like this makes particular sense for C++ code, because C++ binaries tend to be incompatible between compilers). At present, one can use this in a package's requirements section like this:
```yml
requirements:
build:
- mypackage  *.vc11    # [win]
```
but not in combination with another constraint like this:
```yml
- mypackage  >=2,*.vc11    # [win]
```
since conda forbids wildcards `*` in comma-separated version specs. The present pull request simply lifts this restriction, making the second spec legal as well. It contains tests for the new option and should otherwise be fully backwards compatible.
> allow wildcards in AND-connected version specs

- conda/config.py
- conda/fetch.py
As of conda 3.9.0, `pip` is automatically added as a dependency of `python` (2 or 3).  This behavior might not always be desirable, and this PR adds an option to the condarc file in order to make this behavior optional:
```
add_pip_as_python_dependency: False
```
> add config option to makes the python dependency on pip optional

- conda/compat.py
I was experiencing this issue:
```
NotImplementedError: chmod: follow_symlinks unavailable on this platform
During handling of the above exception, another exception occurred:
File "/home/scopatz/miniconda3/bin/conda-build", line 5, in <module>
File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 190, in main
args_func(args, p)
File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 429, in args_func
args.func(args, p)
File "/home/scopatz/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 384, in execute
override_channels=args.override_channels, include_recipe=args.include_recipe)
File …
```
> Fix for Python 3.5

- conda/toposort.py
- tests/test_toposort.py
**Update:** I simplified this PR with @asmeurer's suggestion to simply break the `python`/`pip` cycle before sorting.  See comments below.
----
When an environment is constructed, the package install order is chosen by `conda.toposort()`.
If the list of package specs contains any circular dependencies, then `conda.toposort()` uses a [simple heuristic](https://github.com/conda/conda/blob/81a3a34b8b5fda9095ccfa3e8ffac636a2b80343/conda/toposort.py#L49-L50) to guide the package install order.  Yet, recipes may still occasionally fail to build, or `post-link.sh` may fail to execute, due to an unfortunate install order. (For example, see conda/conda-build#401)
The **most common culprit** is the circular dependency between `python` and `pip`.  Since python is used by many many recipes, it seems …
> Fix install order for all python packages: Add special case in conda.toposort()

- conda/resolve.py
According to [PEP-440](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) the separator for the local version identifier should be a`+` which isn't currently handled by conda.
This PR simply allows for `+` to be used as a separator. Without it conda can't handle PEP-440 compliant package names and gives either a somewhat misleading *"Could not find some dependencies"* error or an assertion error of the form:
```
File "C:\dev\bin\Anaconda\Scripts\conda-script.py", line 4, in <module>
File "C:\dev\bin\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
args_func(args, p)
File "C:\dev\bin\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
args.func(args, p)
File …
```
> PEP-440 Fix

- conda/install.py
This change will attempt to 'fix' issues when removing locked files in Windows.
To avoid that problem, I just used the trash mechanism already implemented in conda, and put it into `rm_rf`.
I slightly broke the api for `move_to_trash, but it doesn't look like the `tempdir` was used anywhere.
Fixes #1594
> Moving files to trash if failed to remove them in windows

- conda/cli/install.py
This allows, for instance, conda update --all python=3.5 to update an
environment to Python 3.5.
> Allow to include specs with conda update --all

- conda/resolve.py
- tests/test_resolve.py
follow up on PR https://github.com/conda/conda/pull/1601
> interpret underscores as version separators

- conda/cli/main_clean.py
This makes `conda clean` properly handle multiple envs dirs.
> Clean envs dirs

- conda/console.py
Sometimes updating Python in the root environment on Windows raises this
error. See #1657 and #1133.
> Catch LooupError in conda.console

- conda/cli/common.py
- conda/cli/main_remove.py
The index cache is now used by default. The index is needed only to display
the channel information when show_channel_urls is set to True. The worst that
will happen when there is no cache present is that the channel will show as
`<unknown>` instead of the actual channel. This makes conda remove much
faster.
The index can still be forcibly fetched with conda remove
--no-use-index-cache.
Fixes #1667.
> Don't fetch the package metadata from the network with conda remove

- conda/cli/install.py
- conda/misc.py
We ensure that when installing packages directly, using `conda install <conda pkg>`, installed packages of the same names are also remove.  Otherwise, you can end up having two (or more) packages with the same name installed, which causes other problems.
> Fix for issue 1685

- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_list.py
- conda/misc.py
- conda/plan.py
- tests/test_toposort.py
Using the `--file` option, this PR allows having an explicit file, which contains the URLs of all conda packages to be installed.  The first (non-comment) line of this file has to start with `@EXPLICIT`.
> Allow explicit file with all URLs of packages

- conda/install.py
Currently `menuinst` menu items are only installed when installing into the root environment. This PR will relax this constraint. Suggest to filter out envs with names starting with "_build" and "_test" to prevent menu items being installed into build or test environments.
> Allow menu items to be installed in non-root env

- conda/resolve.py
This adds a method `prune_packages` and some supporting methods that reduces the number of dists that the subsequent Resolve processing sees. This pruning step is relatively fast compared to the typical processing time, and yet significantly speeds up the solve process in some of the more difficult cases we've encountered.
The pruning pass consists of two stages. The first stage identifies what I call "strong" dependencies, and eliminates any packages that do not satisfy those dependencies. A "strong" dependency is one that all versions of a given package rely upon. 
For instance, consider `anaconda`. Anaconda _always_ depends on some version of `python`. Therefore, if `anaconda` is included in the spec, we can immediately prune away all versions of `python` that are not accepted by at …
> Added a pruning step for more efficient solves

- conda/install.py
Removes restriction that shortcuts can only be installed in the root environment.  Passes information to menuinst that menuinst can use to customize shortcuts and add pre-run steps (such as activating an environment)
Part of a 4-part set of PRs across the conda system.  Other PRs:
* https://github.com/conda/conda-env/pull/178
* https://github.com/ContinuumIO/menuinst/pull/4
* https://github.com/conda/conda-recipes/pull/439
> pass env name and setup cmd to menuinst

- conda/resolve.py
This addresses issue [https://github.com/conda/conda/issues/1748](1748). Setting `valid[fn]` temporarily ensures that if a dependency cycle is detected, it will terminate. It is not clear to me why this *isn't* there; it was in a previous version of my code. My apologies for the omission.
> Stop infinite recursion during certain resolve operations

- conda/cli/main_search.py
Resolves https://github.com/conda/conda/issues/1125 by saying that
we use Python flavored regexes in conda search, as confirmed by
Ilan.
> say we use Python regexes in the conda search help

- conda/install.py
- tests/test_install.py
Ask for forgiveness, rather than permission.
When creating a user environment based on a root environment, extra package files would be left in the root of the new user environment. `os.access` checks if the inode itself is writable, not if the directory containing it is writable (which is all that is needed to unlink a file).
Fixes conda/conda#1861
> Always attempt to delete files in `rm_rf`

- conda/cli/common.py
- conda/cli/main_list.py
- conda/config.py
When all packages come from the defaults channel, which is the case for most users, there is no need to show the channels. In this PR (by default) only show the channels, if at least one package comes from something other than defaults.
See also https://github.com/conda/conda/pull/1771
> improve default for --show-channel-urls in conda list

- conda/config.py
- conda/install.py
Hello,
I would really like to be able to use conda on OpenBSD 5.x.
This only requires two minor changes:
- Conda should be able to detect OpenBSD as a new platform `openbsd` instead of `unknown`. This way it is possible to create a repository e.g. "openbsd-64". Unlike linux, ABI compatibility is not guaranteed between BSDs so Open/Net/FreeBSD should have their own platform.
- Conda should not rely on `/bin/bash` being available. First because many linux distributions (or other unixes) install it somewhere else (e.g. `/usr/local/bin/bash`). And more importantly because `bash` is not part of POSIX, so you cannot rely on it being present. Instead conda should use `/bin/sh`, which is guaranteed to be present on any POSIX/coreutils compliant system (Linux + BSDs). Luckily, shells scripts in …
> OpenBSD 5.x support

- conda/resolve.py
While investigating various version-number related issues happened upon this bug. The intended behavior is to escape literal periods in the version specification regex, but that escaping is overwritten by line 283.
> resolve.py: properly escape periods in version numbers

- conda/config.py
- conda/plan.py
This pull request is a small accompaniment for a larger PR in the `conda-build` repo here: https://github.com/conda/conda-build/pull/719
This pull request pins Lua versions by default, because Lua releases, like Python, do not occur often, but when they do, they often break packages.
> Support for pinning Lua by default

- conda/cli/common.py
after spotting duplicated description in docs:
```
--no-use-index-cache
Use cache of channel index files.
--use-index-cache
Use cache of channel index files.
```
> corrected --no-use-index-cache help in common.py

- conda/api.py
- conda/cli/install.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/install.py
Suppose an environment has a package that was installed using the `-c` command line option: that is, from a channel that is _not_ in the default channel list. Subsequent calls to `install` or `update` will be unable to properly handle that package's presence for the purposes of dependency resolution. In particular, it will be possible to break said package by modifying its dependencies.
This PR solves the problem by adding a `prefix=` keyword argument to `api.get_index`, which in turn calls a new function `install.linked_data`. When a non-empty `prefix` is supplied, it will add the JSON data it finds in that `prefix` into the index. Now that it is available, the solver will have full dependency and version data available when it sees that package in the `installed` list.
> Add linked packages to the output of get_index()

- bin/conda.fish
This is a basic take on fish-compatible `activate` and `deactivate` commands. This also adds `conda activate`, `conda deactivate` and `conda ls` commands for convenience.
Autocompletions and event handlers may follow later; the basics seem to work fine for now.
Usage:
```sh
source (conda info --root)/bin/conda.fish
```
> Added basic activate/deactivate, conda activate/deactivate/ls for fish shell

- conda/config.py
This is harmless.  It's redundant, but has no ill effects AFAICT.  On the other hand, this error message gets in my way sometimes.
> Remove error when CONDA_FORCE_32BIT is set on 32-bit systems

- conda/cli/common.py
The conda package cache, has been (from my point of view at least) been more and more abused to get to data which is available on the local system, in order to make conda work better in offline mode. However, the package cache was originally never designed for that purpose.  The `--unknown` option is one such example.  This option has a very confusing name, and does not always work correctly.
In this PR, we remove the help text for this option (to confuse people less).  Hopefully, it will be possible to remove the functionality soon as well.
> suppress help text for --unknown option

- conda/instructions.py
This is meant to address Windows permissions issues with files being in use during conda installing things.  In particular, Conda should not extract already-extracted files, because these already-extracted files may be in use.  This patch should prevent conda create from hitting the file locking issues when creating an environment with the same python version as the root python.  It does not attempt to address the issue of any permissions issues that may arise from (force) updating packages that Conda uses directly in the root environment.
xref:
* https://github.com/ContinuumIO/anaconda/pull/465
* #1936 
* https://github.com/Anaconda-Server/nb_conda/pull/9#issuecomment-179265547
* #2079 
Ping @insertinterestingnamehere @groutr @ilanschnell @PeterDSteinberg
See discussion in Anaconda Build …
> do not extract already extracted packages

- conda/misc.py
- conda/resolve.py
Currently, conda create --clone <env> links all packages in <env>
into a new environment. This is done without respecting package
dependencies. This can cause issues with packages that have
install-time dependencies (for example, post-link scripts).
This fixes https://github.com/conda/conda/issues/1451.
> Make clone_env link packages in toposorted order

- conda/history.py
- tests/conda-meta/history
- tests/test_history.py
The method `get_user_requests` adds information about user requested packages (all information is already in the `histroy` file), this method merely provides a convenient way for retrieving the data.  Here is an example:
```
>>> from conda.history import History
>>> h = History('/Users/ilan/anaconda')  # prefix
>>> h.get_user_requests()[237]
{'action': 'install',
'cmd': ['conda', 'install', 'pandas'],
'date': '2016-01-31 12:39:33',
'specs': ['pandas', 'conda', 'python 2.7*']}
```
CC @mcg1969, @kalefranz, @groutr
> Add get_user_requests method to History call

- conda/resolve.py
If the resolver comes across a badly formed version in a conda package name, conda-build barfs but does not tell you **which** package is causing the error.  This PR adds a little bit of helper functionality to conda-build by outputting the package name that is raising the version string error.  The extra output is this for the error that I am getting:
```
The following stack trace is in reference to package:
databroker-.post-_npNonepy34.tar.bz2
```
Full stack trace:
```
BUILD END: datamuxer-v0.3.0.post1-py27_0
TEST START: datamuxer-v0.3.0.post1-py27_0
Fetching package metadata: ............
The following stack trace is in reference to package:
databroker-.post-_npNonepy34.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue …
```
> Log the package name that has a bad package name to stderr

- conda/api.py
The breakage of 3.19.2 was caused by a recent fix which adds the metadata from installed packages, found in `conda-meta`, directly into the master index. If these metadata entries do not include a `depends` field, then the `Resolve.ms_depends` method choked.
This leads to the question: why did they not have a `depends` field? Apparently, some older packages did not populate the `depends` field inside the package data itself. But this explanation isn't enough: because when packages are downloaded from the repo, _that_ metadata is preferred, and written to `conda-meta`, and this metadata _does_ include a `depends` field.
So the only situation in which the `conda-meta` data will be missing dependency information is for packages included in the initial installation---which cannot go to the …
> Improve handling of local dependency information

- conda/api.py
This should fix the problem with the launcher listing apps which cannot be installed into the current root environment.
> filter app index to only use current Python version

- conda/connection.py
**Problem**:
meta.yaml source url using UNC path
> Error: HTTPError: 404 Client Error: None for url:  
```
source:
fn: blah.blah [win]
url: file://\\blah\blah.blah [win]
```
**Fix**:
Leave Windows UNC source url paths as is
> Fix Windows UNC source path

- conda/connection.py
Currently, for s3 channels, conda uses boto's default `validate=True` for `get_bucket` (cf. [boto docs](http://boto.cloudhackers.com/en/latest/ref/s3.html?highlight=get_bucket#boto.s3.connection.S3Connection.get_bucket)) when grabbing packages from s3.  This requires one to have permissions both for the root of the bucket (e.g., `s3://my-bucket/`) as well as the specific key where the conda repository lives (e.g., `s3://my-bucket/path/to/conda/`).
It seems better to use `validate=False` so that one can put a conda repo in a place on s3 where not all the users would have to have permissions for the root of the bucket.
Also, the current error message if you don't have permissions for the root of the bucket is fairly confusing. 
```
> conda install my-package -c s3://my-bucket/path/to/conda/ …
```
> turned off S3 bucket validation

- conda/cli/main_clean.py
Fixes #1285.
Prior to version 3.2, python contains a bug on Windows where `os.lstat` does not set the `st_nlink` property of its result correctly. See: https://bugs.python.org/issue10027
This commit introduces a platform independent function to query the `st_nlink` value.
> Fix conda clean --packages on Windows

- conda/resolve.py
Fixes the issues Ilan was experiencing when removing packages from broken environments. This should be doing a straight remove now, but it's hard for me to test without Ilan's fabulously broken envs. Let's test before merge, please.
> Fix for removing packages from broken environments

- conda/logic.py
- conda/resolve.py
- tests/test_logic.py
- tests/test_resolve.py
With the new solver, we were seeing cases where `conda update --all` would cause featured packages to lose those features. This was because 1) the newest versions of those packages did not have a featured version; and 2) the `update` command was prioritizing version number over feature count.
But if we reverse that priority, then we can't be sure that there will be tracked features to install at all. after all, we don't install features, we install packages with `track_features` settings. And some packages, like `mkl` or `python`, have different values for this field with different versions. To make sure we get the proper number of features, then, we *have* to pull their latest versions.
So what this PR does is this: first, it does a *preliminary* version maximization of all explicitly …
> Updates no longer upgrade past features

- conda/logic.py
- conda/resolve.py
@dhirschfeld's issue (https://github.com/conda/conda/issues/2158) brings together two issues with the revamped solver: strange remove behavior and occasional performance hangs. This is a not-so-minor PR to address both.
The primary cause of the remove problems was an incorrect ordering of priorities in the optimization passes. When removing a package, the primary goal of the solver should be to _preserve as many of the remaining packages as possible_. Sometimes, additional packages must be removed, because the package that was _explicitly_ requested for removal was a dependency. And if a track_feature is removed, alternative versions of the packages without that feature should be sought. Otherwise, the environment should be left as close to its original state as possible.
In the current …
> Fixes to remove functionality and general performance issues

- conda/resolve.py
This should fix the issue reported in #1967. I don't have a good test for this though---it involves pinned specs. Can one of you test it out before merging?
> Fix for pinned spec matching

- conda/api.py
This addresses issue #2179.
The new behavior us quite simple: only if a (local) package in not in the repodata, use the local `conda-meta`, with `depends` defaulting to [].
Needs testing.
> simplify get_index() prefix behavior

- conda/resolve.py
If using old form string formatting, it is generally safer to put the thing you want formatting into a tuple:
```
>>> bar = (1, 2); print("foo %s" % bar)
File "<stdin>", line 1, in <module>
TypeError: not all arguments converted during string formatting
```
```
bar = (1, 2); print("foo %s" % (bar, ))
foo (1, 2)
```
> Fixed solver string format.

- conda/lock.py
The wrong lock file is warned about in the lock_str LOCKERROR string.  This corrects that.
> correct lock file path in LOCKERROR

- conda/resolve.py
`clone_env` is passing a list of dists into `dependency_sort`, but in fact that function is expecting a dictionary of (name,dist) pairs.
> Fix `dependency_sort` issue in clone

- conda/misc.py
`clone_env` doesn't handle symlinks properly---specifically it copies the file instead. This is causing problems on the Mac during the `shutil.copystat` call. This is an attempt to rectify this. It's a three-line fix but please review.
But @ilanschnell, I'm curious why `clone_env` is using low-level file operations to do a file copy instead of `shutil.copy`?
> Fix symlink errors during clone

- conda/resolve.py
- tests/test_resolve.py
#2208 revealed an interesting performance issue that manifested itself only in situations where there are a _lot_ of builds, a situation likely to be encountered more by developers than users.
The crux of the issue is that, in the passes that maximize build numbers, the maximum build number for each package is being taken _across all versions_ of the package. So if an old version had 1000 builds, and the new one had only 200, the solver seemed to think the new version was a full 800 builds "old" Mathematically, this doesn't matter, and for typical repos the gap is not going to be big like that. But it slows the solver down, because now it has to bisect over 800 values to get to the true newest build.
Still, I'm not content to leave it there, so I fixed it by combining the "version" and …
> Performance improvements for large numbers of builds

- conda/fetch.py
Replaces #1072 from @pelson, who says:
> Avoids some noisy warnings in Python 3 (I have ResourceWarnings enabled).
> Close session handles

- conda/cli/main_list.py
Create a minimal environment
```
$ conda create -p /tmp/foo python=3.4
Fetching package metadata: ..........
Solving package specifications: .........
Package plan for installation in environment /tmp/foo:
The following NEW packages will be INSTALLED:
openssl:    1.0.2d-0      defaults
pip:        7.1.2-py34_0  defaults
python:     3.4.3-2       defaults
readline:   6.2-2         defaults
setuptools: 18.4-py34_0   defaults
sqlite:     3.8.4.1-1     defaults
tk:         8.5.18-0      defaults
wheel:      0.26.0-py34_1 defaults
xz:         5.0.5-0       defaults
zlib:       1.2.8-0       defaults
Proceed ([y]/n)? y
Linking packages ...
#
#
#
```
activate the environment and install a package from my anaconda channel
```
edill$ sa /tmp/foo
discarding /Users/edill/mc/bin from PATH
prepending …
```
> Make an attempt to format the correct URL with the `--explicit` flag on conda list

- conda/cli/common.py
- conda/cli/install.py
- conda/plan.py
- conda/resolve.py
- tests/test_resolve.py
Cleaning up the behavior of `conda update`, in particular `conda update --all`. Notes:
- Because of [this commit](https://github.com/conda/conda/commit/da8dea22e0acdb28dcb76de68b9be1a77df697b3), `anaconda` is being removed from the update list. This is useless now that `conda` verifies that updates remain consistent with the rest of the installed packages.
- Because of [this commit](https://github.com/conda/conda/commit/1301aae0e3d28623b8d14df46537e7ae6964d6ce), `cli.install.install` has a hard-coded test to prevent accidental/unwanted upgrades from Python 2 to Python 3. That's handled better and more generally by `plan.add_defaults_to_specs`. For example, `add_defaults_to_specs` now does similar version protection for Lua, so it would be nice to have that for `conda update --all`.
- On …
> Initial commit: improvements to update behavior

- conda/plan.py
This will allow conda-env to implement "conda env update --prune" command,
as discussed in conda/conda-env#190
I could not figure out how to write tests for this though... any help here?
CC @malev
> Add "prune" option to plan.install_actions

- conda/logic.py
- conda/resolve.py
- tests/test_resolve.py
Inspired by the discussion with @jjhelmus in #2219, I sought an alternative solver approach that would do a better job of preferring the latest builds of all packages. 
The existing merit functions gave a slight preference to removing packages completely as opposed to installing the latest version of a package. If enough of these "potential removals" accumulated, the solver would prefer downgrading a package so it could remove several others.
This fix removes that bias and replaces it with a lower-priority "package pruning" pass. That is to say, first the versions are maximized, and *then*, once they are locked in, a pass is performed to see if any of those packages can safely be removed. 
Just removing the bias without adding the extra pass isn't an option---that results in ambiguous …
> Weak dependency resolution improvements

- conda/pip.py
https://github.com/conda/conda/issues/2258
on Windows pip is installed in the Scripts folder
when one tries to conda env create/update from an exported environment with a pip section it fails miserably ... no more!
> bug: windows pip_path incorrect

- conda/resolve.py
An attempt to address #2229 and #2250.
I honestly do not know what a particular combination of installed packages is causing my code to generate bad inputs to `C.sat`. However, for now, I'm going to make an assumption here that only broken installations are doing so. And since all I need to know is if an install is broken or not, catching the exception and acting accordingly will work just fine.
I know I should figure out exactly why the bad input is being generated, and I will, but in the meanwhile this is preventing people from updating conda.
> Gracefully handle unexpected errors in bad_installed

- conda/resolve.py
- tests/integration/regression.bats
To address #2259 ... and https://github.com/Anaconda-Server/support/issues/26 ... this is resulting in further code simplification and fewer optimization passes, which is a good sign, but it means we _must_ test this more before merge. Specifically, please test it against `mkl`/`nomkl` weirdness, and the issues we recently put to bed with Accelerate, so that there are no regressions.
As a result of this simplification, the optimization passes proceed as follows:
0. (Remove only) Minimize the number of removed packages
1. (Install/update only) Maximize requested version numbers
2. (Install/update only) Maximize requested builds
3. Minimize number of active features
4. Maximize number of packages with features (or, more precisely: minimize the number of packages that *have* a featured …
> Ensure latest versions preserved after features selected

- conda/resolve.py
The new hint generation logic isn't quite as solid as I'd hoped; it includes a lot of extra information that is not helpful. This fix cuts all that extra cruft out by abandoning the solve _as soon as_ an incompatibility is detected. The downside is that this sometimes results in less helpful hints, but I think the _overall_ quality of hints goes up with this.
> Reduce the amount of extraneous info in hints

- conda/plan.py
One of our first support requests regarding the new Anaconda "custom" package: someone asked on Gitter why Anaconda was being "downgraded" to custom when performing certain actions.
This simply changes the version comparison logic in plan.py so that if a version is changed to "custom" it is _always_ treated as an "update" instead of a "downgrade". If we want to go further than this, we should add text to plan.py to full explain what the "custom" version is.
Probably could be cherry-picked to 4.0.x.
```
0203-mgrant:conda mgrant$ python conda/cli/main.py update -n testa pandas
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications ............
Package plan for installation in environment /Users/mgrant/miniconda2/envs/testa: …
```
> Version changes to/from "custom" are now both logged as "updates"

- conda/cli/common.py
- conda/version.py
- tests/test_cli.py
_Copied from #2234_
Without this fix, the steps taken to verify specs supplied on the command line (e.g., `python=3*`) are not as strict as those performed by the solver. So if an invalid spec leaks through to the solver, we get a crash. It's the user's fault, sure, but we're telling the user to file an issue instead of fix their spec. So it's a bug.
This fix uses the solver's own MatchSpec parser to assist in the verification process. Thus if a spec makes it out of this function, we know that the solver will like it later.
Lines 451-455 aren't exercised yet, but will be in master. (And note that if you cherry pick this over there you'll want to resolve the conflict to this version.)
Needed to tune up the `__str__` function for `VersionSpec` to get this to work well.
> Use MatchSpec to verify specs supplied on the command line

- auxlib/path.py
`site_packages_paths` is supposed to return a list of strings, but in a branch not used in production, it returns a single string. I exercise this branch when I debug conda with iPython.
> auxlib: site_packages_paths fix

- conda/egg_info.py
- conda/exceptions.py
- conda/lock.py
- tests/test_exceptions.py
- tests/test_lock.py
Add tests for and refactor `conda/lock.py` (embarassingly, I think it was actually possible to have two locks that didn't block each other).
The last commit (custom exception) might be a little overkill. Happy to remove it if you want.
> Test Locked

- conda/logic.py
pycosat 0.6.1 is supposed to accept an iterator of iterators as input, whereas pycosat 0.6.0 requires a true list of lists. The former is preferred for a variety of reasons, including performance, so we introduced a `pycosat 0.6.1` version requirement for recent versions of `conda`, and dropped code that implemented the old list-of-lists conversion.
But for some reasons, issues like #2276 reveal that _even people who have `pycosat 0.6.1` installed_ are seeing this old behavior, which manifests itself by a `TypeError: list expected` exception. This PR intercepts that exception, performs the conversion, and re-calls pycosat.
> Fix for mysterious pycosat 0.6.1 behavior

- conda/api.py
- conda/cli/common.py
- conda/config.py
- conda/fetch.py
- conda/resolve.py
- tests/test_config.py
- tests/test_resolve.py
cc: @ukoethe @jakirkham 
This is what I hope will be the first attempt to properly handle cases where packages with the same name are hosted in multiple channels. The current behavior does the following:
1. When the package filenames are identical, the version found in a lower priority channel is dropped from consideration, even if that would have been the right choice for dependency reasons.
2. Even when package filenames are distinct, they are prioritized as if they all came from the same channel. In particular, build numbers are assumed to imply consistent chronology across channels. But this clearly is not a correct assumption; build 5 in channel A could in fact be _older_ than build 10 in channel B.
To fix this we have done the following:
- Assign a _channel priority number_ to each …
> Better handling of channel collisions

- conda/cli/main_search.py
If --spec is passed to conda search, ms is a string consisting of 'name version build'.
Currently, conda breaks as follows:
```
$ conda search --spec python=3.5.0
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
File "/Users/ElCapitanVM/projects/conda-lsst/miniconda/bin/conda", line 6, in <module>
File "/Users/ElCapitanVM/projects/conda-lsst/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
args_func(args, p)
File "/Users/ElCapitanVM/projects/conda-lsst/miniconda/lib/python2.7/site-packages/conda/cli/main.py", …
```
> Fix 'conda search --spec' breakage

- conda/api.py
pri0 was a tuple, and not always the max value (because of how tuples are compared).
Because `pri0` was a tuple, I got the following exception
```
<snip>
File "/Users/rgrout/continuum/projects/conda/conda/api.py", line 46, in get_index
channel_urls[url] = (rec[0], rec[1] + pri0)
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```
Looking at api.py in conda, I noticed that following line does not do what I think it was intended to do.
That is find the max priority from the values of a dictionary. 
```
pri0 = max(itervalues(channel_urls)) if channel_urls else 0
```
`pri0` will take on the wrong value in the following instance.
Example
```
In [14]: d2 = {'file:///Users/rgrout/miniconda/conda-bld/noarch/': ('file:///Users/rgrout/miniconda/conda-bld', 1), …
```
> fix bug with channel priority.

- conda/connection.py
- conda/utils.py
This PR replaces the old User-Agent string for conda connections with something a little more useful about the platforms and python versions conda is being used with.  This addresses a change made in requests 2.8.0.
> User-Agent for conda connections

- conda/fetch.py
I was getting some very odd errors using s3 as an index. The `response.raw` object is sometimes empty, sometimes contains my index. Reading from the BufferedReader was sometimes empty. Seek sometimes works, tell is not always right, etc. Something about the sessions is not thread-safe. 
Using a new Session in each thread solves the issue reliably for me.
Related: https://github.com/kennethreitz/requests/issues/2766
> BUG: request.Session not thread-safe

- conda/install.py
This is a try to fix #2345 
If BeeGFS is configured with:
sysCreateHardlinksAsSymlinks  = true
Symbolic-link is created instead of a hard-link, which can cause problem, for
example:
pkgs/bin/mpicc
pkgs/lib/libopen-pal.so
envs/bin/mpicc # symlink to pkgs/bin/mpicc instead of hardlink
envs/lib/libopen-pal.so
Here, when envs/bin/mpicc is executed, it is actually pkgs/bin/mpicc that is
executed, and the library $PREFIX/../lib/libopen-pal.so actually loaded is
pkgs/lib/libopen-pal.so, which is different from envs/lib/libopen-pal.so for
which conda has fixed hard-coded prefix path, and as a final consequence mpicc
fails to find its configuration file.
> Manage BeeGFS hard-links non-POSIX configuration

- conda/resolve.py
- tests/test_resolve.py
A simpler attempt to implement #2385 (with a nice side effect of ripping out some unused logic from the solver). See that PR's description for a full explanation of the problem.
This PR simply prevents `conda remove` from performing version downgrades on any remaining packages that might be suggested to resolve dependency losses; the package will just be removed instead. Version _upgrades_ are still allowed, and this seems fitting: if a package has been upgraded to remove a dependency, then it is reasonable to perform that upgrade when that dependency is removed.
Build downgrades are still possible (e.g., `1.7.0 1 -> 1.7.0 0`). I'd like to prevent that, but the `MatchSpec` logic doesn't quite allow it yet. Given the vast improvement in "remove" solutions that this produces, that seems …
> Prevent version downgrades during removes

- conda/connection.py
Boto doesn't actually work with config files on Python >= 3.4 because of this bug.
> Workaround for https://github.com/boto/boto/issues/2617

- conda/plan.py
I made a mistake when revising `plan.remove`. If `config.track_features` is set, it would add those features to the remove list. Obviously that's not what is desired. Fortunately, I believe very few people hardcode a `track_features` value into their `.condarc`.
> Quick fix: shouldn't add `config.track_features` contents to remove spec

- conda/cli/install.py
- conda/config.py
- conda/fetch.py
- conda/install.py
- conda/misc.py
- conda/plan.py
- conda/resolve.py
Fixes the problems first noticed [in this conda-build issue](https://github.com/conda/conda-build/issues/899#issuecomment-214767717). `master` is currently not handling local `.tar.bz` packages properly. This rewrites `misc.install_local_packages` to use the cache machinery.
> Fix misc.install_local_packages

- conda/install.py
- tests/test_install.py
Fixes https://github.com/conda/conda-build/issues/891
> move_to_trash uses UNC paths on Windows to get around MAX_PATH 260

- conda/resolve.py
- tests/test_resolve.py
The weighting function for dependencies that are _already installed_ but may require updating to meet specifications was broken somehow in recent updates. 
Updates are supposed to prefer *maximum* updates for packages specified on the command line, and *minimum* updates for everything else. The idea is that `conda` should not be modifying a user's environment any more than necessary to do what is requested. It was the "minimum" update ordering that was broken, so it was updating more aggressively as a result.
I blame myself and/or a messed up merge.
> Fix the sort order for updates

- conda/resolve.py
- tests/test_resolve.py
@kalefranz: here you go, play with this please.
When installing or updating packages, `conda`'s first priority is to install latest possible versions of the packages explicitly listed on the command line, subject to dependency constraints. Its second priority is to minimize the change to the current environment that are needed to achieve this objective.
In particular: if it is possible to install the new package, or perform the requested updates, _without_ modifying any other package in the environment, it will not do so. This helps ensure that environments that are already working well don't break due to new installs or updates.
When some additional modifications to the environment _are_ necessary, `conda` seeks to minimize them---but this PR changes what that means. Prior to this PR, …
> Adjust behavior for dependencies that need updating

- conda/install.py
This avoids a package being partially extracted if the conda
process is interrupted.
> Always extract packages to a temporary directory first

- conda/cli/common.py
- conda/plan.py
- conda/resolve.py
- conda/version.py
- tests/test_resolve.py
The current version of conda requires exact string matches for three-element (package/version/build) matches; e.g., `numpy 1.10.0 py27_1`. This PR allows the version match to include inequalities or wildcards, and allows the build string to have wildcards as well.
So, for instance:
- `numpy >=1.0.1a py27*` will match `numpy-1.0.1z-py27_1.tar.bz2`.
- `blas * openblas` will match `blas-1.0-openblas.tar.bz2`. (@jakirkham will appreciate this one.)
> Improved version & build matching

- conda/plan.py
- conda/resolve.py
```
conda create -n test anaconda python=2.7
conda remove -n test enum34
```
The `remove` command forces an upgrade to Python 3.4. That's because `remove` currently doesn't utilize `add_defaults_to_specs`. This change fixes that.
> Respect add_defaults_to_specs in conda remove

- .travis.yml
- conda/cli/common.py
fixes `conda install --help ` from 1cc64811
> fix help in install. broken from 1cc64811

- README.rst
Instructions for creating a development installation (and removing it) are unclear. Just some added clarity. 
Note: Not clear on full directions for uninstalling, but seems that it requires some changes be made by hand. Can anyone advise?
> clarify development installation

- conda/cli/activate.py
.. which makes it into PATH via conda ..activate and activate.bat
@kalefranz as we discussed, in lieu of activate being used for the root env.
> activate: Add MSYS2 entries to binpath_from_arg

- conda/resolve.py
I didn't realize it was used outside of `conda`. @mingwandroid has a fix for `conda-build`, but it would probably be best if this one little thing didn't force people to upgrade `conda-build`, particularly since it's easy to reverse.
Note that because we've made the `MatchSpec` a bit more flexible, I'm reserving `strictness==3` for exact version/build matches (`is_exact()`). All other matches with version or build specifications are `strictness==2`. That's the best fit for prior logic.
> Put strictness back.

- conda/fetch.py
- conda/install.py
- conda/plan.py
Hi @mcg1969, I'm not sure this is the right fix, it could be that find_new_location is meant to be returning something different (possibly not doing the dirname?).
> plan: Fix re-install when sha1 differs

- conda/cli/activate.py
- conda/install.py
- conda/utils.py
- tests/test_activate.py
We need to use the same shell name as is identified in utils.py
shells, otherwise find_parent_shell() will return an executable
that cannot be found there later.
Also use /usr/bin/env to run the shell, fix one typo and two
badly formatted lines.
> install: Use bash not sh as POSIX shell on Windows

- conda/utils.py
It seems ConEmu has a preference for sh.exe.
Fixes https://github.com/conda/conda/issues/2509
> MSYS2: Also allow sh.exe as shell

- conda/api.py
- conda/cli/main_info.py
- conda/config.py
- conda/fetch.py
- tests/test_config.py
Motivated by #2513. While investigating that issue, I discovered that `canonical_channel_name` would not return the correct result if the platform suffix (e.g., `/noarch`, `/osx-64`) was included in the URL, so I fixed that as well.
The primary fix for #2513 is to have `fetch_index` call `normalize_urls` if the caller passes in a bare list/iterable of channels. This converts the list into the format needed later in `fetch_index` which is a dictionary: the keys are the long channel URLs, and the keys are (canonical channel name, priority) tuples.
Removed some unused options in `canonical_channel_name` as well.
> Fix 2513, fix canonical_channel_name when platform is appended

- conda/install.py
fixes #2525 
Initial attempt to address https://github.com/conda/conda/issues/2525. Haven't tested yet, but since it's the end of the day I thought I'd commit: @kalefranz @ilanschnell @mingwandroid 
The one "wrinkle" is the need to replace `url_channel` in standalone mode. To do this, I basically use the full channel URL, minus the trailing slash, as the so-called "short" channel name. All that matters, really, is that the channels give distinct short channel names. But this is the part that needs to be exercised the most.
> WIP: Restoring ability to run conda.install standalone

- README.rst
Since #2094 was merged, tests require the `pytest-cov` package to run. Include this in the instructions.
> Running tests also requires pytest-cov package

- conda/api.py
While investigating #2538 I noticed something interesting. On Linux-64, I did this:
```
conda install -c Massimo cryptography
conda update cryptography
```
The first command installs version `1.1.1` of `cryptography`, as found in the `Massimo` channel. So far so good. The current version of `cryptography` in the default channel is `1.3.2`, so I expected the second command to upgrade it---but instead it kept the original version. 
The reason for this is that Massimo is not in the channel list for the second command---and packages that come from channels _outside_ the channel list are now being assigned the _highest_ channel priority. I thought this was going to be the best choice, because it would prevent accidental upgrades. But I'm afraid it has a worse effect, which is to prevent …
> Reduced priority for packages installed with `-c`

- conda/config.py
- conda/resolve.py
In #2203, a user reported a "bug" in the processing of the `track_features` entry in `.condarc`. @ilanschnell "fixed" this in https://github.com/conda/conda/commit/c6c0ea1d6181da3be5b32da78857e74124d4e8eb
It turns out it wasn't a bug. Ever since the `track_features` setting was added to `.condarc`, it was expected to be a string, which was then `split()` to separate the elements into a list; see https://github.com/conda/conda/commit/9caa576ffa5b5db04883a129922ef3c3e8fd80ee
Sure enough, one user depended on the old behavior and reported issue #2524. Now we have users depending upon both syntaxes. This PR supports both, by splitting `track_features` only if it is a string.
> Allow track_features to be a string *or* a list in .condarc

- conda/cli/install.py
The world's shortest pull request: *one character.*
The function `add_defaults_to_specs` adds a `python 2.7*` spec (or `3.5*`, etc. as appropriate) to the spec list for `conda install/update/remove` to ensure that Python is not upgraded undesirable version boundaries. Very useful function.
Unfortunately, `conda install --force` was incorporating this spec into its version upgrade. e.g, `conda install --force numpy` would reinstall _both_ `numpy` and `python`, when it should just install `python`.
Like I said, though, a one character fix.
> Don't try and reinstall python if not specifically asked for

- conda/bundle.py
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_list.py
- conda/cli/main_search.py
- conda/history.py
- conda/install.py
- conda/packup.py
- conda/plan.py
- conda/resolve.py
There were still a couple of places that rely on the `dist` strings taking the form `name-version-build`, though they are now `channel::name-version-build`. The best thing to do in general is to retrieve `name`, `version`, and/or `build` from the package index itself and not rely on parsing the build string.
I'll look carefully for other places where this assumption is made.
Addresses #2543
> Fix dependency on dist string format

- conda/cli/main_remove.py
`conda remove -n <env> --all` shouldn't bother downloading an index.
> Don't fetch an index if we're removing everything

- conda/install.py
- tests/test_install.py
I broke `_dist2filename`. Not sure why tests didn't catch it so I've added new tests for `dist2quad`, `name_dist`, `_dist2filename`, and `_dist2pair`. #2554
> Fix regression due to mgrant/urlmeta

- conda/resolve.py
Fixes https://github.com/conda/conda/issues/2559, which was caused by the way the `Resolve` class handles the obscure `with_features_depends` metadata entry.
May we never document that feature, and cease to use it ourselves. It should be replaced with separate packages with distinguishing build strings. But at least this prevents it from breaking for the packages that already use it.
> Prevent repeated processing of with_features_depends

- bin/deactivate.bat
Otherwise other find executables such as GNU find may
get found and the parameters won't be understood.
GNU find returns:
FIND: unknown predicate `-h'
.. and therefore `conda ..deactivate -h` does not get called.
Note, we explicitly using `System32` here, but that's the
right thing to do since Windows substitutes this for `SysWOW64`
at a low level when appropriate.
Also use the correct case for find.exe since it is possible
(but uncommon) to run the Windows kernel case-sensitively.
> deactivate.bat: Use full path for Windows find.exe

- conda/install.py
- tests/test_install.py
The relpath() calculation was only added as a debugging aid in
56539d, but it made a dangerous assumption that the path being
trashed was a subfolder of the root environment.
Now, people have been using it with folders that are not in the
same hierarchy at all and this leads to escaping the .trash dir
(and potentially the root prefix) so here we guard against this
security issue.
To do so, we normalize and remove any leading '..' from the path.
This has a nice side effect of preventing *any* '..' from making
their way to the final UNC trash path, which is required because
UNC paths must be absolute and normalized for Windows to process
them.
.. which fixes:
https://github.com/conda/conda/issues/2582
.. and gets to the bottom of the code smell in:
https://github.com/conda/conda/issues/2579
> install: Make move_to_trash less frightening

- tests/helpers.py
When running the test suite locally, I get a few test failures caused by the presence of the informational stderr message
```
Using Anaconda Cloud api site https://api.anaconda.org
```
This PR creates a variable called `expected_error_prefix`  n `tests/helpers.py`. The value of `expected_error_prefix` is initialized to the above string. The helper functions `run_conda_command` and `capture_with_argv` call a new function `strip_expected` on their captured value of `stderr`, which looks for the presence of the above string and removes it.
I'm open to alternative approaches but I'd really rather not have test failures locally.
> Strip the anaconda cloud message from test stderr

- conda/api.py
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/config.py
Studying the code while fixing other issues reveals that support for `--offline` is a bit of swiss cheese. 
This PR takes the approach of siphoning off the `--offline` argument and immediately dumping it into `config.offline`. By moving the `offline` spec into the global configuration, it greatly reduces the number of functions that need to maintain an `offline` input argument. Instead, only the functions that must explicitly make offline decisions (e.g., `normalize_urls`) need worry about offline logic.
> WIP: More aggressive enforcement of --offline

- conda/api.py
- conda/cli/install.py
- conda/fetch.py
- conda/resolve.py
- tests/test_version.py
`invalid_chains` finds the "dependency" chains from a top-level package to any missing dependencies. In #2415 a report of infinite recursion was reported. This is fixed here; and while fixing, I cleaned up the error messages.
> Fix #2415: infinite recursion in invalid_chains

- conda/cli/main_list.py
- conda/history.py
- conda/install.py
- conda/plan.py
- conda/resolve.py
- tests/test_install.py
Addresses #2570 and #2569, which is actually a continuation of the problem encountered in #2559 that I attempted to address in #2562.
Technically both #2570 and #2569 would go a way with the one-line fix in resolve.py included here. But in the process of studying the formatting issue in #2569 I realized that further cleanup of the dist string processing would be necessary, so that is included here as well.
> Fixes #2570, further cleanup of dist formatting

- CHANGELOG.txt
- appveyor.yml
- conda/install.py
- tests/test_install.py
The relpath() calculation was only added as a debugging aid in
56539d, but it made a dangerous assumption that the path being
trashed was a subfolder of the root environment.
Now, people have been using it with folders that are not in the
same hierarchy at all and this leads to escaping the .trash dir
(and potentially the root prefix) so here we guard against this
security issue.
To do so, we normalize and remove any leading '..' from the path.
This has a nice side effect of preventing *any* '..' from making
their way to the final UNC trash path, which is required because
UNC paths must be absolute and normalized for Windows to process
them.
.. which fixes:
https://github.com/conda/conda/issues/2582
.. and gets to the bottom of the code smell in:
https://github.com/conda/conda/issues/2579
> merge 4.0.x to master after 4.0.8

- .codecov.yml
- conda/utils.py
- tests/helpers.py
- tests/test_config.py
- tests/test_create.py
This PR contains a simple, an in-process integration test framework for conda installs.  Right now, all relevant code is in the new `tests/test_create.py` file.  The framework right now is limited to a one-shot `conda create ...` call.  In the future, I'll extend it to be able to run additional `conda install ...` calls within the temporary environment.
CC @mcg1969
> create some create tests

- conda/plan.py
- conda/resolve.py
An initial attempt to address #2572 revealed several issues:
- [Lines 368-369](https://github.com/conda/conda/blob/6c19525611c8fd4f4f02bad3ff752931860fd637/conda/plan.py#L368-L369): why just look at `specs[0]`?
- [Lines 388-389](https://github.com/conda/conda/blob/6c19525611c8fd4f4f02bad3ff752931860fd637/conda/plan.py#L388-L389): we should make this independent of the minor version of Python
- [Line 394](https://github.com/conda/conda/blob/6c19525611c8fd4f4f02bad3ff752931860fd637/conda/plan.py#L394) This needs to be skipped for `lua`, otherwise we end up inserting `lua None*` as a spec.
Another issue _not_ addressed by this PR is in [lines 356-359](https://github.com/conda/conda/blob/6c19525611c8fd4f4f02bad3ff752931860fd637/conda/plan.py#L394): this only scans the first layer of …
> Basic fixes for add_defaults_to_specs

- conda/install.py
The new package cache logic fails if the package directory does not exist; see #2596
> Fix #2596: Properly handle absence of package directory

- conda/plan.py
- conda/resolve.py
- tests/test_plan.py
- tests/test_resolve.py
Try this:
```
conda create -n test -c conda-forge python=3.5
conda install -n test decorator
```
(There's nothing special about `decorator`; any package will do.) On master, this will cause the `conda-forge` version of Python to be replaced with defaults, but there's no need for this. Furthermore, it _says_ it is replacing the conda-forge Python with... conda-forge Python. That's just a printing error, but it will be fixed in the second commit.
> Eliminate unnecessary python updates

- conda/install.py
Conda packages should always install the same way, so it would not be good to have this environment variable available in the post-link step.
> remove PKG_CHANNEL from environment

- conda/install.py
- conda/plan.py
- tests/test_create.py
See #2599 
This does three things:
- Ignores `.json` files in `conda-meta/` whose filenames do not match the underlying package name
- Ignore filenames in `add_defaults_to_specs` that aren't found in the index for some reason
- A change I had made to pull the dist name from `r.index` instead of using `name_dist` was reverted for some reason: I've put that back. That was actually the code that caused the bug anyway.
I'm adding an integration test. Wait for that before merging
> Handle invalid metadata files

- conda/cli/main_remove.py
- tests/test_create.py
The current version of `conda remove -n env --all` doesn't retrieve any information about the installed packages. Previously this didn't matter, but now that we care more about channels, it does. The current version, for instance, prints this:
```
Package plan for package removal in environment /Users/mgrant/miniconda2/envs/test2:
The following packages will be REMOVED:
openssl:    1.0.2h-1      <unknown>
pip:        8.1.2-py27_0  <unknown>
python:     2.7.11-0      <unknown>
readline:   6.2-2         <unknown>
setuptools: 22.0.5-py27_0 <unknown>
sqlite:     3.13.0-0      <unknown>
tk:         8.5.18-0      <unknown>
wheel:      0.29.0-py27_0 <unknown>
zlib:       1.2.8-3       <unknown>
```
But it should print something like this:
```
Package plan for package removal in environment …
```
> Get channel information during remove --all

- conda/misc.py
- conda/resolve.py
- tests/test_create.py
Addresses #2633, #2510 and others.
Clone functionality has already been greatly improved in 4.1. However, the new version of clone fails with older environments where the original URL is not available in the installed metadata (in the `conda-meta`) directory.
What this does is assemble a list of these "orphan" packages. If that list is non-empty, it fetches the channel index according to the current `.condarc` settings, and attempts to match each package filename to a record in that channel index. If a match cannot be found for one or more orphan packages, an error will be raised. The user can then add additional channels into their channel list and re-try.
Moving forward, the full URL where the package was retrieve is saved in the metadata, so future cloning operations can be done much …
> Handle clones of environments with no url metadata

- conda/resolve.py
On some of our Linux 64 Travis CI test we were finding that _sometimes_ `conda` give this package list for `conda create -n test -c conda-forge install python=3.5`:
```
ca-certificates: 2016.2.28-0   conda-forge
ncurses:         5.9-7         conda-forge
openssl:         1.0.2h-0      conda-forge
pip:             8.1.2-py35_0
python:          3.5.1-0
readline:        6.2-0         conda-forge
setuptools:      23.0.0-py35_0
sqlite:          3.13.0-1      conda-forge
tk:              8.5.19-0      conda-forge
wheel:           0.29.0-py35_0
xz:              5.0.5-1       conda-forge
zlib:            1.2.8-3       conda-forge
```
Notice the fact that `python` is _not_ coming from conda-forge as requested. What it _should_ be doing, and indeed it was doing correctly most of the time, is this: …
> Fix the occasional/random package resolution errors

- conda/install.py
- tests/test_install.py
This might be a fix for https://github.com/conda/conda-build/issues/997
> skip binary replacement on win; force / in replacement prefix on win.

- bin/activate
- bin/activate.bat
- bin/deactivate
- bin/deactivate.bat
- conda.recipe/meta.yaml
- conda/cli/activate.py
- conda/cli/install.py
- conda/instructions.py
- conda/utils.py
- setup.py
- tests/test_activate.py
As we very briefly discussed, this change ensures that some system prompt process is returned from find_parent_process, so that we can make a shell behave appropriately.
This should not affect activation scripts at all - their parents are always shells.
> fallback default process in find_parent_process

- conda/api.py
- conda/fetch.py
- conda/install.py
Fixes #2693. conda 4.1 is depending on the `link` entry in the `conda-meta` metadata to track which packages in the index are installed. Sufficiently old versions of Anaconda, such as those used by AppVeyor, are missing this information. We need to create it, otherwise `conda` will think packages are not installed, and install duplicates.
> Ensure info['link'] is accurate even for old installations

- conda/config.py
- conda/misc.py
fixes #2688. Logic needed to be added to `explicit` to better differentiate between file-based channels and bare files.
> Restore explicit file installs

- conda/console.py
- conda/resolve.py
@quasiben This reverts the dotlog thing.  But maybe Antione's suggestion was better than reverting this.  Will consider for 4.1.2.
Reference https://github.com/conda/conda/pull/2281 and https://github.com/conda/conda/pull/2005
> revert print progress bar terminal

- conda/plan.py
- conda/resolve.py
- tests/test_plan.py
Motivated by #2713, this PR improves the explanation that `conda` provides when downgrading packages. There are (now) two reasons to downgrade versions: 1) because the same package is available on a higher-priority channels; or 2) because dependency conflicts require it. We've partitioned the downgrade list into these two categories, and these are the messages I'm using:
```
The following packages will be SUPERCEDED by a higher-priority channel:
```
and
```
The following packages will be DOWNGRADED due to dependency conflicts:
```
> Improve messaging for "downgrades" due to channel priority

- conda/install.py
This bug, fixed the ability to create shell installers (using tolls like constructor).
> remove --shortcuts option to internal CLI code

- conda/connection.py
- setup.cfg
Closes #2725.
@dsludwig @bkreider 
I'm reverting the commits that disabled netrc files.  There's quite a bit of history here, and I just can't seem to get it right so far I guess.
Previous PRs were #2514 and #2695.
Issues filed were #2677 and #2725.  The original ticket is #2161, which I'm re-opening for discussion.
> revert disabling of .netrc files

- conda/cli/main_config.py
- tests/test_config.py
cc: @jreback
Any conda installation with no `.condarc` or with no `channels:` key should allow this:
```
conda config --remove channels defaults
conda config --add channels conda-forge
```
That's because, _logically_, a nonexistent `channels` key should be treated like `['defaults']`.
Furthermore: if I do this
```
conda config --add channels conda-forge
conda config --add channels defaults
```
It should *not* cause an error, because now _channel ordering matters_.
Finally. We need
```
conda config --add channels conda-forge
conda config --append channels defaults
```
so that we can allow channels to be placed at the end of the channel list.
> Support channel append/prepend, handle duplicates better

- bin/activate.bat
.. since ~dp0 can be in a folder with spaces.
Fixes https://github.com/ContinuumIO/anaconda-issues/issues/830
> activate.bat: Add quotes around %~dp0\deactivate.bat

- conda/install.py
This will need to be released before we can create Anaconda 4.1 installers.  Without those changes the link process (which follows the package extraction process, when running `.sh` installers) is broken.
CC @mcg1969 @kalefranz
> Restore functionality in install.main

- conda/cli/main_info.py
- tests/test_info.py
See #2808. Note that this affects *only* the output of `conda info`. There are other issues with proper honoring of offline mode that we must continue to investigate.
> Add offline mode to printed info; use offline flag when grabbing channels

- conda/cli/main_info.py
Given how many issues we're having with `conda env` being out of date it seems wise for `conda info` to print out its version. At least until we do the right thing and merge it into core conda.
> Show conda-env version in conda info

- conda/utils.py
Wasn't able to use `source activate` on Windows with Git Bash, but this fixed it.
> Git Bash executable is called bash on Windows

- conda/plan.py
If a package is being replaced with a version with the _same_ version number but a higher priority channel, it should be in the "superseded" list.
> Adjust channel priority superseded list

- conda/config.py
- tests/test_config.py
When someone mirrors the Anaconda repository and points the `default_channels` setting to their internal mirror, packages installed from the installer will be assigned the channel `<unknown>`. This PR recognizes these old URLs when canonicalizing the channel names, which helps to avoid an unnecessary "upgrade" from `<unknown>` to `defaults`.
A couple of potential improvements for later:
- Add `https://conda.anaconda.org/anaconda` to the hardcoded list
- Even better, make this configurable.
> Accept old default names and new ones when canonicalizing channel URLs

- conda/fetch.py
- conda/install.py
- conda/misc.py
- conda/plan.py
fixes #2746 
Some of the branches were using logic like `'url' in info`, but it looks like there are certain scenarios where the key could be present, but the value could be `None`---and we need to treat that case as well. This does some cleanup to that effect.
I believe this is the cause of issue #2746.
> Handle cases where info['url'], info['channel'] is None

- conda/resolve.py
@ilanschnell was encountering a performance issue where a `conda update` with a `-c` channel was causing a significant slowdown. 
This is only going to be a problem when the additional channel has a lot of the same packages as the existing channels. What happens is that `conda` tries to minimize the number of existing packages that need to be "touched" in order to accomplish a given install/update. Once that minimum number is established, _then_ it seeks to maximize the version and build numbers for those packages.
Well, if _none_ of the packages need changing, that second pass should be lightning-fast, because there's nothing to do. Only, it's not. For technical reasons, it is still including those packages in the version maximization pass---and thanks to the addition of a new …
> Skip dependency version/build optimization if no dependency updates

- conda/install.py
The failure to link to a file during installation is now treated like other errors -- it exits the script.  To address the silent swallowing of link errors described in [this comment](https://github.com/conda/conda/issues/2437#issuecomment-224662622) on issue #2437.
> Exit on link error instead of logging it

- bin/activate.bat
- conda/install.py
Calling the activate scripts is especially important. This was causing builds to mysteriously stop just after activation.
Error checking here isn't strictly necessary, but it probably doesn't hurt.
CC @kalefranz @mingwandroid
Originally submitted as #2849 - resubmitted here to apply to 4.1.x branch.
> call scripts with redirect on win; more error checking to activate

- bin/activate
- bin/activate.bat
- bin/deactivate
- bin/deactivate.bat
- shell/conda.fish
CONDA_DEFAULT_ENV is not always valid here.  For environments activated by name, activate.d scripts will (usually) not actually run, since the path logic will fail.  This fixes those to use CONDA_PREFIX.
CC @kalefranz - please get this in before you release the other related changes that you have already merged.
> use CONDA_PREFIX, not CONDA_DEFAULT_ENV for activate.d

- .travis.yml
- conda/install.py
- tests/test_install.py
cc: @kalefranz @msarahan @mingwandroid 
Using bisection I determined that issue #2846 has been with us since 4.0.6. It turns out that the cause was [this commit](https://github.com/conda/conda/commit/226ac99f07e8394e025de6f18be86f2a927d3c1c), submitted in PR #2542. It turns out that, for reasons yet undetermined, `shutil.move` is unable to move open files to the trash when the trash directory uses a UNC pathname. We don't know why.
So why use UNC pathnames at all? The motivation for this PR was https://github.com/conda/conda-build/issues/891; the pathnames generated for `move_path_to_trash` were too long for Windows. But that's in part because, for some reason, `conda` was determined to preserve the _entire path_ to the deleted file (relative to `root_dir`) inside the `.trash` directory. …
> Revert the use of UNC paths; shorten trash filenames

- conda/install.py
- tests/test_install.py
@mcg1969 I think this isn't going to be trivial for me to port back to 4.0.x.  Looks like there's a lot of stuff you use that's not in the 4.0.x code line.
cherry-picked from #2859
> Trash fix 4.1

- conda/cli/conda_argparse.py
- conda/cli/find_commands.py
Currently, when typing `conda`, `conda -h`, `conda --help`, one get horrible output shown below.  Apart from the fact that this operation takes a long time, it is not really useful for the user.  In this PR, we remove all the subprocess calls, and reduce the conda help information to the conda builtin commands themselves.
```
$ conda --help
usage: conda [-h] [-V] [--debug] command ...
conda is a tool for managing and deploying applications, environments and packages.
Options:
positional arguments:
command
info         Display information about current conda install.
help         Displays a list of available conda commands and their help
strings.
list         List linked packages in a conda environment.
search       Search for packages and display their information. The input
is a Python …
```
> remove excess output from conda -h

- conda/cli/main.py
See #2864, #2801. Simple fix necessitated by a change in argparse in Python 3.3; see
http://stackoverflow.com/questions/18282403/argparse-with-required-subcommands
I recommend cherry picking to 4.0.x and 4.1.x.
> Graceful exit for `conda --debug`, `conda --json`, etc. with no command

- conda/install.py
People are seeing strange issues with conda-build, where activation overwrites the root prefix activation scripts with the bat redirect scripts.  This avoids clobbering those scripts, which should at least prevent things from breaking.
> Change root prefix detection to avoid clobbering root activate scripts

- conda/install.py
- tests/test_create.py
- tests/test_install.py
A proper fix for #2876 and related issues.
The problem is this: when removing an extracted package from the package cache, the `rm_rf` command will fail if any one of the files inside that package directory is open. This prevents conda from moving the new package into place.
The solution, in my view, is to make more aggressive use of `move_path_to_trash`: specifically, the _first_ step on Windows should be to move the directory to the trash, _then_ attempt a full deletion. The `os.rename` in `move_path_to_trash` is far more likely to succeed, and any failure during the deletion process will be benign (except for the unclaimed disk space).
For files, it is still better to try `os.unlink` first, but then if that fails, attempt `move_path_to_trash` as well.
This logic allows us to simplify …
> More aggressive use of move_path_to_trash to fix permissions issues

- conda/plan.py
Until such time as we remove auto updating of conda altogether, or make it more default to `false`, I propose we add these changes to make it more conservative:
- Don't add updates to `conda` or `conda-env` if either of them are explicitly specified or pinned.
- Don't allow version downgrades for `conda` (unless explicitly requested, of course, but this is covered by the previous rule).
Motivated by #2898.
> More conservative auto updates of conda

- conda/install.py
- conda/misc.py
- tests/test_create.py
Fixes #2886, #2907. Installing a tarball _directly from the package cache_ was failing.
Fix provided, and the integration test `test_tarball_install_and_bad_metadata` has been expanded to include two different package cache installs: one from the `defaults` channel and one from a local channel.
> Handle tarball installs from cache

- bin/activate.bat
- bin/deactivate.bat
- conda/cli/activate.py
- tests/test_activate.py
This is meant to address #2914.  Rather than store a backup PATH, we add/remove with shell scripting.  This also has a placeholder feature with the deactivate script - when passed any argument, it leaves a placeholder.  The activate script then puts the new path entries there, rather than always prepending.
This PR does not address this issue with the bash shell scripts.
> add/subtract from PATH; kill folder output text

- conda/cli/install.py
- conda/misc.py
- tests/test_create.py
The bug revealed by https://github.com/conda/conda/issues/2925 is due to the fact that the `explicit` code in `misc.py` is not honoring the command-line channels list. This is preventing packages with `<unknown>` channels from being resolved.
> Normalize use of get_index behavior across clone/explicit

- conda/install.py
Windows case insenstivity causes some major issues, ending in root activate scripts being overwritten with shortcuts, leading to infinite recursion and tears.
Solution suggested by @ajspeck in https://github.com/conda/conda/pull/2880/files/1e7673b4ccdeb8e625fb21c6aa0fe3378ef2e3dc#r69057375
> wrap root prefix check with normcase

- conda/install.py
@mcg1969 @mingwandroid 
I'm including this in the `4.1.6` release to go out shortly.
This changes the "max total time" from about 3.2 seconds to 6.5 seconds.  Meaning the final sleep has a time of 3.2 sec, with the total cumulative time before failure being 6.5 sec.
> bump max total time on exp_backoff to ~= 6.5 sec

- conda/plan.py
- conda/resolve.py
- tests/test_create.py
Inspired by #2946. Do a better job of error messaging if someone attempts to install `conda` into a non-root environment. In particular, if `conda` is selected _by dependency_, then this will find out which specs may have caused it.
> Better error behavior if conda is spec'ed for a non-root environment

- conda/api.py
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_info.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/config.py
- conda/fetch.py
- conda/plan.py
- tests/test_config.py
- tests/test_create.py
Here's the strategy for fixing #2939 without re-breaking #2556:
- Created a new function `init_binstar()` to grab the binstar domain and the tokenized domain. Placed these in _separate variables_ from `channel_alias`, so we can still refer to them if the user has changed `channel_alias` to point away from their Anaconda Server instance (as we saw in #2556).
- Created a new function `channel_prefix()` that returns the proper value of `channel_alias`. From now on, `channel_alias` is accessed only through this function, so that it can be properly initialized when first needed. If `channel_alias` is `None` when this function is first called, it will be set to the Anaconda Server URL; but if it has been hardcoded, it will not be changed. 
- `channel_prefix` actually has two arguments: `token` …
> Fix channel_alias issues; improve offline enforcement

- conda/misc.py
- tests/test_create.py
See #2970. Really frustrating getting all of these corner case worked out. In this cases, someone is using an absolute path to a tarball in the `conda-bld` directory. You would think we have that case covered. Well, we do now, though with some difficulty---I will not be surprised if we have an initial test failure here. The reason is that local testing is necessarily different than CI testing in this case, because locally the tests are running against my existing installation.
> Improve handling of file:// URLs inside channel

- conda/install.py
People are seeing issues with bat file redirects in the root environment being overwritten, leading to infinite loops.  I tried to solve this in before by refining the path checking, but that apparently didn't work.  This is more of a hack, but safer.
Issues: 
* https://github.com/conda-forge/conda-smithy-feedstock/pull/29#issuecomment-231543820
* https://github.com/conda-forge/conda-build-all-feedstock/issues/12#issuecomment-231340770
probably others that I'm missing.
> don't overwrite existing redirect shortcuts when symlinking envs

- conda/install.py
There is no reason to have an `os.remove` (identical to `os.unlink`) here, because files which are going to processed by `update_prefix()` are already ensured to be copies, see https://github.com/conda/conda/blob/master/conda/install.py#L1060, so there is no danger in destroying the hard-linked cache.  Moreover, since we are writing a new file (as opposed to appending) a new inode created anyway.
> remove os.remove in update_prefix

- conda/cli/install.py
- conda/cli/main_create.py
- conda/cli/main_install.py
- conda/config.py
- conda/install.py
- conda/instructions.py
- conda/plan.py
- tests/test_create.py
Closes https://github.com/ContinuumIO/navigator/issues/570
This changes shortcuts to again be installed by default, but adds a condarc setting "shortcuts" that can be set to False to disable shortcut installation.
CC @joelhullcio @csoja @multicastmatt
> partially revert no default shortcuts

- conda/cli/main_install.py
CC @msarahan 
This is just adding both a `--shortcuts` and `--no-shortcuts` flag for backward compatibility now.  The default is still set to `True` for installing shortcuts..
> put --shortcuts option back for backward compatibility

- conda/install.py
When running source activate on a read-only mounted file system we cannot affect the symlinks either, but it should not cause source activate to break if it exists as in other cases.
> Ignore symlink failure because of read-only file system.

- conda/cli/main_info.py
- conda/cli/main_remove.py
- conda/config.py
- conda/plan.py
In this PR, we add the ability for conda to reside in the `_conda` environment. Don't worry, conda will still work when installed in the root environment. This is achieved by having a Boolean config variable `config.conda_in_root` (and `config.conda_private` for convenience inience) in order preserve old behavior.  Also, because the `_conda` environment is considered private, it is not treated special in any way. That is, you can install or remove any package from `_conda`, even `conda remove -n _conda conda`.
To do (all these items imply that `config.conda_private` is `True`):
* `conda update conda` will have to somehow alias to to `conda update -n _conda conda`. Should regular usage of conda try self updates too?
* think about disallowing `conda install -n root conda`, as it would …
> ability to have conda reside in private environment

- bin/activate
When using a more sophisticated shell prompt the `activate` script does not work properly.
The error in my zsh is:
```
13:16:17 conda                                                                        proper_ps1_backup_when_activate_env✓
‣ source activate foobar
/Users/blindgaenger/anaconda/bin/activate:export:65: not valid in this context: "+%T"`%{$reset_color%}
```
I'm using the fix by @Zibi92 described in #3042 👍
> fix PS1 backup in activate script

- conda/cli/install.py
- conda/plan.py
fix the bug for empty environment
In original code, if it is a install-action, and everything is already installed, the program however will create a empty environment. This is caused by https://github.com/conda/conda/blob/master/conda/plan.py#L525. Now, there is always symlink in action, which means it cannot pass nothing_to_do function in https://github.com/conda/conda/blob/master/conda/cli/install.py#L363.
Here is a tmp fix
@kalefranz  @dorzel
> tmp fix for empty env

- conda/cli/install.py
- conda/exceptions.py
- conda/plan.py
Conda install --revision number, when the packages in old state is no long available in repodata, it will raise a keyError, which is not good. 
Now a CondaRevisionError will be raised if there is potential keyError in future. However, still need to improve this one, and tell user to revert to a most recent stable version.
#3158
> check revision

- conda/cli/common.py
If user say no, may be there is no need to raise a condaSystemExitError(condaError). If so, when in debug mode, it will show the trace back info
> SystemExit with user choice 'no'

- conda/models/channel.py
fix bug for --use-local, 
in https://github.com/conda/conda/blob/master/conda/models/channel.py#L74, the code will iterate through self._local_url, which is return of get_conda_build_local_url(). However , that function will return a str instead of a list, so it will never match for 'local' channel.
> fix conda-build local channel bug

- conda/base/context.py
- conda/cli/activate.py
- conda/cli/install.py
- conda/cli/main_list.py
- conda/cli/main_remove.py
- conda/exceptions.py
- tests/test_activate.py
This PR fixes 2 issues
1. Do not remove empty environment without asking
2. Raise `CondaValueError` when a named environment can't be found
> Remove fix

- conda_env/specs/requirements.py
conda env create --file xxx.txt does not handle whole-line comments very carefully.
Should skip if line.strip() is None to line start with "#"
Fix issue #3253
> Fix #3253: conda env create from a txt file, handle comments carefully

- conda/cli/common.py
- conda/misc.py
- tests/test_create.py
For install tar from local, it goes to misc/explicit function. In this function, when specify the link action, it will ignore the link type from context or --copy from command line.
Add code to fix this , please refer to issue #3182
> change for copy setting

- conda/cli/main_list.py
- conda_env/cli/main_create.py
This PR solves 2 issue related to empty environment
1. conda list -n empty-environment should not return 1 as return code
2. conda env create -f empty-environment.yml cannot handle empty environment
> Fix empty environment issue in conda and conda-env

- tests/conda_env/cli.py
- tests/conda_env/support/notebook.ipynb
- tests/test_create.py
Add more conda env integration test
1. test conda env --help
2. test conda env remove
3. test conda env export and conda env create
4. test conda list -e and conda create --file xxx.txt
Following instruction here : http://conda.pydata.org/docs/using/envs.html#export-the-environment-file
> Testcase : add integration test for conda-env

- conda/cli/main_list.py
Fix issue #3277 .
When sorting the package, the name should be pure name without channel prefix
> Fix issue #3277 : change conda list sorting key

- conda/models/channel.py
When duplicated channel in channel_urls list, priority of channel may be wrong.
Fix with a check
> Fix Channel Priority issue with duplicated channel

- conda/cli/install.py
"Conda install "  should raise error .
ToDo:
1. Change conda install --help, a package or file name is required 
2. Empty environment should not fetching index
3. Better error message. 
4. Optional : 2 new line below conda error message. too much \n !
> Fix Conda install No package specified

- conda/plan.py
- tests/test_create.py
The prune option is used only by conda-env and it was not being tested
neither by conda nor conda-env.
> Fix prune option when installing packages

- conda/cli/main_config.py
- tests/test_config.py
- tests/test_create.py
- tests/test_export.py
- tests/test_info.py
- tests/test_install.py
- tests/test_instructions.py
- tests/test_lock.py
- tests/test_logic.py
- tests/test_misc.py
- tests/test_plan.py
- tests/test_priority.py
- tests/test_resolve.py
- tests/test_toposort.py
- tests/test_utils.py
Changes 'conda config --add' back to prepending behavior. Now aliases with 
--prepend
response to #3336
> Config --add back to prepend behavior

- conda/install.py
Since unicode_literals are used a fair bit, this replaces them at the
point of setting them in an env with str-ified versions.
> Account for the Windows Python 2.7 os.environ unicode aversion

- bin/activate.bat
We have a problem with the activate scripts where if PATH is too long, there is one particular command in activate.bat that barfs because the command is too long.  This replaces that command with a similar way of doing it in Python that does not violate these length constraints.
Further explanation from chat with @mingwandroid:
that bit in activate.bat is saying basically "is the placeholder in PATH", but batch is awkward, and so it has to fully expand the original PATH, and the modified PATH to do the comparison.  So for long PATH, we have a very, very long command line: PATH x2 + a bit
See example error at https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/build/1.0.504/job/470lesgbhsj9ixt9#L999
CC @mingwandroid @kalefranz
> change check for placeholder to be more friendly to long PATH

- conda/lock.py
- tests/test_lock.py
@kalefranz 
This PR will fix #3307 , add try / except block when creating files . Even no lock , as long as not run multiple process at parallel, conda is safe 
Generally, we will add a try/except block when create lock file. That is what we do for conda 4.1 [here](https://github.com/conda/conda/blob/4.1.x/conda/lock.py#L69-L72)
> Fix #3307 Add try/except block for touch lock

- conda/cli/main_clean.py
- conda/exceptions.py
- tests/test_lock.py
This PR clean the lock on finally block in exception handler
1. add delete lock function
2. add extra parameter for find_lock, give extra input of path, and lock file extension
3. add test cases for  delete_lock
> Clean the pid based lock on exception

- conda/common/disk.py
- conda/exceptions.py
- conda/install.py
- conda/instructions.py
- tests/test_create.py
resolves #3433
@msarahan can you review?
So this really was a bug with the new `rm_rf` code.  The issue was using `os.exists` and `os.stat` instead of `os.lexists` and `os.lstat`.
> fix #3433 rm_rf fails to remove broken symlinks

- conda/connection.py
Making this change after chatting with @dsludwig working to address #3442.  Much more work needs to be done here.  But this changes clearly incorrect code to something that might possibly be closer.
> remove remote_site from binstar get_config

- conda/cli/main_list.py
- tests/test_create.py
- tests/test_export.py
> Bring back `conda list --export`

- conda/config.py
- tests/test_config.py
If an Anaconda server's domain name contains `api`, the `channel_alias` substitution is incorrect. The `api` to `conda` substitution needs to be done only at the end of the URL.
> Fix the api->conda substitution

- conda/version.py
Did a little profiling and found a simple way to speed up the solver: by memoizing the creation of VersionOrder objects. On my computer, this drops `py.test tests/test_resolve.py` from 2.7 seconds to 2.0 seconds. This could easily be cherry-picked into 4.1 and 4.2.
> Cache VersionOrder objects to improve performance

- conda/common/disk.py
- tests/common/test_disk.py
Supersedes #3605.  Repointed to 4.2.x branch.
Resolves #3600.
> Ensure links are removed when unlinking

- conda/cli/common.py
Before, it was the same as for --no-update-dependencies, which doesn't make sense, see [here](https://github.com/conda/conda/compare/master...bilderbuchi:patch-1#diff-ae6ced2baf06e49bf278c2c66aa0d7d0R300).
Ping @asmeurer who originally wrote the original, correct string, which was changed at some point.
> Fix help string of --update-dependencies option.

- conda_env/installers/conda.py
- tests/conda_env/support/example/environment_pinned.yml
- tests/conda_env/support/example/environment_pinned_updated.yml
- tests/conda_env/test_create.py
When updating an environment, the currently installed packages were not
being considered, so new versions of packages were installed without
uninstalling old versions.
> Fix duplicated packages when updating environment

- README.rst
Tests now require a few more packages to run cleanly.
> Add additional test dependencies

- conda/common/configuration.py
> allow conda config files to have .yaml extensions or 'condarc' anywhere in filename

- conda/connection.py
This PR reverts #2380.  boto 2.42.0 is now available in the defaults channel.
@jseabold ok with you now?
> revert boto patch from #2380

- LICENSE.txt
Github is supposed to [recognize license files now](https://github.com/blog/2252-license-now-displayed-on-repository-overview), but it apparently doesn't recognize conda's LICENSE.txt as BSD 3-Clause.  
This PR should fix that.  The text is copied directly from 
http://choosealicense.com/licenses/bsd-3-clause/
> modify LICENSE.txt so that github recognizes it as BSD 3-Clause

- conda/cli/main_remove.py
By default conda cli looks for environments in the current directory as a last resort.
So, if we issue 'conda remove -n name --all' and 'name' is found in the current directory (e.g., $HOME) conda 4.1.x will proceed with the removal of this directory and all of its contents without asking for confirmation.
> fix silent directory removal

- setup.py
Adds an entrypoint for `conda-env` to `setup.py`.
> Add `conda-env` entrypoint

- conda/cli/main_config.py
- conda/models/channel.py
- Add method `__json__` to class 'Channel'
- Use EntityDecoder in execute_config to serialize output
Fixes #3807
> Fix json dump on conda config --show --json

- conda/misc.py
The command:
$ conda install https://repo.continuum.io/pkgs/free/linux-64/affine-1.1.0-py27_0.tar.bz2 --debug
Reveals:
DEBUG conda.common.disk:rm_rf(198): rm_rf /home/wani/conda/.tmp-affine-1.1.0-py27_0
The command:
$ conda install /tmp/affine-1.1.0-py27_0.tar.bz2 --debug
Reveals:
DEBUG conda.common.disk:rm_rf(198): rm_rf /home/wani/conda/file:/tmp::/.tmp-affine-1.1.0-py27_0
As is evident, when the protocol is file://, conda creates a bogus
folder by the name: file:/ + /path/to/folder/of/tar.gz + '::'
The variable 'prefix' is required by the function try_hard_link().
We shouldn't modify it before that. This change ensures that the
file ${prefix}/.tmp-${pkgname} is indeed created inside the folder
${prefix}.
Fixes #3801
> Fix location of temporary hard links of index.json

- conda/base/context.py
This PR follows #1637.  It adds a `pkgs_dirs` config parameter.  I have no idea how it will behave.  User beware. Use at your own risk.  At least, until we revisit package cache issues in 4.4.
It will also remain undocumented until it is tested and ready for prime time.
@mcg1969 Are you ok with this?
> add a pkgs_dirs config parameter

- conda/plan.py
Previously it was choosing specs from dists_for_envs which, without
matching to original specs, causing spec specifiers to be ignored
> Get install actions for requrired specs

- CHANGELOG.md
- conda/base/constants.py
- conda/core/link.py
- conda/core/path_actions.py
- conda/exceptions.py
- conda/gateways/disk/create.py
- conda/gateways/disk/update.py
Add an additional verification step to UnlinkLinkTransaction that
looks at the transaction as a whole, making sure that any
paths being linked are either unlinked first or don't exist
in the prefix.
Addressing more of https://github.com/conda/conda/issues/3494
> Additional pre-transaction validation

- conda/_vendor/auxlib/logz.py
- conda/base/context.py
- conda/common/disk.py
- conda/core/index.py
- conda/core/package_cache.py
- conda/gateways/disk/update.py
- conda/models/channel.py
- tests/core/test_index.py
- tests/test_create.py
- tests/test_fetch.py
- tests/test_misc.py
As users add more and more channels, just the process of getting `304` responses from remove servers can really slow down the experience.  Configurable local caching of repodata information with a modest timeout seems reasonable.  I've implemented it here, with a default timeout of 5 minutes.  Really all I'm doing is taking the `mtime` of the locally cached file into account (and updating it when the server tells us to with a `304`).
> Modest local caching of repodata without remote server calls

- conda/_vendor/auxlib/type_coercion.py
- conda/base/constants.py
- conda/base/context.py
- conda/cli/common.py
- conda/core/link.py
- conda/exceptions.py
- conda/gateways/disk/create.py
- conda/gateways/download.py
- tests/base/test_context.py
This PR implements a new configuration option, called `path_conflict`.  It has three possible values: `clobber`, `warn`, and `prevent`.  In 4.3, the default value will be `clobber`.  That will give package maintainers time to correct current incompatibilities within their package ecosystem. In 4.4, the default will switch to `warn`, which means these operations continue to clobber, but the warning messages are displayed.  In `4.5`, the default value will switch to `prevent`.
This PR also implements a `--clobber` command line flag.  Using it overrides the setting for `path_conflict` to effectively be `clobber` for that operation.
> Add clobber configuration

- tests/conda_env/test_cli.py
- tests/test_create.py
- tests/test_export.py
- tests/test_priority.py
Tests are failing due to the incomplete Python 3.6 package set.
> Hardcode some tests to avoid 3.6

- conda/history.py
- tests/conda_env/test_cli.py
- tests/test_create.py
- tests/test_export.py
- tests/test_priority.py
`linked` returns `Dist` objects, while `get_state` returns strings, and neither will be unordered, so it will never be true (except in empty environments) that `last == cur`.
> Fix history tracking

- conda/core/index.py
- tests/conda_env/test_cli.py
- tests/core/test_index.py
- tests/test_create.py
- tests/test_export.py
- tests/test_priority.py
This restores `add_unknown` functionality with a new function `supplement_index_with_cache`, and it simplifies `supplement_index_with_prefix` as well. It also moves `add_pip_dependency` into `get_index`.
> Add/fix supplement_index_with_*

- tests/test_export.py
We are very close to getting full channel support into conda env. Until then, this test continues to fail.
> Bump date to fix test_multi_channel_export

- conda/plan.py
- conda/resolve.py
- tests/test_export.py
- tests/test_plan.py
It doesn't make sense for there to be an UNLINK instruction for packages that are not in the index, now that all installed packages are included _in_ the index when constructing any plan.
Similarly, Resolve.match should never be called for a package that is not in the index.
More generally: `Dist` should move towards being nothing more than a record key, and should not assume to contain information like package name, version, etc. This will become much more important when namespaces come out.
> Do not consider dists that are not in the index

- conda/core/package_cache.py
- conda/misc.py
- tests/test_create.py
- tests/test_export.py
This modifies the `explicit` function, used both by tarball installs and clones, so that it fetches and extracts packages into the package cache before proceeding with the link/unlink step.
There are a couple of reasons for this. First of all, it eliminates the assumption that the name of the file can be parsed into a package name/version/build string triple. I've been wanting to jettison that assumption for some time; this is one of the places that proved more difficult to modify. (I'm working on the simpler cases in another PR).
Secondly, it paves the way for us to do proper dependency handling on tarball installs, if we so choose.
> Separate fetch/extract pass for explicit URLs

- conda/core/index.py
- tests/test_create.py
addresses #3708 
A valid repo must minimally contain a file (even if blank) `noarch/repodata.json` and `noarch/repodata.json.bz2`.  Right now, conda assumes that the platform directory for a channel always exists, and it causes errors when it doesn't.  We'll likely be adding new platforms soon, and noarch is/should be in all cases the common `subdir`.  anaconda.org is already compatible:
- https://conda.anaconda.org/kalefranz/noarch/repodata.json
- https://conda.anaconda.org/kalefranz/label/main/noarch/repodata.json
- https://conda.anaconda.org/kalefranz/label/NOPE/noarch/repodata.json
The changes needed to be made will mostly affect `conda/core/index.py` and `fetch_repodata`.  Right now, we assume a `404` response on `/noarch/repodata.json` is ok.  We simply need to flip the assumption, …
> Further refine conda channels specification

- conda/cli/main.py
- conda/install.py
The purpose here is to be able to call cli.main to run conda from within an existing process.  It's an alternative to the API that is present in conda 4.3.
> allow args passed to cli.main()

- conda/cli/main_remove.py
- conda/plan.py
- conda/resolve.py
- tests/test_create.py
- tests/test_resolve.py
I never did like how we had separate logic for removing features from an environment. The remove logic for normal packages should suffice. And it does suffice, with very minor modifications, as I hope you can see. The benefit here is no more special `remove_features_actions` method, no `find_substitute` method.
> Remove features properly

- CHANGELOG.md
target 4.3.x release branch
supersedes #4228
> Fix year in 4.3.2 release

- shell/activate
- shell/deactivate
Unfortunately this change would remain active afterwards and
this meant that normal variable delimiting did not work, so if a
script set CFLAGS="flag1 flag2", that value would be treated as
a single argument when passed to the compiler.
Instead `eval` and `find -exec echo` are used
{de,}activate
> {de,}activate: Do not use `IFS` to find scripts to source

- shell/activate.bat
This is necessary for shortcuts to work when users install and choose not to modify their PATH setting during installation
> Fix relative path to python in activate.bat

- conda/common/url.py
- conda/models/channel.py
This makes channel URLs of the type
file://\server\share\dir
and
file://\\server\share\dir  # Windows uses this form internally
work again on Windows after it stopped working in the 4.2.x branch after version 4.2.9. More precisely, the last good commit was 63c67adc0fd9cd187bec79abdd5ca23f8ff73297 and the first bad commit is 027ee0dc94c5d6d21e8ce5585d778859d11a8313. The intermediate commits are savepoints where conda install does not run.
It was mentioned in issue #3779 that some instances of `value = value.replace('\\', '/')` could be the cause of the URLs not working anymore.
This is a fix for the 4.2.x branch only, and relevant only if there will be more 4.2.x releases. The proper fix for Windows UNC network paths was already merged into 4.3.x in PR #4190. This 4.2.x fix does not …
> Do not replace \ with / in file:// URLs on Windows

- conda/cli/main.py
`main_modules` does not have the 'upgrade' and 'uninstall' aliases.
supersedes #4262
targeting 4.2.x
> include aliases for first command-line argument

- conda/connection.py
This steals more code from requests-ftp to handle FTP servers that return multi-line status codes. This code is taken from requests-ftp 40ce5fd.
I encountered this problem in the wild.
> Fix for multi-line FTP status codes

- conda/core/link.py
Existing pre-link scripts expect $PREFIX to be the destination
prefix into which the package is being installed.
In 4.3 that code changed, None gets passed as env_prefix so
prefix gets used instead which is now the package cache and
not the destination. The commit which made this change is:
95241d2c6e19fd8a3223e3c703a39db8a9dcdb8f
This bug can be reproduced by:
```
conda install conda=4.3
conda install -c continuumcrew anaconda-navigator
```
resulting in:
```
/home/ray/mc-x64-3.5/pkgs/anaconda-navigator-1.4rc2-py_1/bin/.anaconda-navigator-pre-link.sh: line 3: /home/ray/mc-x64-3.5/pkgs/anaconda-navigator-1.4rc2-py_1/bin/python: No such file or directory
```
> link: Pass target_prefix as env_prefix regardless of is_unlink

- conda/gateways/download.py
Issue can be reproduced by:
```bash
(root) $ touch /tmp/src.tar.gz
(root) $ python3 -c '
from conda import fetch;
fetch.download(url="file:///tmp/src.tar.gz", dst_path="dest.tar.gz")'
(root) $ python3 -c '
from conda import fetch;
fetch.download(url="file:///tmp/src.tar.gz", dst_path="dest.tar.gz")'
File "<string>", line 1, in <module>
File "/tmp/condadev3/lib/python3.5/site-packages/conda/core/package_cache.py", line 514, in download
gateway_download(url, dst_path, md5)
File "/tmp/condadev3/lib/python3.5/site-packages/conda/gateways/download.py", line 55, in download
maybe_raise(BasicClobberError(target_full_path, url, context))
TypeError: maybe_raise() missing 1 required positional argument: 'context'
```
`BasicClobberError()`: 'context' is a …
> Pass positional argument 'context' to BasicClobberError

- conda/gateways/download.py
Since the requests module encapsulates the decoding of data received
over HTTP(S?), the chunk obtained from `iter_content()` could be the
decompressed form of the actual data received over the wire. Now, the
'Content-Length' HTTP header holds the raw length of the HTTP body.
Since `streamed_bytes` always ends up calculating the total length
of the decoded data, it may not match the value present in the header
'Content-Length' received as a response to the initial GET request.
Possible scenarios include cases when the data is compressed using
either gzip or deflate mechanisms.
This patch fixes this by calculating `streamed_bytes` from the method
`requests.packages.urllib3.response.HTTPResponse.tell`, which returns
the number of (undecoded) bytes pulled over the wire so far.
Fixes #4299
> Calculate streamed_bytes correctly

- conda/install.py
See: https://github.com/conda/conda/issues/3001
This should fix a bug related to symlink race conditions on cluster shared filesystems.
Supersedes #4345.
Target is 4.2.x branch.  Will get merged up into 4.3.x for all future releases.
> workaround for symlink race conditions

- conda/cli/find_commands.py
- conda/utils.py
.. and use it in find_commands.py to account for the fact that conda
is installed into sub-environments as a symlink only and that sys.prefix
follows those symlinks meaning it does not give the environment's prefix
There may be other parts of the codebase that need to use this function
but find_commands.py fails to find external programs without this. It is
necessary to search both sys_prefix_unfollowed *and* sys.prefix in this
case as conda-build will often not be installed into the environment.
The failure here was seen when trying to run the test for conda-build-all
while building it through conda-build.
Do we really need to add C:\cygwin\bin here too? I hope not, at least not
in the non-'backwards compatibility' function.
> utils: Add sys_prefix_unfollowed

- conda/exceptions.py
- conda/install.py
@kalefranz this error is tripping up conda-build.  When I build in parallel, conda (or the OS beneath conda) is still doing some not-quite-synchronous I/O, and conda does not find files that should be there.  I have a retry mechanism in place, but the sys.exit that I replace in this PR is not friendly to that retry mechanism.
Please consider this PR as a more friendly error that will make the retry in conda-build work much better.
> change sys.exit to raise LinkError when info/files not found

- conda/core/index.py
- conda/models/index_record.py
- conda/resolve.py
- tests/test_resolve.py
This change prevents Resolve from having to copy and modify its index.
To accomplish this, all of the modifications have been moved to `conda.core.index` so they can be done during the `fetch_index`/`get_index` phase. I'll comment more later, for now I'm getting this pushed up for better testing.
> Eliminate index modification in Resolve.__init__

- conda/resolve.py
- tests/test_resolve.py
I remain bothered by the behavior of `Resolve.bad_installed`; see, for instance, #4394. This modification hopefully improves its behavior.
When a broken environment is found, `bad_installed` limits the set of packages that are considered to a consistent set. Previously, this consisted simply of all the packages specified on the command line, and their dependencies. This addition looks for the the largest subset of the installed packages that are consistent, and includes those as well. This way, we can be sure that `bad_installed` shouldn't make things _worse_.
This new version also makes the assumption that all of the packages passed in `installed` are, in fact, in the index. Given that we include the installed packages in the index before we ever call the solver, this is a reasonable …
> Expand scope of packages included by bad_installed

- shell/conda.fish
supersedes #4033
CC @zzag
targeting 4.3.x branch for next patch release
-----
While activating or deactivating an environment with `conda activate some-cool-env` or `conda deactivate` in fish shell, a warning is popping out, like 
```
No matches for wildcard '$activate_d/*.fish'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
~/Apps/Anaconda/etc/fish/conf.d/conda.fish (line 35):             source $activate_d/*.fish
^
```
or
```
No matches for wildcard '$deactivate_d/*.fish'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
~/Apps/Anaconda/etc/fish/conf.d/conda.fish (line 5):               source $deactivate_d/*.fish
^
```
We cannot source multiple scripts with a wildcard(usage is `source filename [arguments ...]`)! So, we have to source each script in a loop.
> Fixed "No matches for wildcard '$activate_d/*.fish'" warning.

- conda/cli/install.py
supersedes #4417 
------
Under `fish`, every `conda create` command produces this unvalid usage message. A correct suggestion would be `conda activate/deactivate`, and that's what I try to address here. I realize that there are plans to change all `source activate/deactivate` commands into `conda *` ones, but for the time being, I think this does not hurt anybody!
Also, I don't know if this way of checking the shell in use is the most elegant, but at least it works in my system. Further testing would be appreciated.
> Print correct activate/deactivate message for fish shell

- conda/base/context.py
- conda/core/index.py
conda 4.3 was released to only warn when noarch repodata doesn't exist.  This easily leads to "no packages available" errors when the error actually is an invalid channel.  This allows a debug option to enforce noarch repodata rather than just warn.
> add configuration to optionally require noach repodata

- conda/core/index.py
- conda/models/index_record.py
- tests/test_fetch.py
- utils/travis-run-install.sh
- utils/travis-run-script.sh
Builds on #4473. By moving the IndexRecord wrapping into the fetch_repodata tasks, we can cache those objects. Significant improvements in speed result for subsequent loads of the same channels.
For `defaults` and `conda-forge`: first call to `get_index`, no pickled data:
```
CPU times: user 7.5 s, sys: 209 ms, total: 7.71 s
Wall time: 7.79 s
```
Second call:
```
CPU times: user 834 ms, sys: 86.6 ms, total: 921 ms
Wall time: 1.11 s
```
The cost is, in my view, reasonable. Here is the equivalent call prior to this PR:
```
CPU times: user 6.6 s, sys: 127 ms, total: 6.73 s
Wall time: 6.94 s
```
> Pickle object-ified repodata for performance

- conda/core/index.py
@mcg1969 Ilan raised concern about having `.json` in the pickle path.  This PR just changes the filename slightly to remove the `.json` part.
CC @ilanschnell
> remove .json from pickle path

- conda/core/index.py
- tests/test_create.py
> fix #4513 null pointer exception for channel without noarch

- conda/common/compat.py
resolves #4567
supersedes #4583 
------
On new environment creation, subprocess_call function is called:
https://github.com/conda/conda/blob/33303158f070c0eda1ce0bbcb7807ddc7a4972d6/conda/gateways/subprocess.py#L62
Inside, this function calls ensure_text_type to validate standard output:
https://github.com/conda/conda/blob/7005e366a2a7dcd19430114c4a3d30f2eb735995/conda/common/compat.py#L154
However, ensure_text_type raises a Unicode error if the standard output includes not-encoded-in-utf-8 string.
I fixed this error by using chardet package.
> fix UnicodeDecodeError for ensure_text_type

- conda/core/link.py
This should have been done in #4451, but there was more work to do.  This PR should fix the issue.
CC @ijstokes
> disable old python noarch warning

- conda/base/constants.py
- tests/models/test_channel.py
- tests/models/test_dist.py
With the conda 4.4 release, we will officially be moving https://repo.continuum.io/pkgs/free/ to https://repo.continuum.io/pkgs/anaconda/.
> change default channel from pkgs/free to pkgs/anaconda in 4.4.0

- conda/resolve.py
Fixes #2384.
If the latest build numbers for "featured" and "unfeatured" packages are different, then `conda` will select the package with the highest build number during installation, without regard to whether or not the feature is present. This fix changes this determination by making build number maximization a lower priority than feature determination.
Note however if the _versions_ differ between the "featured" and "unfeatured" versions of a package, then conda will still prefer version maximization over features. At this point I'm not sure this fact can be avoided.
> Maximize requested builds after feature determination

- .travis.yml
- Makefile
- appveyor.yml
- conda/base/context.py
- conda/common/configuration.py
- conda_env/cli/common.py
- conda_env/cli/main_create.py
- tests/common/test_configuration.py
- tests/conda_env/test_create.py
- tests/test_activate.py
- tests/test_cli.py
- tests/test_create.py
- tests/test_install.py
- utils/functions.sh
- utils/requirements-test.txt
- utils/travis-run-install.sh
- utils/travis-run-script.sh
This PR took a lot of back-and-forth with Travis-CI, but I think the result it worth it.  Besides a few bug fixes to make everything pass, this PR adds a test target where conda is installed into a read-only prefix `/usr/local` so conda's executable is at `/usr/local/bin/conda`, and then the full test-suite is ran with a non-privileged user.
addresses #4649
> create sudo target for travis-ci test runs

- conda/core/repodata.py
This is roughly 2x faster for me on win with python 2.7.
It may be worthwhile to also investigate ujson for this serialization: https://github.com/esnme/ultrajson
There are some very interesting benchmarks at https://blog.hartleybrody.com/python-serialize/
CC @mcg1969 @kalefranz
> use cPickle in place of pickle for repodata

- conda/base/context.py
- conda/core/link.py
@mingwandroid This could help with your install time benchmark.  It'll be included in 4.3.14.
> add skip_safety_checks configuration parameter

- conda/gateways/disk/create.py
- conda/gateways/disk/permissions.py
- conda/gateways/disk/read.py
- tests/core/test_path_actions.py
A low-level response to https://github.com/conda/conda/issues/3974 and https://github.com/ContinuumIO/anaconda-issues/issues/1392.
This is targeted for 4.4.0 because I'd prefer a change like this go through a full feature canary cycle.
CC @mingwandroid
> never symlink executables

- conda/gateways/disk/delete.py
The `if` statement was wrong. If `path` was deleted correctly, it would never call
`delete_prefix_from_linked_data(path)` because at that stage it is neither a link
nor a file.
This bug turned up when trying to use `conda-build` variants. The build prefix did
not contain any packages for subsequent variants because `conda` thought they were
already installed.
If the `rmdir` fails, perhaps we could make a best effort fixup of marking the env
as 'ok to be trivially clobbered' or something like that? Here I have elected to
remove `path` from `linked_data` regardless of the (complete) success of `rmdir`.
The commit that introduced this bug was a1b79e58:
```
@@ -192,10 +192,10 @@ def rm_rf(path, max_retries=5, trash=True):
backoff_rmdir(path)
finally:
-                if not isdir(path):
+ …
```
> rm_rf: Remove incorrect elision of delete_prefix_from_linked_data()

- conda/resolve.py
> Fix arg name typo from "verison" to "version"

- conda/cli/main.py
- conda/exceptions.py
This PR pulls some logic out of `conda_exception_handler` and into its own function so that it can be used to prevent full stack traces that happen under expected circumstances during activate and deactivate.
CC @goanpeca
> fix exceptions triggered during activate

- conda/base/context.py
- conda/cli/main_config.py
- conda/config.py
- conda/plan.py
- tests/helpers.py
- tests/test_plan.py
@electronwill This will soon be merged, and while it's a new feature, I'm still going to break the rule and merge it into 4.3.  It'll probably be included in 4.3.16.
With this PR, packages can be pinned with configuration in a condarc file, rather than as currently documented [here](https://conda.io/docs/faq.html#pinning-packages).
Within a condarc file, users can add something like:
```
pinned_packages:
- python >3
- numpy 1.11
```
From the command line, you could do something like
conda config --env --add pinned_packages python=2.7
Notice the new `--env` flag there.  That's being added as part of https://github.com/conda/conda/pull/4913.  It just specifies that that config should be written to the active environment's condarc file--if there is one active--otherwise it'll fall back to …
> enable configuring packaging pinning with condarc

- conda/base/constants.py
Slight modification to make conda configuration SEARCH_PATH more consistent.  The complete search path is now
```python
SEARCH_PATH = (
'/etc/conda/.condarc',
'/etc/conda/condarc',
'/etc/conda/condarc.d/',
'/var/lib/conda/.condarc',
'/var/lib/conda/condarc',
'/var/lib/conda/condarc.d/',
'$CONDA_ROOT/.condarc',
'$CONDA_ROOT/condarc',
'$CONDA_ROOT/condarc.d/',
'~/.conda/.condarc',
'~/.conda/condarc',
'~/.conda/condarc.d/',
'~/.condarc',
'$CONDA_PREFIX/.condarc',
'$CONDA_PREFIX/condarc',
'$CONDA_PREFIX/condarc.d/',
'$CONDARC',
)
```
> make configuration SEARCH_PATH more consistent

- conda/cli/help.py
supersedes #5007, with target 4.3.x
resolves #5006
-------
The prefix location may contain spaces in the path -- quote the path
to handle this case.
> Quote prefix paths for locations with spaces

- conda/core/path_actions.py
- conda/gateways/disk/create.py
supersedes #5005
closes #5001
---
When creating entry point script use the template used by pip for creating
entry points for wheels.
> make python entry point format match pip entry points

- conda/cli/install.py
superseded #4993 
closes #4998
-----
If the pinned file contains multiple entries, the current code will
traceback. Instead, pack the result into a tuple which will safely
print.
> fix pinned string format

- conda/models/index_record.py
- conda/resolve.py
supersedes #5015 
closes #5017
---
@kalefranz, I'd really like if this could be merged into 4.3.  However, I'll settle for 4.4 if you deem necessary (but then conda-build 3 will require a release of conda 4.4).
@mcg1969 please take a look.  I think I've done what you and I talked about.  This works locally for me.
> add timestamp metadata for tiebreaking conda-build 3 hashed packages

- conda/base/context.py
If client_ssl_cert{_key} is set to None, or not set, then the value is
literally interpreted as the string "None" in the context of Conda. This
patch fixes this issue by:
- allowing the datatype for the value to be None
- setting the default value to None instead of ''
Fixes #5073
> Allow client_ssl_cert{_key} to be of type None

- conda/gateways/anaconda_client.py
fixes https://github.com/conda/conda/issues/5101
The current regex substitutor fails when the Anaconda Client URL ends in `/api` (which is, unfortunately, always). This needs to be cherry picked to 4.2, 4.3, and 4.4.
> fix api->conda regex substitution for Anaconda API channels

- conda/core/path_actions.py
The 4.4 branch ended up having even more of these race conditions happen for whatever reason than the 4.3 branch.  I caught them in basically every test run with conda-build.  This is a backport of the solution that seemed to work for now in the 4.4 branch.
CC @msarahan
> fix #4671 backoff for package validate race condition

- conda/base/context.py
- tests/base/test_context.py
Don't interpret proxy_servers as the string: "None" if param is
specified without any value. Similar to b517e48b
Fixes #5102
> Allow proxy_servers to be of type None

- conda/cli/main_remove.py
- conda/models/index_record.py
- conda/models/match_spec.py
- conda/resolve.py
- tests/models/test_match_spec.py
resolves #5121
@kalefranz check it. I'm not _using_ this yet, but I did at least add tests. This provides the ability to match on `features/track_features` cleanly even when there are multiple values embedded in those strings.
One trick is that I wanted `exact_field('track_features')` to return a non-`None` value even though I needed to use regex matching to accomplish this. So that's the explanation for the new `.exact` convention that you see in the `exact_field` function.
> Add features/track_features support for MatchSpec

- conda/activate.py
- tests/test_activate.py
Head start following #5044 for csh and xonsh shells.
One huge win out of this framework for both shells... We'll probably fairly soon be developing a new way to set environment variables outside of the current sourcing of scripts in `activate.d` and `deactivate.d` directories.  https://conda.io/docs/using/envs.html#saved-environment-variables
The problem is that pretty much all conda packages that need to set environment variables assume your shell is either bash or cmd.exe.  Nobody is putting files in `activate.d` for `.xsh`, `.fish`, or `.csh`.  Once we get our shell wrappers using this framework, we'll figure out an extension that'll let packages write environment variable management code, but only have to do it once, and not for every shell imaginable.
> start of modification to activate.py for csh and xonsh

- conda/core/repodata.py
- tests/test_create.py
In conda 4.2.x, I had a workflow where I would run `conda install ... --use-index-cache` and rely on the fact that it actually uses the local cache, i.e. does not try to go online to update any index. If all packages that are in the local index cache are also available on disk, this allows creating new environments without connectivity.
Now I might be missing something as to what the intention of the  `--use-index-cache` flag is, but this behavior broke in conda 4.3.x. It looks somewhat unintentional because in the case that there is no index cache, the behavior still is to return an empty index instead of updating the index remotely if `--use-index-cache` is set.
This PR adds a test that makes sure that if a local cache exists and `--use-index-cache` is set, the cache is actually hit, …
> Fix --use-index-cache actually hitting the index cache

- conda/activate.py
- conda/base/context.py
**Conda will not stack multiple levels of environments by default.**  This PR does not do that.
This PR implements environment stacking via an opt-in configuration parameter.  For now it will be undocumented.  Many people think this feature is dangerous.  However, as trivial as it is was now to implement, there's no reason it can't live behind a feature switch that users can opt in to.
resolves #3580
supersedes #3924
> support stacking environments

- conda/base/constants.py
- conda/base/context.py
- conda/models/enums.py
closes #5125
supersedes #5187 
-------
This is a different, more direct approach to fixing #5125 than #4809.  I've built a minimal aarch64 installer and some [basic packages](https://anaconda.org/aarch64_gbox/) using this patch and did not run into any issue.
> Add support for the linux-aarch64 platform

- conda/core/repodata.py
- tests/test_create.py
Add a test and fix a scenario where conda would attempt to fetch repodata remotely despite the `--offline` flag given. Mentioned originally in [this comment](https://github.com/conda/conda/pull/5134#issuecomment-297115358).
> Fix possibly repodata fetch with the `--offline` flag

- conda/exceptions.py
- tests/test_config.py
- tests/test_exceptions.py
addresses #3470 
Not sure if this should be added to 4.4.x but here we go.
This PR reduces somewhat redundunt error messages that are self-explanatory from the their names.
e.g.
```
Before:
- CondaValueError: Value error: Key 'ssl-verify' is not a known primitive parameter.
- TooManyArgumentsError: Too many arguments:  Got 5 arguments ....
After:
- CondaValueError: Key 'ssl-verify' is not a known primitive parameter.
- TooManyArgumentsError: Got 5 arguments ... 
```
> Reduce excessive error messages

- conda_env/pip_util.py
supersedes #4330
targeting 4.4.x
-------
Makes pip package discovery more robust by forcing pip list to output
json, overriding any settings in user's pip.conf.
> Use --format=json to parse list of pip packages

- conda/cli/install.py
fixes #5214
This also applies to branch `4.4.x`!
Running any install command with `--json` could never execute
```python
common.stdout_json_success(
message='All requested packages already installed.')
```
due to the top `if not context.json:`.
Furthermore this fixes #5214 which was caused by escaping the conditional `|`.
> fix #5214 install messages for 'nothing_to_do' case

- conda/models/channel.py
- tests/models/test_channel.py
fix #5207
The code that changed this in 4.3.17 is around https://github.com/conda/conda/pull/5030/files?diff=unified#diff-edc4b700cecabc4dfc8d00225250ea89R413
This PR reverts the behavior change introduced in #5030.
CC @ma-ba
> fix #5207 give all subdirs within channel same channel priority

- conda/core/link.py
> resolve #1509 bash doesn't need full path for pre/post link/unlink scripts on unix

- conda/cli/main_info.py
resolve #5147 
```
$ python -m conda info
Current conda install:
platform : osx-64
conda version : None
conda is private : False
conda-env version : None
conda-build version : 2.1.10+6.g99aaa148
python version : 3.5.2.final.0
requests version : 2.10.0
root environment : /usr/local/bin/../Cellar/python3/3.5.2_1/bin/../Frameworks/Python.framework/Versions/3.5  (writable)
default environment : /usr/local/bin/../Cellar/python3/3.5.2_1/bin/../Frameworks/Python.framework/Versions/3.5
envs directories : /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/envs
/Users/kfranz/.conda/envs
package cache : /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/pkgs
/Users/kfranz/.conda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/osx-64 …
```
> resolve #5147 add 'config files' to conda info

- conda/core/package_cache.py
- conda/core/path_actions.py
- conda/gateways/disk/read.py
- conda/misc.py
- tests/test_create.py
Currently, when linking a package, an already-extracted package is only
used when the corresponding tarball also exists and its md5 checksum
matches what is in the repodata. This means that if the tarball is not
present and only the extracted directory exists, conda always re-downloads
the tarball (and re-extracts it) even if the extracted directory exists
already because it can't compare the checksums otherwise.
This used to be different in previous versions such as 4.2.x where conda
would link a package from an extracted directory even if the tarball was
gone.
The current behavior is somewhat unfortunate in the sense that after a Miniconda
install, the pkgs directory is left with only extracted directories and no
tarballs. Also, `conda clean --tarballs` removes *all* tarballs and so …
> Allow to link packages from extracted tarballs when tarball is gone

- conda/cli/main_config.py
resolves #2511
Adds a `--stdin` flag to `conda config`.
> resolve #2511 accept config information from stdin

- utils/requirements.txt
Something going on with appveyor not being able to pip install pycrypto.  It's not used in 4.3, so just remove it as a requirement.
> remove pycrypto as requirement on windows

- conda/utils.py
> fix sys_prefix_unfollowed for Python 3

- shell/activate.bat
fix #5321
If `PROMPT` is not set, subsequent commands will not work as expected, e.g.,
```batch
@SET "CONDA_PS1_BACKUP=%PROMPT%"
```
and
```batch
@IF "%CHANGE_PROMPT%" == "1" @IF "x%PROMPT:CONDA_DEFAULT_ENV=%" == "x%PROMPT%" (
SET "PROMPT=(%CONDA_NEW_ENV%) %PROMPT%"
)
```
Note though, I'm not sure how/why a user's `PROMPT` environment variable would not be set, but it happened in #5321. This might just be misconfigured user settings which wouldn't necessarily need to be supported -- this PR handles it nonetheless.
> fix 5321: ensure variable PROMPT is set in activate.bat

- conda/resolve.py
fix #5298
@mcg1969 Could this be the cause (and fix) for #5298?
> fix #5298 record has 'build', not 'build_string'

- conda/cli/python_api.py
supersedes #5399 
targeting 4.3.x
---
Resolves #5217 by always forcing `args.yes = True` and thus `context.always_yes = True`.
Currently it does not make sense to allow user interactions in `conda.cli.python_api.run_command` as the user will never see the confirmation prompt due to `stdout`-capturing.
> fix #5217: skip user confirm in python_api, force always_yes

- conda/cli/activate.py
- conda/cli/main.py
- conda/cli/python_api.py
- conda/gateways/__init__.py
- conda/gateways/logging.py
- conda_env/cli/main.py
fix #5356
supersedes #5396
targeting 4.3.x
---
#5380 removed the execution of `initialize_logging` on module initialization, which has been necessary.
It also removed the root logger configuration in `initialize_logging` and `set_all_logger_level` which is a behavioral change, since:
- root logger's default level no longer gets set to `ERROR` in `initialize_logging`
- root logger's level and handler/format do not change in `set_all_logger_level` (and thus also in `set_verbosity`). Notice this is a more subtle change since this would only concern log messages from loggers other than `"conda"` and `"requests"` since those get treated separately and don't propagate to the root logger.
This PR restores the old behavior and avoids configuring root/`"conda"` loggers only in `cli.python_api`. …
> fix #5356 (additions): skip root/conda logger init for cli.python_api

- conda/cli/main_config.py
- tests/test_create.py
resolve #5411 
Adds a command `conda config --write-defaults` that creates a default, descriptive `~/.condarc` file.  The contents of the file are identical to `conda config --describe`.
> resolve #5411 add 'conda config --write-default'

- conda/models/channel.py
- tests/models/test_channel.py
resolves #5466
supersedes #5456
----
The URL parsing would swap around locations of URL parts if passed a `/t/<TOKEN>` URL that was not the `channel_alias`.
Patch includes a test that reproduces the problem, and a possible fix.
> fix #5466 scrambled URL of non-alias channel with token #5456

- conda/cli/conda_argparse.py
- conda/cli/install.py
- conda/core/solve.py
- conda/plan.py
resolves #5468
supersedes #5427
----
I couldn't figure out what `--alt-hint` did, so I looked at the source code only to find that it doesn't do anything. Now I'm removing the option so no one else wastes their time the same way.
> resolve #5468 remove --alt-hint from CLI API

- conda/cli/python_api.py
- conda/common/io.py
- tests/common/test_io.py
resolves #5470
supersedes #5394
----
This adds two keyword arguments `stdout`/`stderr` to `conda.cli.python_api.run_command` which let the user customize how and if the standard output/error streams should be captured.
This would be extremely useful for long-running tasks, e.g., when downloading an Anaconda-sized set of packages over a slow network connection. Currently the output is captured and only available after the (long-running) task has finished, not providing intermediate outputs to the caller.
It is inspired by the identically named arguments of `subprocess.Popen` with which the subprocess's stream can be set. There the arguments may have values from `{PIPE, STDOUT, DEVNULL, None}` or an existing file descriptor or file-like object. Here, instead of `PIPE` we've …
> resolve #5470 make stdout/stderr capture in python_api customizable

- shell/Library/bin/conda.bat
- shell/Scripts/activate.bat
- shell/Scripts/deactivate.bat
Congrats for the progress in #5210!
These are some minor modification on the `.bat` files.
- added quotes since `%~dp0` can contain spaces and stuff
- reactivate instead of deactivate environments for install commands
- added argument passing to deactivate so that it behaves like `conda deactivate`, i.e., let `conda.activate` complain if there are additional arguments
- made activate/deactivate pass along all arguments to make them behave more like `conda.bat (de)activate`
> #5210 followup

- conda/gateways/adapters/ftp.py
For example:
```
from ftplib import FTP
ftp = FTP()
ftp.set_debuglevel(2)
ftp.connect("ftp.tcl.tk")
ftp.login("anonymous", "guest")
print(ftp.sock.getpeername())
ftp.set_pasv(True)
ftp.retrlines("LIST")
```
Notice how the IP address in getpeername():
```
('38.88.76.19', 21)
```
.. is completely different from the IP address in the 227
response to PASV:
```
227 Entering Passive Mode (204,244,102,23,117,115)
```
See:
https://stackoverflow.com/a/44073062/3257826
https://stackoverflow.com/a/35368154/3257826
https://stumbles.id.au/python-ftps-and-mis-configured-servers.html
> ftp: Ignore host IP from PASV as it is often wrong

- conda/exports.py
Will allow fixing https://github.com/conda/conda-build/issues/2059
Note that CondaFileNotFoundError has been renamed to FileNotFoundError in conda 4.4.x.
> expose common race condition exceptions in exports for conda-build

- conda/activate.py
- conda/base/constants.py
- conda/base/context.py
- conda/cli/conda_argparse.py
- conda/cli/main_config.py
- conda/common/configuration.py
- conda/common/io.py
- conda/exceptions.py
- conda/resolve.py
- tests/test_exceptions.py
- tests/test_info.py
resolve #5530
This PR also adds a new configuration parameter, `report_errors`.  The default value is `None`, which means conda will prompt and ask if the user wants to send the error report or not.  With
conda config --set report_errors true
there won't be any prompt, and the error will automatically be sent.  This is equivalent to an opt-in always.  While
conda config --set report_errors false
is equivalent to "always opt out."
> resolve #5530 add ability for users to choose to post unexpected errors to core maintainers

- conda/models/match_spec.py
- tests/conda_env/test_env.py
- tests/models/test_match_spec.py
The MatchSpec docstring is now
```
:class:`MatchSpec` is, fundamentally, a query language for conda packages.  Any of the fields
that comprise a :class:`PackageRecord` can be used to compose a :class:`MatchSpec`.
:class:`MatchSpec` can be composed with keyword arguments, where keys are any of the
attributes of :class:`PackageRecord`.  Values for keyword arguments are the exact values the
attribute should match against.  Many fields can also be matched against non-exact values--by
including wildcard `*` and `>`/`<` ranges--where supported.  Any non-specified field is
the equivalent of a full wildcard match.
:class:`MatchSpec` can also be composed using a single positional argument, with optional
keyword arguments.  Keyword arguments also override any conflicting information provided in
the …
```
> update MatchSpec docstring

- .travis.yml
- conda/core/path_actions.py
- utils/functions.sh
Bug fix for conda 4.4.x compatibility (including `skip_safety_checks: false`) with conda-build 2.1.x.
> conda-build compatibility work

- conda/core/solve.py
- conda/history.py
- conda/models/match_spec.py
- conda/plan.py
- tests/core/test_solve.py
- tests/models/test_match_spec.py
* handles the case when a spec was recorded in the history file with something like `(target=fn,optional)`
* doesn't force specs into the returned history specs if a spec doesn't actually match a package in the current environment
> Minor bug fixes for new Solve code

- conda/cli/install.py
- conda/cli/main.py
- conda/cli/python_api.py
- conda/core/index.py
- conda/core/link.py
- conda/core/package_cache.py
- conda/core/repodata.py
- conda/exceptions.py
- conda/gateways/__init__.py
- conda/gateways/connection/adapters/s3.py
- conda/gateways/disk/create.py
- conda/gateways/logging.py
- conda/install.py
- conda/instructions.py
- conda/lock.py
- conda/resolve.py
Notable changes:
- cherry-picked "remove redundant log handler/formatter, propagate instead" from #5397
- merge conflicts fixed
- replaced loggers `"stdoutlog"`/`"stderrlog"` with `"conda.stdoutlog"`/`"conda.stderrlog"`~~`"conda.stdout.raw"`/`"conda.stderr.raw"`~~
- replaced logger `"print"` with `"conda.stdout.verbose"`
- where possible, used `exc_info` argument instead of manually calling `traceback.format_exc`
In contrast to the previous `"stdoutlog"`/`"stderrlog"` loggers, which output record messages directly without formatting, `"conda.stdoutlog"`/`"conda.stderrlog"` do normal log formatting.~~The loggers `"conda.stdout.raw"`/`"conda.stderr.raw"` are named that way since they previously output record messages directly without formatting.~~ I changed that in …
>  logging simplifications/improvements: #5547 followup

- conda/cli/common.py
- tests/test_create.py
This looks like a regression in the current 4.4.x beta release: When running the command `conda create -n <env> --dry --json python`, the command would fail with `AttributeError("'PrefixSetup' object has no attribute 'link_dists')`.
This PR fixes this by using the `link_precs` and `unlink_precs` attributes instead. It also removes the `unlink_link_transaction` key from `kwargs` because otherwise the JSON serializer would complain that "an object of type `UnlinkLinkTransaction` is not JSON serializable."
It's not fully clear to me what the desired JSON output should be. In conda 4.2.x, it used to be
```
"actions": {
"LINK": [
"defaults::vs2015_runtime-14.00.23026.0-0 1",
...
]
}
```
In conda 4.3.x, it used to be
```
"actions": [
{
"LINK": [
{
"base_url": null,
"build_number": 0, …
```
> Fix exception when generating JSON output

- conda/core/link.py
- conda/core/package_cache.py
- conda/core/repodata.py
- conda/gateways/disk/create.py
This backports a commit from #5578 which might fix #5574.
Notable changes:
- where possible, used `exc_info` argument instead of manually calling `traceback.format_exc`
Other behavioral changes:
- for `make_menu`/`menuinst` exception: use standard newline instead of ":" as separator
> fix/improve traceback formatting (4.3.x)

- conda/cli/install.py
- conda/cli/main.py
- conda/console.py
- conda/core/index.py
- conda/fetch.py
- conda/resolve.py
@msarahan Can you please review if you have time (and hit the merge button if it looks good).
We don't have a lot of unit or integration tests for logging.  Kind of hard to test.  But I've ran manually all the scenarios I could think of using the `--quiet`, `--json` and `--verbose` flags, and I think this PR gets us back to the correct behavior.
fix #5554
> fix #5554 logger configuration levels

- conda/cli/main_info.py
previously:
```
`$ /Users/tkim/miniconda3/bin/conda info efefef`
File "/Users/tkim/Documents/projects/conda/conda/exceptions.py", line 647, in __call__
return func(*args, **kwargs)
File "/Users/tkim/Documents/projects/conda/conda/cli/main.py", line 136, in _main
exit_code = args.func(args, p)
File "/Users/tkim/Documents/projects/conda/conda/cli/main_info.py", line 334, in execute
print_package_info(args.packages)
File "/Users/tkim/Documents/projects/conda/conda/cli/main_info.py", line 153, in print_package_info
for dist in r.get_dists_for_spec(arg2spec(package)):
File "/Users/tkim/Documents/projects/conda/conda/resolve.py", line 423, in get_dists_for_spec
raise ResolvePackageNotFound([(ms,)])
ResolvePackageNotFound:
- efefef
```
Now: 
``` …
```
> conda info now raises PackagesNotFoundError

- conda/activate.py
- conda/base/context.py
- conda/cli/activate.py
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_list.py
- conda/cli/main_package.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/core/envs_manager.py
- conda/exceptions.py
- conda/exports.py
- conda_env/cli/common.py
- conda_env/cli/main_remove.py
- tests/cli/test_activate.py
- tests/conda_env/test_cli.py
- tests/core/test_envs_manager.py
- tests/test_cli.py
- tests/test_create.py
- tests/test_export.py
This PR cleans up the `prefix`, `prefix_w_legacy_search`, and `` properties on the `context` object, and adds a `target_prefix` property to the `context` object.  `context.target_prefix` should be used for the prefix that is the target of the command currently being executed.  It's potentially different from the *active* prefix, because target prefix is often specified with `-p` or `-n` command line flags.
> fix target prefix determination

- conda/resolve.py
Resolves #5708.  Root cause was created in the initial timestamp sort order implementation in https://github.com/conda/conda/pull/5015.  Build string should be prioritized after timestamp, and not before.
> fix #5708 package priority sort order

- conda/base/context.py
- conda/cli/common.py
- conda/cli/install.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/core/index.py
- conda/core/solve.py
- conda/models/channel.py
- conda_env/installers/conda.py
- tests/cli/test_activate.py
- tests/core/test_index.py
- tests/test_create.py
In addition to re-enabling the `--override-channels` command line functionality, this PR adds two additional configuration parameters, and implements the associated logic.
```
'override_channels_enabled': dals("""
Permit use of the --overide-channels command-line flag.
"""),
'whitelist_channels': dals("""
The exclusive list of channels allowed to be used on the system. Use of any
other channels will result in an error. If conda-build channels are to be
allowed, along with the --use-local command line flag, be sure to include the
'local' channel in the list. If the list is empty or left undefined, no
channel exclusions will be enforced.
""")
```
> fix --override-channels and add whitelist_channels config

- conda/base/constants.py
- conda/base/context.py
- conda/core/link.py
- conda/core/path_actions.py
- conda/exceptions.py
- tests/test_create.py
- utils/functions.sh
fix #5811 
Conda 4.4 added per-path checking of sha256 and byte size as part of of the pre-transaction verification step.  There are packages in the ecosystem that have bad shas recorded though.  #5811 has an example.  This PR changes the `skip_safety_checks` configuration parameter that had a boolean value to just a `safety_checks` configuration parameter that has enum values `enabled`, `warn`, and `disabled`.
The default for Conda 4.4 will now be `warn`, and we'll schedule the default to change to `enabled` in conda 4.5.  We've also added a rule to conda-verify https://github.com/conda/conda-verify/pull/12 to help get the packaging ecosystem cleaned up.
> fix #5811 change safety_checks default to 'warn' for conda 4.4

- conda/core/repodata.py
supersedes #5719
---
On CentOS line `closing(mmap(f.fileno(), 0, access=ACCESS_READ)) as m:`
caused an OSError.
> Catch OSError for missing device

- tests/core/test_solve.py
- tests/test_create.py
Segfault now seems to always trigger on `test_freeze_deps_1` in python 3.6.
https://travis-ci.org/conda/conda/builds/264845425
https://travis-ci.org/conda/conda/builds/264799481
https://travis-ci.org/conda/conda/builds/264844445
https://travis-ci.org/conda/conda/builds/264842508
https://travis-ci.org/conda/conda/builds/264842179
> more debugging for segfault

- conda/base/context.py
backport of #5835 to 4.3.x
resolves #5834 in 4.3.x
> resolve #5834 change default value of 'always_softlink' from True to False

- conda/gateways/disk/delete.py
- tests/test_create.py
resolves #5847
The cached prefix entry was sticking around on windows.  This was causing bizarre errors removing envs, especially when switching to a different subdir (win-64 --> win-32 for example).  This addresses the intradependencies conda-build test failure, and so should make a completely green conda-build build on appveyor.
> always remove linked prefix entry with rm_rf

- conda/core/link.py
- tests/test_create.py
supersedes #5727
------------
The /D flag prevents the command prompt to invoke an autorun script that
is otherwise being run at the beginning of every command prompt session if
specified in the registry. From the `cmd.exe /?` output:
```
If /D was NOT specified on the command line, then when CMD.EXE starts, it
looks for the following REG_SZ/REG_EXPAND_SZ registry variables, and if
either or both are present, they are executed first.
HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
and/or
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
```
Since such autorun scripts might make one pre/post link/unlink script to
behave different on one machine than on another, this provides a more
reproducible environment to run these scripts in.
> Invoke cmd.exe with /D for pre/post link/unlink scripts

- conda/gateways/adapters/s3.py
resolve #5948
supersedes #5947
---
Following the recommendation from boto's documentation (https://github.com/boto/boto), this patch replaces boto with boto3 for conda's s3 adapter:
>  Boto3, the next version of Boto, is now stable and recommended for general use.
Additionally, following the example in localfs.py, the patch:
- replaces the mkstemp file object (which has to be manually destroyed) to SpooledTemporaryFile (which is destroyed automatically on closing)
- wraps exceptions raised by boto3 into a valid adapter response
> Add boto3 use to s3 adapter

- conda/plan.py
As discussed in #6164, `add_defaults_to_specs` is not behaving as desired when installing a non-Python package into the root environment _and_ `auto_update_conda` is `True`. This is because `add_defaults_to_specs` isn't "seeing" the addition of `conda` and `conda-env` to the spec list. This moves `add_defaults_to_specs` so that it is called after `augment_specs` where these additions are made.
> move add_defaults_to_specs after augment_specs

- conda/gateways/disk/create.py
> fix #6057 add additional detail for message 'cannot link source that does not exist'

- conda/resolve.py
- tests/test_resolve.py
Aggressive timestamp maximization is causing issues like #6271. This delays timestamp maximization until late in the optimization process.
We need to document somewhere that all versions of a package with the same version & build combination should now be considered "equivalent" for the purposes of optimization.
> Delay timestamp maximization until late in the optimization passes

- tests/test_create.py
- tests/test_priority.py
These two tests were temporarily ignored in 4.3.x because of some things caused by the `pkgs/main` transition.  They should now be re-enabled.
> re-enable feature tests in 4.3.x

- .codecov.yml
- conda/exports.py
- conda/instructions.py
- conda/models/dag.py
- conda/models/package_cache_record.py
- conda/plan.py
- setup.cfg
- tests/test_instructions.py
- tests/test_plan.py
This PR removes large chunks of unused dead code.  It also moves several large chunks to `conda/exports.py`, which should be considered queued for having deprecation warnings added.  There are no functional parts of conda's internal code that use `conda/exports.py`.
> remove dead code

- conda/base/context.py
The `aggressive_update_packages` config parameter is called out in the 4.4 changelog, but it was never actually enabled as a user-accessible config parameter.  This PR fixes that.
> enable aggressive_update_packages

- shell/etc/profile.d/conda.sh
Playing around with a busybox docker container, and this seems to be the most appropriate thing to do at this point.  Open to other ideas though.
> default conda.sh to dash if otherwise can't detect

- conda_env/pip_util.py
supersedes #6391
---
because pip canonicalizes names, so `conda install jupyter_client`
will show up as `jupyter-client` installed with pip.
> canonicalize package names when comparing with pip

- conda/base/context.py
- conda/core/path_actions.py
This PR does what I think is the goal of #6162 (and detailed in #6104) by @rainwoodman.  I ended up needing it myself for building some minimal docker containers.
Usage remains undocumented right now.  Easiest way to use is to set and environment variable, e.g.
export CONDA_TARGET_PREFIX_OVERRIDE=/usr/local
> target prefix override

- conda/core/solve.py
This PR does not _close_ #6430, but it adds an exception with additional information for the next time anybody runs across it.
> add debug exception for #6430

- conda/activate.py
fix #6445 issue 2
With this change, if you have a conda environment in your current working directory with folder name `tests`, you must now use
conda activate ./tests
The upshot is that if your `tests` directory in your current directory isn't a conda environment, but you have an environments named `tests` in one of your `envs` directories, behavior is as expected.
> fix #6445 scale back directory activation in PWD

- conda/cli/main_info.py
- conda/exceptions.py
To be compliant with GDPR (according to Mathew Lodge), for the error upload report, we need to indicate what information is being uploaded, why, and how that information will be used.  This PR should bring us into GDPR compliance.
> add information to displayed error report

- conda/activate.py
- shell/etc/profile.d/conda.sh
- tests/test_activate.py
fix #6419
This PR slightly reworks how PS1 is set for Bourne shells.  Basically setting PS1 through our python code, and not doing logic at the shell level.
> fix #6419 set PS1 in python code

- conda/core/index.py
resolves #5158 
resolves #6400
---
Turns out this was already done, including configuration options that allow us to not violate the security model.
```
override_channels_enabled:
Permit use of the --overide-channels command-line flag.
whitelist_channels:
The exclusive list of channels allowed to be used on the system. Use of any
other channels will result in an error. If conda-build channels are to be
allowed, along with the --use-local command line flag, be sure to include the
'local' channel in the list. If the list is empty or left undefined, no
channel exclusions will be enforced.
```
This PR *only* adds whitelist checking at one particularly important point where it was previously missed.
> resolve #5158 --override-channels

- conda/activate.py
- conda/shell/etc/fish/conf.d/conda.fish
- tests/test_activate.py
This PR makes progress on bringing the fish wrapper in line with the other 4.4 shell wrappers.  I'm not a fish expert, so I'm sure it's probably not perfect yet.
One particular problem with the integration test... I can't get the `pexpect` library to collect stdout from a fish terminal.  Not sure exactly what's going on there.  With manual testing though, this PR at least appears to have basic functionality.
> fish update for conda 4.4

- conda/shell/Library/bin/conda.bat
- conda/shell/etc/profile.d/conda.sh
fix #6512
Note that only `conda.sh` and `conda.bat` have this problem.  The xonsh, csh, and fish wrappers aren't affected.
> fix #6512 reactivate does not accept arguments

- conda/base/context.py
- conda/exceptions.py
- conda/gateways/disk/update.py
fix #6508 
The particular stack trace in #6508 happens when people have used `sudo` in front of `conda` incorrectly.  This will at least give them a helpful error report now on what the problem file is.
> fix #6508 environments.txt permissions error stack trace

- conda/core/solve.py
- tests/core/test_solve.py
resolve #6523
Until we get https://github.com/conda/constructor/issues/138 resolved and also until it has some time to settle in, we're just going to have to be more conservative with what `--update-all` is allowed to do.  If users want prune behavior, there's always the `--prune` flag.
> resolve #6523 don't prune with --update-all

- conda/core/solve.py
When we removed the prune behavior from `conda update --all` in #6524, we should have also removed the hack that disabled the anaconda-custom package.
I believe with this, `conda update --all` should mostly work as it did on conda 4.3.
> remove anaconda metapackage hack

- conda_env/installers/pip.py
- conda_env/pip_util.py
fix #6536
PR #5205 introduced code that assumed pip>=9.  This PR just copies back in the previous code path from 4.3.x if pip is older than version 9.
> fix #6536 'conda env export' for old versions of pip

- conda/history.py
fix #6546
I'm not sure if this is the only fix we should implement for this problem, but at least it's one of them.
It's probably an issue that `MatchSpec('')` is equal to `*`, which matches everything.
This PR at least avoids the issue altogether for the workflow encountered in #6546, which was creating an empty env with no packages, and then installing some packages, and then calling `conda update`.
> fix #6546 update after creating an empty env

- conda/core/package_cache.py
fix #6554 
A follow-on to #6533.  We might now be about to the end of package cache stack traces.
> fix #6554 package cache FileNotFoundError

- conda/cli/main_info.py
Per https://github.com/conda/conda/issues/6562#issuecomment-353747774, this will, in part, help us determine if sudo usage is causing problems for users.
> add SUDO_ env vars to info reports

- conda/activate.py
fix #6577
fix #6580
Both issues are caused by having single-quotes in the PS1 string, and also trying to re-set that string using single-qutoes, as `PS1='<CONTENTS>'`, where `<CONTENTS>` itself then contains single-quotes.
It appears the best solution is https://stackoverflow.com/a/1250279.  It seems to work, based on my testing.
> fix #6577, #6580 single quote in PS1

- conda/cli/conda_argparse.py
> fix #6607 use subprocess rather than execv for conda command extensions

- conda/models/version.py
- tests/models/test_match_spec.py
fix #6643
This PR makes the following work as expected
CONDA_SUBDIR=linux-64 conda search boost==1.60
CONDA_SUBDIR=linux-64 conda search boost==1.60.0
CONDA_SUBDIR=linux-64 conda search boost==1.60.0.0
This behavior is identical to 4.3.x.  It changed in 4.4.x because of a parsing change.  The PR brings 4.4.x behavior inline with 4.3.x.
After this PR is merged, there will be a difference that specifically affects conda-build and meta.yaml.  Given the below examples
```
requirements:
run:
- boost 1.60.0
```
```
requirements:
run:
- boost ==1.60.0
```
Currently in 4.4, the above are treated differently (also in 4.3).  The first uses `exact_match_()` and thus the version string has to be exactly `1.60.0`.  The second uses `veval_match_()` and thus will match `1.60`, or `1.60.0.0`, etc.  With …
> fix #6643 difference between '==' and 'exact_match_'

- conda/models/dist.py
fix #6665
This was brutal.  I wrote several variations of integration tests as regression tests, but everything I wrote seemed to pass fine, thus not reproducing the error.
I was able to reproduce it ultimately though, using the exact steps in #6665, and narrowed the problem down to these two characters.
Ultimately, the best solution will be to kill off the `Dist` object altogether.  Hopefully we can do that in conda 4.5.
> fix #6665 KeyError for channel '<unknown>'

- conda/base/context.py
Fix https://github.com/ContinuumIO/navigator/issues/1387
@kalefranz it seems the validation was not allowing `None` values. `None` was supposed to mean, no pinning right?
Also it seems that default_python is no longer a config option?
If I try to set it on the CLI I get
```
$ conda config --set default_python None --json --force --file /Users/gpena-castellanos/.condarc
{
"caused_by": "None", 
"error": "CondaValueError: Key 'default_python' is not a known primitive parameter.", 
"exception_name": "CondaValueError", 
"exception_type": "<class 'conda.exceptions.CondaValueError'>", 
"message": "Key 'default_python' is not a known primitive parameter."
}
```
how is that working then?
> PR: Allow None or '' values for default_python to avoid pinning python

- conda/shell/Library/bin/conda.bat
Fixes #6713.
I can't say I know what's exactly going on, but there seems to be a problem with using parenthesis expressions and quoted arguments to `set` that include quotes and `)`, see the following:
```bat
@echo off
set X=")1"
(
set X=")2"
)
( set X=")3" )
set "X=")4""
(
set "X=")5""
)
( set "X=")6"" )
```
which fails for case 5 and 6:
```
5"" was unexpected at this time.
```
. I have no idea about the exact semantics for parenthesis expressions...
If we run into trouble with those expressions again, we could also just resort to replacing some
```bat
if condition (
...
) else (
...
)
```
with
```bat
if not condition goto :condition_else
...
goto :condition_end
:condition_else
...
:condition_end
```
.
> conda.bat: fix #6713 allow parenthesis in prefix path

- .github/ISSUE_TEMPLATE.md
Some improvements to `.github/ISSUE_TEMPLATE.md` I like to suggest after seeing the first uses of the issue template.
Changes are in single single commits so can be (mostly) cherry-picked if only a subset is used. Changes are:
* Add `Environment Information` section: so that `conda info` etc. are not part of `Expected Behavior` secion.
* `Steps to Reproduce` can be part of `Current Behavior`: mainly to hint at/"indirectly suggest" to rather put output from commands there.
* Directly suggest to include console output between tick-enclosed lines: to hopefully make the user put tracebacks and such there for better formatting.
* Reducing subsection depth: gives better visual separation, esp. if `Steps to Reproduce` is moved inside `Current Behavior`.
* Put `conda (info|config|list)` output in …
> issue template improvements

- conda/base/constants.py
- conda/base/context.py
- tests/base/test_context.py
- tests/core/test_solve.py
This is a followup to #6392 and makes `aggressive_update_packages` available under its designated name as it was previously only accessible via
```
_aggressive_update_packages:
- ...
```
. Additionally, `aggressive_update_packages` wasn't allow to be empty before, which is also fixed.
> fix aggressive_update_packages availability

- conda_env/installers/conda.py
Fixes #6745.
As written, the `conda_env` installer (invoked during the `conda env create` command) will:
1) Truncate authentication components of available channels (e.g. token authenticated channels) before passing those channels to the `Solver`.
2) Truncate channels with the same channel name but different properties (e.g. authenticated vs unautheticated) channels before passing those channels to the `Solver`.
This change removes this truncation from the conda installer. Which should bring it in line with other invocations of the `Solver` that are not in `conda env`. 
See #6745 for full details.
> Don't truncate channel priority map in conda installer

- conda/_vendor/distro.py
supersedes #6768 targeting 4.4.x
See: https://github.com/ContinuumIO/anaconda-issues/issues/8244
> Add workaround for system Python usage by lsb_release

- conda/shell/etc/fish/conf.d/conda.fish
The fish_prompt function typically does things like changing the color
of the prompt based on the exit status of the last command. This
status is however lost in the function defined by conda, since the
status of the last operation is always zero.
This fixes the issue by defining an identity function that returns the
last status (thereby setting the $status variable) before the original
fish_prompt function is called.
> Preserve status in fish shell

- conda/common/io.py
- conda/core/index.py
- conda/core/repodata.py
fix #6624 
This PR removes the `backdown_thread_pool` context manager, and replaces it with `ThreadLimitedThreadPoolExecutor`.  The original purpose of `backdown_thread_pool` was to prevent `RuntimeError`s as shown in #6624, but the strategy failed to do so.  After looking more at `concurrent.futures.ThreadPoolExecutor`, it seems the exception will only be thrown when a new thread is created, and that only happens after submitting the first task.  So `backdown_thread_pool` was wholly ineffective at its intended purpose.
This PR has some ugly parts, things I complain about in comments.  Specifically import and usage of "protected" attributes (names starting with `_`) from `concurrent.futures`.  That seems unavoidable though.  The only solution there would be to vendor our own …
> fix #6624 can't start new thread

- conda/resolve.py
- tests/test_resolve.py
Fixes #6765 . Built off of 4.3.x, but it should to port to 4.4.x with no changes.
The bug is this: consider the first three optimization passes:
1. Maximize the channel priority and version of the requested packages
2. Minimize the number of features required
3. Maximize the number of installed packages that utilize the features
4. Maximize the build number of the requested packages
We deliberately placed 4 after 2 and 3 in response to previous issues; for instance, if there are fewer builds of a featured package than a non-featured package, we need to be able to reach back and grab the featured build if requested. Now, per #6765, however, consider this scenario:
- The current version of a package `foo` has multiple builds with distinct build numbers.
- Newer builds depend on a second …
> Adjust the feature score assigned to packages not installed

- conda/cli/conda_argparse.py
When an external command contains a hypne, the command is listed as
available commands but cannot be executed.
At least conda 4.3.30, this https://github.com/lambdalisue/conda-offline-channel external conda command works correctly.
However with conda 4.4.7, the command execution fail even the command is listed in the available commands list.
> fix external command execution issue

- conda/cli/main_remove.py
Conda 4.3.x displayed the packages that would be removed when a user
chose to remove an environment using `conda env remove`, however Conda
4.4.x did not do so. This patch fixes the problem by making a call to
display_actions() if the context is not json.
Fix #6632
> Display package removal plan when deleting an env

- conda/plan.py
fix #6531 
Fixes a problem introduced in #6517 to fix #6516.
> fix #6531 don't drop credentials for conda-build workaround

- conda/models/channel.py
- conda/models/match_spec.py
- tests/models/test_channel.py
- tests/models/test_index_record.py
- tests/models/test_match_spec.py
Looks like conda-build-all is incompatible with conda 4.4 without this patch.
See https://github.com/conda-tools/conda-build-all/pull/96
> fix MatchSpec.match() accepting dict

- conda/activate.py
- tests/test_activate.py
fix #6796
By launching a new shell (that isn't as subshell), e.g., via `tmux`, `PATH` and `PS1` are reset. A `conda activate base` would then "reactivate" the environment if `base` was previously active. The "reactivate" previously skipped resetting path and prompt since in a normal shell (/subshell) context those weren't reset in the meantime.
> fix #6796 update PATH/prompt on reactivate

- conda.recipe/meta.yaml
- conda/core/index.py
- conda/core/repodata.py
fix for #6837 : conda apparently requires at least version 3.0.0 of `futures` package
> fix #6837 require at least futures 3.0.0

- conda/cli/common.py
- conda/cli/main_search.py
- conda/common/io.py
- conda/core/link.py
- conda/core/solve.py
resolve #6582
Besides the Spinner refactor and swallow_broken_pipe context manager, this PR also replaces several `sys.stderr.write()` and `sys.stdout.write()` calls with `print()`.
> resolve #6582 swallow_broken_pipe context manager and Spinner refactor

- conda/misc.py
ln23 import symlink and readlink
ln243 use them not os.
Note : this replaces #6866 , because I used github web and didn't trust what it was doing switching off master to 4.4. Sorry
> Update misc.py with imported links, not os.

- conda/common/configuration.py
- tests/common/test_configuration.py
resolve #6733 
@mbargull Let's see how this works...  I don't even know if there's a situation where we'd actually *want* an empty string, instead of just an empty sequence.
> resolve #6733 make empty env vars sequence-safe for sequence parameters

- conda/models/version.py
- tests/models/test_match_spec.py
fix #6880
There's a lot of surface area to cover here for testing the 4.4 MatchSpec implementation.  We haven't gotten it all yet.
> fix #6880 build_number comparison not functional in match_spec

- conda/cli/main_help.py
> resolve #6192 deprecate 'conda help' in favor of --help CLI flag

- conda/models/index_record.py
> fix #6910 conda 4.4 sort key prioritizes build string over build number

- conda/activate.py
- conda/base/context.py
- tests/test_activate.py
>  resolve #6810 add CONDA_EXE environment variable to activate

- conda/api.py
- conda/cli/install.py
- conda/cli/main_info.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/core/link.py
- conda/core/package_cache_data.py
- conda/core/prefix_data.py
- conda/core/solve.py
- conda/core/subdir_data.py
- conda_env/installers/conda.py
- tests/test_api.py
> resolve #5610 add PrefixData, SubdirData, and PackageCacheData to conda/api.py

- conda/gateways/connection/adapters/s3.py
* conda/gateways/connection/adapters/s3.py
Lack of return statement causes None to be returned, leading to an
AttributeError when an attribute access is attempted on the return
value.
Fixes #6930
> fix #6930 add missing return statement to S3Adapter

- conda/activate.py
- conda/cli/main.py
- conda/common/compat.py
- tests/test_activate.py
Followup to #6909. I completely misread
```python
File "/opt/conda/lib/python3.6/codecs.py", line 377, in write
self.stream.write(data)
TypeError: string argument expected, got 'bytes'
```
before and though `self.encode` failed instead of `self.stream.write`.
So, easy fix is to apply the IO encoding only for the case that is needed, i.e., `PY2 and isinstance(stream, file)`.
(To make sure everything is in order, I added an "inverted" test that fails for Python 3 and passed for Python 2. Once CI shows exactly that result, I'll update the test accordingly.)
> set encoding for PY2 stdout/stderr

- conda/core/package_cache_data.py
resolve #6952
Right now, targeted at master (4.5.x).  If this works ok there, we can backport to 4.3.x.
> resolve #6952 memoize url search in package cache loading

- conda/shell/etc/fish/conf.d/conda.fish
- conda/shell/etc/profile.d/conda.sh
1. Fix #6891: turns out fish has some unusual list slicing semantics... empty slices
* raise an error for `fish <2.7b1` (https://github.com/fish-shell/fish-shell/blame/2.7.1/CHANGELOG.md#L22)
* but also aren't usable in `fish >=2.7b1`:
```fish
~> function f; echo $argv[2..-1]; end
~> f
~> f 1
1
~> f 1 2
2
~> f 1 2 3
2 3
```
But we can mirror the behavior in `conda.sh` by using `set -e argv[1]` as a `shift`.
2. Port return value handling from #6850 over to `conda.fish`.
3. Use the same logic in `conda.sh` when calling `conda` without args: run `$_CONDA_EXE` instead of `$_CONDA_EXE ''`.
> fix #6891 index out of bound when running deactivate on fish shell

- conda/shell/etc/fish/conf.d/conda.fish
This more closely mimics a closure in Python: the value of _CONDA_EXE will be "snapshot" to a local variable (see fish docs https://fishshell.com/docs/current/commands.html#function).
Not doing this can cause problems when sourcing this file from other scripts.
> Properly close over $_CONDA_EXE variable

- conda/common/configuration.py
- tests/common/test_configuration.py
Configuration entries like
```yaml
custom_multichannels:
bioconda-repro:
- bioconda/label/main
- conda-forge
- defaults
- bioconda/label/deprecated
- bioconda/label/broken
```
caused
```python
AttributeError: 'NoneType' object has no attribute 'value'
```
to be raised in
```python
common.configuration.YamlRawParameter._get_yaml_map_comments
```
> fix: configuration: parse map with comments

- conda/core/path_actions.py
See error below:
File "MY_CONDA_DIR\lib\site-packages\conda\core\link.py", line 281, in execute
pkg_data, actions)
File "MY_CONDA_DIR\lib\site-packages\conda\core\link.py", line 344, in _execute_actions
reverse_excs,
conda.CondaMultiError: 
'CreateNonadminAction' object has no attribute '_file_created'
During handling of the above exception, another exception occurred:
File "MY_CONDA_DIR\Scripts\conda-build-script.py", line 10, in <module>
File "MY_CONDA_DIR\lib\site-packages\conda_build\cli\main_build.py", line 388, in main
execute(sys.argv[1:])
File "MY_CONDA_DIR\lib\site-packages\conda_build\cli\main_build.py", line 379, in execute
noverify=args.no_verify)
File …
> Add _file_created attribute

- conda/cli/main_config.py
I have a private conda repository in the local network. The path to it contains non-ascii characters, because of my german language.
I recently found out that I can assign an alias by setting up a `custom_multichannel` like it is done for the locally built packages with [conda-build](https://github.com/conda/conda-build).
However the non-ascii characters are parsed differently there, which can be shown with the following example:
```python
import os
from conda.cli.python_api import Commands, run_command
config = """
channels:
- defaults
- file:///C:/some-drive/cäöüßc
- file:////some-network-share/cäöüßc
custom_multichannels:
mychannel1: ["file:///C:/some-drive/cäöüßc"]
mychannel2: ["file:////some-network-share/cäöüßc"]
"""
with open('.condarc', 'w') as fh:
fh.writelines(config) …
```
> Fix handling of non-ascii characters in custom_multichannels

- conda/common/configuration.py
- conda/common/path.py
- conda/common/serialize.py
- conda/common/url.py
- conda/models/channel.py
`conda`'s startup time is heavily influenced by some costly imports of external modules.
This PR alone cuts the overall import time of `conda.base.context` by approx. 25 % (using `conda 4.5.0`+`python 3.6.5`).
One costly import we cannot avoid is `ruamel.yaml`/`ruamel_yaml`. 1/3 of the import time\* of that package is spent compiling regular expression (of which usually only few are actually used). We could monkeypatch `re.compile` to avoid this, but the saner approach is of course to fix this upstream. This is done in https://bitbucket.org/ruamel/yaml/pull-requests/27/improve-package-import-time/diff.
```python
>>> t_base = 0.01278
>>> t_ruamel_unpatched = 0.04364
>>> t_ruamel_patched = 0.03291
>>> (t_ruamel_patched - t_base) / (t_ruamel_unpatched - t_base)
0.6523007128969541
```
If that …
> Import speedups

- conda/base/context.py
- conda/cli/conda_argparse.py
- conda/cli/install.py
- conda/cli/main_config.py
- conda/cli/main_install.py
- conda/cli/main_remove.py
- conda/cli/main_search.py
- conda/cli/main_update.py
- conda/common/configuration.py
- conda/core/solve.py
- conda/exceptions.py
- conda_env/cli/main_remove.py
- setup.cfg
- tests/base/test_context.py
- tests/test_create.py
This PR dramatically cleans up the output of `conda <COMMAND> --help` and `conda config --describe`. 
Easiest way to review this PR will be to just test the outputs.  E.g.
python -m conda config --describe
python -m conda install --help
> clean up the formatting of help output

- conda/shell/etc/fish/conf.d/conda.fish
This PR adds autocompletion for `conda env` to the fish shell.
> fish autocompletion for conda env

- conda/_vendor/auxlib/logz.py
- conda/core/subdir_data.py
- conda/exceptions.py
- conda/gateways/connection/download.py
A member of the anaconda.org team pointed out in a private issue tracker that, without knowledge of the response body for HTTP 4XX errors such as https://github.com/conda/conda/issues/7140, our hands are kind of tied in understanding what's going on.  This PR should at least give us more information in the debug output.
> add http error body to debug information

- conda/base/context.py
`CondaValueError` is thrown when `conda create --name "environment name"`.
The exception is raised before the `source activate environment name` is shown in the red box. So the quotes haven't been added.
> Creating env name with space is not supported

- conda_env/installers/conda.py
I think this fixes #6385.
I've run the conda_env tests and they seem OK, but I'm not sure if there are other wider impacts of this change.
> Support complete MatchSpec syntax in environment.yml files

- conda/activate.py
Currently, the activation script paths are gathered with `glob.glob` which returns its results in arbitrary order. AFAICT the resulting results are not sorted or manipulated anywhere else. This caused us problems when we added an activation script to a metapackage of ours where we wanted to manipulate the environment variables set by the new compilers, https://github.com/ContinuumIO/anaconda-issues/issues/9172. This PR sorts the resulting list of activation scripts. This way packages can ensure when their activation scripts are run by naming them accordingly. As @msarahan [suggested](https://github.com/ContinuumIO/anaconda-issues/issues/9172#issuecomment-381607827), a script named `zz_patch_flags.sh` will run after compiler scripts that are `activate-*.sh`.
Here, sorting is done in two …
> Sort activation order of the activation scripts

- conda/base/context.py
- conda/common/io.py
- conda/core/package_cache_data.py
- conda/exceptions.py
- conda/gateways/disk/__init__.py
- conda/gateways/disk/create.py
- conda/gateways/disk/update.py
- tests/base/test_context.py
resolve #6569
The goal of this PR is to only *write* to these magic file locations when we know we're actually going to be writing to that "location" (either `pkgs` dir or `envs` dir).
> resolve #6569 make conda more conservative writing to home directories

- setup.cfg
Per [this request from GvR](https://github.com/PyCQA/pycodestyle/issues/466), the project has been renamed, and will emit deprecation warnings when linting conda if the [pep8] section remains.
https://github.com/conda/conda/issues/7220
> The pep8 project has been renamed to pycodestyle

- conda/misc.py
- tests/test_create.py
> fix #7094 exit early for --dry-run with explicit and clone

- conda/exports.py
> fix #7240 conda's configuration context is not initialized in conda.exports

- conda/exports.py
Summary:  This PR adds symbols to `conda.exports` that are being used by conda-build in `conda_build.conda_interface`.
---
Discovered it's not there while working on https://github.com/conda/conda-build/pull/2843
> clean up conda.exports

- conda/gateways/disk/create.py
Tarballs are index-less archives, thus a call of `tarfile.TarFile.getmembers()` usually extracts the whole file, such that `tar_file.getmembers() ; tar_file.extractall()` extracts the file twice.
Because of that, users see a "stall" on the progress output at `75 %` for big tarballs when the package extraction starts. That lead them to cancel (CTRL+C) the process. When they re-run that `conda` command the extraction happens silently without any progress indication, i.e., another perceived stall. (This was reported some weeks ago -- need to find that issue again...)
This PR fixes the first part, that is, avoid the twofold extraction and progress bar stall, but not the silent extraction for previously interrupted extractions.
The first commit retained the progress update on a tarball member …
> Fix twofold tarball extraction, improve progress update

- conda/core/package_cache_data.py
Backports PR ( https://github.com/conda/conda/pull/7191 ) for the 4.5.x branch.
cc @kalefranz
> Backport PR #7191: resolve #7189 progress bar improvement

- circle.yml
- conda/_vendor/auxlib/__init__.py
- conda/api.py
- conda/base/constants.py
- conda/base/context.py
- conda/cli/conda_argparse.py
- conda/cli/install.py
- conda/core/solve.py
- tests/base/test_context.py
- tests/core/test_solve.py
- tests/test_activate.py
- tests/test_api.py
- tests/test_resolve.py
resolve #6845
```
-S, --satisfied-skip-solve
Exit early and do not run the solver if the requested
specs are satisfied. Also skips aggressive updates as
configured by 'aggressive_update_packages'. Similar to
the default behavior of 'pip install'.
```
This PR also makes `aggressive_update_packages` even more aggressive, by overriding any user-requested specs in history.
> resolve #6845 add option -S / --satisfied-skip-solve to exit early for satisfied specs

- conda/gateways/disk/create.py
- tests/test_activate.py
- tests/test_create.py
fix #7341
> I think that error being thrown essentially means that a `fileobj.tell()` (with `fileobj` being an `io.BufferedReader` created by `open(..., 'rb')`) can return negative values!? That's a really strange thing...
I'll submit a PR that constrains the values we use to
```python
0 <= v <= max(1, fstat(fileobj.fileno()).st_size)
```
> fix #7341: constrain tell() return value to [0,filesize]

- conda_env/specs/__init__.py
- tests/conda_env/test_cli.py
Fixes #5681 
```
$ conda env create -f does_not_exist.txt
EnvironmentFileNotFound: Conda Env Exception: /Users/gpena-castellanos/Continuum/conda/does_not_exist.txt file not found
```
```
$ conda env update -f does_not_exist.txt
EnvironmentFileNotFound: Conda Env Exception: /Users/gpena-castellanos/Continuum/conda/does_not_exist.txt file not found
```
```
$ conda env create
EnvironmentFileNotFound: Conda Env Exception: /Users/gpena-castellanos/Continuum/conda/environment.yml file not found
```
> fix #5681 conda env create / update when --file does not exist

- circle.yml
- conda/cli/install.py
- conda/exceptions.py
- conda/gateways/disk/__init__.py
- tests/test_create.py
If we post conda 4.6 to PyPI, and people do something like
yum install python-pip
pip install conda
this `NoBaseEnvironmentError` should prevent a `conda install python` operation from clobbering the system python.
> add NoBaseEnvironmentError and DirectoryNotACondaEnvironmentError

- conda_env/env.py
- conda_env/exceptions.py
- conda_env/specs/__init__.py
- conda_env/specs/requirements.py
- conda_env/specs/yaml_file.py
- tests/conda_env/support/invalid_keys.yml
- tests/conda_env/support/valid_keys.yml
- tests/conda_env/test_cli.py
- tests/conda_env/test_env.py
fix #5885 
```
$ conda env create -f asdadsasdasd
EnvironmentFileNotFound: '/Users/gpena-castellanos/Continuum/conda/asdadsasdasd' file not found
```
For a file environment.yml of contents
```yaml
name: ps-env3
dependecies:
- python = 3.6
foo: bar
```
```
$ conda env create -f environment.yml
EnvironmentSectionNotValid: The following sections on '/Users/gpena-castellanos/Continuum/conda/environment.yml' are invalid and will be ignored:
- dependecies
- foo
#
#
#
#
```
For a file environment.ymlaa
```
$ conda env create -f environment.ymlaa 
EnvironmentFileExtensionNotValid: '/Users/gpena-castellanos/Continuum/conda/environment.ymlaa' file extension must be one of '.txt', '.yaml' or '.yml'
```
> Fix #5885 improve conda env error messages and add extra tests

- appveyor.yml
- circle.yml
- conda/activate.py
- conda/base/constants.py
- conda/base/context.py
- conda/cli/conda_argparse.py
- conda/cli/main.py
- conda/cli/main_run.py
- conda/common/path.py
- conda/exceptions.py
- conda/gateways/subprocess.py
- conda/shell/condacmd/conda_hook.bat
- conda/shell/etc/profile.d/conda.csh
- tests/core/test_initialize.py
- tests/test_activate.py
Per conversation with @mingwandroid, `cygpath "$(cygpath -w "$PATH")"` is not invariant.  See https://github.com/conda/conda/pull/7316 for additional context. This PR is only a partial fix. A full fix would require substantial hacks and additional logic in `conda.sh`.  It's my opinion at this time that suboptimal decisions made by upstream msys2 have lead to this situation (msys2 should have no `/bin`--just `/usr/bin`--and there'd be no bind mount for us to worry about here), and a full solution is ultimately incumbent on upstream.
NOTE: This PR needs to be rebased against master following merge of https://github.com/conda/conda/pull/7320. The functionality in this PR will most likely be back ported to conda 4.5.x.
The first commit of this PR is …
> msys2 path conversion

- conda/cli/conda_argparse.py
- conda/cli/main.py
- conda/cli/main_run.py
- conda/exceptions.py
- tests/test_activate.py
resolve #2682
Proof of concept code for `conda run`, implemented at the python level.  So far, only implemented on unix.  To test on unix
1. check out repo
2. `. dev/start`
3. `conda run python -- -V`
Will show python version.
4. `mkdir -p "$CONDA_PREFIX/etc/conda/activate.d"`
`echo "export TESTVAR=123456" > "$CONDA_PREFIX/etc/conda/activate.d/test.sh"`
`conda run python -- -c "import os; print(os.environ['TESTVAR'])"`
Will print `123456` to stdout.
I used the command `conda run` here instead of `conda exec` because we historically already "own" `conda run`, and I think there's already a `conda-exec` extension project that we would clobber.
This pretty much implements the old `conda run`, except we don't assume that users want to "run a package," but instead users know the name of the …
> resolve #2682 add conda run experimental support

- circle.yml
- tests/core/test_path_actions.py
- tests/gateways/disk/test_delete.py
- tests/gateways/disk/test_link.py
- tests/test_exports.py
These failures went undiscovered for so long because apparently appveyor is configured with symlinks enabled by default.  The failures showed up in the Anaconda build system, where symlinks aren't enabled by default on Windows workers.
> fix windows test failures when symlink not available

- circle.yml
- tests/test_create.py
The conda-build runs are broken because we released conda-verify 3.0.0 instead of conda-verify 3.0.2.
> Fix ci 4.5.x

- conda/shell/etc/fish/conf.d/conda.fish
Fixes #7412.
The original code used `find -printf` which does not exist on Mac.
Replaced `printf` (which is is not posix) with `basename` and `xargs` to fix autocompletion in fish.
Thanks!
> FIx autocompletion in fish

- conda_env/pip_util.py
This was causing conda env export to omit pip installed packages because later versions of pip (18.0) would fail when given conflicting formats. If you use conda-forge then pip 18.0 now gets installed by default.
> Fix inconsistent format setting given to pip list

- conda_env/pip_util.py
> fix conda env compatibility with pip 18

- conda/core/prefix_data.py
Special characters like '[',']' in prefix path need to be escaped for the glob module, which is annoying. Use fnmatch instead, which is used by glob1 internally anyway.
> PrefixData: replace glob with fnmatch 4.5.x

- conda/common/compat.py
Follow up to gh-7675; just fixing a minor oversight.
> common.compat: explicitly add Mapping, Sequence to module namespace

- tests/test_create.py
> A consequence of discontinuing use of the 'features' key and instead
> using direct dependencies is that removing the feature means that
> packages associated with the track_features base package are completely removed
> and not replaced with equivalent non-variant packages as before.
> integration test updates targeted at 4.5.x

- conda/_vendor/boltons/__init__.py
- conda/_vendor/boltons/setutils.py
- conda/_vendor/boltons/timeutils.py
- conda/cli/main_search.py
- conda/core/subdir_data.py
- conda/models/records.py
- tests/models/test_index_record.py
- tests/test_cli.py
resolve #7336, #7717
* Adds timestamp information to output of `conda search --info`. If timestamp is not given in repodata, tries falling back to date field.
* Addresses #7336 by trying exact match first, but then falling back to more flexible search by padding the package name with `*` before raising `PackagesNotFoundError`.
> conda search improvements

- appveyor.yml
- conda/base/constants.py
- conda/base/context.py
- conda/cli/conda_argparse.py
- conda/cli/install.py
- conda/cli/main_config.py
- conda/common/compat.py
- conda/core/link.py
- conda/core/solve.py
- conda/exceptions.py
- conda/models/records.py
- conda/resolve.py
- tests/base/test_constants.py
- tests/base/test_context.py
- tests/test_create.py
- tests/test_resolve.py
resolves #7656 
supersedes #7660
```
$ conda config --describe channel_priority
```
> strict channel priority via 'channel_priority' config option or --strict-channel-priority CLI flag

- conda/models/match_spec.py
- conda/models/version.py
- tests/models/test_match_spec.py
- tests/models/test_version.py
- tests/test_create.py
resolve #7782
See https://www.python.org/dev/peps/pep-0440/#compatible-release
> resolve #7782 implement PEP-440 '~=' compatible release operator

- conda/cli/main_list.py
> fix #7770 'conda list regex' only applies regex to package name

- conda/base/context.py
- conda/common/logic.py
- conda/resolve.py
The first two commits are not related to the configuration parameter and are just to move the stored clauses to the `SatSolver` instances (helpful in regards to https://github.com/conda/conda/issues/7697 and https://github.com/conda/conda/issues/7699). With CMS `5.6.5` we can then easily use `conda.common.logic.ClauseArray` without affecting the Pycosat interface that doesn't yet support that.
The main objective for this PR is to get some configuration parameter into the next prerelease versions so that people can easily try out the CryptoMiniSat solver, e.g., via
```sh
conda install -ynbase conda-forge::cryptominisat
export CONDA_TIMED_LOGGING=1
export CONDA_SAT_SOLVER=pycryptosat
conda create -vvdnx anaconda
```
It's obviously not supposed to be a configuration that is meant to stay, …
> add undocumented sat_solver config parameter

- conda/core/prefix_data.py
- setup.cfg
> warn about invalid python prefix data, instead of erroring out

- tests/common/pkg_formats/test_python.py
- tests/test_resolve.py
This should allow the CI to pass for a few more weeks until these tests can be more properly addressed.
> delay failing tests until 2018-12-01

- conda/shell/Library/bin/conda.bat
The return (status) code of `conda.bat` is not reliable and might return `0` while the command actually failed. 
This issue is particularly annoying in the context of CI:
```
BUILD START: ['test-0.0.1-0.tar.bz2']
source tree in: C:\miniconda3\conda-bld\test_1541521612815\work
...
File "C:\miniconda3\lib\site-packages\conda_build\utils.py", line 313, in check_call_env
return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
File "C:\miniconda3\lib\site-packages\conda_build\utils.py", line 293, in _func_defaulting_env_to_os_environ
raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
Job succeeded
```
I believe this is fixed in the …
> Fix `conda.bat` return code

- circle.yml
- conda/core/path_actions.py
- tests/common/pkg_formats/test_python.py
- tests/test_create.py
- tests/test_resolve.py
In case package to be installed is a noarch python package but the target
prefix doesn't have any version of python installed in it, target_site_packages
will not be filled. Raise an exception if the end user hits this scenario.
Fixes #5588
> Raise error if target_site_packages is needed but can't be computed

- conda/resolve.py
Speed up the solver by skipping the timestamp minimization step when there is a single "simple" solution after the package count minimization step.
It may be possible to skip other minimization steps using similar logic but further testing is needed.
> speed up solver by skipping timestamp minimization when not needed

- conda/gateways/disk/delete.py
Windows thinks the core python stuff is in use while conda is running.  Our method of retrying does nothing more than slow things down on windows.  This avoids the retry stuff for permission errors, and tries to schedule removal at reboot.  Unfortunately, that only works for admin users (elevated prompts, probably) these days (https://marc.durdin.net/2011/09/why-you-should-not-use-movefileex-with-movefile_delay_until_reboot-2/)
so, we give up much sooner and post a warning.
> try scheduling removal at reboot on win.  Fall back to warning message

- conda/base/context.py
When creating an environment name with colon, an error is thrown.
> Env name with colon is not supported.(#7716)

- conda/core/solve.py
When an inconsistent environment is detected try loading the package metadata
from the index to see if that results if that restores consistency. The
original metadata was loaded from the environments conda-meta directory and may
not have contain 'hotfixed' metadata.
closes #8076
> load metadata from index for inconsistent envs

- conda/shell/Scripts/activate.bat
Conda-forge has been complaining that direct calls to the old activate script, like:
```call c:\blah\Miniconda3\Scripts\activate.bat "env_path"```
are broken with conda 4.6, resulting in errors like 
```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.
To initialize your shell, run
$ conda init <SHELL_NAME>
Currently supported shells are:
- bash
- cmd.exe
- fish
- tcsh
- xonsh
- zsh
- powershell
See 'conda init --help' for more information and options.
IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```
This PR should fix those errors and provide better continuing support for this script.
> call conda.bat more directly in legacy activate.bat

- conda/resolve.py
we don't need to recurse through a package's specs if we're not including it because of strict channel priority.
> fix indentation in get_reduced_index that was make-work

- conda/core/prefix_data.py
- tests/core/test_prefix_data.py
> fix #8185 conda package filtering with embedded/vendored python metadata

- docs/source/user-guide/troubleshooting.rst
Added tip to troubleshooting for issues when downgrading conda from 4.6.1 to 4.5.x and then trying to ``conda install conda`` or  ``conda upgrade conda``, which produces a solving and upgrade error.
Related issues: https://github.com/conda/conda/issues/8080 & https://github.com/ContinuumIO/anaconda-issues/issues/10557
> Conda upgrade error tip in troubleshooting [skip ci]

- conda/shell/condabin/_conda_activate.bat
- conda/shell/condabin/conda.bat
- conda/shell/condabin/conda_auto_activate.bat
- conda/shell/condabin/conda_hook.bat
- tests/test_activate.py
CONDA_EXE and CONDA_BAT quoting changed so that they are quoted on use rather than on set.
Tested by installing miniconda 4.5 in a directory with spaces on windows, then updating conda to 4.6. At this point the problems show themselves. You can't run conda anything.
Replace the contents of condabin with these modified files and conda works again.
This problem was initially reported by me at https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/jHyb8uvIOnc
> CONDA_EXE and CONDA_BAT quoting changed so that they are quoted on use

- conda/gateways/disk/delete.py
- conda/gateways/disk/update.py
We've seen some issues where rename_tmp.bat can disappear in the middle of an install, which totally trashes that install.  Hopefully this PR downgrades those errors.  Things may still be in a non-ideal state, but at least this will allow the process to get further and maybe closer to a working state.
> handle missing rename script more gracefully

- conda/common/io.py
- conda/core/solve.py
The instrumentation added here will be visible with e.g.
```
export CONDA_INSTRUMENTATION_ENABLED=1
conda create -n rtest --dry-run -c r -c anaconda r-base --override-channels -v
```
> instrument more solve calls

- conda/core/link.py
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/activate_d_test.bat
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/bld.bat
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/build.sh
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/meta.yaml
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/post-link.bat
- tests/data/_conda_test_env_activated_when_post_link_executed_recipe/post-link.sh
- tests/test_create.py
Run post-link and post-unlink scripts in an activated environment. This is
implemented via an temporary script which activates the environment and then
calls the original script.
closes #7789
> activate env when running post-link/unlink scripts

- conda/core/link.py
Leving the variable unbound can trigger `UnboundLocalError("local variable 'script_caller' referenced before assignment")` on windows when executing pre-unlink scripts.
As in:
```00:00:44 ERROR conda.core.link:_execute(544): An error occurred while uninstalling package 'esss::conda-devenv-cleanup-0.1.0-1'.
00:00:44 UnboundLocalError("local variable 'script_caller' referenced before assignment")
00:00:44 Attempting to roll back.
00:00:44 
00:00:44 Rolling back transaction: ...working... done
00:00:44 
00:00:44 UnboundLocalError("local variable 'script_caller' referenced before assignment")
00:00:44```
> Ensure `script_caller` is bound

- conda/base/context.py
- conda/resolve.py
The behavior enabled by this experimental feature flag didn't pan out as hoped, and I think it's now safe to remove from the code base.
xref: #7601
> remove experimental featureless_minimization_disabled_feature_flag

- conda/core/link.py
using `prefix` as the tempfile prefix puts the temp file *next to* the prefix directory
instead of inside, which can fail with permission errors if the parent of the conda dir
is not writable by the current user.
This is a regression in conda 4.6.3 from #8229
I'm not sure how to write a unittest for this, but it can be reproduced with this Dockerfile:
```dockerfile
FROM continuumio/miniconda3:4.5.12
RUN conda config --system --set auto_update_conda false
RUN echo 'update_dependencies: false' >> /opt/conda/.condarc
ARG CONDA_VERSION=4.6.3
RUN conda install -yq -c conda-forge conda=${CONDA_VERSION}
RUN useradd -m test
RUN chown -R test:test /opt/conda
USER test
```
```bash
docker build -t test .
docker run --rm -it test conda install -vy -c conda-forge dbus
```
which gives:
```
Traceback …
```
> link: ensure prefix temp files are inside prefix

- docs/source/conf.py
Argparse was "fixing" double hyphens into a longer dash. Added in smartquotes = False to conf.py to stop this behavior.
> [skip ci] Argparse now keeps double hyphens as is

- conda/activate.py
- conda/common/compat.py
- tests/test_create.py
Allows activate.d scripts to be run on Windows if even if the prefix path contains unicode characters. 
closes #8241
> Use active code page for encoding activate script on Windows

- conda/shell/condabin/conda.bat
We cannot run python.exe (and expect it to work in general) without having all of the environment's path entries on PATH.
> Set the necessary PATH entries in conda.bat

- conda/cli/main.py
supersedes #8287 
This depends on a python patch that is in development.  This should not be merged until we can link it to confirmation that those python builds are available.
> prepend root prefix paths to PATH before running conda commands on win

- conda/cli/main.py
- conda/gateways/disk/update.py
os.environ['PATH'] is a string.  You can't add a generator to a string.  Shame on me.
> fix activator path output incorrectly adding to PATH

- conda/core/path_actions.py
- tests/core/test_path_actions.py
Just ignore folders for these reversals.  It's a bit messy, but it maintains the fix and it'll be faster.
> skip scanning folders for contents during reversal of transactions

- conda/compat.py
- conda/gateways/disk/delete.py
The previous code here was incorrect.  It led to only the first file being renamed in-place to .conda_trash - all others were left untouched, which resulted in permissions errors on the next thing to overwrite them.  This was especially a problem with conda-build and subpackages, where a prefix is removed and then created with new deps.
> tweak some logic in trash renaming to fix permission errors

- conda/gateways/disk/create.py
- conda_env/env.py
These were identified from user error logs as very high frequency errors.  There's one more remaining that would be good to fix:
```
Traceback (most recent call last):\n  File \""C:\\Users\\eanb.EDBIT\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\"", line 1002, in __call__\n    return func(*args, **kwargs)\n  File \""C:\\Users\\eanb.EDBIT\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\"", line 84, in _main\n    exit_code = do_call(args, p)\n  File \""C:\\Users\\eanb.EDBIT\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\"", line 82, in do_call\n    exit_code = getattr(module, func_name)(args, parser)\n  File \""C:\\Users\\eanb.EDBIT\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-pack …
```
> Improve some exception handling

- conda_env/installers/pip.py
If there is a space in the path to the .yml file for an environment, conda create will fail. This is because the temporary requirements file created here will be created in the same directory as the .yml file, and when the path to it is given to pip, it will fail if there is a space in it and the full path isn't quoted. This commit is ensuring that the path is quoted as part of the pip command. This fixes #8347.
I have not tested this change on Windows or Linux, just Mac OS.
> Quote path to temporary requirements file - fixes #8347

- conda/cli/install.py
Corrected the helper messages shown after 'conda create -n ENV_NAME'  as noted in [8364](https://github.com/conda/conda/issues/8364).
> Corrected the helper messages shown after 'conda create -n ENV_NAME' 

- conda/core/link.py
Reported by @oleksandr-pavlyk in conda 4.6.7
> handle None values for channel name in diff_strs gracefully

- circle.yml
The previous method of doing this on circleci broke since the
git diff, when stored in an environment variable did not include
any line breaks
> Fix checking for docs changes 

- tests/conda_env/test_env.py
Instead of using `ruamel_yaml` in one of the tests, continue to use `yaml_load`.
cc @jjhelmus
> Use `yaml_load` in all tests

- tests/test_create.py
This was a bit of a regression in #8307.  This fixes the source code ending up in cwd, which is generally conda root, which then dumps this extra "src" folder where you don't really want it.
> fix checkout of urllib code into cleaner location

- conda/core/envs_manager.py
In my Disaster Recovery environment we have read-only home directories because they are replicated from our normal environment.
> Handle read-only FS for environments.txt

- conda/core/solve.py
- conda/resolve.py
- tests/test_create.py
- tests/test_resolve.py
Improve the user experience when an environment is inconsistent.  
* Environments where pip has been removing or upgraded and `add_pip_as_python_dependency` was set when installing python will remove pip and a dependency of pip to try to restore consistency.
* The Python major and minor version will be maintained during modification of a inconsistent environment unless the user explicitly requests a Python version.
* A message is printed out informing users when a inconsistent environment is being modified.
closes #8391
> Improve handling of inconsistent environments

- conda/core/envs_manager.py
- conda/core/path_actions.py
I found an edge case related to #8451 where if the environments.txt file didn't exist package installation would fail when the user home directory was on a read-only file system. This patch prevents failure when trying to create the environments.txt or if the file doesn't exist when trying to register the environment.
> Edge case for RO FS & environments.txt

- conda/core/initialize.py
Python 2 does not have a FileNotFoundError so use IOError
> use IOError in Python 2 for FileNotFoundError

- conda_env/env.py
This PR fixes a minor bug in the detection of `pip` as a conda dependency in environment files. Without this patch, `conda env` would warn about `pip` dependencies being used when `pip` itself wasn't listed as a dependency, even if `pip` was listed like this:
```yaml
- pip=x.y.z
```
The change uses a regular expression (`r"[\s=]"`) to detect the name `pip` in the dependencies list.
> Improve detection of explicit pip specs in environment yml files

- conda/shell/etc/profile.d/conda.sh
testing with ==  works in bash, but not in zsh (may be other shells too), causing errors like "eval: = not found". Using single = ensures proper posix behaviour.
> Update conda.sh to support all shells
