tests/test_activate.py

This should fix the tests on TravisCI

Add code to skip tests when conda-env isn't on the PATH

---

conda/history.py
tests/test_history.py

Was just looking around and decided to add a few simple tests.  Trying to get in that habit.

A few tests to History

---

conda/cli/install.py

@ilanschnell @teoliphant this should fix the most common issues that come up with conda update --all. Since it's such a simple change, I suggest we play around with it a little, and then just release it, and see if we still have issues.

Update --all fixes

---

setup.py

Just a really small change to a string in setup.py.

Add missing word to setup.py string.

---

conda/connection.py

This pull request prepends conda/version to the user agent string in CondaSession.

add conda/version to user agent string

---

README.rst

For windows user is not trivial to figure out the correct command to activate and deactivate an environment, you need search on the web to find the correct answer.

Instructions to activate environment for windows

---

conda/cli/common.py
conda/cli/main.py
conda/cli/main_clean.py
conda/cli/main_config.py
conda/cli/main_create.py
conda/cli/main_help.py
conda/cli/main_info.py
conda/cli/main_init.py
conda/cli/main_install.py
conda/cli/main_list.py
conda/cli/main_package.py
conda/cli/main_remove.py
conda/cli/main_run.py
conda/cli/main_search.py
conda/cli/main_update.py

Updates to the conda command help

---

conda/cli/common.py
conda/cli/main.py
conda/cli/main_bundle.py
conda/cli/main_clean.py
conda/cli/main_config.py
conda/cli/main_create.py
conda/cli/main_help.py
conda/cli/main_info.py
conda/cli/main_init.py
conda/cli/main_install.py
conda/cli/main_list.py
conda/cli/main_package.py
conda/cli/main_remove.py
conda/cli/main_run.py
conda/cli/main_search.py
conda/cli/main_update.py

Mostly capitalization and periods. @kerrywatson1

More updates to the conda command docs

---

conda/logic.py
conda/resolve.py

Faster hint generation

---

conda/install.py
tests/test_install.py

As reported by @LilaHickey and confirmed by @asmeurer.

Fix issue where upgrades in Windows fail (v3.11.1)

---

conda/cli/main_remove.py

This also fixes conda remove --dry-run. Fixes #1317.

Add a confirmation to conda remove

---

CHANGELOG.txt
conda/fetch.py
conda/signature.py
conda/utils.py
tests/test_misc.py

The purpose of this PR is to implement the ability to handle signed packages, ie. packages which have associated with them a signature file (`.sig`).  The signature is downloaded after the package itself has been downloaded and then verified against the public keys stored in the `.conda/keys` directory.

Signed packages

---

.travis.yml

This lets it use the faster Docker infrastructure

Use sudo: false in .travis.yml

---

conda/cli/main_config.py
conda/config.py
conda/fetch.py
tests/test_config.py

Addresses https://github.com/conda/conda/issues/1387

allow arbitrary strings for ssl_verify option.

---

CHANGELOG.txt

add new features to CHANGELOG

---

conda/cli/main_search.py

Should provide a reasonable fix for #1378.

Add conda search --reverse-dependency

---

conda/connection.py
conda/fetch.py

Fixes #1495 and conda/conda-build#523.
@jasongrout can you test this?

Set the verify flag directly on CondaSession

---

conda/install.py

Fix issue where hardlinked cache contents were being overwritten

---

conda/cli/install.py

Fix conda create --clone with create_default_packages

---

conda/cli/install.py

Respect --no-deps when installing from .tar or .tar.bz2

---

tests/test_resolve.py

A minimal test for PR #1629. Feel free to merge or pick anything useful from it

Added test for local identifier separator

---

conda/cli/main.py
conda/cli/main_update.py

like uninstall for remove
some packagers user update, others use upgrade. This makes conda one case where I don't have to think so hard.

add conda-upgrade alias for conda-update

---

conda/cli/conda_argparse.py

This try block is otherwise masking an exception.

improve error output for bad command input

---

conda/utils.py

Used tempfile to determine whether a directory is writable.

---

conda/cli/main_config.py
conda/config.py

Add capability to add default_channels from the cli

default_channels from the cli

---

README.rst

add gitter to README

---

conda.recipe/bld.bat
conda.recipe/build.sh
conda.recipe/meta.yaml
conda.recipe/run_test.py
setup.py

Do not merge until @ilanschnell can add the `--old-and-unmanageable` flag to the conda build recipes.

cleanup setup.py

---

conda/resolve.py

fix for 3.19.2

---

conda/resolve.py

Minor fix here. When looking at some of the hits produced on a particularly messy unsatisfiable environment I found duplicates like this:
```
matplotlib -> python 2.7*
matplotlib -> python 2.6*
```
I'm now compressing these down to this:
```
matplotlib -> python 2.6*|2.7*
```
And also sorting the output. Should make for a nicer experience.

Improving hints: consolidate according to common sub-dependencies

---

conda/logic.py
conda/resolve.py
tests/test_logic.py
tests/test_resolve.py

We're not using the Sorter approach to linear bounds so I removed it. Logging has been cleaned up a little too

Solver tweaks: code reduction, minor performance tweaks

---

README.rst
auxlib/__init__.py
auxlib/packaging.py
auxlib/path.py
setup.py

@ilanschnell, merge on approval

auxlib root

---

CHANGELOG.txt

update CHANGELOG for 4.0.1

---

conda/resolve.py

The SAT logic system has a notion of "polarity". Generating clauses with polarity True means that you only intend to assert that clause is True (or you don't care). Generating clauses with polarity False means that you only intend to assert that the clause is False (or you don't care). If you need to _sometimes_ assert the clauses is True, and other times that it is False, then you need both polarities in the logic.
Well, it turns out that for the clauses that represent the presence or absence of features, we do sometimes need to assert True, and sometimes False. But the code is currently generating only True polarity. This fixes that

Features need "None" SAT polarity so we can assert they are false

---

conda/resolve.py

Jeff Reback reported some strange version selections in his Pandas CI process. For some reason it was tied to a subtle bug in how I was counting the number of packages with features being installed. I've adjusted the feature package count code a bit and that seems to have done the trick. I must confess I'm not _totally_ clear on why the original code was buggy. But what I removed was simply intended to reduce the complexity of the objective function---a performance hack. What is now here is far simpler and more straightforward.

Fix for strange interaction between features and versions

---

conda/resolve.py

Fix the with_features_depends leakage

---

CHANGELOG.txt
conda/fetch.py

This reverts commit f0bf1da660dc61998f9a33343c25a1cb761156c1.

Revert "Close session handles" #2217

---

conda/common/compat.py
conda/common/connection.py
conda/common/download.py
conda/common/lock.py
conda/common/utils.py
conda/compat.py
conda/connection.py
conda/fetch.py
conda/lock.py
conda/utils.py

give deprecation path for modules moved to conda.common

---

conda/cli/main_install.py
conda/cli/main_remove.py
conda/cli/main_update.py

Better `conda XXX --help` output. Please feel free to modify.

Improved docs for remove, update, install

---

.travis.yml
appveyor.yml
conda.recipe/meta.yaml
conda/cli/main_config.py
conda/config.py
conda/utils.py
setup.py
tests/test_config.py

Also fall back to `pyyaml` if `raml` isn't available.
@ilanschnell @msarahan

replace ruamel.yaml with raml

---

conda/install.py

@msarahan @ilanschnell 
for reference:
https://github.com/conda/conda/pull/1727/files#diff-fb1ca55b90c5cb761d62db03e6e0d406L716

fix install post #1727 flub

---

conda/cli/main_list.py

don't show channel urls by default

---

conda/console.py
conda/fetch.py
conda/resolve.py

#2005 needs rebased.  Doing so in this new PR.

Print progress to the terminal rather than stdout (formerly #2005)

---

conda/cli/main_config.py
conda/config.py
conda/utils.py
tests/test_config.py

create yaml_load and yaml_dump functions

---

conda/cli/activate.py
conda/install.py
conda/utils.py
tests/test_activate.py

Closes #2284 
Also makes test of translation a little more stringent.

better pass-through for paths in activate translation

---

conda/utils.py

See https://github.com/conda/conda/issues/2151 for a discussion on this PR.

Fix for try_write function in case of odd permissions

---

LICENSE.txt
conda/progressbar/LICENSE.txt
conda/progressbar/__init__.py
conda/progressbar/compat.py
conda/progressbar/widgets.py

re-license progressbar under BSD 3-clause

---

bin/conda.fish

As proposed in https://github.com/conda/conda/pull/545#issuecomment-211468499

Fish integration: Check activate.d and deactivate.d for *.fish scripts

---

.travis.yml
appveyor.yml
bin/activate
bin/activate.bat
bin/deactivate
bin/deactivate.bat
conda/cli/activate.py
conda/cli/common.py
conda/cli/install.py
conda/config.py
conda/install.py
conda/utils.py
tests/helpers.py
tests/test_activate.py
tests/test_config.py
tests/test_utils.py

closes #2362
Current state: cmd.exe OK, bash on windows not, OS X/Linux not tested.

WIP: Fix assertions in activate tests; fix exposed problems

---

conda/fetch.py

This is a follow-on from #1550

Detect threading issue on fetch

---

conda/config.py

Closes #2389 
cc @kalefranz @ilanschnell

remove "no path!" debug message

---

conda/cli/activate.py
conda/utils.py

fix ps1 on OSX bash

---

.travis.yml
appveyor.yml
conda/install.py
setup.cfg
tests/test_install.py

CC @ilanschnell @msarahan @mingwandroid 
Ok guys. This code works as expected.  But, what's going to happen on Windows? Should we make this a unix only thing?

use /usr/bin/env on long shebangs

---

conda/cli/activate.py

fix conda symlinking new env

---

conda/resolve.py
conda/version.py
tests/test_cli.py
tests/test_version.py

See https://github.com/conda/conda/issues/2485.

Handle simple trailing wildcards with full VersionOrder logic

---

conda/install.py

Otherwise conda has an incorrect picture of what is installed
in each prefix and using conda-build to build multiple packages
is fail.

install: Remove paths deleted from linked_data_

---

conda/connection.py
setup.cfg

fixes #2161, which I labeled a bug, but I guess was a "feature"

disable .netrc files

---

conda/install.py
tests/test_install.py

Add a test for standalone install

---

conda/install.py

Proper handling of cached packages without URLs

---

conda/install.py
conda/misc.py

Initial attempt to fix #2546 . Have to run so I can't promise this is ready, will look at it later

Handle case when conda-meta doesn't have the URL

---

conda/api.py
conda/cli/common.py
conda/cli/install.py
conda/cli/main_remove.py
conda/cli/main_search.py
conda/config.py

Revert "WIP: More aggressive enforcement of --offline"

---

appveyor.yml

Add early abort when new commits exist in a PR

---

conda/config.py

Addresses #2556 and #1911, I think. Let's check this out.
The scenario: user redefines `channel_alias` to something _other_ than their binstar server, and `add_anaconda_token` is set to `True` (or left to its default value of `True`). Then `normalize_urls` *replaces* the channel alias with the binstar alias plus the token. It shouldn't do this.
I _think_ that the design of the code is assuming that a redefined `channel_alias` always points to a binstar server if `anaconda_client` is installed.
As a side benefit, I'm delaying the call to `get_binstar` until the first time that it is needed. So if the user has no channels at all that call out to an Anaconda server, it won't even try.
@bkreider, @ilanschnell, need your feedback here. Studying the code here it looks like this has been a …

Allow channel_alias to be different than binstar

---

tests/test_create.py

clean up test_create logging output

---

conda/plan.py
tests/test_create.py

found a legit bug!!!
@mcg1969 see test output once it's ready

update and remove integration tests

---

tests/test_create.py

attempt integration test appveyor fix

---

conda/cli/install.py
conda/config.py
conda/utils.py

mgrant(is)crazy: or, make config resetable

---

conda/misc.py
tests/test_misc.py

fix explicit for windows paths with backslash

---

MANIFEST.in
tests/test_create.py

This PR won't address the problem directly reported in #2626.  But it's related.

WIP fix test_create for windows

---

tests/test_config.py

I was trying to run simultaneous tests in two separate conda environments---but with the same conda source directory---and sometimes getting strange errors. Turns out it was due `test_config.py` using a fixed filename for temporary condarc file testing. This fixes that by creating unique temporary files instead. A similar idiom is already employed in `test_create.py` to create temporary environments.

Use temporary files for condarc testing

---

conda/fetch.py

Not sure how this slipped in there; merge conflict perhaps. But `add_unknown` was assuming a dictionary with short channel keys and integer priority values---which is certainly what I'd prefer---but was being passed a dictionary with long URLS and (short channel,priority) tuples. That was the old way of doing things but somehow I reverted it elsewhere. This is the quickest fix.

fix add_unknown's use of the priority dictionary

---

bin/conda.fish
conda/cli/activate.py
conda/utils.py
setup.py

fix fish activate script for conda 4.1

---

conda/connection.py

If I understand everything correctly, this should solve https://github.com/conda/conda/issues/2677

fix #2677 respect HTTP_PROXY

---

conda/cli/main_list.py
conda/egg_info.py

fix #2700 conda list UnicodeDecodeError

---

conda/plan.py

Fix formatting of link instruction in the exceptional case

---

conda/install.py

@kalefranz this should hopefully address https://github.com/conda/conda/issues/2687

Os unlink 5 times

---

conda/config.py
tests/test_create.py

Fix usage of urlparse in is_url; fix windows tests

---

conda/cli/main_config.py
conda/connection.py
conda/utils.py
tests/test_config.py

Restores yes/no/on/off for booleans on the command line

---

conda/cli/main_config.py
conda/connection.py
conda/utils.py
tests/test_config.py

Reverts conda/conda#2734
Changes yaml_load to follow yaml 1.1 spec

make yaml booleans behave how everyone expects them to by now

---

bin/activate
conda/cli/activate.py

fix empty env name activating root on *nix shells

---

conda/fetch.py

Use accept-encoding for repodata

---

conda/cli/main_list.py
conda/config.py
conda/install.py
conda/misc.py
tests/test_create.py

See #2805, #2781. 
@kalefranz, we need to find a way to add an integration test for file-based channels.

Handle both file-based channels and explicit file-based URLs

---

conda/cli/common.py
tests/test_cli.py

Support epoch ! characters in command line specs

---

appveyor.yml
bin/activate
bin/deactivate
conda/cli/activate.py
conda/install.py
conda/instructions.py

Picks up where #2721 left off, aimed at 4.1.x branch.

fix shell recursion issue; install all shell shortcuts on win

---

conda/fetch.py

When downloading a file, the Content-Encoding is unrelated to the internal formatting of the file itself. When attempting to download a file which is being compressed by the web server we will obtain a compressed version of the file which does not match the MD5 sum of the original file.
For example:
```
➜  ~ curl -v http://dist.schmorp.de/libev/Attic/libev-4.22.tar.gz > libev-4.22.tar.gz
* Connected to dist.schmorp.de (5.9.56.12) port 80 (#0)
> GET /libev/Attic/libev-4.22.tar.gz HTTP/1.1
> Host: dist.schmorp.de
> User-Agent: curl/7.43.0
> Accept: */*
>
< Date: Fri, 17 Jun 2016 20:37:18 GMT
< Server: Apache/2.4.10 (Debian) OpenSSL/1.0.1k mod_perl/2.0.9dev Perl/v5.20.2
< Last-Modified: Sun, 20 Dec 2015 21:12:53 GMT
< ETag: "81c4d-5275ad5ee54d8"
< Accept-Ranges: bytes
< Content-Length: …
```

Use Response.iter_content rather than Response.raw

---

bin/activate
bin/activate.bat
bin/deactivate
bin/deactivate.bat
shell/conda.fish

Fixes #2764
Please test. Do not just trust me on this.

restore full path var on win; rename to CONDA_PREFIX

---

conda/fetch.py
tests/test_create.py

fix #2845 local file repo url

---

conda/fetch.py
conda/install.py

patch up exp backoff; pre rm_rf on fetch

---

conda/egg_info.py
tests/test_create.py

fixes #2754 
Supersedes #2870 
Here, we add reading METADATA files in .dist-info directories, see PEP 427.

improve listing pip installed packages

---

conda/cli/main_config.py
tests/test_config.py

add lowest and highest priority to channel config output

---

conda/install.py
tests/test_install.py

4.0 backport of 4.1 trash fix

---

conda/install.py
tests/test_install.py

4.0 backport of rm_rf fixes

---

conda/config.py

allows get_allowed_channels() to work before rc is loaded

---

conda/version.py
tests/test_version.py

Supersedes #2786 with some cleanup.

VersionSpec: expose full regex power

---

conda/_vendor/REAMDE.rst
conda/common/README.rst
conda/common/__init__.py
conda/core/README.rst
conda/core/__init__.py
conda/entities/README.rst
conda/entities/__init__.py
conda/gateways/README.rst
conda/gateways/__init__.py

Laying down some structure to have proper abstraction layers and isolation.
This PR introduces submodules for organization and project architecture.  The new modules are
* `conda._vendor`
* `conda.common`
* `conda.core`
* `conda.entities`
* `conda.gateways`
Descriptions and rules are in both README files and `__init__.py` files.

project structure enhancement

---

.travis.yml
conda/cli/activate.py
conda/cli/common.py
conda/cli/conda_argparse.py
conda/cli/help.py
conda/cli/install.py
conda/cli/main.py
conda/cli/main_clean.py
conda/cli/main_config.py
conda/cli/main_create.py
conda/cli/main_install.py
conda/cli/main_list.py
conda/cli/main_remove.py
conda/cli/main_search.py
conda/config.py
conda/exceptions.py
conda/fetch.py
conda/install.py
conda/misc.py
conda/plan.py
conda/resolve.py
conda/signature.py
conda/utils.py
tests/test_cli.py
tests/test_config.py
tests/test_create.py
tests/test_exceptions.py
tests/test_instructions.py
tests/test_plan.py

Remove *all* `sys.exit`s except for the one in `conda/__main__.py`.

No more exits

---

.travis.yml
Makefile
conda/base/README.rst
conda/base/__init__.py
conda/common/README.rst
conda/common/__init__.py
setup.cfg
utils/travis-run-install.sh

* cleans up .travis.yml
* introduces `conda.base`

Updates from condalib config

---

conda/config.py

@mingwandroid @msarahan @mcg1969 
Not sure how this slipped, or where it went.  I know we agreed a week ago to do this.

add msys2 channel to defaults on Windows

---

conda/config.py
tests/test_config.py

Handle null binstar token

---

conda/cli/main_info.py
conda/connection.py
conda/fetch.py

Revert "replace site-packages requests with vendored requests"

---

conda/cli/common.py
conda/cli/install.py
conda/cli/main_remove.py
conda/cli/main_search.py
conda/exceptions.py

neuter get_index_trap and let the exception handler deal with it

---

conda/lock.py

rename Locked class to Firelock. And add a deprecated warning for that

add deprecated info

---

conda/cli/main_config.py
conda/exceptions.py
conda/fetch.py
tests/test_config.py

address #3036 conda config --append/--prepend functionality

---

conda/cli/activate.py
conda/cli/find_commands.py
conda/cli/main.py
conda/cli/main_create.py
conda/cli/main_info.py
conda/cli/main_install.py
conda/egg_info.py
conda/install.py
conda/misc.py
conda/plan.py
conda/utils.py
tests/test_activate.py
tests/test_import.py
tests/test_plan.py

Only have one check for " sys.platform == 'win32' ", replace existing usages and checks.

One "on_win" check

---

conda/config.py
conda/fetch.py
conda/install.py
conda/misc.py
conda/utils.py
tests/test_create.py

improve repodata locking to enable parallel conda builds

---

conda/fetch.py
conda/install.py
conda/lock.py
tests/test_lock.py

@HugoTian I ran into an issue with `Locked` last night.  I think you'll understand if you review this PR for me.

split Locked between FileLock and DirectoryLock

---

conda/utils.py

@msarahan @mingwandroid 
Any issues with this PR?  Relates to https://github.com/conda/conda/issues/2151

scale back try_write function on unix

---

bin/activate
bin/deactivate

Fixes #2979. Supersedes #3077. Merging to 4.1.x code line.  Thanks @jhunkeler.

prevent redefinition of $SHELL variable

---

conda/misc.py

fixes #3060
@HugoTian I *think* this is the correct fix.  CC @mcg1969

fix #3060 --clone root --copy exception

---

conda/cli/common.py
conda/cli/install.py
conda/history.py
conda/plan.py
tests/test_create.py
tests/test_fetch.py
tests/test_history.py

create empty environments when no packages are supplied in create

Create empty environments

---

conda/utils.py

add threading lock for memoized, make it works better for multithreading, 
fix issue #3124

add thread lock to memoized

---

conda/fetch.py

fix a failure with multi-threaded repodata downloads

---

conda/base/constants.py
conda/cli/activate.py
conda/cli/common.py
conda/cli/install.py
conda/config.py
conda/fetch.py

@ilanschnell This PR will help decrease the size of #2537.

add base/constants.py

---

conda/cli/main_config.py
conda/common/yaml.py
conda/config.py
conda/utils.py
tests/helpers.py
tests/test_config.py

@ilanschnell This PR will help decrease the size of #2537.

move yaml to conda.common.yaml

---

conda/api.py
conda/cli/main_info.py
conda/cli/main_search.py
conda/config.py
conda/entities/channel.py
conda/fetch.py
conda/install.py
conda/misc.py
conda/plan.py
conda/resolve.py
tests/test_config.py
tests/test_create.py

This pulls out a big piece from https://github.com/conda/conda/pull/2537.  Once we merge this, I'll rebase that PR and make it smaller.  Tests pass, but it might not be perfect yet.  Really the goal is to minimize the size of #2537.
CC @ilanschnell @mcg1969

Channel entity

---

conda/_vendor/auxlib/packaging.py
setup.py

remove setuptools (again)

---

conda/base/context.py

Change anaconda_upload parameter type in context

add parameter type for anaconda upload

---

conda/__init__.py
conda/cli/install.py
conda/cli/main_config.py
conda/exceptions.py
conda/install.py
tests/test_create.py
tests/test_exceptions.py
tests/test_plan.py

move base CondaError to conda.__init__; register subclasses

---

conda/config.py
conda/resolve.py
conda/utils.py

check dependencies between conda and conda build

conda 4.2 patchups for conda-build

---

conda/install.py
conda_env/cli/main_export.py
conda_env/env.py

Add a flag to work around #2800

---

conda/exceptions.py

clean the lock in exception handler
#3161

Lock clean

---

conda/config.py
conda/lock.py
conda/utils.py

patches needed for 4.2 and conda-build

---

conda/install.py

fixes #2837
@HugoTian mind looking over this?  Do you agree that this is the right fix for #2837?

fix #2837 "File exists" in symlinked path with parallel activations

---

conda/cli/install.py

For issue #3207, when try to update from a file, should not return when only args.packages are satisfied

fix bug for update from file

---

conda/cli/install.py

Revert "fix bug for update from file"

---

conda_env/cli/main_export.py

name error , should be args.ignore_channels
For issue #3253

change name to ignore_channels

---

conda/cli/conda_argparse.py
conda/exceptions.py

#3242 , remove message for subprocess exiting message

Remove subprocess exiting message

---

conda/install.py
tests/test_install.py

@msarahan putting this in 4.2.  Any objections with the last commit?
supersedes #3224

enable binary prefix replacement on windows

---

conda/utils.py

Added zsh and zsh.exe to Windows shells.

---

conda/base/context.py
conda/cli/main_clean.py
conda/cli/main_remove.py
conda/common/disk.py
conda/connection.py
conda/fetch.py
conda/install.py
conda/lock.py
conda/misc.py
conda/plan.py
conda/utils.py
conda_env/cli/main_create.py
tests/conda_env/support/notebook.ipynb
tests/test_config.py
tests/test_install.py

@mingwandroid I've ended up doing a fairly major refactor to `rm_rf`.  It all started with the comment https://github.com/conda/conda/issues/3266#issuecomment-239241915.
Do you mind giving this a good look?
If you think everything conceptually looks ok, I'll go back and fix the tests in `test_install` that are failing just because of mock issues.  The functional/integration tests in `test_create` all appear to be passing.

windows trash permissions

---

conda/fetch.py

allow download urls with :: in them

---

conda/cli/main_config.py
tests/test_config.py
tests/test_create.py
tests/test_export.py
tests/test_info.py
tests/test_install.py
tests/test_instructions.py
tests/test_lock.py
tests/test_logic.py
tests/test_misc.py
tests/test_plan.py
tests/test_priority.py
tests/test_resolve.py
tests/test_toposort.py
tests/test_utils.py

Pr 3364 port

---

CHANGELOG.md

small spelling fixes to changelog

small spelling fixes to changelog

---

conda/common/configuration.py
setup.cfg
tests/common/test_configuration.py
tests/conda_env/support/notebook.ipynb

fix CONDA_CHANNELS env var

---

conda/base/context.py
conda/cli/common.py
conda/cli/install.py
conda/cli/main_list.py
conda/config.py
conda/connection.py
conda/exceptions.py
conda/models/channel.py
conda/plan.py
tests/test_create.py

fix force_32bit config

---

conda/base/context.py
conda/config.py

Along with https://github.com/ContinuumIO/anaconda/pull/560 resolves #3203.

import cio_test package

---

conda/base/context.py
conda/cli/main_clean.py
conda/cli/main_create.py
conda/cli/main_install.py
conda/cli/main_remove.py
conda/cli/main_update.py
conda/common/disk.py
conda/connection.py
conda/fetch.py
conda/install.py
conda/lock.py
conda/misc.py
conda/plan.py
conda/utils.py
conda_env/cli/main_create.py
tests/conda_env/support/notebook.ipynb
tests/test_config.py
tests/test_install.py
tests/test_instructions.py
utils/travis-run-install.sh
utils/travis-run-script.sh

This is a backport of #3280 for consideration in 4.2.x.
This PR is ultimately intended to address #3379 and #3266

backport rm_rf refactor into 4.2.x

---

conda/cli/install.py

fix #3409 unsatisfiable should raise

---

Makefile
conda/base/context.py
conda/install.py
conda/models/channel.py
conda/plan.py
tests/base/test_context.py
tests/models/test_channel.py

fix #3267 channels clone ent issue

---

conda/cli/install.py
conda/cli/main_remove.py
conda/history.py
conda/models/record.py

remove unnecessary eval

---

conda/connection.py
conda/models/channel.py

don't add binstar token if it's already in the url

---

conda/base/context.py
conda/common/configuration.py
conda/connection.py
conda/install.py
tests/base/test_context.py
tests/test_connection.py

regression tests associated with #3427

add regression tests and fixes associated with #3427

---

conda/cli/main_list.py

This PR implements the real intent of #3450 (and #3445)

fix botched copy/paste from #3450

---

conda/cli/install.py
tests/test_create.py

@quasiben mind doing a quick code review for me?

fix #3453 conda fails with create_default_packages

---

conda/__init__.py
conda/cli/common.py
conda/cli/install.py
conda/exceptions.py
tests/test_create.py

fix #3455 --dry-run and add regression test

---

conda/common/configuration.py
tests/common/test_configuration.py

fix #3467 AttributeError: 'str' object has no attribute 'items'

---

conda/install.py

resolves #3525 
@quasiben Can you please review?

fix #3525 writing to sys.stdout with --json flag for post-link scripts

---

conda/base/constants.py
tests/base/test_constants.py

resolves #3492
supersedes #3513

Make Null falsey with python 3

---

conda_env/cli/main.py

resolves #3536
@goanpeca Can you review please?

fix #3536 conda-env messaging to stdout with --json flag

---

.condarc
conda/exports.py
tests/test_exports.py

add conda.exports module

---

conda/api.py
conda/base/constants.py
conda/cli/main_search.py
conda/models/channel.py
tests/test_create.py
tests/test_export.py

Resolves #3476
Supersedes #3602 (repointed to 4.2.x branch)

Search channels by platform

---

conda/cli/main_info.py

This is a prereq for https://github.com/conda/conda-build/pull/1407 - some of this metadata is otherwise annoying to parse out of text output.  Please review quickly.

add json output for conda info -s

---

conda/install.py
tests/test_install.py

Intended to address https://github.com/conda/conda-build/issues/1409

ignore binary prefixes on windows that we don't yet understand

---

conda/base/context.py
conda/cli/main.py
conda/common/configuration.py
tests/test_config.py

Possible fix for https://github.com/conda/conda/issues/3590

Catch exception when parsing yaml

---

.condarc
conda/exports.py
tests/test_exports.py

Mostly a cherry-pick of #3429
Resolves #3651
CC @msarahan

backport conda.exports module to 4.2.x

---

conda_env/cli/common.py
conda_env/cli/main_create.py
conda_env/cli/main_upload.py
conda_env/env.py
conda_env/pip_util.py
conda_env/specs/binstar.py
setup.cfg

Turn on flake8 for `conda_env`. Thankfully, there aren't that many errors, so there's a relatively small diff.

Flake8 conda-env

---

conda/cli/install.py

@mcg1969 Care to weigh in here? I think this code is dead and should go.

remove dead install_tar function

---

conda/common/url.py
conda/gateways/anaconda_client.py
tests/test_connection.py
tests/test_create.py

This PR will have to be cherry-picked back to 4.2.x. It includes a major bug fix for anaconda.org tokens.

anaconda api token bug fix; additional tests

---

conda/base/constants.py
tests/models/test_channel.py

CC @ilanschnell @csoja @msarahan @mingwandroid

add r channel to default defaults

---

conda/install.py

fix #3646 FileMode enum comparison

---

conda/cli/install.py
tests/test_create.py

fix #3517 conda install --mkdir

---

conda/base/context.py
conda/cli/main_config.py
tests/base/test_context.py

fix #3469 alias envs_path to envs_dirs

---

conda/common/disk.py

only try once for windows trash removal

---

conda/cli/main_info.py
conda/utils.py

@soapy1 Could you please review?

add user-agent, uid, gid to conda info

---

conda_env/yaml.py

fix #3738 move conda-env to ruamel_yaml

---

conda/common/disk.py

@mparry thanks for https://github.com/conda/conda/issues/3664#issuecomment-256665339

another patch for #3664 trash emptying

---

conda/models/channel.py
tests/models/test_channel.py

resolves #3717 
Actually a relatively simple change.

fix #3717 allow no-name channels

---

conda/base/context.py
tests/base/test_context.py

fix #3732, #3471, #3744 CONDA_BLD_PATH

---

.travis.yml
appveyor.yml
conda/install.py

ref: https://github.com/conda/conda/issues/3692

Exit and show error message when prelinking

---

conda/base/context.py
conda/core/index.py
conda/core/package_cache.py

resolves #3830 along with #3831
CC @quasiben

make http timeouts configurable

---

.travis.yml
appveyor.yml
conda/install.py

ref: https://github.com/conda/conda/issues/3692

Error and exit for upgrading noarch and info/files

---

conda/cli/install.py
conda/exceptions.py
tests/test_exceptions.py

ref: https://github.com/conda/conda/issues/3771
A proposed first step for the issue above that just improves error messaging
cc/ @kalefranz

Better error message for assertion errors

---

conda/base/context.py

extra validation per https://github.com/conda/conda/pull/3870#issuecomment-260244320

add check for mutually exclusive always_softlink and always_copy

---

conda/base/context.py
conda/common/disk.py
conda/config.py
tests/base/test_context.py

This should fully address remaining issues in #3744

Backport conda build config

---

conda/_vendor/auxlib/logz.py
conda/base/context.py
conda/cli/install.py
conda/common/compat.py
conda/core/index.py
conda/gateways/adapters/localfs.py

address #3879 don't print activate message when quiet config is enabled

---

conda/misc.py

fixes https://github.com/conda/conda/issues/3881

Don't install conda-env in clones of root

---

conda/cli/main_clean.py
conda/core/index.py
conda/core/package_cache.py
conda/exceptions.py
conda/exports.py
tests/test_lock.py

An experiment to see conda without file locks 📁 🔒 
Ref: https://github.com/conda/conda/issues/3836

Remove file locks

---

.travis.yml
conda/cli/main_list.py
conda/instructions.py
conda/models/dist.py
utils/appveyor-install.bat
utils/tester.bat
utils/travis-install.sh

supersedes: https://github.com/conda/conda/pull/3905

conda-build dist compatibility: make tests past

---

conda/cli/main_clean.py
conda/common/compat.py
conda/exports.py

ref: https://github.com/conda/conda-build/pull/1501#discussion_r87909801

Move CrossPlatformStLink and make available as export

---

conda/base/constants.py
conda/core/portability.py
conda/gateways/disk/create.py
conda/gateways/disk/read.py
conda/gateways/disk/update.py
conda/models/channel.py
tests/core/test_portability.py

fix #3999 spaces in shebang replacement

---

MANIFEST.in
setup.py

This is unfortunate https://github.com/pypa/pip/issues/2933

warning messages in setup.py no longer work with pip + wheel

---

conda/base/constants.py
tests/core/test_portability.py

fixes #4097 (at least it should)

fix #4097 keep split in PREFIX_PLACEHOLDER

---

conda/exports.py

supersedes #4101
pulling back to 4.2.x branch

Include defaults listings for Windows and Unix.

---

conda/core/linked_data.py
conda/models/dist.py
conda/resolve.py
tests/test_plan.py

add fields to dist object

---

conda/core/link.py
tests/test_create.py

At least I can now write tests and mock out the subprocess call.
Addresses part of #4105.

fix pre/post unlink/link scripts

---

conda_env/env.py

fix #4152 conda env export failure

---

conda/base/context.py

make subdir configurable

---

conda/common/path.py
conda/core/index.py
conda/misc.py
conda/models/channel.py
tests/common/test_path.py
tests/models/test_channel.py

Windows test fix and subdir assertion

---

conda/cli/main.py

update context when calling main()

---

conda/cli/main.py

Fix errant sys.argv reference

---

conda.recipe/meta.yaml
conda/common/compat.py
conda/connection.py
utils/travis-run-install.sh

backport of localfs.py from #3886
supersedes #4044

local file:// fix for requests >= 2.12.0

---

conda/core/index.py

don't use local cached repodata for file:// urls

---

conda/cli/activate.py
conda/cli/conda_argparse.py
conda/cli/main_clean.py
conda/cli/python_api.py

I initially found a misspelling in the conda's CLI usage. I searched and fixed a few other instances.

Fix spelling

---

conda/cli/main_remove.py
conda/plan.py
conda/resolve.py
tests/test_create.py
tests/test_resolve.py

Remove features properly

---

conda/cli/install.py

Remove questionable "nothing to install" logic

---

conda/core/index.py

@mcg1969 I think this is the best path forward for 4.3.

relax channel noarch requirement for 4.3

---

conda/misc.py

fix #4235 print message to stderr

---

conda/gateways/download.py

resolves #4299 
@nehaljwani  Thanks for the research.  Any recommendation on a solution?

disable raise for Content-Length mismatch until correct logic can be determined

---

tests/test_create.py

After this passes, we need to use a PR to merge it into 4.3.x.

add update --all and package pinning tests

---

conda/common/compat.py
conda/core/index.py

use unicode_escape after etag regex instead of utf-8

---

conda/__init__.py

put CONDA_ROOT back in __init__.py

---

conda/cli/activate.py
conda/cli/main.py
conda/cli/main_info.py
shell/deactivate

fix deactivate

---

CHANGELOG.md

fix changelog typos

---

conda/resolve.py

fix #4351 infinite recurssion via code in #4120

---

conda/cli/main.py

fix appending to tuple

---

conda/core/path_actions.py

fix #4309 ignore EXDEV error for directory renames

---

conda/core/path_actions.py
conda/gateways/disk/test.py
conda/gateways/disk/update.py

resolves https://github.com/conda/conda/issues/4393

fix #4393 by force-renaming certain backup files if the path already exists

---

conda/models/index_record.py

fixes https://github.com/conda/conda/issues/4398

fix #4398 apparently 'hard' was used for link type at one point

---

conda/core/linked_data.py
conda/models/dist.py

fix https://github.com/SciTools/conda-build-all/issues/76

fix 'Dist' object has no attribute 'fn'

---

conda/core/path_actions.py
conda/models/enums.py
conda/models/index_record.py
conda/models/package_info.py
tests/test_create.py

resolves https://github.com/conda/conda/issues/4428

fix noarch generic and add additional integration test

---

conda/core/path_actions.py
conda/gateways/disk/create.py

resolves #4425 
at least I hope it does

fix #4425 unknown encoding

---

conda/core/link.py

silence pre-link warning for old noarch

---

conda/install.py

silence pre-link warning for old noarch 4.2.x backport

---

.travis.yml
conda/common/subprocess.py
conda/core/link.py
conda/exceptions.py
conda/exports.py
conda/gateways/disk/create.py
conda/gateways/signals.py
conda/gateways/subprocess.py
tests/test_create.py
utils/travis-run-install.sh

This PR is based on advice from http://stackoverflow.com/questions/13593223/making-sure-a-python-script-with-subprocesses-dies-on-sigint
addresses #4443

subprocess_call function

---

conda/gateways/disk/read.py

As proposed for https://github.com/conda/conda/issues/4481
CC @ilanschnell

respect info/link.json

---

conda/core/index.py
tests/test_export.py

improve empty repodata noarch warning and error messages

---

conda/base/context.py
conda/cli/main_config.py
conda/config.py
tests/test_config.py

fix ssl_verify set type

---

conda/_vendor/auxlib/type_coercion.py
conda/base/context.py
conda/plan.py

CC @mcg1969 
Whether we use this for fusion or not, no harm in making it configurable.

let default_python be None

---

README.rst
appveyor.yml
conda/cli/pip_warning.py
setup.py

prepare conda for uploading to pypi

---

conda/gateways/disk/test.py

fix file_path_is_writable without using touch

---

conda/core/index.py
conda/gateways/download.py

better general http error message

---

conda/core/index.py

fix #4592 BufferError cannot close exported pointers exist

---

CHANGELOG.md
conda/base/context.py
conda/cli/main_clean.py
conda/core/index.py
tests/test_create.py

fix pkgs_dirs order regression

---

conda/base/context.py

fix #4636 environment variable expansion for pkgs_dirs

---

conda/core/index.py

fix #4649 incorrect assert statement concerning package cache directory

---

conda/cli/main_clean.py
conda/common/compat.py
conda/compat.py
conda/exports.py
conda/gateways/disk/create.py
conda/gateways/disk/delete.py
conda/gateways/disk/link.py
conda/gateways/disk/permissions.py
conda/gateways/disk/read.py
conda/gateways/disk/test.py
conda/instructions.py
conda/misc.py
tests/gateways/disk/test_delete.py
tests/gateways/disk/test_link.py

link, symlink, islink, and readlink commands for windows

---

conda/core/index.py
conda/core/repodata.py
conda/misc.py
conda/plan.py
tests/core/test_index.py
tests/core/test_repodata.py
tests/test_create.py
tests/test_fetch.py
tests/test_misc.py

separate repodata logic from index into a new core/repodata.py module

---

conda/gateways/disk/create.py

fix #4703 menuinst PathNotFoundException

---

conda/cli/main_info.py

Should help with https://github.com/ContinuumIO/anaconda-issues/issues/1443

ignore permissions error if user_site can't be read

---

conda/models/channel.py

fix #4694 don't import requests directly in models

---

conda.recipe/bld.bat
conda.recipe/build.sh

fix #4715 include resources directory in recipe

---

conda/models/package_info.py

allow sha256 to be None

---

conda/exports.py

add cache_fn_url to exports

---

conda/core/repodata.py
conda/gateways/download.py

make sure url gets included in CondaHTTPError 

---

conda/common/path.py
conda/core/package_cache.py
conda/exports.py
conda/gateways/disk/read.py
conda/utils.py

fix #4777 package cache initialization speed

---

conda/common/configuration.py
tests/common/test_configuration.py

correct fix might be previously executed logic though
fix #4757

fix for #4757 avoid match with value None

---

shell/activate.bat

@kalefranz, @csoja would like a test Miniconda release containing this change. This is an attempt to fix https://github.com/ContinuumIO/anaconda-issues/issues/1410. If you would prefer not to merge it then I'll make a local patch for conda for @ilanschnell to try out.

activate.bat: Set codepage to CP_ACP

---

conda/core/path_actions.py

fix #4788 partial package extraction

---

conda/cli/main_clean.py

fix break-point in conda clean

---

conda/gateways/disk/create.py

Installing noarch packages into paths longer than the shebang limit has been broken.  This hopefully fixes it.  It at least fixes it for conda-build, which recently switched the test path to being the full 255-character prefix length.

fix long shebangs when creating entry points

---

conda/plan.py
tests/test_priority.py

Fix spelling: superceded -> superseded.

---

conda/_vendor/auxlib/type_coercion.py
conda/base/constants.py
conda/base/context.py
conda/cli/main_config.py
conda/common/configuration.py
conda/config.py
conda/connection.py
conda/exports.py
tests/base/test_context.py
tests/test_config.py

@electronwill After this PR is complete, we'll want to make sure the conda docs match this updated content.

add 'conda config --describe' and extra config documentation

---

conda/core/path_actions.py
conda/gateways/disk/create.py

fix #4914
cc @mingwandroid @goanpeca

fix #4914 handle directory creation on top of file paths

---

shell/conda.fish

supersedes #4896 
resolves #2611

Issue #2611: update documentation about how to source conda.fish

---

conda/cli/install.py
conda/cli/main_remove.py
conda/cli/main_search.py
conda/exceptions.py
tests/test_create.py

PR: Fix missing information on `Package not found`error 

---

conda/cli/conda_argparse.py
conda/cli/main.py
conda/exceptions.py
tests/test_exceptions.py

fix #4944 command not found error error

---

conda/gateways/disk/create.py
tests/test_activate.py
tests/test_export.py

fall back to copy if hardlink fails

---

conda/gateways/logging.py

remove binstar logger configuration overrides

---

conda/cli/install.py

Fixing Error in DirectoryNotFoundError

---

conda/cli/activate.py
conda/cli/common.py
conda/cli/install.py
conda/cli/main.py
conda/cli/main_info.py
conda/cli/main_list.py
conda/cli/main_remove.py
conda/cli/main_search.py
conda/config.py
conda/connection.py
conda/exceptions.py
conda/exports.py
conda/gateways/adapters/ftp.py
conda/gateways/adapters/localfs.py
conda/gateways/download.py
conda/install.py

This PR is meant to help with #5039.

fix #5039 collecting main_info shouldn't fail on requests import; full audit for using relative import paths

---

conda/core/repodata.py

fix #5055 improve bad token message for anaconda.org

---

conda/common/signals.py

fix #5033 only re-register valid signal handlers

---

conda/cli/main_list.py

Should help address the first-level issue (and only one we can have knowledge of) in #5028.

fix #5028 imports in main_list

---

conda/_vendor/__init__.py
conda/_vendor/auxlib/__init__.py
conda/_vendor/auxlib/logz.py
conda/common/platform.py
conda/connection.py
conda/utils.py

gnu_get_libc_version => linux_get_libc_version

---

conda/plan.py
tests/test_create.py
tests/test_plan.py

fix #4849 package name match bug

---

conda/cli/common.py
conda/cli/install.py
conda/core/path_actions.py
conda/gateways/disk/create.py
conda/misc.py
conda/resolve.py
tests/core/test_path_actions.py
tests/test_cli.py
tests/test_create.py

improve behavior and add tests for spaces in paths

---

conda/_vendor/auxlib/type_coercion.py
tests/base/test_context.py

fix #5111 incorrect typify for str + NoneType

---

.codecov.yml
conda/base/context.py
conda/cli/main_info.py
conda/common/toposort.py
conda/connection.py
conda/core/repodata.py
conda/exports.py
conda/gateways/connection.py
conda/gateways/download.py
conda/resolve.py
tests/test_connection.py
tests/test_toposort.py

organization and cleanup for 4.4 release

---

conda/core/path_actions.py

further work toward resolve #4671

hold verify backoff count in transaction context

---

conda/exports.py

resolve #5123 export toposort

---

conda.recipe/meta.yaml
conda/cli/activate.py
conda/core/envs_manager.py
conda/core/link.py
conda/core/path_actions.py
conda/gateways/disk/create.py
conda/instructions.py
conda/models/enums.py
conda/models/index_record.py
conda/models/leased_path_entry.py
conda/models/package_info.py
conda_env/cli/main_create.py
tests/core/test_envs_manager.py

It's not needed anymore since conda is now a shell function per #5044

remove symlinking conda

---

conda/common/signals.py
conda/exports.py

resolve #5132
As discussed with @stefanseefeld, may not be the correct solution yet, but at least might help with the current stack trace.

fix #5132 signal handler can only be used in main thread

---

README.rst
tests/conda_env/test_env.py

supersedes #5119
resolves #5136

remove pyyaml dependency in tests and update instructions

---

conda.recipe/bld.bat
conda/activate.py
conda/cli/main.py
shell/conda.xsh
tests/test_activate.py
utils/functions.sh

supersedes #4227
resolves #5160

conda xontrib

---

conda/cli/main_info.py

fix #5152 conda info spacing

---

conda/common/platform.py
conda/install.py
conda/instructions.py
conda/utils.py

remove disk space check instructions

---

conda/core/path_actions.py

backport LinkPathAction verify from 4.4

---

conda/activate.py
tests/test_activate.py

Code to get the new #5044 framework started for fish and powershell.
fish guys:  @jaimergp @zzag @soxofaan feel free to start using this.

fish and powershell starter

---

conda/common/configuration.py
tests/common/test_configuration.py

resolves #5184 
CC @nehaljwani

fix #5184 stack trace on invalid map configuration parameter

---

conda/cli/main_remove.py
tests/test_create.py

conda remove spelling check

---

conda/common/configuration.py
tests/common/test_configuration.py

fix #5189 stack trace on invalid sequence config param

---

conda/base/context.py
conda/core/link.py
conda/core/package_cache.py

resolve #1597 make extra sure --dry-run doesn't take any actions

---

conda/__init__.py
conda/exceptions.py
tests/test_create.py

fix #3470 extra newlines around exceptions

---

conda/cli/install.py

resolve #4987 conda update --all no longer displays full list of packages

---

conda/cli/main_config.py

fix #598 stack trace for condarc write permission denied

---

conda/cli/main_remove.py
tests/test_create.py

fix #3489 don't error on remove --all if environment doesn't exist

---

conda/core/link.py

fix #4974 no matching dist in linked data for prefix

---

conda/cli/main_info.py
conda/common/platform.py

resolve #4151 add admin indicator to conda info on windows

---

conda/gateways/disk/create.py

resolve #4911
details in https://github.com/conda/conda/issues/4911#issuecomment-300185395

fix #4911 separate shutil.copy2 into copy and copystat

---

tests/test_create.py

tests for --update-deps flag

---

conda_env/yaml.py

fix #5272 conda env export ugliness under python2

---

conda_env/pip_util.py

fix #4596 warning message from pip on conda env export

---

conda_env/specs/__init__.py
conda_env/specs/binstar.py

fix #3689 better error messaging for missing anaconda-client

---

conda_env/__main__.py
conda_env/cli/main_export.py

fix #4795 conda env export lacks -p flag

---

tests/test_create.py

fix #462 add regression test

---

conda/cli/install.py
conda/misc.py

resolve #1427 remove startswith '.' environment name constraint

---

conda/__init__.py
conda/_vendor/auxlib/packaging.py
conda/base/context.py
conda/cli/common.py
conda/cli/install.py
conda/common/io.py
conda/common/signals.py
conda/exceptions.py
conda/install.py
tests/cli/test_common.py
tests/test_create.py

fix #5288 confirmation prompt doesn't accept no

---

conda/core/path_actions.py

The #5296 experiment made me want to add this.

add assertion that a path only has a single hard link before rewriting prefixes

---

conda/cli/main_package.py
conda/common/path.py

fix #1713 'conda package -w' is case dependent on Windows

---

conda/cli/main_clean.py

fix #4986 --yes not functioning for conda clean

---

conda/cli/main_config.py
tests/test_config.py

resolve #4302 add ability to set map parameters with conda config

---

conda/cli/main_config.py
tests/test_config.py

fix #5256 enable conda config --get for all primitive parameters

---

conda/cli/conda_argparse.py
conda/cli/main_remove.py

resolve #1992 add short flag -C for --use-index-cache

---

conda/cli/main_clean.py

resolve #2173 add --quiet option to conda clean

---

conda/base/context.py

resolve #5315 add alias verify_ssl for ssl_verify

---

conda/cli/activate.py
conda/cli/main.py
conda/exceptions.py
conda/history.py
conda/install.py

fix #5329 unicode errors on Windows

---

conda/cli/main_info.py
conda/common/platform.py

resolve #3399 add netrc existence/location to 'conda info'

---

conda_env/cli/main_update.py

resolve #3810 add --prefix to conda env update

---

conda/cli/conda_argparse.py

fix #5346 conda subcommands not being forwarded under python 2

---

conda/cli/main.py
conda_env/cli/main.py
conda_env/cli/main_export.py
tests/test_create.py
utils/functions.sh
utils/requirements.txt

fix #5341 add --json to conda-env

---

conda/cli/conda_argparse.py

typo: avaialble -> available

---

conda/cli/conda_argparse.py

resolve #5358 conda should exec to subcommands, not subprocess

---

conda/plan.py
tests/test_plan.py

fix #5248 drop plan description information that might not alwasy be accurate

---

conda/gateways/logging.py

fix #5378 duplicate log messages

---

conda/gateways/logging.py

fix #5356 skip root logger configuration

---

conda/cli/main.py

resolves #5384 
Fixes a little refactoring mistake that caused #5384.

fix #5384 silence logging info to avoid interfering with JSON output

---

tests/test_create.py

resolve #5402 add regression test for #5384

---

conda_env/cli/main_update.py

fix #5420 conda-env update error

---

conda/resolve.py
tests/test_create.py

resolves #5081 
Add a failing test to measure progress in implementing support for optional pinning in 4.4.x

resolve #5081 make pinned packages optional dependencies

---

conda/common/platform.py
tests/common/test_platform.py

fix #5425 is admin on win int not callable

---

conda/cli/common.py
conda/cli/find_commands.py
conda/cli/help.py
conda/cli/main_clean.py
conda/cli/main_config.py
conda/cli/main_create.py
conda/cli/main_install.py
conda/cli/main_package.py
conda/cli/main_remove.py
conda/cli/main_search.py
utils/functions.sh

resolve #5428 clean up cli import in conda 4.3.x

---

conda/cli/main_clean.py
tests/test_create.py

fix #5451 conda clean --json bug

---

conda/cli/install.py

fix #5400 confusing deactivate message

---

conda_env/cli/main_create.py
conda_env/cli/main_update.py

fix #5444 environment.yml file not found

---

conda/base/context.py
conda/common/url.py
conda/models/channel.py
conda/models/dist.py
tests/models/test_channel.py

fix #5459 custom subdir installation

---

conda/exports.py

more selective invalidation of prefix cache for conda-build

---

conda/__init__.py

fix #5515 add contains method to CondaMultiError

---

conda/gateways/disk/test.py

fix #5508 assertion failure after test file not cleaned up

---

conda/misc.py

Catches OSError when home directory doesn't exist

---

conda/exceptions.py

Fixes an error in the logic of how conda handles POST redirects for exception reporting.

fix GET exception redirects

---

conda/cli/install.py
conda/common/io.py
conda/exceptions.py
conda/resolve.py
tests/test_exceptions.py

@mbargull This is something I had been working on but hadn't pushed yet.  There are pieces where lines will conflict with #5578 that we'll have to fix.  Probably should just merge the two PRs together.

refactor ExceptionHandler so it can be more easily extended

---

conda/exceptions.py

One fix for python argparse internals calling sys.exit() and another fix for flake8.

final beta1 fixes

---

conda_env/cli/main_upload.py

In continuation of #4818
Supersedes #5620 

Remove last remnant of CondaEnvRuntimeError

---

conda/cli/install.py
tests/test_activate.py
tests/test_create.py
tests/test_export.py
utils/functions.sh

fix #5649 create_default_packages configuration

---

conda/common/url.py
conda/core/path_actions.py
conda/models/dag.py

This PR also implements a module-level `__main__` in `conda.models.dag` that can be used to generate a graphviz SVG of an environment.  E.g.
/conda/bin/python -m conda.models.dag /path/to/conda/environment

try fixing segfault with proxy

---

conda/models/channel.py
tests/models/test_channel.py
tests/test_activate.py
tests/test_create.py
tests/test_export.py

fix #5763 channel url string splitting error

---

conda/cli/install.py

fix #5790 incorrect activation message

---

conda/core/package_cache.py

fix #5808 assertion error when loading package cache

---

conda_env/cli/main_update.py
conda_env/installers/conda.py
conda_env/installers/pip.py

fix #5809 _pip_install_via_requirements got an unexpected keyword argument 'prune'

---

circle.yml
conda/cli/common.py
conda/cli/install.py
conda/core/link.py
tests/test_create.py

fix #5825 --json output format

---

conda/base/context.py

resolve #5834 change default value of 'always_softlink' from True to False

---

conda/core/repodata.py
conda/core/solve.py
tests/core/test_solve.py

@msarahan Thanks for helping find the bug.  Additional unit test added.

fix force_reinstall for case when packages aren't actually installed

---

conda_env/cli/main_attach.py
conda_env/cli/main_upload.py
conda_env/specs/binstar.py
conda_env/specs/notebook.py

resolve #5842 add deprecation warnings for 'conda env upload' and 'conda env attach'

---

conda/core/repodata.py

resolve #5920 bump repodata pickle version

---

conda.recipe/setup.py
conda/__init__.py
conda/cli/main.py
conda/cli/main_config.py
conda/cli/main_create.py
conda/cli/main_install.py
conda/cli/main_list.py
conda/cli/main_package.py
conda/cli/main_remove.py
conda/install.py
conda/lock.py
utils/setup-testing.py

I'm pretty sure I signed up to do this a while back...

Remove Continuum from the file headers

---

conda/cli/activate.py
conda/utils.py
tests/test_activate.py
tests/test_utils.py

Fix msys2 activate and deactivate 

---

conda/gateways/disk/delete.py
tests/test_create.py

superseding #5975
more discussion there

fix #5980 always delete_prefix_from_linked_data in rm_rf

---

conda/base/context.py
conda/cli/conda_argparse.py
conda/cli/install.py
tests/test_create.py

resolve #5983 add --download-only flag to create, install, and update

---

.travis.yml
conda/base/context.py
conda/common/configuration.py
conda/common/path.py
conda/core/package_cache.py
conda/gateways/disk/test.py
conda/gateways/disk/update.py
conda/misc.py
tests/conda_env/support/advanced-pip/src/pip-delete-this-directory.txt
utils/functions.sh

fix #5854 remove imports of pkg_resources

---

conda/models/index_record.py
tests/models/test_index_record.py

fix #6096 keep timestamps in integer seconds

---

conda_env/env.py
tests/conda_env/test_cli.py

fix #6220 --no-builds flag for 'conda env export'

---

conda/base/context.py
tests/test_activate.py
tests/test_create.py
tests/test_export.py
tests/test_priority.py
utils/functions.sh

resolve #6243 mark root as not writable with sys.prefix is not a conda environment

---

conda_env/cli/main_create.py

add delete_trash to conda_env create

---

conda_env/cli/main_create.py
conda_env/env.py
tests/conda_env/test_env.py

fix #5680 empty pip subsection error in environment.yml

---

conda/cli/conda_argparse.py
conda/cli/find_commands.py
conda/exceptions.py
tests/test_exceptions.py

fix #5827 
fix #5999
All the code here is basically just brought back in from older feature branches.  I was too aggressive in removing code while trying to optimize startup times.

fix #5827 no error message on invalid command

---

shell/Library/bin/conda.bat
shell/etc/profile.d/conda.sh

fix #6173 double prompt immediately after conda 4.4 upgrade

---

conda/core/solve.py
tests/core/test_solve.py
tests/test_create.py

resolve #6181 keep existing pythons pinned to minor version

---

conda/cli/main_search.py

fix #6201 incorrect subdir shown for conda search when package not found

---

conda/core/solve.py
tests/core/test_solve.py

resolve #5417 ensure unlink order is correctly sorted

---

conda/core/index.py

resolve #5370 index is only prefix and cache in --offline mode

---

conda/cli/conda_argparse.py
conda/exceptions.py
tests/test_exceptions.py

fix #6045 help message and zsh shift

---

conda/core/link.py
conda/gateways/disk/create.py

reduce redundant sys call during file copying

---

conda/exceptions.py

fix #6366 shell activation message

---

conda/base/context.py
conda/core/solve.py
tests/test_create.py

resolve #6194 warn when conda is outdated

---

conda/cli/main_info.py
tests/test_info.py

resolve #6431 always add env_vars to info_dict

---

conda/cli/main_remove.py

fix #6429 AttributeError on 'conda remove'

---

conda/cli/common.py
conda/cli/main_info.py
conda/core/envs_manager.py
conda/gateways/disk/test.py
conda_env/cli/main_list.py

fix #6449 problems with 'conda info --envs'

---

conda/models/match_spec.py

fix #6441 NotImplementedError on 'conda list'

---

appveyor.yml
conda/base/context.py
conda/cli/conda_argparse.py
conda/core/solve.py

fix #6283 no-deps for conda update case

---

conda.recipe/build.sh
conda.recipe/meta.yaml
conda/_vendor/auxlib/packaging.py
conda/common/io.py
conda/core/index.py
conda/core/link.py
conda/core/package_cache.py
conda/gateways/download.py
conda/plan.py
conda/resolve.py
utils/functions.sh

This PR has a companion PR pointed at 4.4.x

add timing instrumentation

---

conda/_vendor/auxlib/packaging.py
conda/activate.py
shell/etc/csh/login.d/conda.csh
shell/etc/profile.d/conda.csh
tests/test_activate.py
utils/functions.sh

csh wrapper

---

conda/egg_info.py

fix #6466 sp_dir doesn't exist

---

conda/core/solve.py

fix #6350 
---
As noted in in-code comments, https://github.com/ContinuumIO/anaconda-issues/issues/4298 is a related issue here.  Also https://github.com/conda/constructor/issues/138.

fix #6350 --update-all removes too many packages

---

conda/resolve.py

fix #6057 
This needs a test added, but it will be a lot easier to add in the 4.4.x branch as a targeted solver unit test.

fix #6057 unlink-link order for python noarch packages on windows

---

conda/base/context.py
conda/cli/common.py
conda/cli/main_info.py
conda/cli/main_search.py
conda/common/path.py
conda/core/link.py
conda/core/package_cache.py
conda/core/repodata.py
conda/core/solve.py
conda/gateways/connection/session.py
conda/gateways/disk/test.py
conda/instructions.py
conda/plan.py
conda/resolve.py
tests/test_create.py

This PR just removes some unused, dead code, and also adds a couple tests.

remove dead code

---

conda/core/solve.py

fix #6522 error message formatted incorrectly

---

conda/core/index.py
conda/plan.py
conda/resolve.py

fix #6516 hold channels over from get_index to install_actions

---

conda/common/compat.py
conda/core/package_cache.py

fix #6530 package cache JsonDecodeError / ValueError

---

conda/exceptions.py

User filed an issue directly with github in #6529 rather than (or in addition to) using auto-upload, but left out the command causing the problem, which is usually critical information.  This reformatting will probably help that.

adjust error report message

---

tests/test_activate.py

#6512
For the TODOs called out here, need some light-weight packages that have acitvate.d and deactivate.d scripts.

regression tests for #6512

---

conda/common/io.py

fix #6538 
Did a lot of googling about BrokenPipeError and how it can happen.  It's a major contributor to the volume of auto-uploaded error reports we have right now.
It seems like this is pretty normal in python actually, especially when the output of one program (i.e. conda) is piped via shell to the input of another, like `head`, for example.
https://stackoverflow.com/a/26738736
https://stackoverflow.com/a/15794022
I think it's safe to ignore these errors, and right now, we're only doing it in the `finally` / `close` sections of `ProgressBar` and `spinner`.

fix #6538 BrokenPipeError

---

conda/core/envs_manager.py
conda/gateways/disk/read.py

fix #6541 py2 and unicode in environments.txt

---

conda/egg_info.py

fix #6557 conda list FileNotFoundError

---

conda/core/solve.py

add additional information to the #6546 exception

---

conda/common/serialize.py
conda_env/env.py

fix #6529 yaml parse error

---

conda/history.py

fix #6546
This PR is pointed at 4.4.x, like #6565 should have been.

fix #6546 update after creating an empty env

---

conda/core/package_cache.py
conda/exceptions.py

fix #6562 repodata_record.json permissions error stack trace

---

conda/cli/install.py
conda/models/match_spec.py
tests/test_create.py

fix #6548 'conda update' installs packages not in prefix

---

conda/base/context.py
conda/cli/conda_argparse.py

fix #6520 --use-local flag

---

conda/base/context.py

fix #6584 os.getcwd() FileNotFound

---

README.rst
circle.yml
conda/cli/conda_argparse.py
conda/cli/install.py
conda/cli/main_info.py
conda/plan.py
conda/shell/conda.xsh
conda/shell/etc/profile.d/conda.csh
conda_env/README.rst
conda_env/cli/common.py
conda_env/cli/main.py
conda_env/cli/main_attach.py
tests/test_activate.py

Change instances of 'root' to 'base'

---

conda/activate.py
tests/test_activate.py

fix #6592 deactivate command order

---

conda/activate.py
conda/shell/Library/bin/conda.bat
tests/test_activate.py

fix #6579 python not recognized as command

---

conda/core/repodata.py

fix #6572 cached repodata PermissionsError

---

conda.recipe/bld.bat
utils/functions.sh

fix #6581 git-bash activation

---

conda.recipe/bld.bat
conda/shell/Library/bin/conda.bat
utils/functions.sh

fix #6599 space in path to base prefix

---

conda/activate.py
tests/cli/test_activate.py

supersedes #6613
@mingwandroid PR same as #6613, but with the string corrected as you intended it.

fix #6612 do not assume Anaconda Python on Windows nor Library\bin hack

---

conda.recipe/meta.yaml
conda/cli/conda_argparse.py
conda/cli/main_info.py
conda/exceptions.py
setup.cfg
tests/conda_env/installers/test_pip.py
tests/conda_env/specs/test_requirements.py
tests/test_activate.py
tests/test_exceptions.py
utils/functions.sh

There are three single-line patches (bug fixes) in this PR that could potentially be their own PRs.  They've been called out in comments added to this PR.

recipe test improvements and associated bug fixes

---

conda/activate.py

fix #6620 KeyError(u'CONDA_PREFIX',)

---

conda/cli/main_remove.py

fix #6661 remove env from environments.txt

---

conda/base/context.py

fix #6629 'conda update --name' AssertionError

---

conda/core/repodata.py

fix #6630 repodata AssertionError

---

conda.recipe/meta.yaml

fix #6626 add setuptools as constrained dependency

---

conda/exceptions.py

resolve #6650 add upgrade message for unicode errors in python 2

---

conda/cli/main_list.py
conda/core/linked_data.py

fix #6659 conda list explicit should be dependency sorted

---

conda/activate.py

fix #6627 AttributeError on 'conda activate'

---

conda/models/dist.py
conda/models/index_record.py

more channel work for #6665

---

appveyor.yml
conda/gateways/disk/update.py
utils/install.ps1

resolve #6711 fall back to copy/unlink for EINVAL, EXDEV rename failures

---

conda/cli/conda_argparse.py

fix #6684 --force message

---

conda/core/solve.py

fix #6693 KeyError with '--update-deps'

---

conda/exceptions.py

resolve #6700 add message for no space left on device

---

conda/cli/install.py
conda/plan.py
tests/test_create.py

fix #6718
resolve #6230 
fix #6290

fix #6718 broken 'conda install --rev'

---

conda/plan.py
tests/test_create.py

fix #6628 
This PR will be rebased once #6719 is merged.

 fix #6628 'conda install --rev' in conda 4.4

---

conda/cli/main_list.py
tests/test_create.py

add column headers to conda list results

---

conda/core/package_cache.py

fix #6707 FileNotFoundError when extracting tarball

---

conda_env/installers/pip.py

fix #6208 return for no pip in environment

---

conda/cli/main_info.py

fix #6457 env var cleanup

---

conda/cli/conda_argparse.py

fix #6645 escape paths for argparse help

---

conda/activate.py
tests/test_activate.py

fix #6739 handle unicode in environment variables for py2 activate

---

conda/cli/main_config.py
conda/common/serialize.py

fix #6618
This PR can be verified by checking
conda config --set path_conflict prevent
with and without the patch.

fix #6618 RepresenterError with 'conda config --set'

---

conda/exceptions.py

fix #6699 suppress memory error upload reports

---

conda/activate.py

fix #6770 CRLF for cmd.exe

---

conda/exceptions.py
conda/gateways/disk/create.py

fix #6514 add message for case-insensitive filesystem errors

---

conda/models/index_record.py

fix #6537 AttributeError value for url not set

---

conda/core/envs_manager.py

fix #6748 only warn if unable to register environment due to EACCES

---

conda_env/pip_util.py

fix #5792 conda env export error common in path

---

conda/core/linked_data.py
conda/exceptions.py

fix #6390 add CorruptedEnvironmentError

---

conda/base/context.py
conda/cli/conda_argparse.py
tests/test_create.py

fix #5884 allow --insecure CLI flag without contradicting meaning of ssl_verify

---

conda/common/compat.py

supersedes #6841 targeting 4.4.x

JSONDecodeError was added in Python 3.5

---

conda/common/path.py

fix #6401 non-ascii characters on windows using expanduser

---

conda_env/cli/main_update.py

supersedes #6834 targeting 4.4.x
---
avoids removing parts of conda_env before they are imported, since conda_env itself may be changed or deleted, e.g. by upgrading Python or conda itself.
closes #6824
I was able to test this with this Dockerfile:
```dockerfile
FROM continuumio/miniconda3:4.3.27
RUN conda install -y conda=4.4.8
RUN conda info
RUN conda list
COPY test.yml test.yml
ADD conda_env /conda/conda_env
RUN cp /conda/conda_env/cli/main_update.py /opt/conda/lib/python3.6/site-packages/conda_env/cli/main_update.py
RUN conda env update -n root -f test.yml
```
and this test.yml
```yaml
dependencies:
- python=3.5
- pip=9
- pip:
- wheel
```

fix #6824 import installers before invoking any

---

conda/resolve.py
tests/test_resolve.py

Attempts to fix #6833. Will copy the relevant text from there

fix #6833 improve feature mismatch metric

---

conda/core/path_actions.py

fix #6852 ensure temporary path is writable

---

conda/common/path.py

To keep consistency with https://github.com/ContinuumIO/menuinst/pull/61

fix potential error in ensure_pad(); add more tests

---

conda/shell/etc/profile.d/conda.sh
tests/test_activate.py

fix #6840 handle error return values in conda.sh

---

conda_env/cli/main.py

fix #6672 don't update conda during conda-env operations

---

conda/__init__.py
conda/_vendor/auxlib/entity.py
conda/activate.py
conda/api.py
conda/cli/install.py
conda/cli/main_clean.py
conda/cli/main_list.py
conda/common/compat.py
conda/common/configuration.py
conda/common/constants.py
conda/common/url.py
conda/compat.py
conda/core/link.py
conda/core/linked_data.py
conda/core/path_actions.py
conda/core/solve.py
conda/exceptions.py
conda/exports.py
conda/gateways/connection/__init__.py
conda/gateways/disk/create.py
conda/gateways/disk/delete.py
conda/gateways/disk/link.py
conda/gateways/disk/read.py
conda/install.py
conda/models/index_record.py
conda/models/match_spec.py
conda/plan.py
conda/resolve.py
conda_env/__init__.py

https://lgtm.com/projects/g/conda/conda/alerts/?mode=tree&severity=error
I don't think this covers everything, but it's a huge swath.  Eventually we can probably turn this on for all PRs as part of the pass/fail CI.

fix several lgtm.com flags

---

conda/cli/conda_argparse.py
conda/cli/main_search.py
conda/core/envs_manager.py
conda/core/linked_data.py
conda/core/package_cache.py
conda/core/repodata.py
tests/test_cli.py
tests/test_create.py

resolve #6791 
TODO after merging this PR: Rename `PackageCache` to `PackageCacheData`

resolve #6791 conda search --envs

---

conda/gateways/disk/update.py

Drop custom copy + remove fallback for rename failures
`os.rename()` returns `EXDEV` for directories and `EINVAL` for files in a docker
container with `overlayfs` or `aufs` storage backend.
xref: https://github.com/moby/moby/issues/25409#issuecomment-238537855
The fallback for this was to use copy + remove, but it assumed that the rename
failed for a file. So, whenever a copy attempt was made on a directory, it
cascaded into an uncaught `EISDIR`.
This patch delegates the copy+remove logic to `shutil.move()` which works for
directories and files and saves us from reinventing the wheel.

Don't attempt copy/remove fallback for rename failures

---

conda/shell/etc/fish/conf.d/conda.fish

Uses conda env to get a list on available environments.

Fix #6816 fish environment autocomplete

---

conda/base/context.py

fix #6882 document max_shlvl

---

conda/core/envs_manager.py

resolve #6900 don't record conda skeleton environments in environments.txt

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
conda/base/constants.py
conda/core/subdir_data.py
conda/models/channel.py
tests/build-index2-json.py
tests/build-index4-json.py
tests/cli/test_config.py
tests/core/test_index.py
tests/core/test_repodata.py
tests/models/test_channel.py
tests/models/test_dist.py
tests/models/test_index_record.py
tests/models/test_match_spec.py
tests/test_cli.py
tests/test_create.py
tests/test_fetch.py
tests/test_misc.py
utils/appveyor-install.bat
utils/functions.sh
utils/install.ps1
utils/tester.bat
utils/travis-bootstrap-conda.sh
utils/travis-install.sh

resolve #6886
DO NOT MERGE yet.

resolve #6886 transition defaults from repo.continuum.io to repo.anaconda.com

---

conda/core/index.py
tests/test_create.py

fix #6914, #6691 conda can fail to update packages even though newer versions exist

---

conda/__init__.py
conda/activate.py
conda/cli/common.py
conda/cli/main.py
conda/common/compat.py
conda/common/serialize.py
conda/core/repodata.py

See: https://github.com/conda/conda/issues/6739#issuecomment-362941051

fix #6899 handle Unicode output in activate commands

---

conda/activate.py
conda/models/match_spec.py
tests/models/test_match_spec.py

Fixes included in #6799, which is being closed.

channel matchspec fixes

---

conda/base/context.py
conda/core/subdir_data.py
conda/exceptions.py
conda/plan.py
tests/test_create.py
tests/test_exceptions.py

resolve #6894 add http errors to auto-uploaded error reports

---

conda/core/solve.py

resolve #6695 outdated conda warning respects --quiet flag

---

conda/core/solve.py
conda/models/channel.py
conda/models/match_spec.py
conda/models/records.py
conda/models/version.py
tests/models/test_channel.py
tests/models/test_match_spec.py

reference: https://github.com/conda/conda-build/pull/2694

MatchSpec merge

---

.gitignore
.pytest_cache/v/cache/lastfailed
conda/activate.py
conda/shell/etc/profile.d/conda.csh
tests/test_activate.py

Splitting #7026 
This specifically addresses #6919

Fix csh prompt

---

circle.yml

circleci: skip conda-build test r-cran-nmf

---

conda/shell/etc/profile.d/conda.csh

Splitting #7026
This specifically addresses #6877
#7041 is a prerequisite

Handle non-zero return in CSH

---

conda/activate.py
tests/test_activate.py

resolve #6595 use OO inheritence in activate.py

---

conda/exceptions.py

fix #7075 add anaconda.org search message to PackagesNotFoundError

---

conda/core/path_actions.py

fix #7107 verify hangs when a package is corrupted

---

conda/common/io.py

progress bar uses stderr instead of stdout

---

conda/core/solve.py
tests/test_create.py
tests/test_instructions.py
tests/test_plan.py

fix #2154 
Bug fix about the Issue 2154. With this implementation Conda raises
an exception when the user tries to remove a non-existent package.

fix #2154 conda remove should complain if requested removals don't exist

---

conda/misc.py
tests/test_create.py

fix #7094 exit early for --dry-run with explicit and clone

---

conda/base/constants.py
conda/base/context.py
tests/models/test_channel.py

resolve #7061 remove pkgs/pro from defaults

---

conda/_vendor/auxlib/type_coercion.py
conda/activate.py
conda/base/context.py
tests/test_activate.py

This is a WIP PR that I started a long time ago.  It's still not complete yet because, as I remember, I was having problems with escapes and ANSI color codes working properly.
Note that this commit is old (from Aug 17), and I just rebased against master. There's probably some stuff that has changed since then.
resolves https://github.com/conda/conda/issues/2747
resolves https://github.com/conda/conda/issues/4742

customizable prompt

---

circle.yml
conda/base/context.py
conda/common/io.py
conda/core/package_cache_data.py
conda/exceptions.py
conda/gateways/disk/__init__.py
conda/gateways/disk/create.py
conda/gateways/disk/update.py
tests/base/test_context.py

fix #7109 
also closes #6569 and #6576
This PR builds on #6570.  The first 3 commits are from that PR.

fix #7109 incorrect chown with sudo

---

circle.yml
conda/core/package_cache_data.py

resolve #7189 progress bar improvement

---

conda/cli/conda_argparse.py

fix #7210 add suppressed --mkdir back to 'conda create'

---

conda/exceptions.py

@msarahan This should fix what we discussed this morning.

raise log level for errors to error

---

circle.yml
conda/cli/main_list.py
conda/core/prefix_data.py
conda/models/enums.py
tests/test_create.py

resolve #7087 
This PR remains unmerged because it's difficult to test until we have #7086 complete.

resolve #7087 add non-conda-installed python packages into PrefixData
