conda/conda

conda/core/path_actions.py
=> fix #7253 always respect copy LinkType

conda/core/solve.py
=> fix #7165 conda version check should be restricted to channel conda is from

conda/core/solve.py
further work toward #7165, in addition to #7289
=> conda update notification tweaking

conda/core/initialize.py
=> add design comments to conda.core.initialize

conda/cli/conda_argparse.py, conda/cli/main_info.py
=> fix #7362 remove --license from conda info and related code paths

circle.yml, conda/cli/conda_argparse.py, conda/cli/main_config.py
=> resolve #7375 enable conda config --set update_modifier

conda/base/context.py, conda/cli/common.py, conda/cli/main_info.py, conda/common/os/__init__.py, conda/common/os/linux.py, conda/common/os/unix.py, conda/common/os/windows.py, tests/cli/test_common.py, tests/common/os/test_windows.py
=> Rename common.platform to common.os and split among windows, linux and unix utils

conda/history.py, tests/test_history.py
=> fix #6691 fix history file parsing containing comma-joined version specs

circle.yml, conda/__init__.py, conda/exceptions.py, conda/gateways/connection/__init__.py, tests/test_create.py, utils/functions.sh
resolves #7372 
Includes a commit that monkey patches requests.  See requests/requests#4723 and c88987f.
=> resolve #7372 disable http error uploads and CI cleanup

conda/history.py, tests/test_history.py
=> fix #7494 History spec parsing edge cases

conda/core/link.py, conda/core/path_actions.py
=> resolve #7505 temp directory for UnlinkLinkTransaction should be in target prefix

conda/gateways/connection/__init__.py
=> fix #7506 requests monkeypatch fallback for old requests versions

conda/gateways/connection/__init__.py
=> fix #7524 should_bypass_proxies for requests 2.13.0 and earlier

conda/gateways/connection/adapters/localfs.py
=> fix #7559 symlink stat in localfs adapter

conda/activate.py
=> fix #7486 activate with no PATH set

conda/cli/conda_argparse.py, conda/cli/main_info.py, tests/helpers.py, tests/test_cli.py, tests/test_info.py
=> resolve #7309 deprecate 'conda info package_name'

conda/core/solve.py, tests/core/test_solve.py
resolve #7522 
As promised in https://github.com/conda-forge/conda-feedstock/pull/56#issuecomment-403921347.
CC @isuruf @jakirkham
=> resolve #7522 prevent conda from scheduling downgrades

circle.yml, conda/base/context.py, conda/resolve.py, utils/functions.sh
targeting 4.5.x
supersedes #7543
=> allow skipping feature maximization in resolver

conda/_vendor/frozendict.py, conda/base/constants.py, conda/base/context.py, conda/cli/common.py, conda/cli/main_list.py, conda/cli/main_package.py, conda/common/configuration.py, conda/core/link.py, conda/core/package_cache_data.py, conda/core/path_actions.py, conda/core/prefix_data.py, conda/core/subdir_data.py, conda/exceptions.py, conda/gateways/disk/read.py, conda/models/channel.py, conda/models/dist.py, conda/models/match_spec.py, conda/models/package_info.py, conda/models/records.py, conda/models/version.py, conda/resolve.py, dev/start, tests/core/test_solve.py, tests/helpers.py, tests/models/test_index_record.py, tests/models/test_match_spec.py, tests/models/test_package_info.py, tests/test_api.py, tests/test_create.py, tests/test_priority.py
resolve #7591
Code improvements from #7446 and #7531.
=> resolve #7591 updates and improvements from namespace PR for 4.6

appveyor.yml, conda/cli/common.py, conda/core/subdir_data.py, conda/models/match_spec.py
=> resolve #7592 compatibility shims

conda/base/context.py, conda/common/configuration.py, tests/cli/test_config.py, tests/test_create.py, tests/test_resolve.py
=> resolve #7242 configuration load error message

appveyor.yml, conda/_vendor/cpuinfo.py, conda/base/context.py
=> user-agent context refactor

conda/cli/main_config.py, conda/common/compat.py
=> test against Sequence not list (#7673 retargeted at 4.5.x)

.cla-signers, conda/base/context.py, conda/cli/conda_argparse.py, conda/cli/main_clean.py, conda/common/disk.py, conda/resolve.py, tests/test_create.py, utils/cla.py
=> Remove clean source cache option from conda

conda/base/context.py
=> resolve #7724 move windows package cache and envs dirs back to '~/.conda' directory

conda/activate.py, tests/test_activate.py
=> fix #7706 add condacmd dir to cmd.exe path on first activation

conda.recipe/meta.yaml, conda/base/context.py, conda/core/index.py, conda/exceptions.py, conda/history.py, conda/models/match_spec.py, conda/models/version.py, conda/resolve.py, tests/models/test_match_spec.py, tests/models/test_version.py
=> spec handling errors in 4.6.0b0

conda/resolve.py
I have found these helpful for examining why a conda solve is hanging or otherwise failing.  I hope this is non-controversial.
=> add debug messages to communicate solver stages

conda/shell/condabin/Conda.psm1
This PR is a quick fix for #7828, as per @kalefranz' suggestion.
=> Fix #7828: Correctly handle commands with no further arguments.

appveyor.yml, conda_env/specs/__init__.py, conda_env/specs/binstar.py, tests/conda_env/test_cli.py
=> PR: Fix conda env create handling for remote specs

conda/core/initialize.py
=> Allow not more than one " to preceed conda[-_]

circle.yml, conda/core/initialize.py, tests/common/pkg_formats/test_python.py, tests/core/test_initialize.py, tests/test_create.py, tests/test_resolve.py
Fixes https://github.com/conda/conda/issues/7952
=> Fix long path init/re-init

docs/source/user-guide/configuration/use-condarc.rst
See conda/conda-build#3265 and conda/conda-build#3266.
=> Add documentation on new conda-build condarc settings

conda/models/channel.py
Fixes https://github.com/conda/conda/issues/8006
=> make_simple_channel: ensure channel name isn't NoneType

conda/core/link.py, conda/core/path_actions.py, conda/gateways/disk/create.py, conda/gateways/subprocess.py, tests/core/test_path_actions.py
Create pyc files in a single pass rather than using multiple calls to py_compile.  
closes #7621
=> Single pass pyc creation

conda/core/link.py, conda/core/path_actions.py, conda/gateways/disk/create.py, conda/gateways/subprocess.py, tests/core/test_path_actions.py
=> add compile_multiple_pyc function

conda/cli/main_run.py, conda/core/initialize.py, tests/core/test_initialize.py, tests/test_activate.py
Fixes https://github.com/conda/conda/issues/8004
=> Always quote arguments passed to conda for initialization

conda/gateways/disk/delete.py
Thanks @pv for the recommendation here
fixes #7665
=> fix faulty onerror call for rm

.gitignore, docs/source/index.rst
Consolidated command references into one subsection - deleting redundant information
=> Consolidated command references into one subsection

docs/source/user-guide/install/rpm-debian.rst
Added Sophia P's blog post over RPM and Debian to the installation section of conda
=> rpm and debian guide

docs/source/release-notes.rst
release notes include 4.5.12, 4.6.0, 4.6.1
=> release notes 4.6.1

conda/base/context.py, conda/history.py, tests/test_history.py
=> Conda downgrades master

CHANGELOG.md
=> update CHANGELOG 4.5.13

conda/history.py, conda_env/cli/main_export.py, conda_env/cli/main_update.py, conda_env/env.py, tests/conda_env/support/pip_argh.yml, tests/conda_env/test_create.py, tests/conda_env/test_env.py, tests/conda_env/utils.py
=> fix conda env export missing pip deps when pip interop not enabled

conda/common/pkg_formats/python.py, conda/core/prefix_data.py, tests/common/pkg_formats/test_python.py
=> fix #8178 conda pip interop assertion error

Makefile, conda/cli/common.py, conda/cli/main_config.py, conda/cli/main_info.py, conda/core/path_actions.py, conda/exceptions.py, conda/gateways/logging.py, tests/test_create.py
=> fix #8157 token leakage in errors and config output

conda/models/version.py
=> fix error with .* that should have been specific to ~=

conda/shell/condabin/Conda.psm1, tests/test_activate.py
=> Add -Stack switch Enter-CondaEnvironment PowerShell function

conda/cli/main_search.py
Fixes https://github.com/conda/conda/issues/8238
=> Print info for searching envs

conda/_vendor/auxlib/type_coercion.py, conda/base/constants.py, conda/base/context.py, conda/cli/main_config.py, conda/common/logic.py
=> resolve #8176 SAT solver choice error handling

.gitignore, .vscode/settings.json
Removed .vscode settings and added .vscode to git ignore
=> [skip ci] Clean up vscode settings

conda/core/path_actions.py, tests/test_create.py
=> fix overzealous removal of folders after cleanup of failed post-link

conda/core/link.py, conda/utils.py, conda_env/installers/pip.py
addresses https://github.com/conda/conda/issues/8187
=> Prepend pip commands with activating env

conda/cli/main_config.py
=> Allow 'int' datatype for values to non-sequence parameters

conda/exports.py, conda/gateways/disk/delete.py, conda/shell/condabin/rename_tmp.bat
fixes #8255 
I have tested this on Windows but not on unix yet.
=> squelch subprocess output when removing files with subprocess

docs/source/user-guide/tasks/manage-environments.rst
=> [skip ci] flesh out docs on activation

conda/cli/install.py
=> Used try catch block to detect when parser fails to parse arguments

docs/Makefile, docs/source/glossary.rst, docs/source/user-guide/concepts.rst, docs/source/user-guide/configuration/admin-multi-user-install.rst, docs/source/user-guide/configuration/disable-ssl-verification.rst, docs/source/user-guide/configuration/use-condarc.rst, docs/source/user-guide/getting-started.rst, docs/source/user-guide/install/download.rst, docs/source/user-guide/install/windows.rst, docs/source/user-guide/overview.rst, docs/source/user-guide/tasks/create-custom-channels.rst, docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/tasks/manage-pkgs.rst, docs/source/user-guide/tasks/manage-python.rst, docs/source/user-guide/tasks/use-conda-with-travis-ci.rst, docs/source/user-guide/tasks/view-command-line-help.rst, docs/source/user-guide/troubleshooting.rst
Replaced all "NOTE:" and "WARNING:" entries with directive admonitions to improve visibility of these markers.
=> [skip ci] Added in admonitions

docs/source/user-guide/troubleshooting.rst
CC @mingwandroid @rrigdon - this needs more work and testing based on the final python builds we come up with in the next day or two.
=> [skip ci] [wip] document mkl dll hell and new env vars

docs/source/_static/css/custom.css, docs/source/conf.py
This commit updates the conda site to match the colors and themes of Distro and conda-build.
=> Changed color scheme and thematic elements

conda/base/constants.py
=> Add C:/ProgramData/conda as a search path on Windows

conda/core/initialize.py, tests/test_activate.py
Config fish as per http://mvolkmann.github.io/fish-article/#ConfigurationViaFishConfig
=> Add activation for fish shell

conda/utils.py
=> Fix for chcp output ending with .

CHANGELOG.md, tests/test_activate.py
Not got a lot of insight into why this would happen, sorry.
=> Fix for https://github.com/conda/conda/issues/8485

conda/activate.py, tests/core/test_initialize.py, tests/test_activate.py
@katietz, @jjhelmus, @msarahan 
Nothing beyond removal of special casing that's not needed and broken.
=> Master msys2 old activation

tests/test_activate.py
Note: Although it *could* be argued that the thing I'm testing here is something we don't really support, we will run into the same problem on Windows with conflicts between Python 2.7 and Python 3 and the OpenSSL module.
The fix is to add PATH to the invocation of CONDA_EXE as well as those of activate and deactivate for PowerShell, the same as we do for cmd.exe
=> Add xfail Win/PowerShell use-conda-outside-of-activation test

conda/core/initialize.py
=> Fix conda init profile modification for powershell

appveyor.yml, conda/activate.py, conda/base/context.py, conda/cli/main_init.py, conda/core/initialize.py, conda/shell/condabin/Conda.psm1, conda/shell/condabin/_conda_activate.bat, conda/shell/condabin/conda.bat, conda/shell/etc/profile.d/conda.sh, conda_env/cli/main_update.py, tests/__init__.py, tests/core/test_initialize.py, tests/test_activate.py
fixes #8496
fixes #8486
fixes #8485
fixes #8532
=> Master 4.6.12 stuff

conda/activate.py, conda/shell/condabin/Conda.psm1
=> Dont modify Function:prompt when "changeps1" is false in PowerShell

conda.recipe/bld.bat, conda.recipe/build.sh, conda.recipe/meta.yaml, conda/shell/condabin/_conda_activate.bat, conda/shell/condabin/conda.bat, docs/source/user-guide/troubleshooting.rst
Otherwise people are forced to use call to prevent spurious
errorlevels from being propagated and causing failures.
=> Try exiting with 0 on success from conda.bat

conda/shell/condabin/Conda.psm1
=> fix missing current working path in powershell prompt

conda/core/initialize.py
addresses: https://github.com/conda/conda/issues/8584
=> Make initalization block for tcsh and csh have correct syntax

conda/utils.py
=> wrap_subprocess_call: fallback to sh if no bash

dev/start
Resolves https://github.com/conda/conda/issues/8607
=> Make sure to install deps on osx when using ./dev/start

conda/core/repodata.py, conda/exceptions.py, conda/gateways/download.py
=> fix #3962 add ProxyError message for bad configurations

conda/core/subdir_data.py, conda/exceptions.py, conda/gateways/connection/__init__.py, conda/gateways/connection/download.py
=> port #6205 to master

conda/gateways/disk/__init__.py
=> Fix typo in #8666

conda/base/context.py, conda/cli/install.py, conda/core/subdir_data.py, tests/core/test_subdir_data.py
=> Fall back to old file format

conda/shell/etc/fish/conf.d/conda.fish
=> fix conda.fish

CHANGELOG.md, conda/base/context.py, conda/cli/install.py, conda/core/package_cache_data.py, conda/core/solve.py, conda/gateways/disk/delete.py, tests/test_create.py
https://github.com/conda/conda/pull/8741#issuecomment-500265355
https://github.com/conda/conda-package-handling/pull/25
=> Handle CPH exceptions; fix update/remove behavior of --only-deps specs

conda/core/solve.py, conda/resolve.py, tests/test_create.py
it didn't work as well.
Fixes #8772
=> revert get_reduced_index based unsat determination

conda/shell/condabin/Conda.psm1
=> Fix renaming of existing prompt function

conda/resolve.py
=> handle strict channel priority for unsatisfiable deps better

conda/core/path_actions.py
Handles corrupt packages better, and helps people understand that this is a problem with the upstream source of the package, not their local conda.
Thanks @TomAugspurger for raising this.
=> handle JSONDecodeError better when package is corrupted at extract time

conda/core/package_cache_data.py
Fixes https://github.com/conda/conda/issues/8869
=> Re-extract package if url is None

conda/core/solve.py, tests/test_create.py
=> handle edge case in pinned specs better.  Add test

conda/core/solve.py, tests/core/test_solve.py
=> Allow conda to be downgrade when given an explicit spec

conda/common/io.py, conda/core/solve.py
=> improve fail message for repodatas other than repodata.json

conda/resolve.py
=> fix missing package_type attr in finding virtual packages

conda/core/solve.py, conda/resolve.py, tests/core/test_solve.py
This will give a message to the user when their update is constrained by something. For example:
ipython is installed by anaconda
```
$ conda update ipython ncurses --quiet                                                                           
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... 
Updating ipython is constricted by 
anaconda -> requires ipython==7.2.0=py37h39e3cac_0
If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`
done
```
=> Hint no update

conda/core/link.py
=> make entry points before running post-link scripts

conda/models/prefix_graph.py, tests/core/test_solve.py, tests/test_resolve.py
Resolves https://github.com/conda/conda/issues/8934
The other part of fixing that problem should be to not check for issues when current_repodata.json is unsatisfiable. Will open another PR for that
=> Do depth first search

conda/core/solve.py
Instead, fallback to using repodata.json
=> If solving with current_repodata.json don't find conflicts

conda/cli/install.py, conda/cli/main_search.py, conda/models/prefix_graph.py, conda/models/version.py, conda/resolve.py, tests/models/test_match_spec.py, tests/test_resolve.py
This was found by:
conda create -n py27env python=2.7
conda install -n py27env rasterio -c conda-forge
=> fix None in comprehension that needs to be iterable

conda/models/match_spec.py, conda/models/prefix_graph.py
```
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
return func(*args, **kwargs)
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
exit_code = do_call(args, p)
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
exit_code = getattr(module, func_name)(args, parser)
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
install(args, parser, 'install')
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\cli\install.py", line 256, in install
force_reinstall=context.force_reinstall or context.force,
File "C:\Users\sophi\Miniconda3\lib\site-packages\conda\core\solve.py", line 112, …
```
=> fix empty merge from specs that are not allowed names

docs/source/release-notes.rst
Needs review but especially look over line 21's formatting.
=> Release notes 4.7.8

conda/cli/install.py
=> fix repodata_fns from condarc not being respected

conda/core/prefix_data.py, conda/core/solve.py, tests/core/test_solve.py
Addresses https://github.com/conda/conda/issues/8831
=> Don't add back orphan_precs that already exist

conda/cli/install.py, conda/core/solve.py, setup.cfg
=> Fix satisfied skip

conda/gateways/connection/adapters/s3.py
Fixes https://github.com/conda/conda/issues/8993
=> Fix boto3 initialization race condition

conda/base/context.py, conda/common/pkg_formats/python.py
Appveyor was showing issues where the cph import was causing problems.  Delaying the import should help here.
=> move cph import into function to avoid PATH issues on win

docs/source/user-guide/concepts/environments.rst, docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/configuration/free-channel.rst
=> Added blog links and info

docs/source/user-guide/concepts/channels.rst, docs/source/user-guide/concepts/environments.rst, docs/source/user-guide/configuration/disable-ssl-verification.rst, docs/source/user-guide/configuration/index.rst, docs/source/user-guide/configuration/non-standard-certs.rst
I added a section on using SSL with using non-standard certificates (related to https://github.com/ContinuumIO/anaconda-issues/issues/10340). The other page changes are minor edits.
=> Added SSL info, cleaned up some pages

conda/exceptions.py
Fixes https://github.com/ContinuumIO/anaconda-issues/issues/11202
=> fix ProxyError expected arguments

conda/cli/main_remove.py, conda/core/link.py, conda/core/path_actions.py, conda/core/solve.py, conda/history.py, conda/misc.py, conda/plan.py, tests/core/test_solve.py, tests/test_create.py
fixes https://github.com/conda/conda/issues/9124
CC @jjhelmus
=> fix neutered specs not being recorded in history, leading to sadness

docs/source/commands.rst
and not 'source deactivate' as shown in the doc right now
=> should be conda deactivate

conda/exceptions.py, tests/core/test_solve.py
in order to ease users ability to quickly scan and understand the
error message
=> Put users python version in more easily scannable location

docs/source/glossary.rst, docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/concepts/pkg-specs.rst
I used this blog for info: https://www.anaconda.com/whats-in-a-name-clarifying-the-anaconda-metapackage/
=> Added info about metapackages

docs/source/user-guide/tasks/manage-environments.rst
Pulled info from this blog post: https://www.anaconda.com/using-pip-in-a-conda-environment/
=> Added info on using pip in a conda env

conda_env/README.rst
addresses https://github.com/conda/conda/issues/9161
=> Fix example environment.yaml

conda/core/envs_manager.py
fixes https://github.com/ContinuumIO/anaconda-issues/issues/11148
=> makedirs to initialize .conda folder when registering env

circle.yml, conda/base/context.py, conda/exceptions.py, conda/resolve.py, tests/test_resolve.py
Allows users to set if they want an unsat hint or not
=> Switch for conflict finding

docs/source/user-guide/configuration/use-condarc.rst
Related to this ticket: https://github.com/conda/conda-docs/pull/492
=> Added and clarified pkg_dirs info

docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
From conda-docs PR: https://github.com/conda/conda-docs/pull/590
Corrected the sample Travis CI command.
=> Update sample Travis CI command

docs/source/user-guide/tasks/manage-environments.rst
From this issue in conda-docs: https://github.com/conda/conda-docs/pull/613
=> Update documentation how to get a list of environments 

docs/source/user-guide/tasks/manage-python.rst
Per this PR in conda-docs: https://github.com/conda/conda-docs/pull/615/files
=> Updated supported versions of Python

docs/source/glossary.rst, docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/tasks/manage-pkgs.rst
Added info about mutex metapackages and more context about metapackages in general.
=> Mutex metapkgs

docs/source/user-guide/configuration/use-condarc.rst
Added info about how to use the command line for configuring in the use-condarc page.
=> Directed users to command configs

circle.yml, conda/activate.py, conda/base/constants.py, conda/core/envs_manager.py, conda/core/prefix_data.py, conda_env/cli/main.py, conda_env/cli/main_config.py, conda_env/cli/main_vars.py, tests/conda_env/test_cli.py, tests/core/test_envs_manager.py, tests/core/test_prefix_data.py, tests/test_activate.py
builds on https://github.com/conda/conda/pull/9157
=> Reset env vars

circle.yml, conda/activate.py, conda/base/constants.py, conda/core/envs_manager.py, conda/core/prefix_data.py, conda_env/cli/main.py, conda_env/cli/main_config.py, conda_env/cli/main_vars.py, tests/conda_env/test_cli.py, tests/core/test_envs_manager.py, tests/core/test_prefix_data.py, tests/test_activate.py
resolves: https://github.com/conda/conda/issues/4806 and https://github.com/conda/conda/issues/6649
=> Env vars for environments

docs/source/user-guide/troubleshooting.rst
To address this issue: https://github.com/ContinuumIO/anaconda-issues/issues/11271
=> Clarified - CONDA_DLL_SEARCH_MODIFICATION_ENABLE

conda/activate.py, conda/shell/conda.xsh, tests/test_activate.py
This fixes the issues brought up in https://github.com/xonsh/xonsh/issues/3269
=> fixes xonsh activation and tab completion bugs

conda/shell/etc/profile.d/conda.sh
Resolves: https://github.com/conda/conda/issues/9280
=> Do not add sys_prefix_path for failed activation/deactivation

docs/source/user-guide/concepts/channels.rst, docs/source/user-guide/tasks/manage-channels.rst
Related to: https://github.com/conda/conda/issues/9176
=> Added more info about channels

conda/core/index.py, docs/source/user-guide/tasks/manage-virtual.rst, tests/core/test_index.py
Similar to #9349, implements #9348, and addresses some of the issues in https://github.com/conda-forge/staged-recipes/pull/9902.
CC @mingwandroid @jakirkham @msarahan @jjhelmus @isuruf
=> virtual glibc package

docs/source/user-guide/configuration/use-condarc.rst
Incorporating info from https://github.com/conda/conda/issues/9333
=> Added info on searching for .condarc

conda/common/compat.py, conda/core/index.py, docs/source/user-guide/tasks/manage-virtual.rst, tests/core/test_index.py
This PR adds a virtual package for the OSX version.
=> ENH add osx version virtual package

docs/source/user-guide/tasks/manage-environments.rst
A (very) small edit.
Feedback welcome!
=> minor typo in manage-environments.rst

conda/core/subdir_data.py, tests/core/test_subdir_data.py
=> Fix what channels are queried when context.offline is True

docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
This PR incorporates content from https://github.com/conda/conda/issues/9337#issuecomment-542604108
=> Added bootstrap config

conda/cli/main_run.py, conda/core/index.py
Fixes #8386. Manally confirmed works on OSX.
=> Performance improvements for conda run - avoiding Popen.communicate().

conda/shell/condabin/_conda_activate.bat
Fix for https://github.com/conda/conda/issues/8888
=> set tmp to shortened path to exclude spaces

conda/shell/etc/fish/conf.d/conda.fish
=> avoid function redefinition upon resourcing conda.fish

docs/source/user-guide/concepts/installing-with-conda.rst, docs/source/user-guide/install/macos.rst, docs/source/user-guide/tasks/manage-conda.rst, docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/tasks/manage-pkgs.rst
How to suppress the warning message about updating conda
Add default packages to each new environment automatically 
Restoring environment to a previous revision
conda update vs conda install
Installing conda packages offline
List packages that depend on specific packages
=> Transferred Knowledge Base content

conda/common/configuration.py, tests/common/test_configuration.py
Adds support for Object configuration parameters, with named instance fields of configurable Parameter types.
=> Support Object configuration parameters

conda/gateways/disk/delete.py
On my miniconda installation searching through pkgs takes a couple of seconds.
=> Don't check in pkgs for trash

docs/source/user-guide/tasks/manage-channels.rst
Related - https://github.com/conda/conda/issues/9183
=> Clarified channel priority

docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/troubleshooting.rst
Added info from this troubleshooting section: https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed 
with more context to this section: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment
=> DLL loading verification in Activate an Env

conda_env/specs/binstar.py
Requested in https://github.com/conda/conda/issues/9516
=> add -n base to the install anaconda-client suggestion

conda/utils.py, tests/conda_env/test_cli.py
Sorry for bumping in, but this is kind of an important issue for us and it would be great to have it fixed as soon as possible.
=> Fix for #9220 - exist with pip errorlevel if failed

conda/cli/common.py, conda/cli/main_run.py, tests/test_create.py
addresses https://github.com/conda/conda/issues/9454
=> Check if valid conda environment for conda run

conda/shell/etc/profile.d/conda.csh
ref:
https://github.com/conda/conda/issues/9490
https://github.com/conda/conda/issues/9304
=> Use setenv to set PATH for csh

conda/cli/main_remove.py, tests/test_create.py
Fixes https://github.com/conda/conda/issues/8744
=> Delete empty env

docs/source/user-guide/concepts/conda-commands.rst, docs/source/user-guide/concepts/index.rst, docs/source/user-guide/concepts/installing-with-conda.rst, docs/source/user-guide/index.rst, docs/source/user-guide/install/index.rst
Made user guide more directive and with more info to help readers navigate it.
=> Updated user guide, deleted Overview, minor clean up

.github/ISSUE_TEMPLATE/Feature_request.md
=> update feature issue template

.github/ISSUE_TEMPLATE/Bug_report.md
=> update bug report template

.github/ISSUE_TEMPLATE/Feature_request.md
Fixing code of conduct link added in wrong place
=> update feature template

tests/__init__.py
=> Fix simple typo: submissve -> submissive

dev/start, dev/test-requirements.txt
I missed this one @kalefranz, apologies!
=> Another switch to our own packages, test-requirements.txt

.cla-signers, docs/source/user-guide/concepts/conda-performance.rst
Changed en-dashes to `--` for options.
=> Minor documentation fix

conda/_vendor/cpuinfo.py
This is in continuation to add support for s390x done in https://github.com/conda/conda/pull/9933
=> Enable s390x support in cpuinfo

conda/_vendor/auxlib/compat.py, conda/common/path.py, conda/core/subdir_data.py, conda/gateways/disk/create.py, conda/gateways/disk/link.py, test_data/env_metadata/__init__.py
Removed some deprecation warnings and a py38 incompatible collections import
=> Fix some deprecation warnings for imports and regex: #10083

conda/cli/python_api.py
just two trivial things I noted on the website
=> Fix typos in docstring

CHANGELOG.md
Changelog/release notes for the 4.8.4 release
=> 4.8.4 changelog

conda/cli/conda_argparse.py, conda/cli/main_run.py, conda/gateways/subprocess.py, tests/test_cli.py
This allows the use of interactive commands like ipython.
=> Add option to conda run to not capture the output

conda/core/initialize.py, tests/core/test_initialize.py
Proposed fix for https://github.com/conda/conda/issues/10309
Ping @chenghlee, @kalefranz
=> Add if exist to the AutoRun hook

conda/cli/common.py
.. we expand this to >=X.Y.Z,==X.Y.* as per the PEP
=> Respect PEP440 ~= 'Compatible release clause'

conda/cli/common.py
=> Fix previous PR, strip a space

docs/source/release-notes.rst
https://docs.conda.io/projects/conda/en/latest/release-notes.html did not reflect the latest releases - updated the docs from https://github.com/conda/conda/edit/master/CHANGELOG.md
=> Update conda release notes in docs

conda/models/channel.py, tests/conda_env/support/example/environment_host_port.yml, tests/conda_env/test_create.py, tests/models/test_channel.py
Allows for host:port specification in an environment file.
=> allow for host:port in env file

docs/source/user-guide/tasks/manage-virtual.rst
This PR adds the virtual packages introduced in #10214 to the docs.
Let me know if you'd like a different phrasing for the explanation.
=> Add __unix and __win virtual packages to docs

conda/base/context.py
=> Support python 3.10 version number

conda/core/index.py, docs/source/user-guide/tasks/manage-virtual.rst
Closes #10551
Following what was done in #10214, this PR adds a Linux virtual package.
=>  Add virtual package for __linux

conda_env/specs/binstar.py
This is to check if #10659 can be made using importlib.
=> Don't load binstar_client until needed. Part 2.

docs/source/release-notes.rst
This covers a few versions back.
=> Update release notes.

conda/base/context.py, conda/cli/main_info.py, tests/base/test_context.py
=> Fix channel args cli

CHANGELOG.md, conda/gateways/connection/adapters/s3.py
=> Revert S3 client initialization added in #10516

ci/build_docs.sh, ci/integration_tests.sh, ci/unit_tests.sh, tests/test_create.py
Also set the correct shell shebang.
=> Detect masked test errors by setting errtrace, pipefail, errexit

.github/workflows/stale.yml
This should help with handling old issues and PRs.
There is some research around that as well: https://www.researchgate.net/publication/331718820_Should_I_Stale_or_Should_I_Close_An_Analysis_of_a_Bot_That_Closes_Abandoned_Issues_and_Pull_Requests
=> Add stale GitHub action.

.github/workflows/stale.yml
This is related to https://github.com/actions/stale/issues/551
=> Remove labels-to-add-when-unstale for now.

.github/workflows/ci.yml, ci/scripts/linux/experimental-resolver.sh
Signed-off-by: Filipe Laíns <lains@riseup.net>
=> ci: run tests for the experimental solver

.github/workflows/ci-images.yml, tests/requirements.txt
We need mamba to run the tests :)
=> add mamba to docker image

.github/workflows/ci.yml, ci/scripts/windows/experimental-resolver.bat, ci/scripts/windows/setup.bat
Only to have an idea of how bad things are down there ;)
=> [Mamba POC] Enable windows tests

tests/test_create.py
Built on top of https://github.com/conda/conda/pull/10958
***
Re-raise `RawStrUnsatisfiableError` as `PackagesNotFound` for this test to pass. I don't want to add this to the code itself because it's irrelevant to the user, and Mamba devs might end up working on a nicer way to do this.
See issue https://github.com/mamba-org/mamba/issues/1196 for more details.
=> [Mamba POC] Raise right exception type

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/speed_improvement.yml, .github/workflows/stale.yml
Since https://github.com/actions/stale/issues/551 has been resolved I went ahead and enabled `labels-to-add-when-unstale` and `labels-to-remove-when-unstale` as well.
=> Update templates/workflows to use new label formats

.devcontainer.json, .github/workflows/ci-images.yml, .gitpod.yml, README.rst, ci/scripts/linux/setup.sh, dev/docker.bashrc
We can try with this link while this is being built:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/conda/conda/tree/gitpod)
* [Github.dev](https://github.dev/conda/conda/tree/gitpod) (only VS Code, no container)
* Github Codespaces: Click on `< > Code` on the top right corner, next to the title, and choose Codespaces (2nd tab).
Btw this should work locally with VS Code's Remote containers too, I think!
=> Enable one-click gitpod setup for Linux development (WIP)

conda/common/compat.py, conda/gateways/disk/link.py
=> Support running conda with PyPy on windows

docs/source/user-guide/tasks/manage-pkgs.rst, docs/source/user-guide/troubleshooting.rst
=> Use conda search instead of deprecated info subcommand in docs.

setup.py
Both the 'if' and 'else' sides seem to be doing the same thing
=> Remove unnecessary conditional

conda/core/link.py, conda/utils.py, news/gh-11168-get-comspec
Better envvar handling and simplify usage.
Working towards #10972
=> Rework `ensure_comspec_set` into `get_comspec`

conda/cli/main_run.py
=> Cleanup `conda.cli.main_run.execute`

conda/core/solve.py
Instead of falling back to the classic solver, explicitly error out.
=> [libmamba] Error out if libmamba is chosen but unavailable

.pre-commit-config.yaml
=> Disable autofix for pre-commit.ci.

docs/source/user-guide/install/download.rst
Line 46 - reworded `a curated and vetted set of packages` to `a set of packages curated and vetted for interoperability and usability`
=> Clarify on AIE messaging in download.rst

dev/start.bat
Cannot rely on running subprocess/commands within an IF-clause, instead rely on CALL/GOTO. Resolves issue occurring when `~\.condarc` is undefined (or the `devenv` key is undefined).
cc @jezdez
=> Flatten `dev\start.bat`

conda/core/initialize.py, dev/start, dev/start.bat
=> Do not auto activate base before activating devenv

.github/workflows/builds-canary.yaml, .github/workflows/builds-review.yaml, .github/workflows/ci-images.yml, .github/workflows/ci.yml
Resolves https://github.com/conda/conda/issues/11085
=> Only run GHAs on non-forks

tests/test_create.py
This was overly specific and didn't add any value to the test.
=> Relax python constrain in --only-deps test.

.authors.yml, rever.xsh
This is in preperation to 4.12.0.
Fix #11281.
=> Authors update

docs/source/commands/run.rst
Since gh-11293 was tagged as "good first issue", I went ahead and attempted this myself. I _think_ this should be all but I'll see what the CI says, or try to actually build the docs locally.
=> Document `conda run`

conda/cli/conda_argparse.py, docs/source/user-guide/tasks/manage-python.rst
=> Update conda run docs to not mention double dash.

.github/labels.yml
=> Add `[plugins::activate]` & `[plugins::init]` labels

docs/source/commands/compare.rst
Resolves https://github.com/conda/conda/issues/11329
=> Include docs for `conda compare`

.github/workflows/ci.yml, conda/_vendor/boltons/setutils.py, conda/_vendor/boltons/timeutils.py, conda/_vendor/vendor.txt, conda/common/path.py, tests/test_activate.py, tests/test_create.py
=> Add Python 3.10 as a test target.

docs/source/user-guide/install/windows.rst
@awwad I have revised the RegisterPython description that was inaccurate and raised as an issue. Please review my PR!
Fixes https://github.com/conda/conda/issues/11266
=> Correction of RegisterPython description in Windows Installer arguements 

news/11349-remove-unused-conda.auxlib
Forgot to include news for https://github.com/conda/conda/pull/11349
=> Add news for `auxlib` removals

CONTRIBUTING.md, docs/source/_static/css/custom.css, docs/source/dev-guide/contributing.md, docs/source/dev-guide/development-environment.md, docs/source/dev-guide/index.rst, docs/source/dev-guide/releasing.md, docs/source/user-guide/troubleshooting.rst
This PR is directly related to this open issue I created: https://github.com/conda/conda/issues/11376
The ultimate goal here is just getting to the contributing guide to a form where it's a little more user friendly.
We will be returning to update this once more, especially once everything with our governance planning is set.
One big change I introduced to this PR is layout related. On large screens, the docs become really hard to read because the text stretches across the entire screen. I have proposed a simple CSS fix to address this. It limits the width of the screen to no more than 80 characters wide, which is prime reading width.
Here's what the before and after look like:
**Before**
**After**
=> Updating contributing docs

CONTRIBUTING.md, docs/source/_static/css/custom.css
=> Fix Markdown syntax.

conda/base/context.py, conda/exceptions.py, conda_env/exceptions.py, conda_env/specs/binstar.py, news/11424-remove-unused-exceptions, tests/test_create.py, tests/test_exceptions.py
Removes `conda.exceptions.CommandArgumentError` in favor of `conda.exceptions.ArgumentError`.
Removes:
- `conda.exceptions.TooFewArgumentsError`
- `conda.exceptions.CondaRevisionError`
- `conda.exceptions.InstallError`
- `conda.exceptions.CondaTypeError`
- `conda.exceptions.CaseInsensitiveFileSystemError`
- `conda_env.exceptions.NoBinstar`
- `conda_env.exceptions.AlreadyExist`
- `conda_env.exceptions.EnvironmentAlreadyInNotebook`
- `conda_env.exceptions.EnvironmentFileDoesNotExist`
- `conda_env.exceptions.InvalidLoader`
- `conda_env.exceptions.NBFormatNotInstalled`
See #11321
=> Remove unused exceptions

dev/start, dev/start.bat
When adding new dependencies (e.g. pluggy) the base install is unable to invoke `init` on the devenv. Unfortunately, this means our devenv will no longer be nicely labeled when activated and is instead [mis]labeled as base.
<table>
<tr>
<th>Previously</th>
<th>Now</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Resolves issues @beeankha identified in #11435
=> Use `_ENVEXE` to init/activate devenv

.codecov.yml
Hi, Tom from Codecov here. I noticed that you were using Codecov but weren't actually getting any notifications on pull requests. I figured it would be useful to get some idea if code being changed is being tested, but also not blocking CI/merging. Let me know if this makes sense or if we can do something that would be helpful.
=> Add informational Codecov status checks

CHANGELOG.md
=> Update release date.

docs/source/user-guide/configuration/enable-tab-completion.rst
=> completions have moved to conda-incubator

conda/cli/main_clean.py
`conda clean` was missing a period for some of it's statements:
=> Add missing period to `conda clean`

conda_env/cli/common.py, conda_env/cli/main_export.py, news/11595-pendingdeprecation-conda_env.cli.common.stdout_json
Favoring `conda.cli.common.stdout_json` implementation over `conda_env.cli.common.stdout_json`.
=> Replace `conda_env.cli.common.stdout_json` with `conda.cli.common.stdout_json`

conda/base/context.py, conda_env/cli/common.py, conda_env/cli/main_create.py, conda_env/cli/main_export.py, conda_env/cli/main_update.py, conda_env/cli/main_vars.py, news/11594-pendingdeprecation-get_prefix
`get_prefix` has long since been replaced with `determine_target_prefix`, let's finish the deprecation.
=> Replace `conda_env.cli.common.get_prefix` with `conda.base.context.determine_target_prefix`

conda_env/specs/binstar.py, news/11601-mention-invalid-name-in-error-message, tests/conda_env/specs/test_binstar.py
This helps finding the source of the error.
=> Mention invalid package name in error message

tests/conda_env/test_cli.py
Tests started to fail. Looks like an old change related to `conda rename` slipped through the rebase. This removes this unused code.
=> Remove unused test clauses

docs/source/user-guide/tasks/manage-python.rst
=> Fix repeated `conda config` in documented commands

conda_env/cli/main_create.py, news/9396-outdated-examples-section-in-help-for-conda-env-create
This PR is an update to the conda env create CLI help text. I added more to the description and updated the examples to be a bit more generic. Fixes #9396.
=> Updated conda env create CLI help text.

conda/exceptions.py, news/11625-correct-conda-help-err-msg
Fix https://github.com/conda/conda/issues/11585
=> Suggest conda --help instead of non-existing 'conda help'

conda/exceptions.py, conda_env/env.py, conda_env/specs/yaml_file.py, news/11542-conda-crashes-on-empty-environment, tests/conda_env/test_cli.py
Resolves https://github.com/conda/conda/issues/11542
Original PR submitted by @dogukanteber: https://github.com/conda/conda/pull/11556
=> Fix empty environment.yml

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/builds-canary.yaml, .github/workflows/ci-images.yml, .github/workflows/ci.yml, README.md, conda_env/cli/main_create.py, docs/source/release-notes.md, news/11570-rename-master-to-main, tests/conda_env/__init__.py, tests/conda_env/test_cli.py, tests/conda_env/test_env.py
Performing necessary changes to rename master branch to main.
Ref: #11517 
These tests are expected to fail until the rename occurs.
=> Modify code to refer to `main` branch instead of `master`

.devcontainer.json, .github/workflows/ci.yml, .gitpod.yml
Missed a few references to the master branch. @jaimergp I'm no expert on GitPod so it would be great if you could take a look.
Ref: https://github.com/conda/conda/issues/11517
=> Update gitpod/images to use main branch

conda/auxlib/decorators.py, conda/base/context.py, conda/cli/find_commands.py, conda/common/_os/linux.py, conda/common/path.py, conda/common/serialize.py, conda/common/url.py, conda/exports.py, conda/gateways/disk/test.py, conda/gateways/logging.py, conda/resolve.py, conda/testing/helpers.py, conda/testing/integration.py, conda/utils.py, news/11597-pendingdeprecation-conda.auxlib.decorators.memoize, tests/models/test_prefix_graph.py, tests/test_activate.py
Deprecating custom caching in favor of stdlib caching.
Notable observations:
1. `conda.auxlib.decorators.memoizedproperty` and `conda.auxlib.decorators.memoizemethod` implement a shared cache (shared within the object instance) which allows for the entire object's cache to be reset all at once (instead of individually per property/method as can be done with `lru_cache.cache_clear`). This makes it less straightforward to replace with `lru_cache` at this time.
2. `conda.exports.memoized` is yet another custom implementation of caching that is only still in use in `conda-build` and includes logic to skip caching when any of the arguments are unhashable. This will need to be addressed in `conda-build` separately.
=> Deprecate `conda.auxlib.decorators.memoize` in favor of `functools.lru_cache`

conda/cli/main.py
Looks like we forgot to import `CondaError` as part of https://github.com/conda/conda/pull/11309.
=> Add missing `CondaError` import

conda/common/cuda.py, news/11626-cuda-wsl2
Support CUDA detection on WSL. We are just adding a known location for `libcuda.so`, which corresponds to the WSL path (WSL is detected as Linux).
Closes https://github.com/conda/conda/issues/11615
Closes https://github.com/conda/conda/issues/11488
=> Support CUDA detection on WSL

conda/auxlib/entity.py, conda/base/context.py, conda/core/index.py, conda/core/subdir_data.py, conda/exceptions.py, docs/source/user-guide/configuration/use-condarc.rst, news/11647-allowlist_channels, tests/base/test_context.py, tests/core/test_index.py, tests/data/build-index2-json.py, tests/data/build-index4-json.py, tests/data/build-index5-json.py, tests/integration/proxy/squid.conf, tests/models/test_channel.py
Part of inclusive language efforts. This is a low-impact change as no other conda org project refers to `whitelist_channels`.
Ref: https://github.com/conda/conda/issues/11517
> **Warning**
> pre-commit/darker/black will not be satisfied until this has been reviewed. Prior to merge we will apply the necessary changes.
=> Rename `whitelist_channels` to `allowlist_channels`

.pre-commit-config.yaml, pyproject.toml, setup.cfg
Since we [dropped Python 3.6 support](https://github.com/conda/conda/releases/tag/4.13.0), let's stop requiring black/darker to format for it.
=> Bump black's python versions

docs/source/user-guide/tasks/manage-python.rst
- [ x] Add / update outdated documentation?
=> fixed typo in manage-python documentation

conda/core/solve.py, news/11671-channel-update
Comes from https://github.com/conda-incubator/conda-libmamba-solver/pull/46#discussion_r930919841
=> Always mention channel in the outdated conda messages

conda/core/package_cache_data.py, news/11679-fix-typeerror.md
Prevent `TypeError` when log level is debug and reporting `index.json` cannot be read.
```
File ".../miniconda/lib/python3.9/logging/__init__.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
...
File ".../miniconda/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 329, in _make_single_record
log.debug("unable to read %s\n  because",
Message: 'unable to read %s\n  because'
Arguments: ('.../miniconda/pkgs/wrapt-1.14.1-py38h0a891b7_0/info/index.json', FileNotFoundError(2, 'No such file or directory'))
```
=> Fix `log.debug` `TypeError` in `conda.core.package_cache_data`

conda/exceptions.py
Minor refactor while working on #11689. Opted not to include a news snippet since using this change is fully backward compatible.
=> Modify `ExceptionHandler.write_out` to use `*args`

conda/exceptions.py
Another minor refactor from https://github.com/conda/conda/issues/11689 efforts.
=> Move `ExceptionHandler._calculate_ask_do_upload`'s `isatty` value into a cached property

conda/common/io.py, conda/exceptions.py
Minor refactor while working on https://github.com/conda/conda/issues/11689. Opted not to include a news snippet since these are private methods.
=> Simplify `ExceptionHandler._calculate_ask_do_upload ` logic

docs/requirements.txt, docs/source/conf.py, docs/source/robots.txt
Refs https://github.com/conda/conda-docs/issues/810.
=> Add sphinx-sitemap to docs.

conda/_vendor/toolz/LICENSE.txt, conda/_vendor/toolz/__init__.py, conda/_vendor/toolz/compatibility.py, conda/_vendor/toolz/dicttoolz.py, conda/_vendor/toolz/itertoolz.py, conda/_vendor/toolz/recipes.py, conda/_vendor/toolz/utils.py, conda/_vendor/vendor.txt, news/11333-replace-toolz-dependency-with-cytoolz, tools/vendoring/patches/toolz.patch
Oops, `conda-build` still depends on `conda._vendor.toolz` (https://github.com/conda/conda/issues/11698, https://github.com/conda/conda-build/pull/4556) so let's add it back and follow a proper deprecation schedule.
~Went ahead and finished removal of `conda._vendor.urllib3` https://github.com/conda/conda/pull/11373~ (see https://github.com/conda/conda/pull/11705)
=> Revert dropping `conda._vendor.toolz`

conda/common/serialize.py
Used to be here, but the call no longer serves any purpose. https://github.com/conda/conda/commit/88292dd1f927d58031b7a24fcff52a6b0c078c0e
=> normalize unused lazy import

conda/shell/etc/profile.d/conda.csh
Forgot to remove commented prefix injection code in CSH shell interface. See https://github.com/conda/conda/pull/11666#discussion_r944321131.
Xref: #11666
=> Remove CSH prefix injection

conda.recipe/run_test.sh
It looks like all of the tlz fixes (https://github.com/conda/conda/pull/11700, https://github.com/conda/conda/pull/11704, https://github.com/conda/conda/pull/11709) actually worked.
[The issue](https://github.com/conda/conda/runs/7774814177?check_suite_focus=true#step:3:2110) now appears to be related to dropping the prefix injection (https://github.com/conda/conda/pull/11666).
=> Debugging borked builds

conda.recipe/meta.yaml
The license in the meta.yaml of the conda.recipe directory is currently missing a dash. This might not impact many things, but could impact anything that checks that meta.yaml license values conform to SPDX standards.
=> add dash to license per SPDX standards

dev/linux/integration.sh
Stacking tests randomly started to fail. See https://github.com/conda/conda/runs/7978894522?check_suite_focus=true#step:3:1723
After much debugging found that the test is still using the old (before dropping the prefix injection) shell interface scripts:
This is a short-term solution as we continue working on redesigning the CI scripts (e.g. https://github.com/conda/conda-build/issues/4558)
=> Fix failing stacking tests

dev/linux/integration.sh, dev/start, news/11751-arm64-dev-support
Add architecture to download URL for development scrip to benefit arm64; fix #11751
=> update dev/start for arm64

.github/workflows/builds-canary.yaml, .github/workflows/builds-review.yaml, news/11761-use-canary-releasev22.8.0
Supersedes #11760 
Resolves #11758
=> Use `canary-release@v22.8.0` to resolve broken canary build issue

conda/activate.py, conda/models/channel.py
Replace toolz.drop() with stdlib equivalent.
=> remove toolz.drop()

CONTRIBUTING.md, news/11711-add-conda-capitalization-standards
Added conda capitalization standards to CONTRIBUTING.md.
=> Added conda capitalization standards to CONTRIBUTING.md.

conda/core/link.py, conda/core/subdir_data.py, conda/models/records.py, conda/trust/signature_verification.py, news/11545-move-content-trust-into-submodule
In an effort to speed up package signature verification we move the verification process to occur after solving. This way only the packages included in the transaction are validated (tens of packages, not thousands).
~A secondary goal was to move even more of the signature verification logic into `conda-content-trust` itself. This is in preparation for making this a conda plugin once the framework is available (#11435). With this change, conda knows/cares even less about what and how signature verification happens.~
Depends on #11646 
Resolves #11154
~See conda/conda-content-trust#29~
=> Change `conda-content-trust` from pre-solve to post-solve

conda/gateways/disk/link.py
Removing auxlib/six indirection for stdlib `builtins`.
=> Fix pypy win

recipe/meta.yaml, recipe/run_test.sh
This pull request adds the same changes that were implemented in the official conda feedstock. See this issue for more information: https://github.com/conda/conda-build/issues/4572
=> Fixes an issue that we are having with carnary builds

dev/start, news/11851-devenv-mach-arch
We added Mac ARM support to the devenv script (https://github.com/conda/conda/pull/11752) but occasionally still find it desirable to use the x86_64 installer.
=> Expose --mach and --arch to devenv script

news/11868-require-ruamel-yaml, recipe/meta.yaml, setup.py, tests/requirements.txt
Introducing the "new" dependency (`ruamel.yaml`) separately from the code change itself. Splitting this work so CI/canary build will pass.
Xref #10691
Required for #11837
=> Require `ruamel.yaml`

docs/source/user-guide/configuration/use-condarc.rst
Document option to create `.conda` instead of `.tar.bz2` with `conda-build`.
Should become the default...
=> document conda-build: pkg_format: 2

conda/core/initialize.py
Refactor/cleanup while working on #11812
=> Flatten script building for `conda init --dev`

conda/cli/conda_argparse.py, conda/cli/main_init.py
By refactoring the `SHELLS` option as argparse choices we get the built-in value verifications.
=> Refactor `conda init SHELLS` as argparse choices

conda_env/installers/pip.py, news/11818-conda-hang
When using an environment.yml that asks pip to clone a git repo and that path exists, pip will ask for user input. As we are not in a context to provide such, tell pip what to do so it doesn't hang on waiting for user input.
environment.yml has
```
name: exists
dependencies:
- python
- pip
- pip:
- -e git+https://github.com/conda/conda
```
1. Run `conda env create`.
1. Run `conda env update`.
The env create runs fine. The conda env update, however, will hang while displaying a spinner . Hacking the code to [say what it's doing](https://github.com/fragmede/conda/commit/e4862e20508b75144e067be0aba3ce0e122565e7) (might want to add that as a debug option) show that the pip process is asking for user input:  `What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup`, which corresponds to the files …
=> Avoid a specific case where `conda env update` hangs.

conda/notices/core.py
Noticed that pyupgrade made unrelated changes in https://github.com/conda/conda/pull/11865, extracted into separate PR.
=> Minor auto fixes from pre-commit.com hooks

.git-blame-ignore-revs
This helps exploring the repo history with `git blame ...` by being able to ignore/mark changes that are e.g. the result of generated commits, like done with pyupgrade in #11909. For usage see the comments added to the file.
=> Introduce git-blame-ignore-revs file, add pyupgrade commit to it

docs/source/user-guide/install/index.rst
There were some `.`s at the end of non-complete sentence bullet points, this PR is for fixing the formatting of those lists.
=> Fix Some Documentation Formatting

conda/core/package_cache_data.py, conda/core/repo.py, conda/core/subdir_data.py, conda/testing/integration.py, dev/linux/integration.sh, dev/linux/unit.sh, tests/core/test_solve.py, tests/core/test_subdir_data.py, tests/requirements.txt, tests/test_create.py, tests/test_fetch.py
=> Repodata gateway merged

.github/workflows/ci.yml
Does not change based on project requirements.
=> simplify minio cache key

conda/common/url.py
=> remove python 3 try/except import

conda/activate.py, tests/test_create.py
Add typing to activate, to help with updating test_activate.py
=> typing changes for activate

tests/core/test_initialize.py
Flatten unittest class into pytest functions and refacted setup/teardown as fixture.
Also contains minimal reformatting of c-style string formatting.
Prework for adding new tests in #11865.
=> Convert `conda.core.initialize` unittest to pytest

docs/requirements.txt
Adds tqdm as a dependency for our documentation.
=> Fixes a bug with the current documentation

.github/workflows/tests.yml
We're moving the token from being per-project to org-wide and it'd be best to be overly specific about the name to prevent overlap.
Similar to https://github.com/conda/conda-build/pull/4614
=> Update token name to be more specific.

conda/core/subdir_data.py
This is to make https://github.com/conda/conda/pull/12003 display without reformatting noise
=> reformat subdir_data.py with no additional changes

dev/linux/integration.sh, dev/linux/unit.sh
Will hardlinks be allowed, quieting the test run?
=> set pytest --basetemp

conda/plugins/manager.py, conda/plugins/virtual_packages/__init__.py, tests/plugins/conftest.py
POC of internal discussion.
Subclasses `pluggy.PluginManager` with a new `registers` method accepting a set of plugins to load.
Xref: https://github.com/conda/conda/pull/12059
=> Implement `PluginManager.load_plugins`

docs/source/glossary.rst, docs/source/user-guide/concepts/conda-plugins.rst, docs/source/user-guide/concepts/index.rst, docs/source/user-guide/tasks/manage-virtual.rst
Addresses/resolves the following issue:
- https://github.com/conda/conda/issues/12072
=> Add More Plugins-Related Info to Conda Documentation

news/11608-parallel-package-download
Provide missing news for parallel package downloads.
=> news item for #11608 parallel downloads

conda/core/initialize.py, conda/core/portability.py, news/12043-fix-shebang-ps1, recipe/build.sh, recipe/run_test.sh, tests/core/test_path_actions.py, tests/test_activate.py
Minimum work to fix https://github.com/conda/conda/issues/11885 and close https://github.com/conda/conda/issues/11893.
More robust solution long-term available at https://github.com/conda/conda/pull/11995.
Basically we prevent `conda` from using the polyglot shebang approach with two checks:
* If conda-build is being used and the executable is inside `$PREFIX`, we are most probably packaging `conda`. Do nothing and let prefix replacement handle that at install time (`replace_long_shebang()` right above our function)
* If somebody uses `conda init --install` outside conda-build (there's no reason to, but :shrug:), we ensure they end up with a `#!/usr/bin/env python` shebang by calling the function with a new flag.
=> Make sure conda does not use polyglot shebangs

.github/workflows/builds-review.yaml, .github/workflows/tests.yml, recipe/build.sh, recipe/run_test.bat, recipe/run_test.sh
=> Set env var triggering the isolated build mode added in conda-build 3.23.0

README.md
=> Added conda Discourse link

.github/workflows/docs.yml, .github/workflows/tests.yml, news/12141-skip-testing-non-code
After reviewing the [Github docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) (again), it should be possible to be more selective when we run tests versus a dummy job to satisfy the required check.
When we previously attempted this, we used a deny list for the `tests.yml`; here, I trying to use an allow list instead.
> **Warning**
> For this change to work correctly, we will need to modify the required checks to only require the `Tests / Analyze results` job.
Xref https://github.com/conda/conda/pull/11941, https://github.com/conda/conda/issues/12133
=> Skip tests when non-code is modified

news/12128-avoid-warning-when-env-vars-same-value-as-os-values
Forgot to ask for a news file in the following pull request:
- https://github.com/conda/conda/pull/12128
=> Add news file for PR 12128

docs/source/dev-guide/plugins/virtual_packages.rst
=> Fix typo in Virtual Packages plugin documentation page

recipe/meta.yaml
Is this spelled correctly?
TODO
=> add run_constrained

recipe/meta.yaml
Hm look like the tqdm dependency was missing from `host`.
Resolves https://github.com/conda/conda/issues/12189
Xref:
- https://github.com/AnacondaRecipes/conda-feedstock/blob/51e3269fc688bf6094c3f7f11dd4f1a7ffc979c6/recipe/meta.yaml#L47
- https://github.com/conda-forge/conda-feedstock/blob/303129379bd6383fc0336411ed1475336841b34b/recipe/meta.yaml#L48
=> Add missing tqdm dependency to host

RELEASE.md
This was missed for 4.14.x, 22.9.x and 22.11.x
=> Update release process to include creating a version on RTD.

conda/base/context.py, conda/cli/main_info.py, conda/common/_os/linux.py, conda/common/compat.py, conda/common/configuration.py, conda/common/pkg_formats/python.py, conda/common/serialize.py, conda/core/link.py, conda/core/prefix_data.py, conda/core/solve.py, conda/gateways/connection/session.py, conda/models/channel.py, conda/models/prefix_graph.py, conda/resolve.py, conda/testing/fixtures.py, conda/testing/solver_helpers.py, conda_env/env.py, news/12254-remove-odict, tests/base/test_context.py, tests/common/pkg_formats/test_python.py, tests/common/test_configuration.py, tests/conda_env/test_cli.py, tests/conda_env/test_env.py, tests/core/test_prefix_data.py, tests/models/test_channel.py, tests/test_activate.py, tests/test_api.py, tests/test_resolve.py
Experimenting with removing `OrderedDict`/`odict`.
Xref https://github.com/conda/conda/issues/11718
=> Remove `OrderedDict`/`odict`

conda/base/context.py, conda/common/configuration.py, conda/common/iterators.py, conda_env/env.py, news/12252-custom-unique-implementation
Inlined a simplified version of toolz's `unique` function.
Xref https://github.com/conda/conda/issues/11718
=> Implement custom `unique` function

.github/workflows/tests.yml, dev/windows/setup.bat
Should save time downloading minio.exe. Downloaded where the cache can find it, then copied to (I'm not sure where) CONDA_PREFIX is.
=> cache minio for windows

dev/start.bat, news/12311-improve-start-bat
This was necessary for the script to work, and the slow powershell progress bars have been turned off.
Will need to double check whether [this line must be removed](https://github.com/conda/conda/pull/12090/files#diff-8614d4f1c611ae587d54a767d15b9fe72c5be79f88be5f07702937c8b35c3fffL19-L21)
=> improve windows development setup script

tests/models/test_channel.py, tests/notices/test_fetch.py
=> miscellaneous test improvements

conda/common/compat.py, conda/common/serialize.py, conda/gateways/disk/create.py, news/12231-skip-chown-root-linux, tests/core/test_package_cache_data.py, tests/core/test_subdir_data.py, tests/gateways/test_repodata_gateway.py
Split off another pull request, improve test coverage of these two areas.
Add a little bit of type annotation; remove a Python 2 compatibility call; detect cph 2.x and skip chown when you're root in linux.
=> Tests to improve coverage of repodata gateway, subdir_data

.github/workflows/tests.yml, conda/testing/__init__.py, dev/linux/integration.sh, dev/linux/unit.sh, dev/macos/integration.sh, dev/macos/setup.sh, dev/macos/unit.sh, news/12350-conda-forge-ci, tests/requirements.txt, tests/test_activate.py, tests/test_cli.py, tests/test_create.py, tests/test_info.py, tests/test_priority.py
We have conda-forge Docker images with #12335, but some tests in the test suite assume the default value for the channels would be always `defaults`. This PR adds the relevant entries to the build matrix, adjust the environment setup logic and updates the assumptions made in the failing tests.
=> Add support for a `conda-forge`-based CI

tests/cli/test_config.py, tests/cli/test_main_notices.py, tests/core/test_subdir_data.py, tests/test_activate.py, tests/test_cli.py, tests/test_misc.py
"multiple statements on a line" etc., all in the tests
=> simple lint fixes pointed out by ruff

.readthedocs.yml, docs/source/_ext/conda_umls.py
=> Build UML files on RTD separately.

conda/exceptions.py, news/12353-use-only-tar-bz2-hint, tests/test_exceptions.py
Comes from https://github.com/conda/conda/issues/12332, and https://github.com/conda-incubator/setup-miniconda/issues/267
=> add note to exception if 'use_only_tar_bz2' is enabled

conda/base/context.py, conda/cli/main_info.py, conda/gateways/connection/adapters/s3.py, news/12276-context-and-cli-deprecations, news/12398-context-and-cli-deprecations, tests/test_create.py, tests/test_info.py
Related to this issue: 
- https://github.com/conda/conda/issues/12276
=> Mark some code in `context.py` and `cli/main_info.py` for official deprecation

dev/linux/unit.sh, news/12350-conda-forge-ci
=> Remove defaults from command line in Linux unit tests

conda/common/configuration.py, tests/common/test_configuration.py
A few test coverage improvements for configuration. Also reformats the test file with black.
=> improve test coverage of conda.common.configuration

conda/base/constants.py, conda/core/initialize.py, tests/models/test_prefix_graph.py, tests/notices/test_core.py
=> Trivial coverage improvements

dev/start
When updating our devenv base environment need to use the stable conda installation that came with our miniconda installation, not the source code.
Resolves #12467
=> Ignore `PYTHONPATH` when updating `devenv`

.github/workflows/images.yml, news/12498-s390x-container
This adds linux-s390x to the multi-arch ci/dev container. s390x was missing so far due to missing dependencies, which got resolved by https://github.com/conda-forge/pre-commit-feedstock/pull/66
=> Add s390x to multi-arch container

conda/auxlib/entity.py, conda/base/context.py, conda/common/configuration.py, conda/core/index.py, conda/core/solve.py, conda/core/subdir_data.py, conda/gateways/disk/link.py, conda/instructions.py, conda/lock.py, conda/models/channel.py, conda/models/prefix_graph.py, conda/models/records.py, conda/plan.py, conda_env/installers/conda.py, tests/cli/test_conda_argparse.py, tests/core/test_package_cache_data.py, tests/test_instructions.py, tests/test_toposort.py
Including "no cover" on many ImportError fallbacks.
=> Coverage tests for conda list, etc.

dev/linux/setup.sh, news/12528-jsonpatch, recipe/meta.yaml, tests/requirements.txt
Related to https://github.com/conda/conda/pull/12476; add jsonpatch without trying to update other dependencies.
=> add jsonpatch dependency, explicit coverage dependency

.github/workflows/tests.yml
To offer better release candidate testing we need to build canaries for release branches.
Xref https://github.com/conda/conda-build/pull/4857
=> Enable canary builds for release branches

docs/source/user-guide/index.rst
This would help some users that are looking for a course format to get started with conda.
=> Adding Anaconda's conda basics course.

docs/source/user-guide/configuration/index.rst, docs/source/user-guide/configuration/mirroring.rst, news/12583-doc-mirror
=> Add docs about mirroring channels

docs/source/dev-guide/deep-dives/solvers.md, docs/source/user-guide/configuration/mirroring.rst, news/12583-doc-mirror
Just a couple references broken in the previous PR #12583.
=> Follow up #12583: fix broken references

conda/gateways/repodata/__init__.py
Resolves [this comment](https://github.com/conda/conda/pull/12475#issuecomment-1552767334).
=> Add missing `f` for fstring and update imports

tests/test_history.py
Converted test_history to use pytest-style tests instead of unittest.
Reworked static tests into parametrized tests, added appropriate ids and added some missing tests.
=> Convert `test_history.py` to pytest-style

tests/test_create.py
Convert to pytest-style tests so we can start using fixtures and other modern testing features.
Part of the effort to adopt the new `tmp_env` fixture (#12592).
=> Convert `tests/test_create.py` to pytest-style

pyproject.toml, recipe/meta.yaml
We forgot to remove the `version_scheme` which fails to derive a valid development version when the tagged version ends in `.0`.
See https://github.com/conda/conda/actions/runs/5060896255/jobs/9087261786#step:3:797
Other recipe changes are to sync with [AnacondaRecipes](https://github.com/AnacondaRecipes/conda-feedstock) and [conda-forge](https://github.com/conda-forge/conda-feedstock) feedstocks.
Xref https://github.com/conda/conda-build/pull/4899
=> Fix hatch-vcs error in canary builds

conda/models/match_spec.py, docs/source/configuration.rst, docs/source/user-guide/concepts/pkg-search.rst, news/12707-sha256-matchspec, tests/models/test_match_spec.py
Closes #12654.
This was simpler than expected!
=> Add support for sha256 field in matchspec

.readthedocs.yml
This is a regression fix following #12707 for the https://docs.conda.io/projects/conda/en/latest/configuration.html page:
=> Fix rendering conda configuration documentation page.

.github/workflows/durations.yml, .github/workflows/tests.yml, tests/durations/combine.py
Introduce a new `durations.yml` workflow to run on a weekly schedule updating the duration files based on recent runs. This will help to keep the durations up to date as we continue to evolve the test suite.
=> Introduce `durations.yml` workflow

.github/workflows/durations.yml, .github/workflows/tests.yml, tests/durations/combine.py
Continuation of https://github.com/conda/conda/pull/12765
Adds missing permissions.
=> Fix `durations.yml` permissions

.github/workflows/tests.yml
Minor edits in preparation to update tests.yml with all the CI improvements we added to conda-build earlier in the year.
This change also eliminates 24 jobs from the testing matrix.
Xref #12772
=> Minor cleanup of tests.yml

conda/activate.py, news/12769-fix-bug-deactivation, tests/test_activate.py
Resolves https://github.com/conda/conda/issues/12769
=> Fix equal env variable deactivation #12769

conda/common/disk.py, news/12795-deprecate-temporary_content_in_file, tests/core/test_subdir_data.py
=> Mark `conda.common.disk.temporary_content_in_file` for deprecation

.gitignore, conda/plugins/subcommands/doctor/cli.py, docs/source/commands/doctor.rst, docs/source/commands/env/config/index.rst, docs/source/commands/env/config/vars/index.rst, docs/source/commands/env/config/vars/list.rst, docs/source/commands/env/config/vars/set.rst, docs/source/commands/env/config/vars/unset.rst, docs/source/commands/env/create.rst, docs/source/commands/env/export.rst, docs/source/commands/env/index.rst, docs/source/commands/env/list.rst, docs/source/commands/env/remove.rst, docs/source/commands/env/update.rst, docs/source/commands/index.rst, news/12841-add-conda-env-cli-docs
Resolves https://github.com/conda/conda/issues/10253
=> Add `conda env` CLI docs

.github/workflows/tests.yml
Followup to #12861 
https://github.com/conda/conda/actions/runs/5518409011/jobs/10062323000
=> Fix SyntaxError in canary CI step.

.github/workflows/tests.yml
Each of the OS runners has a different default Python (Ubuntu 22 has Python 3.10.6, Windows 2022 has Python 3.9.13, MacOS 13 has Python 3.11.4). Why?!?!?! 🤦🏼‍♂️
This reverts the recent tinkering in favor of just using Python 3.11.
All of the current runners has Python 3.11 pre-cached so this is a cheap change:
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#python
- https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#python
- https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#python
- https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#python
- https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#python
- …
=> Revert `tests.yml` syntax changes in favor of using Python 3.11

docs/source/user-guide/configuration/use-condarc.rst
This adds organizations to the documentation of how non-URL channels are interpreted.
=> docs: non-URL channels can be organizations

conda/activate.py, news/12874-cygpath-fallback, tests/core/test_initialize.py
The `cygpath` fallback logic was removed in https://github.com/conda/conda/pull/12627 because the code stated:
https://github.com/conda/conda/blob/84f0d2b56c2e81b62841f8926d2ee319182fdb67/conda/activate.py#L850-L851
So we incorrectly assumed that `conda` would always have `cygpath` available on Windows (this is in fact not the case, see https://github.com/conda/conda/issues/12873).
We add back the fallback logic until a better solution (if there is one) is decided upon.
Resolves #12873
=> Add (back) `cygpath` fallback

.github/workflows/builds-review.yaml, .github/workflows/tests.yml
We want to use the latest version of https://github.com/conda/actions/releases/tag/v23.7.0.
We especially want https://github.com/conda/actions/pull/113.
=> Bump conda/actions to 23.7.0

conda/activate.py, news/12880-correct-native_path_to_unix, tests/test_activate.py
Followup to https://github.com/conda/conda/pull/12874 and https://github.com/conda/conda/pull/12627
The path_conversion functions (`native_path_to_unix` is one of them) need to handle all of the following inputs:
- `None`: null
- `""`: an empty string
- `()`: any empty iterable
- `"path"`: a single path
- `["path", ...]`: an iterable with one or more paths
As previously written the `native_path_to_unix` handled everything except empty strings & iterables. This caused issues when, for example, the `$CONDA_PREFIX/etc/conda/{de,}activate.d` exists and is either empty or doesn't include any scripts supported by the current shell (see https://github.com/anaconda-distribution/installers/actions/runs/5538377518/jobs/10108261051#step:6:1579).
Resolves #12836
=> `native_path_to_unix`  needs to handle empty strings and empty iterables

.readthedocs.yml
=> Build ePub, PDF and HTML zip formats as well.

conda/cli/conda_argparse.py, news/12893-deduplicate-subcommands
<table>
<tr>
<th>Previously</th>
<th>Now</th>
</tr>
<tr>
<td>
```
usage: conda ...
conda is a tool ...
optional arguments:
-h, --help          ...
-V, --version       ...
--no-plugins        ...
commands:
The following ...
COMMAND
clean             ...
compare           ...
config            ...
create            ...
info              ...
init              ...
install           ...
list              ...
notices           ...
package           ...
remove (uninstall)...
rename            ...
run               ...
search            ...
update (upgrade)  ...
build             ...
convert           ...
debug             ...
develop           ...
doctor            ...
index             ...
inspect           ...
metapackage       ...
render            ...
skeleton          ...
conda commands ... …
```
=> Deduplicate plugin and legacy subcommands

docs/requirements.txt
We no longer use PyYAML for our docs and including it now results in an error since its incompatible with the recently released Cython 3.0.
=> Remove unused docs dependency

docs/requirements.txt
Backport dropping unused PyYAML dependency for docs.
Xref #12897
=> Remove unused PyYAML dependency

.pre-commit-config.yaml, conda/cli/conda_argparse.py, conda/exception_handler.py, conda/plugins/manager.py, tests/plugins/test_manager.py, tests/plugins/test_subcommands.py
=> Move plugin disabling into argument parser initialization.

recipe/meta.yaml
Updating conda's recipe file to have the most up-to-date version requirements, per comparison to [Anaconda's feedstock](https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml).
- [`packaging`](https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml#L53) 
- [`requests`](https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml#L56)
=> Update conda recipe file

.authors.yml, .mailmap, CHANGELOG.md, conda/cli/conda_argparse.py, conda/cli/main.py, conda/testing/__init__.py, tests/cli/test_subcommands.py
Merged hotfix (#12929) back into `main`.
Xref #12849 
> **Warning**
> DO NOT SQUASH MERGE!
=> Merge `23.7.x` branch back into `main`

conda/cli/main.py, news/12936-fix-parsing-json-debug-for-executable-subcommands
Followup to https://github.com/conda/conda/issues/12906 and https://github.com/conda/conda/issues/12928.
Resolves #12935
=> Do not parse unknowns, reparse entire args

conda/gateways/repodata/__init__.py, conda/gateways/repodata/jlap/interface.py, news/12927-remove-unused-cache-path-arguments
Remove paths replaced by cache object.
=> remove cache_path_* arguments

docs/source/user-guide/configuration/use-condarc.rst
=> add note about yaml extension in .condarc docs

dev/start, dev/start.bat
It's probably time to update the default Python version for our devenv.
=> Bump default devenv Python to 3.10

tests/test-recipes/private_package/meta.yaml, tests/test_create.py
=> Refactor private channel test

conda/cli/conda_argparse.py, news/12988-CONDA_JSON
Fix for `CONDA_JSON=true conda ...` regression.
Resolves https://github.com/conda-forge/miniforge/issues/477
Resolves https://github.com/conda/conda/issues/12987
=> Default `--json` & `--debug` to `NULL`

conda/cli/find_commands.py, news/13006-non-base-plugins
Resolves https://github.com/conda/conda/issues/12955 regression.
=> Find `conda-*` executables on `PATH`

.github/labels.yml
Adding this label so that we can keep track of update/upgrade issues
=> Add `tag::update` label

tests/test_activate.py
=> Ignore setup output for `tests/test_activate.py::test_stacking`

docs/source/dev-guide/deep-dives/activation.md
=> Fix typo in activation.md

.github/workflows/tests.yml, tests/cli/test_main_clean.py
Recent tests have seen tests fail in `test_main_clean.py` for unrelated changes. This is an effort to continue debugging this issue (and taking the opportunity to update the tests).
See:
- https://github.com/conda/conda/actions/runs/6087199341/job/16515312477?pr=13057
- https://github.com/conda/conda/actions/runs/6086676360/job/16517913451?pr=13062
(edit) Still unsure why this failure started to occur. The package in question `conda-forge::bzip2` hasn't been modified in 2 years. Either way it appears that switching to `zlib` fixes the problem.
Otherwise this PR also cleans up type hints.
=> Debugging recent failures in `test_main_clean.py`

.github/workflows/tests.yml, conda/testing/gateways/fixtures.py, news/12986-fix-S3-bucket-name
Backporting https://github.com/conda/conda/pull/12986 and https://github.com/conda/conda/commit/0a2244f0995be1f7f5759bb6c19ea8c3393ec099#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR350
=> Backport test fixes to 23.7.x

tests/requirements.txt
Default's `anaconda-client` recently added `anaconda-anon-usage` as a dependency which monkeypatches the context object. This monkeypatching breaks our tests.
This is a patch until we have time to investigate further.
=> Install anaconda-client from conda-forge for tests

conda/gateways/repodata/__init__.py, news/13056-jsondecodeerror, tests/gateways/test_jlap.py
=> catch JSONDecodeError when loading repodata cache metadata

news/13107-add-py-typed-marker
Fixes: #13106
- ~Add / update necessary tests?~
- ~Add / update outdated documentation?~
=> Add a py.typed marker

conda/gateways/connection/adapters/s3.py, news/drop-boto2
Remove code for the unsupported boto library; use boto3 only for s3 support.
This PR has awkward wording in the description/news.
=> remove code for unsupported boto library (boto3 remains)

CHANGELOG.md
The changelog should say the s3 bucket name issue affected the test suite only, and is not otherwise interesting to a conda user.
=> clarify changelog

.pre-commit-config.yaml
Inspired by:
* https://results.pre-commit.ci/run/github/6235174/1695125561.aWYSRacsRzyD-dSc5BLmfA (to be able to see what ruff fixed here)
* https://github.com/pre-commit/pre-commit/issues/1712
=> Show git diff after all pre-commit hooks to be able to see auto-format/fix changes

conda/cli/find_commands.py, news/13125-find_commands-catch-oserror, tests/cli/test_find_commands.py
=> Catch OSError in find_commands

conda/gateways/connection/__init__.py, conda/gateways/connection/adapters/s3.py
Followup to #13112
Bring `boto3` import logic inline to where it gets used. Remove fallback imports from `pip._vendor.requests`.
=> Lazily import boto3 within method

.pre-commit-config.yaml, tests/requirements-extra.txt, tests/requirements.txt
Removes comments from requirement files and enables pre-commit sorting.
This is an easier improvement extracted from https://github.com/conda/conda/pull/13162.
=> Add sort check for requirements.txt files

.authors.yml
Discovered while working on https://github.com/conda/pycosat/pull/75.
=> Correct github id for Travis E. Oliphant

news/13177-minimum-conda-build, recipe/meta.yaml
see https://github.com/conda/conda-build/issues/5026
=> constrain conda-build >=3.27

conda/testing/gateways/fixtures.py, dev/linux/integration.sh, dev/macos/setup.sh, dev/start, dev/start.bat, dev/windows/setup.bat, pyproject.toml, recipe/meta.yaml, tests/cli/test_main_search.py, tests/requirements-Windows.txt, tests/requirements-s3.txt, tests/requirements.txt
Inspired by https://github.com/conda/conda/pull/13162.
Removes dependencies not explicitly imported in code or tests.
=> Cleanup dependencies

conda/common/configuration.py, news/12956-check-condarc-without-resolving-symlink, tests/common/test_configuration.py
=> check symlink, not target name for condarc

conda/gateways/repodata/jlap/fetch.py, news/12193-expected-jlap-error-handling, news/12913-expected-jlap-error-handling, tests/gateways/test_jlap.py
=> Quieter jlap error handling after range request.

conda/common/configuration.py, conda/common/serialize.py, news/drop-ruamel-underscore-yaml
We removed `ruamel_yaml` a year ago.
The `conda install required-dependency` errors are odd - they might be a little hard to follow through on...
=> remove ruamel_yaml import/except fallback

docs/source/dev-guide/plugins/index.rst
Fix error found when copy/pasting code.
I also notice the example is a function that accepts `list[str]`, but the typing on `CondaSubcommand` expects `[Namespace | tuple[str]],  # arguments` (list != tuple)
=> update plugins documentation

conda/cli/conda_argparse.py, news/13232-option-parsing-bugfix, tests/cli/test_main.py
Fixes: #13227 
I think this should do the trick, but I have a suspicion this was left out for some reason... If so, there's another, less desirable way to solve it.
=> Fix for `conda --debug` error

news/13173-conda-cli-and-argparse-updates
Add missing news file for PR https://github.com/conda/conda/pull/13173
=> Add news file for PR 13173

conda/core/index.py, recipe/meta.yaml, tests/requirements.txt
Xref https://github.com/conda-forge/conda-feedstock/pull/222
=> Add archspec dependency

conda/core/package_cache_data.py, news/13248-sort-packages-descending
Fix #13248
PackageRecord says size is optional, under which circumstances can it be missing?
=> sort package downloads by size descending

tests/conda_env/test_cli.py
=> Fix typo in test_cli.py

conda/base/context.py, conda/cli/main_info.py, news/13265-show-solver-conda-info, tests/cli/test_main_info.py
=> Show used solver in `conda info` output.

conda/_vendor/cpuinfo/__init__.py, conda/base/context.py, conda/common/io.py, conda/common/pkg_formats/python.py, conda/core/index.py, conda/core/package_cache_data.py, conda/core/solve.py, conda/core/subdir_data.py, conda/exceptions.py, conda/gateways/connection/adapters/ftp.py, conda/gateways/connection/download.py, conda/gateways/disk/create.py, conda/gateways/disk/delete.py, conda/gateways/disk/lock.py, conda/gateways/repodata/jlap/fetch.py, conda/gateways/repodata/jlap/interface.py, conda/gateways/repodata/lock.py, conda/gateways/subprocess.py, conda/history.py, conda/models/match_spec.py, conda/plugins/subcommands/doctor/health_checks.py, conda/resolve.py, conda/testing/__init__.py, conda/testing/fixtures.py, conda/testing/helpers.py, conda/testing/integration.py, conda/testing/notices/fixtures.py, conda/testing/notices/helpers.py, conda/utils.py
We have been [implicitly](https://github.com/conda/conda/issues/13241#issuecomment-1783272754) preferring relative imports for a while.
This finishes the job and converts all outstanding absolute imports into relative ones.
=> Convert all absolute imports to relative

pyproject.toml, recipe/meta.yaml, tests/requirements.txt
To account for the release of conda-libmamba-solver 23.11.0 that we require in conda 23.10.0's recipes.
=> `23.10.x` Bump up minimum version of conda-libmamba-solver dependency to 23.11.0

conda/plugins/subcommands/doctor/health_checks.py, tests/conftest.py
During releases theres a possible race condition during which the release appears on defaults/conda-forge perhaps before we get around to merging the release branch back into `main` (e.g. https://github.com/conda/conda/pull/13286). This results in tests starting to fail as the "WARNING: A newer version of conda exists" starts appearing in stderr.
E.g.:
- https://github.com/conda/conda/actions/runs/6789566222/job/18457066445?pr=13186
- https://github.com/conda/conda/actions/runs/6788677900/job/18454198593?pr=13293
- https://github.com/conda/conda/actions/runs/6788872838/job/18454814378?pr=13211
Avoid the issue by disabling checking for newer conda versions.
=> Prevent notify outdated conda during testing

tests/cli/__init__.py, tests/cli/test_subcommands.py
This should supersede #13284 as less drastic and focusing on the subcommand tests alone.
=> Increase logger level for CLI tests.

LICENSE, conda/_vendor/appdirs.py, conda/base/context.py, conda/gateways/anaconda_client.py, conda/notices/cache.py, news/13306-appdirs-platformdirs, pyproject.toml, recipe/meta.yaml
=> Switch from `appdirs` to `platformdirs`.

conda/plugins/virtual_packages/__init__.py, conda/plugins/virtual_packages/conda.py, docs/source/user-guide/tasks/manage-virtual.rst, news/13266-conda-virtual-package, tests/plugins/test_virtual_packages.py
Add the `__conda` virtual package using the virtual package plugin hook.
Also expand the virtual package test suite for better coverage.
Supersedes #11764 
Resolves #13308
=> Implement `__conda` virtual package

docs/source/commands/doctor.rst
[Conda documentation](https://docs.conda.io/projects/conda/en/stable/commands/doctor.html) shows
`usage: conda doctor doctor [-v] [-h] [-n ENVIRONMENT | -p PATH]`.
This PR deletes the second `doctor`, updating the text to
`usage: conda doctor [-v] [-h] [-n ENVIRONMENT | -p PATH]`
=> Minor fix of doctor cli command documentation.

conda/base/context.py, conda/gateways/anaconda_client.py, conda/notices/cache.py
Follow up to #13307 (as found in https://github.com/conda/conda/pull/13317#discussion_r1389840396)
=> Fix deprecation of the vendored appdirs.

conda/plugins/subcommands/doctor/__init__.py
Per the refactoring done in https://github.com/conda/conda/pull/13173 (discovered while doing work in https://github.com/conda/conda/pull/13168)
=> Update import line in `conda/plugins/subcommands/doctor/__init__.py` to point to new CLI helper module

docs/source/conf.py
Fixes: #13354 
Manually test the following URLs to make sure they resolve to the correct page:
- api/api.html
- api/index.html
- api/python_api.html
- api/solver.html
=> Fixing broken redirects

tests/core/test_solve.py
This is being tracked in https://github.com/conda/conda-libmamba-solver/issues/317, but right now it merely adds noise to CI. Retries usually fix it, so for now we'll just leave it as xfailable, but I plan to revisit it soon.
=> mark `test_conda_downgrade` as xfail

tests/requirements-s3.txt
In the last 24h some PRs were failing with:
```
tests/gateways/test_connection.py::test_s3_server - TypeError: not all arguments converted during string formatting
```
This was caused by a regression in boto3 1.33.0, fixed in 1.33.1 via https://github.com/boto/boto3/pull/3950.
[conda-forge already built 1.33.1](https://github.com/conda-forge/boto3-feedstock/pull/1409), so the solver should pick it but, _juuuust in case_.
=> do not use boto3 1.33.0

conda/activate.py, dev/start, dev/start.bat, tests/requirements.txt
Conda's initialize code would remove any `conda-*info`, `conda.*`, and `conda-*.egg` files found in site-packages making it more difficult to use devenv for development of other conda projects (e.g. conda-build, conda-libmamba-solver, etc.):
https://github.com/conda/conda/blob/e783377439ed1c413c6bffb9b785ae1d79c2392a/conda/core/initialize.py#L1785-L1816
This change removes usage of `conda init --dev` in favor of `conda shell.bash hook` and `$CONDA_PREFIX/condabin/conda_hook.bat` which accomplishes the same thing in a less violent manner.
=> Update devenv to avoid `rm -rf` codes

pyproject.toml, recipe/meta.yaml, tests/requirements-Windows.txt, tests/requirements-s3.txt, tests/requirements.txt
Resolving canary build issues.
Needed to relax `menuinst` requirement for the solve to succeed, can add back `>=2.0` bound later.
Supersedes https://github.com/conda/conda/pull/13378
=> Correct & sync dependencies

docs/source/user-guide/concepts/installing-with-conda.rst
Fixes: #13373 
I also took a little time to update the introduction. I think this a good thing, but I am happy to hear feedback.
=> Display issue with flow chart on user-guide/concepts/installing-with-conda page

CHANGELOG.md
See https://github.com/conda-forge/conda-feedstock/pull/228#discussion_r1411932435.
Supersedes https://github.com/conda/conda/pull/13393
=> add special note about menuinst

.github/workflows/images.yml, dev/linux/install_miniconda.sh
XRefs https://github.com/conda/conda-build/issues/4997 and should precede https://github.com/conda/conda-build/pull/4998 and https://github.com/conda/conda/pull/13073
=> Build Python 3.12 based CI images.

conda/deprecations.py
=> Correct typing in `conda.deprecations`

tests/test_activate.py
Grrrr the solve + install time appears to have increased again, time to bump up the timeout yet again...
See recent failures:
- https://github.com/conda/conda/actions/runs/7221962507/job/19687175389?pr=13419
- https://github.com/conda/conda/actions/runs/7205012904/job/19687911550?pr=13389
- https://github.com/conda/conda/actions/runs/7205272822/job/19687912856?pr=13426
=> Bump timeout up by 60 seconds

tests/test_create.py
Xref https://github.com/conda/conda/issues/13292
=> Update `test_safety_checks` & `test_json_create_install_update_remove`

tests/cli/test_main_run.py, tests/cli/test_main_search.py, tests/test_create.py
More `tests/test_create.py` refactoring:
- `test_rpy_search` (moved to `tests/cli/test_main_search.py`)
- `test_compile_pyc`
- `test_conda_run_1` (eliminated, duplicate of existing test in `tests/cli/test_main_run.py`)
- `test_conda_run_nonexistant_prefix` (moved to `tests/cli/test_main_run.py`)
- `test_conda_run_prefix_not_a_conda_env` (moved to `tests/cli/test_main_run.py`)
- `test_clone_offline_multichannel_with_untracked` (simplified, renamed to `test_clone_offline_with_untracked`)
- `test_package_pinning`
- `test_update_all_updates_pip_pkg`
Xref https://github.com/conda/conda/issues/13292
=> Another test create batch

tests/test_create.py
Refactored:
- `test_package_optional_pinning`
- `test_update_deps_flag_absent`
- `test_update_deps_flag_present`
- `test_shortcut_creation_installs_shortcut`
- `test_shortcut_absent_does_not_barf_on_uninstall`
- `test_shortcut_absent_when_condarc_set`
- `test_menuinst_v2`
- `test_create_default_packages`
- `test_create_default_packages_no_default_packages`
Removed:
- `test_shortcut_in_underscore_env_shows_message`: tests private envs which have been deprecated, see https://github.com/conda/conda/pull/12101
- `test_shortcut_not_attempted_with_no_shortcuts_arg`: `--no-shortcuts` tested in `test_shortcut_absent_does_not_barf_on_uninstall`
Xref https://github.com/conda/conda/issues/13292
=> More test_create refactoring

tests/cli/test_main_search.py, tests/test_create.py
Xref https://github.com/conda/conda/issues/13292
Refactored:
- `test_search_gawk_not_win_filter`
- moved to `tests/cli/test_main_search.py::test_unknown_platform_package_missing`
- `test_search_gawk_on_win`
- moved to `tests/cli/test_main_search.py::test_mocked_platform_package_found`
- added `tests/cli/test_main_search.py::test_current_platform_package_missing`
- `test_search_gawk_on_win_filter`
- moved to `tests/cli/test_main_search.py::test_different_platform_package_found`
- `test_bad_anaconda_token_infinite_loop`
- moved to `tests/cli/test_main_search.py::test_bad_anaconda_token`
- `test_use_index_cache`
- `test_offline_with_empty_index_cache`
For consistency also moved:
- `test_anaconda_token_with_private_package`
- moved to …
=> Refactor gawk tests, anaconda token tests, and index cache tests

conda/__version__.py, conda/gateways/connection/session.py, conda/testing/fixtures.py, tests/conftest.py, tests/gateways/test_jlap.py, tests/plugins/test_solvers.py, tests/test_features.py, tests/test_misc.py
A few seemingly unrelated fixes that were surfaced with the recent conda-forge `pytest 8.0.0` release.
`pytest 8.0.0` corrects `pytest.warns` behavior breaking one of the tests in `tests/gateways/test_jlap.py`. This corrects the test per pytest's docs: https://docs.pytest.org/en/7.4.x/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests
Also identified an incorrect mocking of `context.solver` in `tests/plugins/test_solver.py` which resulted in the context object behaving oddly in subsequent tests (e.g., `tests/test_features.py`). It would continue to report `context.solver == "libmamba"` even when that was no longer the case. Fixed by using the `solver_classic` fixture when possible and otherwise used `monkeypatch.setenv` instead of `monkeypatch.setattr`.
=> Fix test to work with `pytest 8.0.0`

conda/plugins/hookspec.py
The examples yield from plugins.Conda<plugin> rather than using Conda<plugin> directly.  
Fix the conda pre, post and health check plugin example so that they correctly use the classes from the `plugins` module.
=> Fix conda pre, post and health check plugin examples

pyproject.toml
See deprecations in https://github.com/astral-sh/ruff/releases/tag/v0.2.0.
- ruff.ignore → [ruff.lint.ignore](https://docs.astral.sh//ruff/settings/#lint_ignore)
- ruff.select → [ruff.lint.select](https://docs.astral.sh//ruff/settings/#lint_select)
- ruff.extend-per-file-ignores → [ruff.lint.extend-per-file-ignores](https://docs.astral.sh//ruff/settings/#lint_extend-per-file-ignores)
- ruff.pydocstyle → [ruff.lint.pydocstyle](https://docs.astral.sh//ruff/settings/#lint_pydocstyle)
=> Ruff has moved some of the config values

conda/gateways/repodata/jlap/fetch.py, news/13558-bad-zst-fallback, news/13573-skip-zst-on-4xx, tests/core/test_solve.py, tests/gateways/test_jlap.py
Cherry pick both https://github.com/conda/conda/pull/13559 and https://github.com/conda/conda/pull/13576 over to the `24.1.x` branch for a patch release.
=> Port `ZstdError` & HTTP 400-500 to `24.1.x`

conda/core/subdir_data.py, news/fetch-repodata-remote-request, tests/core/test_subdir_data.py
=> Repair deprecated fetch repodata

conda/shell/bin/conda
=> Update testing entrypoint deprecation

.github/workflows/tests.yml
This updates all actions to their latest version. To reduce the noise/diff in https://github.com/conda/conda/pull/13617
Biggest update of most of the actions (but not relevant to us) is the bump to node20. The important update is conda-incubator/setup-miniconda@v3 as that is a bump to node20 and support for the apple silicon runners.
~~- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?~~
~~- [ ] Add / update necessary tests?~~
~~- [ ] Add / update outdated documentation?~~
=> Update all actions including setup-miniconda to their latest version

.github/workflows/tests.yml, news/13617-enable-osx-arm64-tests, tests/cli/test_main_info.py, tests/test_activate.py, tests/test_create.py
Finally available for OSS projects: [GitHub Actions: Introducing the new M1 macOS runner available to open source!](
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
=> Run macos tests on osx-64 and osx-arm64 runners

conda/exports.py, news/13629-remove-handle_proxy_407
=> Remove `conda.export.handle_proxy_407`

conda/cli/main_env_create.py, news/13632-fix-conda-env-create-subdir-platform-regression
=> Fix `conda env create` "`--subdir` / `--platform`" flag regression

README.md
Just a minor follow-up to #13162
=> Remove outdated badge.

conda/plugins/hookspec.py
Fix the example for the settings plugin hook.
=> Fix the settings plugin hook example

.github/workflows/tests.yml, .github/workflows/upload.yml, news/13663-release-uploads
=> Upload a release archive during release.

recipe/meta.yaml
The current canary build in main is broken after the merge of the deprecation PR #13634. Trying to fix it by adding boltons to the host section..
https://github.com/conda/conda/actions/runs/8192976141/job/22405685594#step:5:846
<details>
<summary>Log output</summary>
```
2024-03-07T18:24:05.5471091Z WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.26
2024-03-07T18:24:05.7451490Z Cloning into bare repository '/home/runner/work/conda/conda/pkgs/git_cache/home/runner/work/conda/conda'...
2024-03-07T18:24:05.7577210Z done.
2024-03-07T18:24:09.7514281Z Cloning into '/home/runner/work/conda/conda/pkgs/conda_1709835845697/work'...
2024-03-07T18:24:09.7585206Z done.
2024-03-07T18:24:10.3385476Z Your branch is up to date with 'origin/main'. …
```
=> Fix canary builds

tests/requirements.txt
We include `zstandard` in `recipe/meta.yaml`, might as well also test with it.
=> Add `zstandard` to `requirements.txt`

docs/source/_static/switcher.json, docs/source/conf.py
This follows [the docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#version-dropdowns), not sure if this also works in the scenario the conda docs are under, since there is [some auto-detection happening](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/readthedocs.html) around the version switcher.
=> Show version banner in docs

.github/workflows/tests.yml, tests/__init__.py, tests/conftest.py
Asserts pytest is using the conda source code found alongside the test suite. Also includes conda's path in pytest's header for reference.
Supersedes #13696 
Xref https://github.com/conda/conda-build/pull/5236
=> Ensure the development version of conda is being tested

conda/common/io.py, conda/common/url.py, conda/plugins/hookspec.py
Minor issues that I found when looking at the docs build log.
=> Fix some indentation issues.

conda/cli/install.py
Instead of manually parsing package strings use MatchSpec (as the comment suggests we should do).
=> Use MatchSpec instead of custom parsing

conda/__init__.py, conda/_vendor/frozendict/__init__.py, conda/auxlib/collection.py, conda/auxlib/entity.py, conda/base/context.py, conda/common/configuration.py, conda/common/pkg_formats/python.py, conda/core/solve.py, conda/models/match_spec.py, conda/resolve.py, news/13766-devendor-frozendict, pyproject.toml, recipe/meta.yaml, tests/requirements.txt
`frozendict` is the last vendored dependency not marked for deprecation.
Resolves #13767
=> Devendor `frozendict`

tests/test_activate.py
Refactor `write_pkg_env_vars` into `write_pkg_A`, `write_pkg_b`, and `write_okgs`. And abstract state file creation into new `write_state_file`.
Extends https://github.com/conda/conda/pull/13757
Split from https://github.com/conda/conda/pull/13620
=> Add state & env_var helpers to `test_activate.py`

conda/core/subdir_data.py, conda/testing/helpers.py, news/13744-base-url, tests/core/test_package_cache_data.py, tests/core/test_solve.py, tests/core/test_subdir_data.py, tests/data/base_url_channel/linux-64/repodata.json, tests/data/base_url_channel/noarch/repodata.json, tests/data/base_url_channel/osx-64/repodata.json, tests/data/base_url_channel/win-64/repodata.json, tests/test_create.py
Closes #13137 
Works with classic, but it will need extra work in libmamba. Assumes same credentials as parent channel.
=> Add support for CEP-15 `base_url`

conda/env/env.py
Fixes #13560
Alternative to #13737 and #13743.
Copy into Dockerfile in repo:
```dockerfile
FROM --platform=linux/amd64 continuumio/miniconda3:24.1.2-0
RUN echo "dependencies:\n- python=3.9" > env.yml
COPY conda/env/env.py "/opt/conda/lib/python3.11/site-packages/conda/env/env.py"
RUN conda env update -n base -f env.yml
```
Run:
```
docker build --no-cache .
```
=> Don't inline imports for a more stable upgrade experience.

.github/condarc-conda-forge, .github/condarc-defaults, tests/gateways/test_connection.py
=> Disable anaconda-anon-usage for CI.

.github/dependabot.yml
Add depedabot config for docs.
Xref https://github.com/conda/conda-build/pull/5006
=> Add dependabot config for docs

tests/plugins/test_manager.py
Backport of #13838.
Refs #13844
=> Fix `pluggy 1.5.0` failure in tests

.github/workflows/builds-review.yaml
The review builds fail if `macos-latest` resolves to `macos-14` (`osx-amr64`).
See https://github.com/conda/conda/actions/runs/8809949546/job/24181531935?pr=13837
=> Add arm64 review builds

conda/env/pip_util.py, tests/env/support/example/environment_with_pip.yml, tests/env/test_create.py
Resolves https://github.com/conda/conda/issues/13835
=> Fix `conda env create/update --json` regression

conda/gateways/logging.py, news/13684-remove-setuptools-remainings, news/13732-log-trace, news/13801-deprecate-make_immutable
Some updates/corrections related to `24.5.x` release testing and review.
xref https://github.com/conda/conda/issues/13870
=> `24.5.x`-related updates / corrections

CHANGELOG.md, news/13736-reporters
This feature is not in use yet and is still pending additional work in the feature branch. Until the larger work is merged in we wont mention this in the changelog.
=> Remove `reporters` from 24.5.0 changelog

conda/shell/Library/bin/conda.bat, conda/shell/Scripts/activate.bat, conda/shell/condabin/_conda_activate.bat, conda/shell/condabin/activate.bat, conda/shell/condabin/conda.bat, conda/shell/condabin/conda_auto_activate.bat, conda/shell/condabin/conda_hook.bat, conda/shell/condabin/deactivate.bat, conda/shell/condabin/rename_tmp.bat
Split from #13837 since the simple cleanups aggregated into too many changes making the diff illegible.
**This PR has no logic changes.**
Changes here include:
- Replace `@REM` with the tidier `::`
- Format all DOS commands as uppercase
=> Standardize batch script comments and commands

conda/history.py, news/13960-history-file-parse-fix, tests/test_history.py
=> Improve `history` file parsing

conda/auxlib/logz.py, conda/common/io.py, conda/gateways/logging.py, news/13939-mask-token-logs, tests/gateways/test_logging.py
Tokens could leak in verbose logs as part of the networking messages (urllib3, among others). This adds the already existing `TokenURLFilters` to more handlers to prevent it.
=> Filter tokens from more logging calls

docs/source/user-guide/configuration/index.rst
Closes https://github.com/conda/conda/issues/13983.
https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/index.html was missing a doc link. I've added it.
=> Added missing doc link

conda/exports.py, conda/utils.py, news/14034-exports-deprecations, tests/test_exports.py, tests/test_utils.py
While working on https://github.com/conda/conda/pull/14029 a number of unused attributes in `conda.exports` and `conda.utils` were found. Marking the following for deprecation:
- `conda.exports.iteritems`
- `conda.exports.Completer`
- `conda.exports.InstalledPackages`
- `conda.exports.KEYS`
- `conda.exports.KEYS_DIR`
- `conda.exports.hash_file`
- `conda.exports.verify`
- `conda.exports.symlink_conda`
- `conda.exports._symlink_conda_hlp`
- `conda.exports.win_conda_bat_redirect`
- `conda.utils.win_path_to_cygwin`
- `conda.utils.cygwin_path_to_win`
- `conda.utils.translate_stream`
- `conda.utils.unix_shell_base`
- `conda.utils.msys2_shell_base`
- `conda.utils.shells`
=> Deprecate unused attributes in `conda.exports` & `conda.utils`

conda/base/constants.py, conda/base/context.py, news/14065-revert-13975, tests/test_create.py
Reverts #13975 after concerns raised in https://github.com/conda/conda/issues/12558#issuecomment-2245517955.
=> Revert #13975

tests/test_create.py
The `tests/test_create.py::test_override_channels[libmamba]` has been unusually flaky this week. This is an attempt to resolve the flakiness by switching channels & packages.
=> Refactor override_channels test

tests/cli/test_main_search.py
Update test to use new `anaconda.org/conda-test` access token.
Resolves #14114
=> Update `anaconda.org/conda-test` token

conda/deprecations.py
While debugging conda_build elevating an unexpected number of deprecation warnings (see https://github.com/conda/conda-build/actions/runs/10189443419/job/28187505660) found that `conda.deprecations.deprecated.constant`'s stack level was too low.
Before (the stack level incorrectly points to `conda.deprecations`):
After (the stack level correctly points to `conda.exports`):
Also took the opportunity to sync `conda.deprecations` with `conda_build.deprecations`.
=> Sync `conda.deprecations` with `conda_build.deprecations`

conda/exports.py, news/14118-deprecate-conda.exports.move_to_trash, tests/test_exports.py
Followup to https://github.com/conda/conda/pull/14094.
Identified while debugging conda_build elevating an unexpected number of deprecation warnings (see [conda/conda-build/actions/runs/10189443419/job/28187505660](https://github.com/conda/conda-build/actions/runs/10189443419/job/28187505660)).
Just another argument in favor of completing https://github.com/conda/conda/issues/12372 ASAP so we can catch this in the future.
=> Fix `conda.exports.move_to_trash` import

tests/env/utils.py
As found per https://results.pre-commit.ci/run/github/6235174/1722870797.R2bWTV95RSeXb_UuMz3xTw. Follow-up to #14077.
=> Add missing import in tests/envs/utils.py

conda/common/configuration.py, news/14149-fix-object-parameter-defaults, tests/common/test_configuration.py
=> Bug fix for `ObjectParameter` defaults

tests/cli/test_main_info.py
Replace `env_var` usage in tests/cli/test_main_info.py` with `monkeypatch.setenv`.
Xref https://github.com/conda/conda/issues/14095
=> `test_main_info.py`: Replace `env_var` with `monkeypatch.setenv`

docs/source/conf.py, docs/source/user-guide/getting-started.rst
=> Make version number dynamic for "Getting started" guide

conda/activate.py, conda/common/compat.py, conda/common/pkg_formats/python.py, conda/core/envs_manager.py, conda/core/initialize.py, conda/gateways/disk/read.py, conda/history.py, conda/misc.py, news/14144-deprecate-unused-compat, tests/core/test_initialize.py
Identified via test failures in conda-build (see https://github.com/conda/conda-build/actions/runs/10511287074/job/29121920428?pr=5458) that we were still using deprecated codes in conda.
Split from #12771
Instead of outright deprecating `conda.common.compat.open` we opt to rename it to `open_utf8` with the understanding that `conda_utf8` can likely be deprecated once Python 3.15 comes around, see https://peps.python.org/pep-0686/.
=> Adjust `conda.common.compat.open` deprecation

.github/workflows/tests.yml, README.md
Added/updated the following badges:
- build/CI/tests badge to reflect the status of daily scheduled test (and enabled scheduled tests in workflow)
- remove unused images badge
- add logo to codecov badge
- add logo to release badge
- add Anaconda package badge
- add conda-forge package badge
Xref https://github.com/conda/conda-build/pull/5466
=> Update `README.md` badges

docs/source/user-guide/tasks/manage-environments.rst, news/14181-docs-platform
=> Document `--platform` flag for `conda [env]  create`

dev/start, dev/start.bat
Split from https://github.com/conda/conda/pull/13837 and efforts to refactor `activate` commands into argparse commands (similar to https://github.com/conda/conda/pull/14215).
=> Update `devenv` start scripts to also update shell scripts

.authors.yml
> Modifying the `AUTHORS.md` file isn't enough to correct this since that file is auto generated by `rever` during every release, we would also need to modify `.authors.yml`:
> 
> https://github.com/conda/conda/blob/aa0fb6f3ae669a5ade575d340555aa6a9f71ef5e/.authors.yml#L147-L156
> 
> While `rever` supports aliases and alternative names it does not offer a means of combining multiple GitHub IDs into one entry. This doesn't really matter though since the GitHub ID is only used when generating the next release's changelog entry, so we could do something like this:
> 
> ```yaml
> - name: Shaun Walbridge
>   email: shaun.walbridge@gmail.com
>   alternate_emails:
>     - 46331011+scdub@users.noreply.github.com
>   github: scw  # alternate: scdub
> ```
Followup to …
=> Combine duplicate Shaun Walbridge entries

conda/core/prefix_data.py, conda/core/subdir_data.py, news/replace-ext-end
See also https://github.com/conda/conda-package-handling/issues/251
=> Replace extension from end of string only

.github/workflows/tests.yml
`pytest-memray` is only available via `conda-forge` so we should be explicit about this.
=> Install `pytest-memray` from `conda-forge`

conda/cli/common.py, conda/cli/install.py, conda/cli/main_clean.py, conda/cli/main_create.py, conda/cli/main_remove.py, conda/core/link.py, conda/plugins/reporter_backends/console.py, conda/plugins/reporter_backends/json.py, conda/plugins/types.py, conda/reporters.py, news/14244-confirm-support-reporter-backends, tests/cli/test_common.py, tests/plugins/reporter_backends/test_console.py, tests/test_reporters.py
=> Add support for `confirm_yn` to reporter backends plugin hook

.github/workflows/tests.yml, conda/cli/install.py, conda/core/index.py, conda/core/prefix_data.py, conda/core/subdir_data.py, conda/misc.py, conda/plugins/manager.py, news/13880-lazy-index, tests/core/test_index.py, tests/core/test_prefix_data.py
Looks like we **do** need to load the entire prefix into the reduced index for the classic solver to work correctly:
https://github.com/conda/conda/blob/02929872735150e3fe0482364414441d55760f57/conda/core/index.py#L586-L589
We also discovered that we needed to restore the prefix cache handling in the reduced index for `--offline` tests to work correctly:
https://github.com/conda/conda/blob/22c416e45ceda37914889c0441576ae4635580fc/conda/core/index.py#L415-L421
Other changes done here (all optional improvements):
- correct `PrefixData`'s type annotation
- remove `Index.prefix_path` in favor of just setting `Index.prefix_data`
- implement `PrefixData` equality logic
Closes https://github.com/conda/conda/pull/14263
Closes https://github.com/conda/conda/pull/14270
Closes …
=> Load the entire local prefix into index

README.md, docs/source/conf.py, docs/source/index.rst, docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/configuration/admin-multi-user-install.rst, docs/source/user-guide/configuration/mirroring.rst, docs/source/user-guide/getting-started.rst, docs/source/user-guide/install/index.rst, docs/source/user-guide/install/linux.rst, docs/source/user-guide/install/macos.rst, docs/source/user-guide/install/windows.rst, docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/troubleshooting.rst
Closes #14225.
Refs #14217.
The landing page looks something like this now:
=> Explicitly note Anaconda's TOS, mention miniforge more, update landing page.

conda/base/context.py, docs/source/user-guide/configuration/free-channel.rst, news/14231-restore_free_channel
=> Mark `restore_free_channel` for deprecation.

conda/activate.py
=> Simplify activation's arg parsing error/help handling

conda/shell/etc/profile.d/conda.sh, news/14277-remove-__conda_reactivate-shell-function
The POSIX `__conda_reactivate` shell function is the same as saying `__conda_activate reactivate` so we opt to remove this duplicate code.
=> Remove `__conda_reactivate` shell function

conda/base/context.py, news/#14287-visual-tweaks
=> Fix minor visual issues in channel management deprecation notice

conda/base/context.py, conda/cli/main_config.py, news/14305-refine-deprecation-notice
Refs #14178.
**Before**
**After**
=>  Refine the deprecation warning about the channels prepopulation with `defaults`.

docs/requirements.txt
This version bump resolves an issue caused by the latest release of pydata-sphinx-theme.
=> Version bump for conda-sphinx-theme `0.2.1` -> `0.2.2`

conda/cli/main_search.py, tests/base/test_context.py, tests/cli/test_main_search.py
=> Add two new tests for two functions in conda.base.context; improve coverage

conda/core/package_cache_data.py, conda/plugins/types.py, conda/reporters.py, tests/test_reporters.py
Resolving pre-commit.ci failures that came up after resolving some merge conflicts.
=> pre-commit.ci fixes

.github/workflows/tests.yml
- Use cross-platform compatible cache on GHA Windows runners
- Use separate volume for high restore and save speed
Xrefs https://github.com/conda-incubator/setup-miniconda/pull/328 and https://github.com/conda/conda-build/pull/5082
- ~[ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?~
=> Improve caching on GHA Windows runners.

.github/workflows/tests.yml, tests/requirements-benchmarks.txt
With the `pytest-codspeed 3.0.0` release (https://github.com/CodSpeedHQ/pytest-codspeed/releases/tag/v3.0.0) and conda-forge feedstock update (https://github.com/conda-forge/pytest-codspeed-feedstock/pull/2) we can discontinue depending on a personal fork of `pytest-codspeed`.
=> Remove pytest-codspeed install from personal fork

conda/gateways/connection/__init__.py, conda/gateways/connection/session.py, conda/plugins/hookspec.py, conda/plugins/manager.py, conda/plugins/types.py, docs/source/dev-guide/plugins/request_headers.rst, news/14325-adding-request-headers-plugin-hook, tests/gateways/test_connection.py, tests/plugins/test_manager.py, tests/plugins/test_request_headers.py
=> Make request headers dynamic

conda/plugins/hookspec.py
Our `pluggy` hookspecs return iterables so we need to add a `yield from ()` to satisfy `mypy`.
Xref https://github.com/conda/conda/pull/14382#discussion_r1840302815
=> Add `yield from ()` to hookspecs to satisfy `mypy`

.github/workflows/tests.yml, recipe/meta.yaml
Xref https://github.com/conda/conda-build/pull/5483
=> Conditionally override version after cutting a release branch

conda/activate.py, news/14397-fix-invalid-args-error-message, news/14398-fix-invalid-args-error-message, tests/test_activate.py
=> Fixes bug for invalid arguments to `conda shell.posix` (and others)

pyproject.toml
This is a workaround for the failure introduced in #14412.
=> Ignore UP031.

conda/shell/etc/profile.d/conda.sh, news/14455-revert-14277
Reverts https://github.com/conda/conda/pull/14277
=> Revert removal of `__conda_reactivate`

conda/base/context.py, conda/common/_os/osx.py, conda/common/compat.py, conda/plugins/virtual_packages/archspec.py, conda/plugins/virtual_packages/linux.py, conda/plugins/virtual_packages/osx.py, news/14449-osx-vpkg, tests/plugins/test_virtual_packages.py
- Closes https://github.com/conda/conda/issues/14448
- Closes https://github.com/conda/conda/issues/13832
=> Virtual packages fixes for `__archspec`, `__osx` and `__linux`

conda/models/channel.py, news/14481-url-decode, tests/models/test_match_spec.py
Comes from https://github.com/mamba-org/mamba/issues/3737
=> Decode parts of URLs passed as MatchSpecs

conda/base/context.py
Fixes: #14479 
- This was not tested because it is extremely difficult to test. During the development of this feature, I manually QA tested this according to the bug initially discovered here: https://github.com/anaconda/conda-anaconda-telemetry/issues/87
=> Reinitializes plugin settings in `reset_context`

.github/workflows/tests.yml, .readthedocs.yml, conda/base/context.py, conda/shell/etc/profile.d/conda.sh, news/14517-fix-powershell-null, tests/test_activate.py, tests/test_shell.py
Fixes: #14514 
Fixes: #14292
This is a suggested proposal for addressing the two issue above. I have tested this locally so far with PowerShell 7.5.0 and it appears to be working. Needs more extensive testing though.
=> Fixes PowerShell 7.5.0 environment activation

docs/requirements.txt
Fixes a bug that prevents the menu from working when looked at with mobile view.
=> Bump conda-sphinx-theme version to 0.2.3

.github/workflows/tests.yml
Xref https://github.com/anaconda-distribution/installers/pull/881
Xref https://github.com/docker/setup-qemu-action/issues/188#issuecomment-2604322104
=> Fix QEMU segmentation fault

.pre-commit-config.yaml, tests/test-recipes/linux-fake/repodata.json, tests/test-recipes/noarch/repodata.json, tests/test-recipes/osx-fake/repodata.json, tests/test-recipes/win-fake/repodata.json
Extracted from https://github.com/conda/conda/pull/14547
Pretty-format repodata.json for better git diff, see https://github.com/conda/conda/pull/14547 and https://github.com/conda/conda/pull/14504
=> Pretty-format `repodata.json` for better `git diff`

docs/source/user-guide/tasks/manage-environments.rst
Hi! I was setting up a new env, and I found this small typo. I figured it'd take a quick moment to fix it since it took me a moment to spot it myself 😆
Thanks for the good work that you do!
Before
After
=> Fixing a quick formatting error

conda/cli/main_env_list.py, conda/cli/main_info.py, conda/common/compat.py, conda/env/specs/__init__.py, conda/instructions.py, conda/testing/__init__.py, conda/testing/integration.py, news/14604-remove-deprecations
Removes:
- `conda.cli.main_info.get_info_dict(system)`
- `conda.common.compat.encode_arguments`
- `conda.env.specs.detect(remote_definition)`
- `conda.instructions.PREFIX`
- `conda.testing.integration.FORCE_temp_prefix`
- `conda.testing.integration.tempdir`
- `conda.testing.integration.create_temp_location`
- `conda.testing.integration.make_temp_package_cache`
- `conda.testing.integration.make_temp_channel`
- `conda.testing.integration.make_temp_env`
- `conda.cli.main_env_list.execute`
- `conda rename --force`
Depends on:
- https://github.com/conda/conda/pull/14600
- https://github.com/conda/conda/pull/14601
- https://github.com/conda/conda/pull/14603
=> Remove simple deprecations for 25.3

conda/testing/helpers.py, tests/cli/test_env.py, tests/core/test_solve.py, tests/test_create.py
A potential solution for 🔴 tests in https://github.com/conda/conda/issues/14759
Ideally we would use `pytest-rerunfailures` + `pytest-xdist` (see ["Recover from hard crashes"](https://github.com/pytest-dev/pytest-rerunfailures#recover-from-hard-crashes)), but I didn't find a clean way to do that for only a few tests (we'd need to run _everything_ under xdist). Also [we'd miss the stdout/stderr output](https://pytest-xdist.readthedocs.io/en/stable/known-limitations.html#output-stdout-and-stderr-from-workers). Instead we just need to check for a sentinel env var.
=> Run known flaky tests in subprocess

conda/env/env.py, conda/env/specs/yaml_file.py, news/15237-dont-parse-whole-environment-as-part-of-can_handle, tests/env/test_create.py, tests/env/test_env.py
Previously, the environment.yml plugin would produce duplicate errors for invalid keys. For example, consider  the environment.yml:
```
channels:
- anaconda
dependencies:
- nltk
variables:
VARIABLE: value
prefix: /something/miniconda/envs/test
wrong: surely
```
would produce:
```
$ conda env create --file tests/env/support/test.yml --env-spec environment.yml
EnvironmentSectionNotValid: The following section on 'tests/env/support/test.yml' is invalid and will be ignored:
- wrong
EnvironmentSectionNotValid: The following section on 'tests/env/support/test.yml' is invalid and will be ignored:
- wrong
. . .
```
This change makes the message only appear once:
```
$ conda env create --file tests/env/support/test.yml --env-spec environment.yml
EnvironmentSectionNotValid: The following section on …
```
=> Don't load environment.yml as part of its can_handle
