conda/conda

conda/shell/etc/profile.d/conda.sh
Also:
- Make conda.sh less non-POSIX complaint by removing the use of '=='
```
In conda/shell/etc/profile.d/conda.sh line 57:
if [ "${_CE_CONDA+x}" == "condax" ]; then
^-- SC2039: In POSIX sh, == in place of = is undefined.
In conda/shell/etc/profile.d/conda.sh line 58:
if [ "${PATH+x}" == "x" ]; then
^-- SC2039: In POSIX sh, == in place of = is undefined.
```
- Escape dirname, so that aliases/functions don't surprise the end user
Fixes https://github.com/conda/conda/issues/8474
=> Uncomplicate logic to avoid ':' at end of PATH

conda/gateways/disk/create.py
conda.core.index.get_index will fail with a AttributeError without this unused
import
=> add import to fix conda.core.index.get_index

conda/exports.py
Long term symlink_conda could be replaced by putting up conda.bat within condabin to PATH
=> Point conda.bat to condabin instead of version in Scripts for symlink_conda.

conda/common/compat.py
This PR updates an import from `collections` to remove a `DeprecationWarning` when running on python3.7.
=> Updated import from collections for python>=3.3

conda/base/context.py
Do not allow the number sign (hash, pound sign) character in environment names
as it causes issues.
=> disallow number sign character in prefix names

tests/conda_env/test_cli.py
When a prefix is passed to `run_env_command` with `Commands.ENV_CREATE` it should be passed to `-n`, not `-f`.  Fixed that and corrected tests calling that helper method.
Noticed while investigating #8192.
=> [tests] conda_env create tests confuse -f and -n

tests/test_create.py
moto dependencies are not available for the win-32 platform
=> disable test_legacy_repodata on win-32

conda_env/installers/pip.py
This is intended as a fix for #8541.
The `-U` flag ensures that pip-managed packages are always upgraded (within the requirements) when `conda env update` is used.
Adding the flag here causes it to always be used, even for `conda env create`, but in that case the `-U` has no effect because the package is not already installed.
This strikes me as the simplest solution. If using `pip install -U` with `conda env create`, or any other time `_pip_install_via_requirements` is called, were a problem, a more complicated solution could be built in which the `-U` is added only when the call is coming from `conda env update`. However, I don't think that's necessary.
=> Add upgrade flag to pip installer

conda/_vendor/auxlib/compat.py, conda_env/pip_util.py
Recursive requirements.txt files (that contain
`-r another/requirements.txt`) fail when installing in python2.7.
Regression occurred in the 4.8.9 release, in this patch:
https://github.com/conda/conda/commit/1dc77abacd06eb9bce806ca420068d05309b0cd2#diff-4669597423f213078070c1ee8b92a606R66
Also raise an exception if the pip subprocess fails, so errors like this
don't get missed (in eg CI).
Fixes #8561 .
=> 🐛 fix installing py27 pip requirements files

conda/shell/condabin/Conda.psm1
Reported by QA.  This function shows up in an error report when Anaconda Powershell Prompt is opened.
=> fix missing powershell function export

conda/activate.py
This PR changes the way activated environments are displayed in shell prompt for stacked environments.
Before:
```
(base) $ conda activate envA
(envA) $ conda activate --stack envB
(envB) $ conda activate --stack envC
(envC) $ conda deactivate
(envB) $ conda deactivate
(envA) $ conda deactivate
(base) $
```
After:
```
(base) $ conda activate envA
(envA) $ conda activate --stack envB
(envA,envB) $ conda activate --stack envC
(envA,envB,envC) $ conda deactivate
(envA,envB) $ conda deactivate
(envA) $ conda deactivate
(base) $
```
It also correctly handles reactivation, or deactivation through activating previous environments:
```
(base) $ conda activate envA
(envA) $ conda activate --stack envB
(envA,envB) $ conda activate --stack envC
(envA,envB,envC) $ conda activate envC
(envA,envB,envC) …
```
=> Use comma-separated env names in prompt for stacked env

conda/activate.py, conda/models/version.py, setup.cfg, tests/test-recipes/activate_deactivate_package/meta.yaml, tests/test-recipes/activate_deactivate_package/src/etc/conda/activate.d/activate.bat, tests/test-recipes/activate_deactivate_package/src/etc/conda/activate.d/activate.sh, tests/test-recipes/activate_deactivate_package/src/etc/conda/deactivate.d/deactivate.bat, tests/test-recipes/activate_deactivate_package/src/etc/conda/deactivate.d/deactivate.sh, tests/test_activate.py
I think PATH can be treated differently on deactivation since deactivation scripts might depend on stuff that exists in it. 
Should resolve https://github.com/conda/conda/issues/8393
=> Export PATH prior to deactivate

conda/cli/main_config.py, conda/common/configuration.py, conda/common/logic.py, conda/resolve.py
This is a review for gh-8248.
- moves the SAT solver choice from `conda.common.logic` into `conda.resolve` to avoid importing from `conda.base` into `conda.common.
- adds the choices for enum-based configuration parameters to error messages and replaces `auxlib`'s `TypeCoercionError` with a `CustomValidationError`. With that change we get the following instead of nasty tracebacks:
```
$ conda config --set sat_solver asdf
CustomValidationError: Parameter sat_solver = 'asdf' declared in --set parameter is invalid.
'asdf' is not a valid SatSolverChoice
Valid choices for sat_solver: 'pycosat', 'pycryptosat', 'pysat'
$ CONDA_SAT_SOLVER=asdf conda config --show sat_solver
CustomValidationError: Parameter sat_solver = 'asdf' declared in <<merged>> is invalid.
'asdf' is not a valid …
```
=> review gh-8248 sat solver choice

conda/cli/install.py, conda/common/compat.py, conda/compat.py, conda/core/solve.py, conda/exports.py, conda/gateways/disk/read.py, conda/resolve.py, dev/start, tests/core/test_solve.py, tests/test_create.py
when running conda install, we should try to keep all other deps (those not explicitly specified) frozen.  This should be very fast, relative to having them considered in the solve.
This behavior already existed with the ``--freeze-installed`` or ``--no-update-deps`` CLI arguments, but this puts that behavior as the initial default, with a fallback to the old, full solve if that returns an unsatisfiable result.
=> fast frozen solve

conda/resolve.py, tests/test_create.py
This shifts the sort introduced in #8117 into get_reduced_index, so that it applies to more tests.  It also implements a new potential optimization: only add specs that have some overlap with the precs found for any explicit specs.  In other words, do not add a package if it conflicts with an explicit spec.
Conversion of sets to tuples is done to preserve order.
=> reduce index based on explicit specs further

conda/core/initialize.py
fixes https://github.com/conda/conda/issues/8590
According to this issue:
https://github.com/fish-shell/fish-shell/issues/3993
you can not just eval a script in fish. The proper way to do this
is apparently to pipe the output to source.
=> Fix fish activation

conda/gateways/disk/__init__.py
I'm currently setting up a multiuser installation where the user's home directories are stored on [AFS](https://en.wikipedia.org/wiki/Andrew_File_System). On this system running `chmod 2775` fails with a permission error. This prevents the package and environment directories from being created.
This PR avoid the issue by silently ignoring the error.
=> Allow setting setgid to fail when making directories

conda/core/package_cache_data.py, conda/core/subdir_data.py, conda/gateways/disk/create.py, conda/gateways/disk/permissions.py, conda/history.py, tests/gateways/disk/test_permissions.py
I'm currently setting up a multiuser conda installation on a distributed read only filesystem ([CVMFS](https://cernvm.cern.ch/portal/filesystem)). This currently fails to skip the root environment as the error raised is `EROFS` ("Read-only filesystem") instead of `EACCES` or `EPERM`.
My issues were with `create_envs_directory` and `create_package_cache_directory` but I've grep-ed though and added it an a few other places as well.
I've also fixed a minor typo in the tests.
=> Handle errors from read only filesystems

conda/common/logic.py
In debugging conda slowness on my computer, I noticed in the debug logs (-vvv) that it seemed like we had an infinite loop:
```
TRACE conda.common.logic:LinearBound_(708): Eliminating 146/146 terms for bound violation
TRACE conda.common.logic:minimize(865): Bisection attempt: (1,0), (807+0) clauses
TRACE conda.common.logic:minimize(869): Bisection failure, new range=(1,0)
TRACE conda.common.logic:LinearBound_(708): Eliminating 146/146 terms for bound violation
TRACE conda.common.logic:minimize(865): Bisection attempt: (1,0), (807+0) clauses
TRACE conda.common.logic:minimize(869): Bisection failure, new range=(1,0)
```
This PR attempts to break out of the bisection loop if the range is empty.  I think this is especially helpful in the presence of inconsistent environments (my root env is …
=> break out of minimization when bisection has nowhere to go

conda/core/link.py
This was already done for the channel name of the package to unlink
in #8379, but the linking package channel name was missed.
If not handled gracefully, this exits with a TypeError when e.g.
updating a package from a 3rd party channel with a custom URL.
=> Handle None values for link channel name gracefully

docs/source/user-guide/configuration/use-condarc.rst
Indicate that the configuration options on this page are not exhaustive, and refer the user to `conda config --describe` for a complete list of options.
=> Add reference to conda config --describe in docs

docs/source/user-guide/concepts/channels.rst, docs/source/user-guide/configuration/enable-tab-completion.rst, docs/source/user-guide/configuration/free-channel.rst, docs/source/user-guide/configuration/index.rst, docs/source/user-guide/configuration/use-condarc.rst, docs/source/user-guide/tasks/manage-channels.rst, docs/source/user-guide/troubleshooting.rst
This PR adds in the free channel page detailing its removal from defaults, minor grammatical/formatting edits, and the reorganized .condarc doc with free channel info.
=> Removing free channel from defaults

conda/core/index.py, docs/source/user-guide/concepts/channels.rst, docs/source/user-guide/tasks/manage-virtual.rst, tests/core/test_index.py, tests/data/index.json
=> establish standard leading __ for virtual packages

conda/common/pkg_formats/python.py, tests/common/pkg_formats/test_python.py
This patch allows the correct parsing of required version strings like ">=1.0.0-beta.1,<2.0.0", which appears in PyPI packages like `eth-keyfile==0.5.1` in the wild.
Unit test case included.
=> Fix for #8687: modified PyPI spec parsing regex to parse hyphenated versions correctly.

conda.recipe/run_test.bat
This is not really the greatest fix, but we need the CI green so that we can save time on actually checking it for when it's really broken.
=> skip env creation in run_test.bat on appveyor (permissions issue)

docs/source/api/python_api.rst
It was referring to nonexistent "conda.api.python_api" module.
=> Fix python_api.rst page title

conda/core/path_actions.py
Target prefix override applies to entry points as well as replacements
of standard files.
=> target prefix override for entrypoints

conda/shell/condabin/_conda_activate.bat
Not the most elegant solution, but this should resolve issue #8733 using two approaches:
1. Use %RANDOM% twice for a more "unique" file name.
2. Create the file immediately using `TYPE NUL`. This is much faster than letting the conda command create the file, so less likely to have a race condition with the `@IF EXIST "%UNIQUE%" goto :tmpName` line.
=> Resolve issue #8733

conda/core/initialize.py, tests/core/test_initialize.py
tcsh/csh do not support shell functions. So to setup conda the conda.csh
script must be sourced.
=> Use tcsh/csh initialization script

appveyor.yml, tests/test_create.py
conda.exe does not do any special PATH insertion stuff, so libarchive and friends can be missing.  This should fix it.
=> rework calls on appveyor a bit to help 32-bit win work

conda/base/context.py
This seems to be confusing people more than helping them.  Let's get rid of it.  Some people will be slower, but that's up to them.
=> remove warning about conda-build needing an update to use new format

CONTRIBUTING.md
The Windows dev env setup steps are not in correct order.
=> Fix the checkout step in the Windows dev env setup instruction

conda/resolve.py
Include target and optional information in list of specs which are
solved for.
Include the requested, optional, missing and all other specs in the
debugging information.
=> add additional debugging info to Resolve.solve

conda/core/subdir_data.py, tests/core/test_subdir_data.py, tests/test_misc.py
This fixes a problem with Navigator where the front tile screen would be mostly empty.  Navigator collects the possible tiles there by looking at repodata caches, and it computes the filenames it expects there without the filename in the url.
=> only add repodata fn into cache key when fn is not repodata.json

conda/core/solve.py
Historic specs should not be considered with the same priority as
explicit specs. By adding a target to historic specs they are still
included as constrains but not optmized at the same level as explicit
specs.
=> add target to specs from historic specs

conda/common/path.py, conda/utils.py
Fixes #8908 
When changing python version, compile_multiple_pyc() is run for noarch packages which ultimately calls wrap_subprocess_call() after packages (setuptools) have been unlinked/linked and are no longer importable. This change works because shutil is included in python.
=> Fix issue where python version can't be changed in base env with noarch packages

conda/cli/conda_argparse.py, conda/cli/install.py, conda/core/solve.py, tests/core/test_solve.py, tests/helpers.py
* do not freeze packages unless in FREEZE_INSTALLED mode
* add a --update-specs argument to conda install/update which opts out of all freezing behavior
* fallback to UPDATE_SPECS mode if no solution is found in FREEZE_INSTALLED mode
=> Address issue with aggressive freezing of packages

conda/core/subdir_data.py
Prevents later channels from clobbering early channels
=> report results of query_all in order

conda/core/index.py
Add the local package to the index with the a canonical channel set to
the URL if the channel information of the local packages does not match
that of the remote package.
Fixes cases where each channel in a multi-channel has a package with the
same subdir, name, version and build_number.
closes #8302
=> add prefix pkg to index if channels do not match

docs/source/user-guide/getting-started.rst
In 'Managing Python', use the same differentiation between pre-4.6 and newer versions of activating an environment as in 'Managing packages'
=> Align 'Managing Python' with 'Managing packages'

conda/shell/condabin/_conda_activate.bat
This may or may not make https://github.com/conda/conda/issues/8733 less likely depending on how if/else is implemented under the hood, but seems a bit cleaner either way.
=> Small refactor of _conda_activate.bat

conda/core/solve.py, conda/models/records.py
With the `add_pip_as_python_dependency` config parameter set to False, conda was removing setuptools after a `conda update conda` command, leaving things broken.  This was happening because the run_constrains entry came after the depends entry, and the run_constrains entry made the setuptools constraint optional, leading to its removal.
=> fix setuptools being removed due to conda run_constrains

conda/common/pkg_formats/python.py, tests/common/pkg_formats/test_python.py
Currently the PYPI version regex matcher in conda does not support local version identifiers as defined here: https://www.python.org/dev/peps/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions . The local version spec allows you to add something like: `'1.2.1+<githash>'`. In some internal environments (such as ours) local versions are occasionally used, and so this breaks our sharing of conda environments using `conda env export`.
This patch adds '+' to the `PARTIAL_PYPI_SPEC_PATTERN` along with an additional unit test.
I just signed the CLA, but I'm not sure how long it take to propagate :).
=> Add support for local version specs in PYPI installed packages.

conda/core/package_cache_data.py
This fixes https://github.com/conda/conda/issues/9034. The issue is that for @EXPLICIT packages, the md5 is initially None, so conda would end up not using existing packages in the cache.
=> Fix https://github.com/conda/conda/issues/9034

conda/core/package_cache_data.py
This is related to https://github.com/conda/conda/issues/9034. It is the reason why there is different behavior for no packages missing from the cache (where cache_actions is false and the code returns early) versus one or more packages missing from the cache.
=> Fix return condition in package_cache_data

conda/base/context.py
This uses a new attribute in conda-package-handling to determine whether or not libarchive is present.  CPH now has a fallback path for people who are having libarchive problems.
CPH PR: https://github.com/conda/conda-package-handling/pull/41
That will constitute CPH 1.4.0
=>  add libarchive_enabled attr from cph into use_only_tar_bz2

conda/cli/install.py, tests/cli/test_cli_install.py
Didn't account for conda create in this..
=> ensure unsat hints are generated when creating environments

conda/base/context.py, conda/common/io.py, conda/core/link.py, conda/core/package_cache_data.py, conda/core/solve.py, conda/core/subdir_data.py, conda/gateways/disk/create.py, conda/gateways/disk/read.py, conda/models/records.py, tests/base/test_context.py, tests/cli/test_cli_install.py, tests/core/test_solve.py, tests/test_resolve.py
menu creation and removal was happening in parallel with unlinking/linking.  This meant that
menuinst might not have the python executable it needed to do its thing.
This also refactors the loops stuff here to do fewer runs through the same loop.
=> serialize menu creation

docs/source/user-guide/concepts/pkg-specs.rst
In response to this issue: https://github.com/conda/conda/issues/9051
And taking the content from here: https://github.com/conda/conda/blob/master/conda/models/version.py#L47
Note: in addition to verifying this content, I need help identifying if I coded everything correctly. The blob version uses ' around terms that are normally identified as code (which is `` in RST). I found a few places where I think the ' is intentional but I'm unsure. Can you please review this and make sure that what I've put in as coding is accurate and if any of my inclusions of ' are problematic or missing?
=> Added version ordering info

conda_env/cli/main_export.py
When neither -p nor -n is given to "conda env export", assume that a
path seperator in CONDA_DEFAULT_ENV should be interpreted as a prefix
path nor an environment name.
closes #9128
=> detect prefix paths when -p nor -n not given

docs/source/user-guide/configuration/use-condarc.rst
From this PR: https://github.com/conda/conda-docs/pull/352
Please take special care to review the change to the URLs in the channel_alias section to ensure they are accurate.
=> Added info about channel_alias and default_channels

conda/core/envs_manager.py, docs/source/user-guide/tasks/manage-environments.rst
"conda env list" previously behaved differently on Windows and Unix -
on Unix, administrators got a list of all environments on the system,
and regular users saw only their environments. On Windows, however,
all users saw all environments.
This change standardizes both platforms to use the Unix behavior.
Administrators see all environments, and standard users only see
their own environments.
Closes #9165
=> Standardize "conda env list" behavior between platforms

conda_env/cli/common.py, conda_env/cli/main.py, conda_env/cli/main_create.py, conda_env/cli/main_update.py, conda_env/installers/conda.py, conda_env/installers/pip.py, conda_env/pip_util.py, tests/conda_env/test_cli.py, tests/conda_env/test_pip_util.py
This PR adds json output to the `conda env create/update` commands.
Some things I'm not sure about:
1. I had to `import conda.exports` in `conda_env/cli/main.py`. Otherwise when it is imported in `conda_env/pip_util.py` it resets the context.
2. In my tests, if I keep the same environment name "env-1", each test passes when I run them individually. But they all fail when run together (running `pytest -v tests/conda_env/test_cli.py::IntegrationTests`). I had to use a different env name for each test. The `setUp` and `tearDown` fixtures seem to run properly. At one point I saw that when trying to run pip in the environment `env-1/bin/python` didn't exist. There was only the `env-1/conda-meta` directory. Could some files be deleted by the fixture after the test starts?
Anyway I'm quite sure …
=> Add json output to conda env create/update

docs/source/user-guide/install/macos.rst
We are installing Miniconda for MacOS but the linkt to download the lastest MacOS version was pointing to the Linux version.
=> Update download link (silent mode)

conda/core/initialize.py
=> Use space for csh setenv in conda init

conda/cli/conda_argparse.py
Btw, I don't get it when it says "look in that directory first". Is it right? Or is there a grammar issue/typo?
=> "source activate" -> "conda activate" in create CLI help

conda/base/context.py, conda/gateways/connection/__init__.py, conda/gateways/connection/session.py
#9312  
``Retry`` class can pass to ``HTTPAdapter`` instead of passing parameter ``max_retries``.
There is an option ``backoff_factor`` in ``Retry`` which can determine the time between two attempts.
I add an option ``remote_backoff_factor`` in context and use ``Retry`` class for ``HTTPAdapter`` instead in order to pass the option ``backoff_factor`` in ``Retry`` class.
Because I cannot reproduce the error "403", I test in the following situation:
1. Run ``conda config --set remote_max_retries 3`` and ``conda config --set remote_backoff_factor 1`` before downloading
2. Execute ``conda install <package>``
3. Before asking ``proceed([y]/N)`` , use ``iptables`` to disable network
4. Enter ``y`` to proceed
5. It waits for about 5 seconds and raised an uncaught exception
*   Originally, …
=> Retry download

conda/shell/etc/profile.d/conda.sh
Users can now modify the PATH variable in the env_vars.sh script (#8464), which is useful for managing non-conda binaries. It is all too tempting to store your old path as $OLDPATH in the activation script, and set `PATH="$OLDPATH"` in the deactivation script. But this won't have the intended effect because conda.sh already uses that name. This modest PR proposes a less clash-prone name.
Hopefully this will save someone else a day of total confusion.
=> Avoid clash-prone OLDPATH variable name in activation script

conda/models/records.py
Change combined_depends from a memoizedproperty to a property.
Memoization was causing problems with conda-build when building against
a matrix using a conda_build_config.yaml file,
c.f. conda/conda-build#3735
=> do not memorize PackageRecord.combined_depends

docs/source/user-guide/tasks/manage-environments.rst
Fixes a typo in the Using Pip section that has already been corrected in [the original blog post](https://www.anaconda.com/using-pip-in-a-conda-environment/). Adds syntax highlighting to flags.
=> Docs correction

docs/source/user-guide/configuration/enable-tab-completion.rst
I do not know what happened to the issue 415 in the `conda-docs` repo (it might have gotten lost in the migration of documentation to this repository), but the link is broken.
Perhaps a new link to https://github.com/conda/conda/issues/3140 is warranted?
And is the existing Fish autocompletion in https://github.com/conda/conda/blob/master/conda/shell/etc/fish/conf.d/conda.fish missing documentation? Reference: https://github.com/conda/conda/issues/8191
Also, this page will need to be updated if #9158 (rebased version of #9139) is merged for new Bash tab completion in the v4.8.0 release. See https://github.com/conda/conda/issues/9178
=> Remove broken link in tab completion documentation

conda/common/url.py
Addresses https://github.com/conda/conda/issues/9278 at least partially.
There are a number of code paths that call `maybe_unquote` to construct exception messages that are logged. Some of these code paths include the password / auth header, which we want to strip out before logging.
Opening for discussion. There may be a better way, likely involving a refactor of how URLs are passed around (not as strings).
=> Remove auth from maybe_unquote

conda/cli/conda_argparse.py
Either a missing period or missing spaces that caused string concatenation where words were being incorrectly conjoined.
=> Touch up help for commands that mention CONDA_EXE

docs/source/user-guide/install/rpm-debian.rst
Installing third party keys to /etc/apt/trusted.gpg.d/ is discouraged
because of security reasons. The commands follow the scheme proposed in
https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry
=> Put conda keyring to /usr/share/keyrings in Debian

conda/cli/python_api.py, tests/cli/test_common.py, tests/cli/test_conda_argparse.py
Addresses https://github.com/conda/conda/issues/9329
=> Fix calling python api run_command with list and string arguments

docs/source/user-guide/configuration/use-condarc.rst
=> Typo in condarc key envs_dirs

conda/shell/etc/profile.d/conda.sh
Restore return statement. Should address  #9531
=> #9531 Fix __conda_activate function to correctly return exit code

conda/gateways/disk/update.py
This fixes #8243 which is the same issue that was fixed in another part of the code by #7180.
(Dupe of  #9463, I goofed that one up.)
=> Fix #8243 incorrect chown call

conda/shell/condabin/_conda_activate.bat
bugfix for  #8628
The cause of the problem:
_conda_activate.bat uses %RANDOM% env var to create a unique temp file.
That isn't very random, details here: https://devblogs.microsoft.com/oldnewthing/20100617-00/?p=13673
When starting multiple processes at the same time, they will try to create and use the same temp file.
The fix:
Create a random directory instead of a file, and check if the creation failed instead of checking the existence of the directory. Only one of the started processes will succeed, the rest will retry.
=> Fix running conda activate in multiple processes #8628

conda_env/cli/main_create.py
This PR adds networking args to `conda env create` as requested by https://github.com/conda/conda/issues/9523
=> add networking args to conda env create

conda_env/installers/conda.py
Implement fast frozen solve for `conda env update`
In [4.7 release](https://www.anaconda.com/how-we-made-conda-faster-4-7/) there was introduced the feature of locking down packages that are not involved in the solution, so that the solver’s problem is simpler, and the install commands are run faster.
Thus, `conda install` has option `--freeze-installed` (or `--no-update-deps`) enabled by default with a fallback to the full solve method in case of an unsatisfiable error.
See the corresponding PR: https://github.com/conda/conda/pull/8620.
In this PR I'm trying to apply the same logic to `conda env update` command which is effectively rather similar to `conda install`. This speeds up `conda env update` by preventing existing packages from unnecessary updating.
I'm not sure whether some …
=> Implement fast frozen solve for `conda env update`

conda/__init__.py, conda/_vendor/frozendict.py
This fixes issues when conda config has maps (such as conda-build) which leads to problems with `conda config --json`, which crashes navigator.
=> make frozendict JSON serializable

conda/core/solve.py, conda/resolve.py, tests/test_create.py, tests/test_resolve.py
This is primarily used for Navigator, to error out faster when a user tries to install rstudio in an env with an incompatible Qt.  The unsatisfiable_hints setting is a condarc setting, and can also be set with CONDA_UNSATISFIABLE_HINTS env var.  It defaults to True.  Setting it to False will enable this fast-error behavior.
=> error out faster when unsatisfiable_hints message set to False

docs/source/api/index.rst, docs/source/glossary.rst, docs/source/index.rst, docs/source/user-guide/concepts/conda-performance.rst, docs/source/user-guide/concepts/environments.rst, docs/source/user-guide/concepts/installing-with-conda.rst, docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/concepts/pkg-specs.rst, docs/source/user-guide/configuration/admin-multi-user-install.rst, docs/source/user-guide/configuration/disable-ssl-verification.rst, docs/source/user-guide/configuration/non-standard-certs.rst, docs/source/user-guide/configuration/use-condarc.rst, docs/source/user-guide/configuration/use-winxp-with-proxy.rst, docs/source/user-guide/getting-started.rst, docs/source/user-guide/install/download.rst, docs/source/user-guide/install/index.rst, docs/source/user-guide/install/linux.rst, docs/source/user-guide/install/macos.rst, docs/source/user-guide/install/rpm-debian.rst, docs/source/user-guide/install/test-installation.rst, docs/source/user-guide/install/windows.rst, docs/source/user-guide/tasks/create-custom-channels.rst, docs/source/user-guide/tasks/manage-conda.rst, docs/source/user-guide/tasks/manage-environments.rst, docs/source/user-guide/tasks/manage-pkgs.rst, docs/source/user-guide/tasks/manage-virtual.rst, docs/source/user-guide/tasks/use-conda-with-travis-ci.rst, docs/source/user-guide/troubleshooting.rst
Grammatical and formatting changes made after reviewing all of the conda docs.
=> January docs sweep

conda/models/match_spec.py
This fixes an issue that has been causing a traceback during `breadth_first_search_for_dep_graph()` such as:
```
File "/Users/fwaters/git/conda/conda/models/match_spec.py", line 766, in union
return '|'.join(options)
TypeError: sequence item 0: expected str instance, Channel found
```
Minimal repro:
```
conda install defaults::statistics defaults::python=3.7
```
=> account for channel in specs

conda/base/constants.py, conda/base/context.py, conda/models/enums.py
I built and started to use conda on ppc64 at work: https://gitlab.esss.lu.se/ics-infrastructure/conda4ppc64e6500
It would be nice to have this patch upstream.
=> Enable ppc64 support

conda/core/link.py
Fixes [9819](https://github.com/conda/conda/issues/9819)
Formatting is a little nicer by removing the byte encoding
On a Linux system:
=> resolve #9819 post-link script output formatting

.gitattributes, appveyor.yml, circle.yml, tests/test-recipes/activate_deactivate_package/meta.yaml, tests/test-recipes/activate_deactivate_package/src/etc/conda/activate.d/activate.bat, tests/test-recipes/activate_deactivate_package/src/etc/conda/deactivate.d/deactivate.bat, tests/test_activate.py, tests/test_create.py
Fix failing CI tests. Changes are scoped to the test code and CI configurations. The conda codebase is not modified.
Utilize a single PR to demonstrate CI tests pass prior to merge.
Disable the following tests (can be restored if deemed necessary/desirable):
- Linux: conda-build 3.10. Conda-build has a dedicated repo, CI testing should be done there.
- Windows: Python 2.7. The install steps fail and 2.7 is EOL. Disabled instead of working through the noise.
Issues of note:
- Unicode Paths on Windows (no surprise, right). Several tests in test_create.py fall on their face when handling unicode paths on Windows - even under Python 3. In all cases, failure is external to conda, with libarchive frequently appearing in the stack traces.  Address failures using the same approach as Python 2.7; …
=> Get CI Tests Passing

conda/models/version.py, tests/models/test_match_spec.py, tests/models/test_version.py
Openssl versions should sort e.g. [1.0.1, 1.0.1a, 1.0.1b] etc., however
this is incompatible with most other version sort conventions and therefore
conda sorts as [1.0.1a, 1.0.1b, 1.0.1]. The VersionOrder docstring
anticipates the need to anchor an openssl-like version sequence at
e.g. 1.0.1, and indicates that appending a dash to the version will
accomplish that goal. However dashes have never been allowed in versions
due to dashes being the delimiters for the legacy 'dist' string.
This commit modifies the anchoring functionality to be provided by
appending an underscore rather than a dash. Therefore a sort order
of [1.0.1_, 1.0.1a, 1.0.1b, 1.0.1] holds.
Note that previous versions of conda prior to this commit will blow up
with VersionOrder("1.0.1_") or MatchSpec("openssl=1.0.1_") being …
=> enable trailing '_' to anchor openssl-like versions

conda/models/match_spec.py, tests/models/test_match_spec.py
This fixes https://github.com/conda/conda/issues/9814
Instead of `split` we use `rsplit` to correctly parse a url. We also change the max split to 1 instead of 2
=> fix url parsing

appveyor.yml, tests/core/test_solve.py, tests/test_create.py
This PR enables Python 2.7 tests on Windows.
Notes:
- test_create.test_conda_downgrade throws a C runtime error which pops a modal dialog on the host and halts test execution. Spent some time trying trying to resolve, but made no progress. Restoring the skip for 2.7 on Windows seemed like a reasonable approach. Specific error message is _"R6034 An application has made an attempt to load the C runtime library incorrectly. Please contact the application's support team for more information"_.
- The combination of channels in the intsall step created a non-functional pytest environment. The default settings work. Did not dig into which channel caused the issue.
=> Enable Windows Py27 tests

conda/gateways/connection/download.py, conda/gateways/connection/session.py, conda_env/cli/main_create.py, conda_env/env.py, conda_env/installers/pip.py, conda_env/specs/__init__.py, tests/conda_env/test_cli.py, tests/conda_env/test_env.py
Fixes https://github.com/conda/conda/issues/5562
This allows for passing web addresses through to conda env create,
like the following:
conda env create -f https://domain.com/my-environment.yml
This uses the urllib module to download the file
and then passes things on as normal.
There are a few cases where we need to avoid explicit checks
about if this is a file or if we want to prepend the directory to the
filename.  In these cases we avoid these operations by checking if
the filename starts with "https://" or "http://"
=> resolve #5562 support creating conda environments from web addresses

docs/source/user-guide/install/rpm-debian.rst, docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
Since apt command-line was introduced in 2014, apt become a better way for user to install packages because users don't have to worry about shifting between apt-get and apt-cache. Therefore, I would suggest we to make this change in the conda project
=> Change apt-get to apt

conda/_vendor/cpuinfo.py, conda/base/constants.py, conda/base/context.py, conda/models/enums.py
Addressing : https://github.com/conda/conda/issues/9791
Initial code drop to enable support for `s390x`;
=> Initial code drop to enable support for s390x

conda/cli/conda_argparse.py
This improves the documentation for the `--channel` argument to `conda build`.
The `file://` syntax is not the only way to specify local
directories. It turns out that you can simply list an absolute or
relative path. This can come in handy when building with a Unix shell,
like git-bash, on Windows where drive letter and forward-/back-slash
conventions might lead to confusion due to the insertion of spurious
characters and/or protective escapes.
=> fixup the documentation for the --channel option

appveyor.yml, circle.yml
Codecov uploads are failing with an HTTP 400 client error.  This PR updates CI tests scripts to utilize the most up-to-date [codecov bash uploader](https://docs.codecov.io/docs/about-the-codecov-bash-uploader).
Moving to a newer version of pytest would address the problem as well, but using the bash uploader aligns with codecov [recommendations](https://github.com/codecov/example-python#whats-the-different-between-the-codecov-bash-and-codecov-python-uploader).
=> Fix failing codecov upload in CI test suite

conda/cli/main_info.py, docs/source/user-guide/configuration/non-standard-certs.rst
`requests` accepts `CURL_CA_BUNDLE` in addition to `REQUESTS_CA_BUNDLE` per https://github.com/psf/requests/blob/2b3436e0e7831676044b57f6f2cc9eb7c188293e/requests/sessions.py#L707 so list that in troubleshooting details.
=> List CURL_CA_BUNDLE also

conda/cli/main_remove.py, tests/test_create.py
Add check to prevent `conda remove` from deleting prefixes (i.e.,
directories) that do not look like conda environments.
Fixes #9755
=> Prevent `conda remove --all` from deleting non-environments

circle.yml, conda/cli/main.py, tests/test_cli.py
Addresses #9599 by handling the namedtuple returned from conda.gateways.subprocess.subprocess_call.
Also, introduces three new "conda run" unit tests:
- returns an int
- properly returns zero exit codes
- properly returns non-zero exit codes
These three tests fail with conda 4.8.2 and pass with this PR
=> set errorlevel when 'conda run' exits (Resolves #9599)

conda/cli/main_create.py, tests/test_create.py
=> Prevent `conda create -d -y` from destroying existing environments

conda/core/solve.py, tests/test_create.py
Send "inconsistent environment" warning to STDERR instead of STDOUT.
=> fix #9737 --json with inconsistent environment

docs/source/user-guide/tasks/manage-environments.rst
The documentation made it appear as if there will always be a version of Python included in the environment.
This might have been the case in the past; currently it is possible to create an environment without Python at al.
See #9982
=> Clarify that Python is not by default included

conda/common/_logic.py
Detected bug while migrating python 2.7 windows unit tests to Azure Pipelines. Previous CI platform ran windows unit tests in a 32-bit environment which does not exhibit this bug.
Recall, python 2 has int and long types, while python 3 has only int. logic.py contains int specific logic which does properly handle longs.
sys.maxsize is an int on win-32 platform, but a long on win-64. This change uses sys.maxint when running under python 2, and sys.maxisze otherwise.
(cherry picked from commit d1aecbdc98537d36f6de9f664606360a1414aa5c)
Split from PR #9954 per @mcg1969 request
=> Fix bug in python 2.7 64-bit platforms

conda_env/cli/main_export.py
Conda's cli command `conda env export` yields a YAML with an extra newline, and that's being an issue due to empty newline warnings on a CVS like Git.
I've wrote a solution that fixes it.
This is the line of code `stdout_json(env.to_dict()) if args.json else print(env.to_yaml())`, the problem I see is happening due to the `print()` function default behavior.
From Python 3 docs, [print()](https://docs.python.org/3/library/functions.html#print) accepts a `end` keyword argument, which determines the last character to be printed, setting it to `''` empty string to prevent extra newlines.
Following the [code source](https://github.com/conda/conda/blob/master/conda_env/cli/main_export.py#L115) to the [YAML dumper](https://github.com/conda/conda/blob/e9a50561880696e57ba80472dce332e08e58ee0b/conda …
=> Removed extra newline from conda env export

docs/source/user-guide/tasks/create-custom-channels.rst
The _Creating custom channels_ doc refers to "using a `file://` URL",
and the conda code uses `urllib.parse.urlsplit` to parse 'file://'
channel references.
A proper `file://`-URI-based reference to a local (linux) file should
include 3 back-to-back slashes (`/`), but the example only uses 2.
The parsing actually goes slightly wrong when used as in the example,
though in a way that (accidentally) doesn't matter:
```
>>> from conda.common.url import path_to_url
>>> path_to_url('/opt/channel')
'file:///opt/channel'
>>> from conda.common.path import url_to_path
>>> url_to_path('file:///opt/channel')
'/opt/channel'
>>> url_to_path('file://opt/channel')
'//opt/channel'                         <= note extra leading slash
```
Fix the example to specify the file URL properly, and make a minor …
=> doc/custom channels: fix formatting and typo

conda_env/cli/main_export.py
Current behaviors of `conda env export` when no environment is activated:
* runs successfully when `--prefix <prefix>` is provided
* raises error when `CONDA_PREFIX` is set.
I think we should either allow or disallow both scenarios for the sake of consistency.
Furthermore, given that `conda list` does run successfully without an activated env when `CONDA_PREFIX` is set,
I made `conda env export` consider `CONDA_PREFIX` in this PR.
=> ENH: exporting env takes CONDA_PREFIX into account

conda/core/solve.py, tests/test_create.py
Virtual packages cannot be remove if there are conflicts and therefore
should not be included in a list of constrained packages.
fixes #10116
=> ignore virtual packages when searching for constrained packages

conda/base/context.py
On ARM based macOS systems platform.machines() returns arm64
=> add arm64 to non_x86_machines

conda/core/index.py
This import error was originally missed because several PRs were not merged in the order in which they were submitted.
=> Fix import error caused by `non_x86_machines` rename

conda/cli/main_config.py
When user runs a command `conda config --json --show-sources` it executes with an error. If either `safety_checks` or `path_conflict` is present in `.condarc`.
=> Fix config json output serialization

conda/_vendor/cpuinfo.py, conda/base/constants.py, conda/base/context.py, conda/exports.py, conda/models/enums.py
Needed since conda-build >=3.20.0 already support this platform, but we aren't ready for a full conda 4.9.0 release just yet.
=> Add osx-arm64 support to 4.8.x release

conda/core/subdir_data.py
.. to distinguish between those post-processed with context.use_only_tar_bz2 set
and those post-processed without it set.
Otherwise we end up considering both .conda and .tar.bz2 packages when loaded
from the cache or pickle file when we've set context.use_only_tar_bz2
=> Add a 0 or 1 to repodata cache and pickle filenames

README.rst
CircleCI badge is still being used for CI. Removing that badge in favor of a badge for all CI tests
=> Update README to use GH Actions Badge

conda/cli/main_remove.py, tests/conda_env/test_cli.py
=> Stop `conda env remove --dry-run` from actually removing environments

docs/source/user-guide/install/windows.rst
In my testing it's actually defaulting to not set aka `0`
=> Correct default /AddToPath option

conda_env/cli/main_create.py, conda_env/env.py, docs/source/user-guide/tasks/manage-environments.rst, tests/conda_env/support/valid_keys.yml, tests/conda_env/test_cli.py
This PR enables creation and export of conda environments that have environment variable created with [`conda env config vars`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=variables#setting-environment-variables).
Tests have been included for this behavior.
Here' an example
First create a new env and set two variables and confirm
```
> conda create -y -n env_with_vars python=3.7
> conda env config vars set DUDE=woah SWEET=yaaa -n env_with_vars
> conda run -n env_with_vars env | grep -E "DUDE|SWEET"
DUDE=woah
SWEET=yaaa
```
When the env is exported the variables are retained in a key called `variables:`
```
> conda env export -n env_with_vars --from-history
name: env_with_vars
channels:
- defaults
dependencies:
- python=3.7
variables: …
```
=> Add environment variables to environment.yml files

conda/resolve.py, tests/core/test_solve.py
In https://github.com/conda-forge/prismatic_split-feedstock/pull/10, I have added `__cuda` as a run dependency to restrict the installation of the GPU build on compatible system, which is working very well! A side effect of this is to make the environment inconsistent because the `__cuda` virtual package is not installed.
For example, on an CUDA capable linux system (there is no cuda package for windows):
```
$ conda install prismatic_cli -c conda-forge
$ conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
- conda-forge/linux-64::prismatic_cli==1.2.1=gpu_h5deb2e2_108
done
```
=> Ignore virtual packages when checking environment consistency

conda/activate.py
Fix unhandled assersion when running `conda shell`, fix inconsistent error message between no command and invalid command.
Note: the case `len(argv) == 3` corresponds to `len(arguments) == 0` which now raises an error instead of an unhandled assertion.
=> Improve error handling for conda shell

conda/_vendor/tqdm/__init__.py, conda/_vendor/tqdm/_monitor.py, conda/_vendor/tqdm/_version.py, conda/_vendor/tqdm/asyncio.py, conda/_vendor/tqdm/auto.py, conda/_vendor/tqdm/cli.py, conda/_vendor/tqdm/contrib/__init__.py, conda/_vendor/tqdm/contrib/concurrent.py, conda/_vendor/tqdm/contrib/itertools.py, conda/_vendor/tqdm/std.py, conda/_vendor/tqdm/utils.py
- Fixes various threading and I/O bugs (see https://tqdm.github.io/releases). The previous vendored version was based on https://tqdm.github.io/releases/#v4480-2020-07-16. Since then, there's been about 2 releases/month often with various fixes, e.g.:
+ https://github.com/tqdm/tqdm/pull/1041, https://github.com/tqdm/tqdm/pull/1036 <- https://github.com/tqdm/tqdm/issues/1033
+ https://github.com/tqdm/tqdm/pull/1046 <- https://github.com/tqdm/tqdm/issues/920, https://github.com/tqdm/tqdm/issues/691
+ also re-patches #10115 (re-fixing #9589)
* as per https://github.com/conda/conda/pull/10115#issuecomment-703991446
* https://github.com/tqdm/tqdm/pull/1044 <- https://github.com/tqdm/tqdm/pull/617
- also includes previous patches (#7157 <- #7040, #8435)
If you want to check the diff, it's …
=> bump vendored tqdm version

conda/cli/conda_argparse.py, conda/cli/main_run.py, conda/gateways/subprocess.py, tests/gateways/test_subprocess.py
This enables the command `conda run` to display the live output from the subprocess's stdout and stderr, in real time.
The current behaviour-- which prints the stdout and stderr only after the process has finished --remains unchanged. 
The `conda run` command now can take a flag `--live-stream` which would flip the behaviour to provide the real time output.
I believe this is related to: https://github.com/conda/conda/issues/9412
=> Enabling "conda run" to display real time output for the subprocess

conda/resolve.py, tests/core/test_solve.py, tests/data/index.json
Don't show hints about CUDA for packages that don't actually depend on it.
=> Fix CUDA solver hint

conda/misc.py
Looking for comment. Interested to optimise conda installation with explicit files so that it will not unlink/link when we have matching specifications already installed (so that reruns of the installation become comparatively cheap).
=> Ignore package installations that match specifications

conda/core/subdir_data.py, conftest.py, tests/core/test_subdir_data.py
(This is the second attempt at this, sorry for any inconvenience.)
As discussed in issue #9661 the performance of "file:///" channels is very poor in some circumstances with the latest conda versions. This seems to be because the solver requests repodata about directories more often than it used to. There is a caching mechanism for repodata but it is explicitly disabled for local channels; this PR removes that check so that the caching mechanism works for file:/// channels in the same way as HTTP channels.
That broke some unit tests, because of the way that an environment variable can be set to force conda to use only .tar.bz2 files, not .conda files. The tests try both settings, which changes the repodata that is fetched and should therefore be cached. The tests fail because the wrong …
=> Allow caching of repodata from file:/// channels

conda/core/subdir_data.py
Partially revert changes made in commit ad75abcad, so when the `use_only_tar_bz2` option is set to false (default), conda uses the same cache filenames it did before.  This helps avoid breaking certain applications that made assumptions about the repodata cache filenames.
=> Use old filenames for "normal" repodata cache files

conda/_vendor/auxlib/__init__.py
Prevents pickling of auxlib objects from failing due to mis-computing the module path.
=> Remove `__name__` from vendored auxlib

conda_env/env.py
this would fix #9749
Changes the decoding used to get the yaml string when reading from file, from the default from open() in text mode, to explicitly using utf8 and utf16
The default .to_yaml() uses utf8, but on windows platforms, redirecting the
stdout to a file using `>`, which is a common way to export the environment,
outputs a utf16 file instead, and so fails to be read when you try to
recreate the environment
=> Try utf16 decoding if utf8 fails when reading environment yml file

conda/core/initialize.py
Currently `conda init zsh` generates the configuration file as $HOME/.zshrc. However, this is a bug as zsh gives preference to $ZDOTDIR/.zshrc if present. This pull request fixes the issue and will also close #9362
=> Fixed Intializtion of Zsh if ZDOTDIR env present

conda.recipe/build.sh, conda.recipe/run_test.sh, dev/start, setup.py
Changes:
1. Attempting to install `conda-build` via `python setup.py develop` would result in:
```
..
File "/opt/Shared.local/asrc/conda-build/conda_build/conda_interface.py", line 9, in <module>
from pkg_resources import parse_version
File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
def _initialize_master_working_set():
File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
f(*args, **kwargs)
File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
ws.require(__requires__)
File …
```
=> We rename ruamel_yaml to ruamel_yaml_conda in our ruamel_yaml package

conda/shell/etc/profile.d/conda.csh
When using csh or tcsh only
After using "conda activate env" for the first time issuing "conda env list" adds the conda/bin directory as a prefix to the PATH variable causeing future python execution to use a non-intended python version. 
Even worse: every time "conda env list is issued a new "conda/bin" is prefixed to the PATH variable.
The same issue happens when an conda command is executed the results in an error e.g "conda activate non_existing".
- setup conda for csh
- create a new environment "py"
- conda activate py
- 'which python` gives correct path to py/python executable
- conda env list
- 'which python` gives incorrect path to conda/bin/python
"conda env list" or any informational or invalid conda com and should not affect the PATH variable
This problem is caused by conda.csh …
=> Fix csh path

docs/source/user-guide/tasks/use-conda-with-travis-ci.rst
Installing directly with `setup.py install` is not recommended. Better to use `pip install .` instead.
=> conda/travis: Install package with pip not setup.py

docs/source/user-guide/tasks/manage-python.rst
This part of the documentation is out of date with respect to the default version of Python 3 which is installed via Anaconda3 and Miniconda3, as of the 2020.11 release. However, I am not sure what the standard is for "supported versions" for this part of the documentation. If we only consider the latest version of the distribution, only 3.8 and 3.7 should be listed as supported. 
If we consider all previous installers, my impression is that 3.5, 3.4, ... 2.6 should also be included (which seems unlikely): https://docs.anaconda.com/anaconda/packages/oldpkglists/
=> Update supported and default versions of Python3

conda_env/cli/common.py, conda_env/cli/main_create.py, conda_env/cli/main_update.py, tests/conda_env/__init__.py, tests/conda_env/test_create.py
`conda env create` already supported using an environment file from url but `conda env update` did not.
The following command will now work:
```bash
conda env update -f https://domain.com/my-environment.yml
```
I didn't really like to copy/paste the `test_create_update` test. It would have been nicer to use `@pytest.mark.parametrize` but this test is still using a class from unittest with setup/teardown.
=> Add http support to conda env update

.github/workflows/ci.yml
- The last Python 2.7 release on defaults & conda-forge was 4.8.4.
- The last Python 3.5 release on defaults & conda-forge was 4.5.11.
We're planning on formally dropping support for Python 2.7 and < 3.6 (conda/conda#10180), and since Python 2.7 is well past its EOL, now seems a good a time as any to stop running CI against it. Further, now that we've built out the package ecosystem, add Python 3.9 to the CI build matrix so we can catch bugs like conda/conda#10542.
=> Update CI to drop Python 2.7, add Python 3.9

conda/base/context.py
Make `_vendor.distro` import absolute to avoid thread safety problems
that were seemingly introduced by change in Python 3.9.
Fixes #10490
=> Fix `conda search` for Python 3.9

conda_env/env.py
Fixes parsing when searching for explicit 'pip' dependency to correctly parse both 'channel::pip' and 'pip'
=> Fix https://github.com/conda/conda/issues/9724

conda/cli/conda_argparse.py, conda_env/cli/main_create.py, tests/conda_env/support/env_with_dependencies.yml, tests/conda_env/test_create.py
resolves #9580 
Supports default-packages from condarc when creating a new environment via `conda env create`
=> support default-packages in conda env create 

conda/cli/main_config.py, tests/cli/test_config.py
Essentially an extension of PR #10447 to address certain test failures induced by that PR.
=> Improve `conda config` support for nested keys

conda/cli/main_config.py
The bug:
$ echo "conda_build:">>~/.condarc
$ echo "  cache_dir: /opt/conda/conda-bld">>~/.condarc
$ conda config --get conda_build.cache_dir
unknown key conda_build.cache_dir
The diagnosis:
We use nested keys in conda-build, but conda refuses to play ball
because it cares not for our nesting when it looks for the key.
The fix:
Step through the requested, dotted, nested key and rc_config in
lock-step.
The resolution:
$ conda config --get conda_build.cache_dir
--set conda_build.cache_dir /opt/conda/conda-bld
=> Support nested keys in conda config --get

conda/cli/main_config.py, tests/cli/test_config.py
Fixes https://github.com/conda-forge/miniforge/issues/44.
Currently, when there is a `.condarc` in the root prefix and no user `.condarc`, setting configuration parameter will use the default values hard-coded in conda - defined in [conda.base.constant](https://github.com/conda/conda/blob/master/conda/base/constants.py).
This is not an issue with anaconda/miniconda distribution, since these hard-coded defaults matches the expectation of these distributions, however, this is an issue for distribution for example, because the `.condarc` provided to constructor is not honoured. An example of this issue is demonstrated in https://github.com/conda-forge/miniforge/issues/44#issuecomment-668125133, where the `defaults` channels are added but obviously this would also applied to any other …
=> Fix setting new user .condarc

conda/core/subdir_data.py
Fixes a typo in subdir_data.py in a canary tag (4.10.0) that is notable only when artifact verification is turned on.
Prior to this, `conda-content-trust` was always treated as not installed.  See https://github.com/conda/conda/commit/e670fdab4951397079a156aee2f58aa5bba061c6.
=> Bugfix import typo, allow conda-content-trust use

conda/shell/etc/profile.d/conda.sh
[PosixActivator#_hook_preamble](https://github.com/conda/conda/blob/e37cf84a57f935c578cdcea6ea034c80d7677ccc/conda/activate.py#L867) sets `_CE_CONDA` to the empty string rather than unsetting it, so `[ -n "${_CE_CONDA+x}" ]` will always return true, resulting in the wrong branch being executed and PATH set incorrectly.
This commit changes `+x` to `:+x` to only return true if `_CE_CONDA` is set and non-empty.
Partially fixes #8693
=> Partially fix profile script PATH setup on MSYS2

conda/core/index.py, tests/core/test_index.py
Use a regex based on documented versioning schemes to extract a version to the `__linux` virtual package; this replaces our naive scheme of splitting on the first "-", which failed on certain vendor strings (e.g., container-optimized OS) and didn't handle bogus version strings.
Fixes conda/conda#10596
=> Improve version detection for `__linux` virtual pkg

conda/gateways/disk/delete.py
after calling rmtree(), .empty directory still exist if rsync is not installed.
so i modified to remove .empty directory regardless of with or without rsync.
=> remove .empty directory even when rsync is not installed

CHANGELOG.md, conda/core/subdir_data.py
This PR fixes an issue pulling trust metadata from the server on Windows when artifact verification is enabled.  The bug resulted in artifact verification not working.
join() was used instead of join_url(), causing singing metadata
URLs on Windows to use the wrong pathsep for a URL.
=> Windows bugfix for artifact verification: URL pathsep issue

conda/core/subdir_data.py
conda already having the latest version of root metadata built in is a normal and common case.  It should not be generating a warning, so I dropped it to debug level and reworded it slightly.  (Perhaps info is better?)  It looks to folks like something is wrong when it's not.
Also clarified that the info line on fetching updated root metadata is looking to see if there is a newer root file.  (There will almost always not be.)
=> AV: logs: correct log level for root metadata retrieval

setup.py
Python 2.7 and Python < 3.6 got formally dropped by conda version 4.10.0.
With CI running for newer Python versions only there is also no way to
ensure that no new code incompatible to older Python versions gets
introduced.
Future imports and utf-8 coding are not required / default since Python 3.
=> Reflect dropping of older Python versions in setup.py

conda_env/cli/main_create.py, conda_env/installers/conda.py, tests/conda_env/test_cli.py
This adds a `--dry-run` flag to `conda env create` that creates YAML for JSON output of the solved environment without installing it.
Question: Without `--json` but with `--quiet` this will still display the spinner. Would another PR to more easily quiet the spinner be appreciated just by using `--quiet`?
By using the `CONDA_SUBDIR` environment variable this flag can also be used to check environment solves cross platform.
Here's an example
```
conda env create --dry-run defusco/py376
Collecting package metadata (repodata.json): done
Solving environment: done
name: py376
channels:
- defaults
dependencies:
- defaults/osx-64::ca-certificates==2021.1.19=hecd8cb5_1
- defaults/osx-64::libcxx==10.0.0=1
- defaults/osx-64::xz==5.2.5=h1de35cc_0
- defaults/osx-64::yaml==0.1.7=hc338f04_2
- …
```
=> Conda env create dry-run

conda/misc.py
Currently an "explicit" install doesn't respect the `--download-only` flag.  
This PR takes the `install.py` logic of exiting with code zero when `--download-only` is set: https://github.com/conda/conda/blob/33a142c16530fcdada6c377486f1c1a385738a96/conda/cli/install.py#L343-L345
and applies it in `explicit` after the fetch and extract action has occurred.
=> explicit install doesn't respect --download-only

conda/gateways/connection/adapters/s3.py
The deleted lines could cause issues when using a [credential process provider](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html).  
Specifically, during test discovery in vscode, conda info would run and import this module.  Creating the client would trigger the process provider to run.  This particular process provider would request credentials, but the prompt would not be visible as conda info was run in the background.
There's a number of places that things went wrong in this scenario, put this change appears to be a simple fix.
=> Don't create an unused s3 client at import time.

docs/source/user-guide/install/macos.rst
This changeset moves the Catalina `conda init` message up into the `note` directive just above, which I think helps clarify the intent of the message a bit. While I was at it I made some of the other shell script notes a bit more generic, and applied code formatting to the list of flags.
Regarding the CLA, I have attempted to sign the CLA in two different browsers, but for some reason I can't get past the signature field - the form won't allow me to submit because it considers the signature field empty (even though it isn't). Please let me know what you need from me to get the CLA on file.
Thanks!
=> maint: update macos install guide

conda/activate.py, conda/shell/condabin/Conda.psm1, conda/shell/condabin/conda-hook.ps1
Since commit ca16da40 using changeps1=false just results in
Add-CondaEnvironmentToPrompt not being called, but still unconditionally
renaming the global prompt function so the end result is the user
ends up with no prompt at all (well, just 'PS>').
Fix this by making everything related to the prompt conditional, but
execute all of that in the module itself (and add arguments to the
module in order to achieve that); see previous issues related to the
prompt function: it should be altered in the global scope and not
in function scope.
Fixes https://github.com/conda/conda/issues/10326, also see https://github.com/conda/conda/pull/8774.
=> Fix changeps1 implementation for Powershell

conda/shell/etc/profile.d/conda.sh
I found some strange behaviour in the shell script that's sourced into `.bashrc`. I may have overlooked or misunderstood some important details, so please triple-check whether the changes make sense.
There were some issues with the function `__conda_activate() `
```sh
CONDA_INTERNAL_OLDPATH="${PATH}"
__add_sys_prefix_to_path
ask_conda="$(PS1="$PS1" "$CONDA_EXE" $_CE_M $_CE_CONDA shell.posix "$cmd" "$@")" || \return $?
rc=$?
PATH="${CONDA_INTERNAL_OLDPATH}"
```
1. `rc` is not local, and is useless, because `$?` is always `0` at that point
2. if the command inside `$( ... )` fails for some reason, the function returns without restoring `PATH`
The second problem was also present in function `__conda_reactivate()`.
Function `conda()` properly restored the `PATH` before returning, but the …
=> fix some issues in conda.sh (injected in .bashrc)

tests/conda_env/support/advanced-pip/environment.yml
The Advanced Pip Example previously used an invalid `file` URI syntax. With Pip version 21.2.1, this syntax is no longer supported and results in `FileNotFoundError`. This PR updates the example to use a valid syntax.
#10815 
https://github.com/pypa/pip/issues/10237
https://github.com/conda-forge/pip-feedstock/issues/76
=> Update Advanced Pip Example

docs/source/user-guide/install/rpm-debian.rst
This is a quick fix of the documentation.
I didn't bother to read the contributor's guidelines, so sorry if I don't follow them.
=> Fixed path of conda repo in RHEL based systems

.github/workflows/ci_image.yml, .github/workflows/conda_ci_container_cicd.yml, ci/Dockerfile
The logic moved from https://github.com/ContinuumIO/docker-images
While the Dockerfile is untouched, the github action was updated to use
a build matrix, to publish to ghcr.io and to specify the Python version in
the image tag instead of the image name.
=> Add creation of the conda-ci-linux-64 container

.github/workflows/ci_image.yml
I'm not sure why the GitHub container registry is working differently compared to Docker Hub to be honest. Let's try to fix this push..
=> Ci image build

.github/workflows/ci.yml
Advantages:
* Defined and published by the conda repo
* No rate limits when used by Github actions
=> Switch to ghcr.io images for testing

.github/workflows/ci.yml, .github/workflows/docs.yml, .readthedocs.yml, Makefile, ci/build_docs.sh, ci/integration_tests.sh, ci/unit_tests.sh, docs/Makefile
* Move to own workflow to trigger only on docs changes
* Remove git docs detect magic from ./ci/*_tests.sh that was used previously to avoid test runs on docs only changes.
* Move ci/build_docs.sh logic to docs/Makefile
* Use dedicated env for doc builds to avoid base env polution on local runs
* Use docs/Makefile targets during docs.yml flow run
* Convert Python version in .readthedocs.yml to string according to https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
=> Refactor docs logic

.github/workflows/ci.yml, Makefile
* Clone without history
* Don't pull the huge conda ci image
* Use a dedicated lint env
=> Speedup flake8

.github/workflows/ci.yml
The lint target itself only needs to run on one platform, but by running it on all three it is continuously proven that the according make targets to create the lint environment and the lint commands run on all platforms for a greater developer experience, when linting locally during development.
=> Run lint on all 3 platforms to prove that used make targets are generic

.github/workflows/ci-images.yml, README.rst
This reduces the number of active workers when lots of changes are pushed in a short time by auto-cancelling previous runs.
=> Add concurrency to CI images workflow.

docs/source/user-guide/install/index.rst
The Python 3.9-based installs fail in Win7 with a not-particularly-intuitive DLL error, and information about versions required is somewhat buried (i.e. in Python docs vs than Conda docs). Add Windows version requirements here.
Source:
https://docs.python.org/3.9/using/windows.html
https://bugs.python.org/issue40740
=> Add Windows versions to system requirements

conda/core/solve.py
To fix the virtual package KeyErrors in the final transactions, we need to patch `mamba.utils.to_txn`. Instead, we are bringing that one over, since we will need to introduce more modifications in how that's being handled.
This should end up fixing the following issues listed in the main PR:
If they are fixed, they won't appear in the failed report. If they do appear, it'll be for a different error, not `KeyError`.
=> [Mamba POC] - Rework `to_txn` usage to fix virtual packages KeyErrors

conda/core/solve.py
Built on top off #10904 
***
Mamba has issues dealing with local channels on our Docker images (and maybe in other places), so we don't rely on it to handle the special case `channel == 'local'`. This can/should be fixed upstream too, but for now this workaround helps us move forward. We are using conda's `Channel` objects to find the local url and pass it to Mamba's API handlers directly.
This fixes `ActivationIntegrationTests.test_activate_deactivate_modify_path_bash`.
=> [Mamba POC] Fix local channels handling

conda/core/solve.py
Built on top of #10901 
***
This PR will uncover the issues behind `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`. Affected tests are:
- This has to do with pip interoperability, not implemented yet. This [block](https://github.com/conda/conda/blob/poc-libsolv-json/conda/core/solve.py#L1389-L1397) is relevant.
- Won't fix here. This has to do with [inconsistency](https://github.com/conda/conda/blob/9e9461760bbd71a178220982e8da85637aa2f699/conda/core/solve.py#L479) analysis, which Mamba does not perform yet.
- This fails with a JSON error, but it is actually different issue: the solver complains about a conflicting request when we try to force reinstall Python (or any other package). Will fix in a later PR.
- This one also uses `--force-reinstall`, which causes …
=> [Mamba POC] Deal with JSON output errors

conda/common/url.py, conda/core/solve.py, tests/core/test_solve.py, tests/test_create.py
Built on top of #10894 -- review that one first!
***
This implements early exit strategies that do not require the solver:
* conda remove --force-remove <pkg>
* conda update --satisfied-skip-solve
Uncovering this required adapting two small parts in a test, which required merging global context state (coming from the CLI or env vars) with the signature-level flags.
=> [Mamba POC] Implement early exit strategies

CODE_OF_CONDUCT.md, CONTRIBUTING.md
- Fix link to anaconda.org issue tracker.
- Mention Code of Conduct as defined in Conda governance.
- Extend steps to clone.
- Use same forking technique between Windows and other platforms.
- Remove old version fo CLA text in favor of link to docs.
- Add Code of Conduct as defined in [conda governance docs](https://github.com/conda-incubator/governance).
=> Contributing and CLA docs cleanup

conda_env/cli/main_vars.py, tests/conda_env/test_cli.py
This fixes the inability of conda to set an environment variable containing "`=`" signs.
`conda env config vars set API_KEY=AaBbCc==` should now set the API_KEY to `AaBbCc==`.
=> fix bug in setting environment variables

conda/core/solve.py, tests/conda_env/test_cli.py
Conda and Mamba have different standard outputs in CLI. This test hardcoded a line number to begin the YAML parsing; instead we find the first token without assuming any particular output before that line.
=> [Mamba POC] Fix YAML parsing in `test_create_dry_run_yaml`

conda/base/context.py, conda/core/solve.py
This tries to fix `test_update_deps_flag_present`. Mamba code only handled the leave nodes I think. In this case we take conda's approach and do a pre-solve to obtain the full chain.
I've also reworked how the solver tasks are precomputed here. This might affect other tests too. Keep an eye on regressions.
=> [Mamba POC] Handle UpdateModifier.UPDATE_DEPS correctly (all graph, not just leaves)

conda/core/solve.py
Libsolv will provide this generic error for some of our tests, probably due to a misconfiguration on our end. Setting `CONDA_VERBOSITY=3` enables the libsolv debug logs, so we can dig the details up. 
I'll be writing my notes and findings here.
List of failing tests at the beginning of this PR:
=> [Mamba POC] Research `conflicting requests` errors: --update-deps

dev/start
Some users (aka me) like to alias `rm` as `rm -i` so avoid that by including `-f`.
=> Force remove miniconda in dev/start

conda/core/solve.py, tests/test_create.py
Built on top of https://github.com/conda/conda/pull/10957
***
This fixes `test_create.py::test_remove_all`, which tests https://github.com/conda/conda/issues/2154. This needs to be upstreamed in Mamba too.
=> [Mamba POC] Don't try removing packages that are not installed

conda/core/solve.py, tests/test_create.py
Built on top of https://github.com/conda/conda/pull/10946
***
Python is special-cased here because otherwise the directory tree for other packages is not available for the dependencies. This makes `test_create.py::test_create_only_deps_flag ` pass.
=> [Mamba POC] Do not drop python if it was requested along with --only-deps

tests/test_create.py
Finally an easy one. Libsolv will print logs to stdout if verbosity=3 is enabled, which pollutes the JSON output that needs to be parsed here. Note that the verbosity is set at first instantiation, so adjusting `CONDA_VERBOSITY` after won't have any effect. In other words, it needs to be done as early as possible.
This fixes `test_install_force_reinstall_flag`.
=> [Mamba POC] Control verbosity on tests where stdout is parsed

conda/core/solve.py
This fixes `test_install_freezes_env_by_default`. If a package is frozen _and_ requested through `specs_to_add` (or any of the implicitly added names via `--update-all`, `--update-deps`, etc), it creates a conflict in `libsolv` because it tries both to lock the currently installed and also explicitly install a new version. Thus, the solution is to not freeze those names mentioned in the job list.
Conda does something similar here:
https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/conda/core/solve.py#L613-L620
=> [Mamba POC] Do not freeze explicitly (or implicitly) requested packages

.pre-commit-config.yaml, CONTRIBUTING.md, pyproject.toml, tests/requirements.txt
Adds necessary [pre-commit](https://pre-commit.com/) config file.
Do we want to update the `README`/`CONTRIBUTING` in this PR to reflect these changes?
After internal brainstorming and discussions we decided on using the following CQ tools:
- [darker](https://github.com/akaihola/darker) (we want the formatting to be gradually applied)
- [blacken-docs](https://github.com/asottile/blacken-docs)
- [flake8](https://github.com/PyCQA/flake8) (this is what we have been using)
We also include two other useful tools which are run but we currently do not monitor the results, these results can be reviewed by running pre-commit in verbose mode:
- [pylint](https://github.com/PyCQA/pylint)
- [bandit](https://github.com/PyCQA/bandit)
Resolves #10932
CC: @rchord @jezdez
=> Pre-commit, darker, blacken-docs, flake8, pylint, bandit

.github/workflows/boards.yml
Implements workflow to auto add new issues to the triaging project board and once the backlog label is added to move the issue from triaging to the backlog project board.
I have successfully tested this with a personal dummy repo & projects.
In working on these automations I found that these GH Actions do not appear to work with beta projects and maintainers of said actions are hesitant to dig into it since beta projects promise builtin workflows/automation. So we will just need to keep any eye on the developments and at some point we will be able to switch from old projects to the beta projects.
=> Automate moving to/from boards

conda/activate.py, tests/test_activate.py
This PR is going to fix #10436
Issue #10436 occurred because of an unique behavior of PowerShell - **setting an environment variable to a blank string is the prescribed way to delete it**. (ref. https://ss64.com/ps/syntax-env.html)
Conda gets the value of `CONDA_PROMPT_MODIFIER` by calling [`_prompt_modifier()`](https://github.com/conda/conda/blob/0d9f24b80febf198e0b77f617cf779d7d5d74a11/conda/activate.py#L654), 
https://github.com/conda/conda/blob/0d9f24b80febf198e0b77f617cf779d7d5d74a11/conda/activate.py#L654-L698
The function returns an empty string *when `changeps1` set to false*. Then in the activator,  env `CONDA_PROMPT_MODIFIER` is set to the empty string by invoking `$Env:CONDA_PROMPT_MODIFIER = ""`, which is actually unsetting/deleting the env because of PowerShell's unique …
=> Fix PowerShellActivator unsetting env

conda/shell/etc/fish/conf.d/conda.fish
Solve issues with shell interpretation and escaping characters in `fish` shell by removing superfluous `eval`s.
This fix is the same as discussed in #9145.
Fixes #9145
Fixes #7611
Fixes #10643
=> Remove extra evals in fish shell

conda/cli/install.py
The conda update error message is confusing. It says something that only works in anaconda, not miniconda, and this upgrade path doesn't work very well / is not recommended.
Instead, copy an example from `conda update --help`
```
$ conda update
CondaValueError: no package names supplied
#
```
=> change bare `conda update` error message

news/gh-10436-powershell-activator, news/gh-10628-interpolate-channel_alias, news/gh-10696-fish-eval, news/gh-10772-pypy-windows, news/gh-10795-conda-ci, news/gh-10799-conda-path-rhel, news/gh-10815-fix-pip-advanced-docs, news/gh-10831-stale-github-action, news/gh-10832-lock-threads-github-action, news/gh-10864-ci-refactor, news/gh-10878-github-issue-forms, news/gh-10896-indent-fish, news/gh-10898-docs-cleanup, news/gh-10905-envvars, news/gh-10933-architecture-docs, news/gh-10950-permissionerror, news/gh-10952-config-sequences, news/gh-10970-python310, news/gh-10982-XDG_CONFIG_HOME, news/gh-11009-styles, news/gh-11012-conda-canary, news/gh-11029-triaging, news/gh-11036-unicode-conda-meta, news/gh-11039-rever, news/gh-11040-gitpod-codespaces, news/gh-11041-dev-guide, news/gh-11045-update-help, news/gh-9789-set-errno
These are the news items that we would usually have included in PRs but since we've introduced [rever](https://regro.github.io/rever-docs/) only recently in #11039 this had to be added afterwards.
I used https://github.com/conda/conda/compare/4.10.3...master as the basis and skipped a few not as noteworthy commits. Please let me know if there is anything that doesn't make sense.
=> Add news items for 4.11.

.github/workflows/boards.yml
Previously the board automation wasn't working correctly so we needed to introduce a new token.
=> Use the appropriate token for GHA

conda/exceptions.py, tests/helpers.py, tests/test_solvers.py
Migration of `test_resolve.py`:
- `TestSolve`
- top-level
=> Adapt behavioural tests in `tests.test_resolve` for multiple solvers

conda_env/cli/main_update.py, tests/conda_env/support/example/environment_pinned.yml, tests/conda_env/support/example/environment_pinned_updated.yml, tests/conda_env/test_create.py
Assume an environment file called `foo.yaml` that looks like:
```yaml
name: foo
dependencies:
- python
variables:
MY_VAR: bar
```
When the user runs `conda env create -f foo.yaml`, conda will create an environment named `foo`, install Python in that environment, and set an env var `MY_VAR=bar`.
Now imagine the user modifies the file:
```yaml
name: foo
dependencies:
- python
- ipython
variables:
MY_VAR: bar
MY_VAR2: baz
```
And then runs: `conda env update -f foo.yaml`. The expectation is that IPython would be installed, and `MY_VAR2` would be set to `baz`. However, currently the `conda env update` command ignores any env variables specified in the yaml file. This PR attempts to remedy that.
Potential issue: This doesn't attempt to track env vars that are removed from the file.
=> Make sure that `conda env update -f` sets env vars from the referenced yaml file

.github/workflows/boards.yml
Adds the following automations:
- If an issue is milestoned:
- the `backlog` label will be removed
- the issue will be removed from the Backlog board
- (fail-safe) the issue will be removed from the Triaging board
- If an issue is demilestoned:
- the `backlog` label will be added
- the issue will be added to the Backlog board in the `Do Next` column
- If an issue is commented by the author:
- the `pending::feedback` label will be removed
- the `pending::support` label is added
=> Automatically handle milestoned/demilestoned/commented issues

conda/common/url.py, conda/core/solve/libmamba.py, conda/core/solve/libmamba_utils.py, tests/test_create.py, tests/test_solvers.py
The new version includes a patch for channel/subdir subpriorities that fixes some tests but makes another fail. It also includes Unicode fixes that might help with our windows issues. We'll take a look here.
Changes:
* Vendored `mamba.utils` into `conda.core.solve.libmamba_utils` as a temporary workaround to try different subpriorities.
* Escape local channels more robustly.
=> Libmamba 0.19 investigation

tests/test_create.py
`test_conda_pip_interop_conda_editable_package` will fail today because [GitHub is performing a brownout](https://github.blog/2021-09-01-improving-git-protocol-security-github/):
```
Obtaining urllib3 from git+git://github.com/urllib3/urllib3.git@1.19.1#egg=urllib3
Cloning git://github.com/urllib3/urllib3.git (to revision 1.19.1) to c:\tmp\test_conda_pip_interop_conda_e0\tmpm948_oac\b183 dcbfae\src\urllib3
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
We were fetching that package with `git://` on pip 10. Instead, we can use `git+https://`. No functionality is changed and the tests pass.
=> Update git:// to git+https:// in tests (GitHub policy changed)

.github/labels.yml
`description` cannot be `null`
=> Fix `labels.yml` syntax error

.github/labels.yml
Further standardizing our `labels.yml` to reflect what was learned from [label sync dry runs](https://github.com/conda/conda/runs/4873761672?check_suite_focus=true#step:5:615)
| Label | Description |
|:-:|:--|
| ![`build::canary`](https://img.shields.io/badge/-build::canary-7B4052) | trigger a canary build for this PR |
cc: @jezdez
=> More local labels

.github/labels.yml
Adding missing labels:
| Label | Description |
|:-:|:--|
| ![`type::installer`](https://img.shields.io/badge/-type::installer-fff2cc) | indicates a request or issue pertaining to the installer |
| ![`type::packaging`](https://img.shields.io/badge/-type::packaging-fff2cc) | indicates a request regarding a package |
| ![`build::review`](https://img.shields.io/badge/-build::review-7B4052) | trigger a build for this PR |
=> Add type::installer & type::packaging, revert build::review

conda/gateways/disk/delete.py, conda/utils.py, tests/test_activate.py
Change expected arguments for cleaner argument passing.
I have checked `conda-build` and it no longer utilizes `quote_for_shell` but if it did this change is designed to be backwards compatible.
Working towards #10972
=> Modify `quote_for_shell` signature

conda/cli/common.py, conda/cli/main_run.py, news/gh-11172-validate-prefix
Another cleanup. This function is also unused in conda-build.
The big change with this function is adding the prefix as a passthrough which helps streamline usage.
Working towards #10972
=> Refactor `is_valid_prefix` into `validate_prefix`

.github/workflows/ci-images.yml
Just the Docker image part of #10992 so we can use the image in the PR.
=> Build Docker image for Linux with Python 3.10.

conda/cli/main_run.py, conda/core/link.py, conda/gateways/subprocess.py, conda/utils.py
At no point does `on_win` deviate from whats detected from the current system so its unnecessary to explicitly pass this in.
If anything the `if on_win` clauses in `conda.utils.wrap_subprocess_call` should simply be moved outside the function but that's out of scope for this change.
=> Remove unnecessary `on_win` arg for `conda.utils.wrap_subprocess_call`

conda/__init__.py, conda/activate.py, conda/base/context.py, conda/utils.py, tests/core/test_initialize.py, tests/test_activate.py, tests/test_create.py
`dirname(CONDA_PACKAGE_ROOT)` is used a number of times in various corners of `conda`. Introducing a new global variable eliminating any repeat `dirname` calls.
Not set on the variable name or the necessity of this change so def up for a discussion.
=> Introduce `CONDA_SITE_PACKAGES`

conda/gateways/logging.py, conda/testing/helpers.py, conda/testing/integration.py, conda/testing/solver_helpers.py, tests/cli/test_cli_install.py, tests/conda_env/test_create.py, tests/core/test_package_cache_data.py, tests/test_activate.py, tests/test_cli.py, tests/test_create.py, tests/test_export.py, tests/test_history.py, tests/test_link_order.py, tests/test_priority.py, tests/test_utils.py
We'll need these too downstream, so let's refactor a bit. I wouldn't pay much attention to `conda/testing/integration.py` because that's essentially a copy-pasted chunk and it needs plenty of work. For now, just check that the new imports are ok and tests still pass.
=> [libmamba] Refactor integration test helpers

conda/gateways/connection/adapters/s3.py
Following the official docs using the boto3's S3 resources in a thread-safe manner (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-or-multiprocessing-with-resources) this instantiates a separate S3 session per call of this function to make sure the used S3 resource instance derived from it is properly thread-safe.
References:
- #8993 (original ticket)
- #10516 (original patch)
- #10756 (regression ticket)
- #10759 (regression fix)
=> Instantiate separate S3 session for thread-safety.

conda/cli/main_run.py, conda/utils.py, tests/test_cli.py
This fixes #11208 by using the system temp file directory instead of trying to create one in the conda environment when executing `conda run`.
=> Allow `conda run` to work in read-only environments.

tests/test_create.py
This should work around the issues with the old Python 3.6 metadata.
Fix #11161.
=> Bump up versions in deps-only tests.

conda/utils.py, tests/test_utils.py
Not in love with this implementation so alternative ideas would be very welcome.
We have already been relying on `subprocess.list2cmdline` to convert our list of str into a str on Windows. Unfortunately the implementation does not identify and handle what may look like redirects, file descriptors, or pipes. This resulted in:
<table>
<tr>
<td>End user input</td>
<td><code>conda run -n NAME pip install "numpy<1.22"</code></td>
</tr>
<tr>
<td>In <code>.tmp</code> script</td>
<td><code>pip install numpy<1.22</code></td>
</tr>
<tr>
<td>Expected</td>
<td><code>pip install "numpy<1.22"</code></td>
</tr>
</table>
So in addition to handling quotes and escape chars as `subprocess.list2cmd` does we also ensure we quote anything that looks like a redirect (`<` or `>`), a file descriptors (`&1` or …
=> Improve command line argument quoting

docs/source/user-guide/tasks/manage-environments.rst
The `echo $my_var` example was missing the `$`, and I added the Windows equivalent.
I also took the opportunity to update the JupyterLab version in the example environment command since 0.35 is very old!
=> Fix conda environment variable echo, update example versions

dev/start, dev/start.bat
When invoking `dev/start{,.bat}` as dry-run it shouldn't be making **any** system changes including any new directories.
=> Don't make devenv dir when running `dev/start --dry-run`

.github/workflows/ci.yml
Concurrency group that uses the workflow name and PR number if available or commit SHA as a fallback. If a new build is triggered under that concurrency group while a previous build is running it will be canceled.
Repeated pushes to a PR will cancel all previous builds, while multiple merges to main will not cancel.
[Previously](https://github.com/pyca/cryptography/pull/6203), [previously](https://github.com/pyca/cryptography/pull/6221), [previously](https://github.com/pypa/pip/pull/10704).
=> Add concurrency group to cancel GHA runs on repeated pushes to branch/PR.

conda/common/io.py
When using the `conda` package in python to inspect package versions, we get lots of logs like:
```
conda.common.io INFO: overtaking stderr and stdout
conda.common.io INFO: stderr and stdout yielding back
```
These logs do not seem actionable and seem unnecessarily verbose.  This PR changes them to `debug` level logs.
=> Change overly verbose info log to debug.

docs/source/user-guide/configuration/use-condarc.rst
Hey! The old link directing to the YAML syntax in the conda documentation is broken, i.e., https://docs.ansible.com/YAMLSyntax.html
I have updated it to : https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
Please Review my PR. 
Thanks!
#11261
=> Fixed : Broken link while referring to YAML syntax #11261

conda/base/context.py, conda/cli/common.py
Part 1/2 solving #11224 
- Fixes an issue where overriding dry-run doesn't propagate from `confirm_yn` to `confirm` (rendering the argument pointless).
- Adds `experimental_solver_confirmation` to the context
=> Experimental solver confirmation

.github/workflows/ci-skip.yml, .github/workflows/ci.yml
When checks are marked as required but also skipped (e.g. when only docs are modified) we get into a catch 22 state. We address this issue by defining a dummy workflow to satisfy the checks.
See [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)
Should resolve merging block for https://github.com/conda/conda/pull/11278
=> ci-skip.yml to circumvent skipped required checks

.github/workflows/ci-skip.yml
Followup to https://github.com/conda/conda/pull/11286
Looks like we need the matrix to be defined as well to properly match the check names.
=> Including strategy matrix in skipped checks

docs/source/user-guide/configuration/non-standard-certs.rst
Found was appears to be a small typo in the example shell profile list.
* `.bshrs` -> `.bashrc`
* combined `.bashrc` and `.zshrc` under single _e.g._
=> docs: update profile examples

dev/start
This was already introduced for `.\dev\start.bat` in https://github.com/conda/conda/pull/11251 so this change just mirrors this functionality back to the bash script.
=> Report update status in `source ./dev/start --dry-run`

conda/base/context.py
Fix #11303.
@jaimergp and me discussed this in a meeting and consider the risk to changing the error handling flow that late before the release too high. Instead we'll rely on the messaging included in the solver library.
=> Partially revert ce5a8a703c9ac1d2f159f6cbf3a67564236fb261.

.github/labels.yml
Reviving the epic label for https://github.com/conda/infra/issues/529
=> Revive epic label

tests/cli/test_cli_install.py, tests/conftest.py, tests/test_activate.py
The packages built by this autouse fixture are only used in two places. Blindly building these packages for any test run is unnecessarily expensive (e.g. when trying to run individual tests locally).
=> Remove expensive conda-build autouse fixture

tests/test_create.py
Due to recent updates to the available packages there seems to be a preference for Python 3.9 over Python 3.10 causing Python to be downgraded for the `--update-deps --only-deps` test:
```bash
$ conda create -n deps flask=2.0.1
$ conda install -n deps flask python --update-deps --only-deps
```
This is yet another "short-term" fix for the larger issue of our testsuite depending on the everchanging defaults channel.
=> Add python constraint back for `--update-deps --only-deps`

conda/cli/main_clean.py, conda/exports.py, conda/gateways/disk/link.py, news/11351-reorg-conda.cli.main_clean, tests/core/test_path_actions.py, tests/gateways/disk/test_link.py
Preparing for #11345, no functional change
- Removes `one_target_ran` in favor of a simpler check
- Removes 7 year old backport (introduced https://github.com/conda/conda/pull/1231, released with conda 3.18)
- Removes `defaultdict` usage in favor of `dict.setdefault`
- Instead of redefining `pkg_sizes` before returning it/using a zip logic just implement it correctly from the start and use `dict.items`
- Convert all `totalsize` variables to `total_size` to match the keyword we return with `--json`
- Change `find_*` functions to return `dict` instead of `tuple`
- Make `.part` extension tuple into a global const
- Remove unnecessary `os.lstat.st_nlink` fix for Windows Python <3.2 (conda-build [implements this fix as well](https://github.com/conda/conda-build/blob/806c3f0c12fd4f0177b396887ba8 …
=> Reorg main_clean

docs/source/user-guide/tasks/manage-python.rst
While reading the conda docs I noticed one of the instructions was written twice.  It looks like it wasn't intended so I thought it was a good idea to correct it.  See attached image below:
=> Remove duplicated instruction in manage-python.rst

conda/base/constants.py, tests/cli/test_main_clean.py, tests/conftest.py, tests/test_create.py
Depends on ~#11351~ & #11356
Discovered while writing tests for the untested functionality that:
- The `.trash` directory and `.trash` suffix no longer appear to be in use and we need to investigate removing it altogether
- Only the `--tempfiles` function requires a prefix but it doesn't check to ensure a prefix is passed but rather simply accepts any valid path, this is inconsistent and should be revisited
=> Reorg + new tests for main_clean

conda/cli/conda_argparse.py, conda/cli/main_clean.py, tests/test_create.py
There are 6 kinds of `conda clean`:
- `--tarballs`
- `--packages`
- `--index-cache`
- `--tempfiles`
- `--all`: all of the above
- `--force-pkgs-dirs`: nuclear option removing the entire package cache
Previously if running as dry-run only the tarball and package removal checks for the dry-run condition. So running the following had no impact with `--dry-run`:
- `--index-cache`
- `--tempfiles`
- `--force-pkgs_dirs`: this is of particular concern given the potentially corrupting nature of this removal
Further if running `--all` with `--dry-run` the way the dry-run check is implemented the program exists after only processing the tarballs. So effectively an incomplete dry-run report.
This addresses all of these inconsistencies.
Also removes `--source-cache` argument deprecated 5 years ago in …
=> Fix inconsistencies with `conda clean --dryrun`

conda/cli/main_clean.py
This is in preparation for combining `rm_tarballs` and `rm_pkgs` since both are identically structured.
The primary changes here is to:
- move the `getsize` logic previously defined in `rm_tarballs` into `find_tarballs`
- combine the `pkgs_dirs` for-loop with the `pkg_sizes` for-loop in `find_pkgs`
- split out a `getsize` helper function shared between the two implementations
=> Standardize tarball & pkg finding in `conda clean`

.github/PULL_REQUEST_TEMPLATE.md
This just updates the template to match with the current release process, we can change it once we're doing this fully.
=> Update PR template to match rever.

conda/cli/main_clean.py
The culmination of all recent `conda clean` work:
- https://github.com/conda/conda/pull/11351
- https://github.com/conda/conda/pull/11360
- https://github.com/conda/conda/pull/11385
- https://github.com/conda/conda/pull/11386
- https://github.com/conda/conda/pull/11387
Removes/combines `rm_tarballs` in favor of `rm_pkgs`. In addition to abstracting/reusing code this change also makes `conda clean` a little more user friendly by not dumping tons of extra info to the screen:
```bash
$ conda clean --all --dry-run
Will remove 93 (222.3 MB) tarball(s).
Will remove 1 index cache(s).
Will remove 77 (1.25 GB) package(s).
There are no tempfile(s) to remove.
DryRunExit: Dry run. Exiting.
```
```bash
$ conda clean --all --dry-run -v
Will remove the following tarball(s): …
```
=> Combine main_clean's `rm_tarballs` with `rm_pkgs`

conda/auxlib/collection.py, conda/auxlib/entity.py, conda/resolve.py, news/11398-replace-conda.auxlib.collection.frozendict, tests/models/test_match_spec.py
Removes custom `conda.auxlib.collection.frozendict` in favor of the already vendored `frozendict`.
Resolves #11337
=> Replace `conda.auxlib.collection.frozendict` with vendored `frozendict`

conda/cli/conda_argparse.py, conda/cli/main_run.py, conda/gateways/subprocess.py, news/11422-conda-run-live-stream-alias, tests/gateways/test_subprocess.py
Resolves #11209
`conda run` offers redundant functionality by providing both `--no-capture-output` and `--live-stream` arguments. Both are valid implementations but they've resulted in weirdly nested logic that is completely unnecessary. This change favors the simpler `--no-capture-output` implementation (less overall code and no precarious stream handling). `--live-stream` is now simply an alias for `--no-capture-output`.
=> Combine `--no-capture-output` with `--live-stream`

conda/cli/install.py
This would close https://github.com/conda/conda/issues/11294.
*** 
I am not sure this is the best solution though. It's arguably the minimum change to make this work (we would only need to set that attribute in the exception raised by libmamba), but it also extends the role of exceptions in flow control, and without a well-defined API. 
Alternatives:
* Some default behaviour in `conda.cli.install` is only defined for `solver=classic` (but this makes everything messier and harder to reason about)
* The retry logic is passed to `conda.core.solve.Solver` directly (but then this would be inherited by other tools in the conda ecosystem like conda-build, conda-smithy, constructor...)
* Essentially, some other refactor that allows us to define CLI behaviours per solver type
Other alternatives:
* …
=> Define optional exception attribute to bypass the retry logic

conda/core/subdir_data.py
Unusual to specify Content-Type in a GET header. Invalid if the file is `repodata.json.bz2`? Or send no header.
=> 'Accept', not 'Content-Type' in GET header

README.rst
The bare conda.io domain redirects to docs.conda.io while direct links to pages on conda.io are not redirected, leading to ambiguity about what is the authoritative URL for conda documentation.  This updates increases consistency toward the doc.conda.io subdomain. Closes #9100
=> Update documentation from bare conda.io domain to docs.conda.io

conda/cli/common.py, conda/cli/conda_argparse.py, conda/cli/install.py, news/11490-deprecate-conda.cli.common.ensure_name_or_prefix
Previously an explicit check/exception is defined to ensure that `conda create` includes either `--name` or `--prefix`. These two arguments are already defined as a mutex group in `argparse`. Just set this group to required and `argparse` will do the rest for us.
=> Remove `conda.cli.common.ensure_name_or_prefix`

docs/source/user-guide/install/windows.rst
Add note to inform Windows users that they can no longer add to PATH when running in AllUsers mode. This note should help avoid more issues like this: https://github.com/ContinuumIO/anaconda-issues/issues/12956
The commit where the security fix was implemented: https://github.com/ContinuumIO/anaconda-distribution-installer/commit/301e84f84b63d654045d4d7871b726de39fc9bb5
=> Add note about disabling adding to PATH during AllUsers installation (on Windows)

conda/common/url.py, news/11573-remove-is_ipv6_address_win_py27
Removing yet another Python 2.7 remnant.
=> Remove `conda.common.url.is_ipv6_address_win_py27`

conda/plan.py, conda/resolve.py, conda/testing/integration.py
`dashlist()` was defined in both `conda/resolve.py` and `conda/common/io.py`; this PR removes that function from `resolve.py` and imports it from `common.io` instead to remove redundancy.
=> Remove Repeated `dashlist` Function from `resolve.py`

CONTRIBUTING.md
This fixes a link that goes to an old list of CLA license signatories.
=> Update CONTRIBUTING.md: fixing broken link for CLA license contributors

conda/lock.py, news/11571-pendingdeprecation-conda.lock
Woo-hoo! Found another unused submodule!
I have searched all Conda and friends repos and `mamba` and as far as I can tell `conda.lock` is not in use anywhere.
=> Mark `conda.lock` as pending deprecation

conda/core/subdir_data.py
It's odd that this doesn't accept a dict. conda-index uses SubdirData to generate `current_repodata.json`, and wastes a json encode / decode to send the data to SubdirData. Not tested.
=> refactor SubdirData._process_raw_repodata_str

conda/testing/notices/helpers.py, tests/cli/test_main_notices.py
This pull request is a bug fix for a previously merged pull request: #11462 .
We are still having trouble with the following test:
- `tests/cli/test_main_notices.py::test_main_notices_read_from_cache`
My hunch right now is that this failure is related to the hard coded cache file names that were present in the tests. The change I'm proposing is to fetch these file names dynamically with a new function:
- `conda.testing.notices.helpers.get_notice_cache_filenames`
This should hopefully solve this problem as now the tests will be looking to the global `context` object to see exactly which cache files it should create.
=> Fix for broken Windows test runners on CI

conda/cli/conda_argparse.py
Realized some spacing was not correct in the conda init changes from #8135 in PR #11574, which caused the note at the end to only be half bold and be on two lines. This should fix that.
=> Fixed outstanding spacing issue in conda init help text.

conda/misc.py
There is a small typo in conda/misc.py.
Should read `eventually` rather than `enventually`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, enventually -> eventually

docs/source/dev-guide/index.rst, docs/source/dev-guide/writing-tests.md, docs/source/dev-guide/writing-tests/index.rst, docs/source/dev-guide/writing-tests/integration-tests.md
This pull request implements issue #11593 by adding a new documentation article on how to write tests. I've organized the pull request to have two pages: one is an index page that has a list of guides and general guidelines and the other is a guide on how to write integration tests in conda. The guides section will initially only have a single guide, but it will be able to accommodate more guides in the future.
=> Adding new documentation article on writing tests

conda/gateways/connection/__init__.py, recipe/meta.yaml, setup.py
Updates requests to the first version after the one that includes the monkeypatch.
https://github.com/psf/requests/blob/main/HISTORY.md#2200-2018-10-18
=> require requests >=2.20.1, drop monkeypatch

conda/core/index.py
#11647 introduced a regression. If the old alias is used, a recursion is hit because it calls itself. It should call the aliased function instead.
cc @kenodegard
=> Fix recursion in error in `check_allowlist` alias

conda/core/subdir_data.py, news/11658-add-fips-md5-support
This pull request is a fix for a problem highlighted in #7335.
Conda fails to install packages on FIPS-enabled systems because use of the MD5 algorithm is disallowed for security purposes. Since conda is not using it for such a purpose, this pull request makes use of the `usedforsecurity=False` flag in `hashlib.md5` (available since Python 3.9 in CPython, and earlier on RHEL/CentOS systems).
=> add usedforsecurity=False for hashlib.md5 for FIPS compliance

conda/activate.py, news/11649-refactor-get_export_unset_vars, tests/test_activate.py
Since conda has [dropped Python 3.6 support](https://github.com/conda/conda/releases/tag/4.13.0), we can finally switch to using `**kwargs` instead of using `OrderedDict`.
=> Use `**kwargs` instead of `OrderedDict` for `_Activator.get_export_unset_vars`

conda/__init__.py, news/11678-pendingdeprecation-another_to_unicode
This is unused across all conda org repos. [Search GitHub](https://cs.github.com/?scopeName=All+repos&scope=&q=another_to_unicode) and only found references to forks defining this function.
=> Deprecate unused `conda.another_to_unicode`

conda.recipe/meta.yaml
[For conda-build's canary tests to work correctly](https://github.com/conda/conda-build/pull/4548) we need our canary recipe to use a PEP 440 compatible version.
=> Use a PEP 440 compatible version for canary recipe

.codecov.yml
Let's add `conda_env` to our coverage reports. This will be helpful for bug fix contributions later down the road.
=> Adding `conda_env` to coverage reports

conda.recipe/meta.yaml, news/11333-replace-toolz-dependency-with-cytoolz, recipe/meta.yaml, tests/requirements.txt
As the codebase can benefit from `cytoolz` when present and still fallback to `toolz` when `cytoolz` is absent, would suggest softening the dependency here to just require `toolz`. This can be particularly helpful when supporting other Python implementations (like PyPy, etc.) since `toolz` is pure Python and should just work out-of-the-box. Thus this simplifies the process of bootstrapping a new Python implementation with Conda. Additionally if one or the other is faster for a Python implementation, this leaves it up to users to decide.
xref: https://github.com/conda/conda/issues/11698, https://github.com/conda/conda/pull/11589, https://github.com/conda/conda-build/pull/4556
supersedes: #11699
=> Require `toolz` & soften `cytoolz` dependency

conda/activate.py, conda/base/context.py, conda/cli/main_config.py, conda/common/configuration.py, conda/common/path.py, conda/common/pkg_formats/python.py, conda/core/index.py, conda/core/link.py, conda/core/package_cache_data.py, conda/core/path_actions.py, conda/core/solve.py, conda/core/subdir_data.py, conda/exceptions.py, conda/history.py, conda/models/channel.py, conda/models/match_spec.py, conda/models/version.py, conda/plan.py, conda/resolve.py
Yet another patch to fix the broken canary builds. Adding fallback imports to `conda._vendor.toolz` for all `tlz` imports.
This is necessary because of how `conda build` builds packages:
1. `conda build` generates the necessary build environment (which contains the new conda dependencies, e.g. `toolz`)
2. `conda build` generates a `build_env_setup.sh` script where at the very end, it runs something like:
```
...
eval "$('path/to/python' -m conda shell.bash hook)"
conda activate <ENV1>
conda activate --stack <ENV2>
```
this occurs in [conda_build.build._write_sh_activation_text](https://github.com/conda/conda-build/blob/11192e0054a3cf42a8d2ee976080a707b1b640e0/conda_build/build.py#L1824-L1827).
3. `conda build` changes directories to the working directory (in this case a shallow clone of …
=> Add `conda._vendor.toolz` fallback for `tlz`

conda/activate.py, conda/shell/condabin/Conda.psm1, conda/shell/condabin/_conda_activate.bat, conda/shell/condabin/conda.bat, conda/shell/etc/profile.d/conda.csh, conda/shell/etc/profile.d/conda.sh, dev/windows/setup.bat, tests/test_activate.py
Depends on #11649
Resolves #11174
When running `conda run`, users discovered that the wrong executable is invoked. This was especially noticeable on Windows. We first attempted to address this issue in #11257 but found that the source of the prefix injection occurred at the shell integration level so trying to do the path deduplication in the Python code would've been ripe for buggy behavior. 
<details> 
<summary>We narrowed it down to being the prefix injection that occurred in the following locations:</summary>
https://github.com/conda/conda/blob/8c835dd3b54b15ed68ef1a58ba8862a0e1ddcbae/conda/shell/etc/profile.d/conda.sh#L4-L30 
https://github.com/conda/conda/blob/8c835dd3b54b15ed68ef1a58ba8862a0e1ddcbae/conda/shell/etc/profile.d/conda.csh#L29-L30 …
=> Resolve prefix injection

Dockerfile
Automated CI for Linux tests [appears to be broken](https://github.com/conda/conda/runs/7977706015?check_suite_focus=true) with the use of `debian:buster-slim` due to the [image being updated recently](https://hub.docker.com/_/debian/tags?page=1&name=buster-slim). Changing the Dockerfile to point to `debian:stable-slim` to avoid usage of release-specific codenames and thus provide more stability to these test runs.
Depends on: https://github.com/conda/conda/pull/11754
=> Change Debian Image from `buster-slim` to `stable-slim` on Dockerfile

conda/exceptions.py, news/11746-modify-write-out
Resolves https://github.com/conda/conda/issues/11689, first brought up in [this comment](https://github.com/conda/conda/pull/11435#pullrequestreview-1059455307).
This code change ensures that exceptions that are raised show up properly instead of resulting in a random and otherwise blank `[y/N]` prompt. We also tidied up the `ExceptionHandler._ask_upload` method where it asks whether or not the user would like to send an error report.
=> Modify `ExceptionHandler.write_out` to Properly Show Errors

conda/cli/conda_argparse.py
Currently, the [`rename` command documentation page](https://docs.conda.io/projects/conda/en/latest/commands/rename.html) has no line spacing for the example commands and thus looks confusing:
This change will add the proper line spacing so that the examples show up properly.
=> Formatting `rename` Command Examples to Have Proper Line Spacing

conda/base/constants.py, conda/models/enums.py, news/11778-add-win-arm64
Add `win-64` to the list of known platforms (subdirs) as a first step to addressing conda/conda#11472.
=> Add `win-arm64` as a recognized platform

conda/misc.py, news/11591-readable-error-message-if-packagecacherecords-missing, tests/test_misc.py
I recently got tripped up by a broken channel that triggered the assertion.
However, the error is not quite helpful to the user. Even from the code context it's hard to understand what the issue is.
This PR replaces the `assert` statement by  an `AssertionError` with a proper message. I've chosen `AssertionError` to raise the same exception type. Let me know if you would like to raise a different exception here.
=> Fail with a readable error message if PackageCacheRecords are missing

.github/workflows/ci.yml
Run one single fast test per docker+qemu emulated linux platform to test that test execution is possible there (container+tools+dependencies work). Can be changed / extended to run specific tests in case there are platform related things to test. Running more tests is time consuming due to emulation (factor 2-10x slower).
Superseds https://github.com/conda/conda/pull/11566
=> Enable one single test for linux-{aarch64, ppc64le}

conda/testing/gateways/fixtures.py
It seems as if the URL of the minio docs changed from docs.min.io to min.io/docs/.
Fix #11923.
=> Update xprocess minio pattern. 

conda/core/package_cache_data.py, tests/core/test_package_cache_data.py
Jaime noticed we were raising a http error here instead of collecting them all into `CondaMultiError`. Fix and test.
Do we do a good job of formatting CondaMultiError for the end user?
=> restore CondaMultiError from package downloads

tests/cli/test_main_rename.py
Fixes https://github.com/conda/conda/issues/11905
All of the tests in `tests/cli/conda_main_rename.py` [fail on feature branches](https://github.com/conda/conda/actions/runs/3152698373/jobs/5128256911#step:3:536) due to the `notify_outdated_conda` warning.
=> Fix error output bug in rename tests

conda/core/initialize.py, news/11839-document-bashrc-bashprofile
This PR adds a comment explaining why `.bashrc` gets modified on Linux and why `.bash_profile` gets modified on macOS + Windows instead when executing `conda init`.
Closes #11830
=> Add comment to explain .bashrc vs .bash_profile

.github/workflows/ci.yml, dev/macos/setup.sh, dev/windows/integration.bat, tests/test_activate.py
Test change. Does pexpect buffer size affect performance? (larger = slower)?
Appears to hang if the regex capture is larger than the buffer size, causing failures in osx-64 CI. readline() is better than increasing the buffer indefinitely.
Do we have to worry about multi-line env var's?
=> tests: use readline instead of regex capture to avoid deadlock

LICENSE.txt, Makefile, conda/base/context.py, conda/common/configuration.py, conda/common/pkg_formats/python.py, conda/core/index.py, conda/core/link.py, conda/core/package_cache_data.py, conda/core/solve.py, conda/models/channel.py, conda/models/match_spec.py, conda/plan.py, conda_env/env.py, news/12020-stop-using-toolz.itertoolz.concatv, setup.cfg, tests/test_activate.py
Opting to use argument unpacking instead of `toolz.itertoolz.concatv`. All of the uses of `concatv` were immediately expanded into static types, so the generator `concatv` returned was unnecessary.
Alternative to #11769
=> Remove `toolz.itertoolz.concatv`

conda/core/package_cache_data.py
If the user presses CTRL-C it will raise BaseException instead of Exception, in one of the threads. re-raise to make sure the main thread immediately sees the CTRL-C or other BaseException.
=> handle BaseException in package_cache_data for expedient CTRL-C handling

conda/plugins/hookspec.py
When `self` is declared in a plugin function decorated with `@plugins.hookimpl`, the following error is output:
```
hookimpl definition: conda_subcommands(self)
Argument(s) {'self'} are declared in the hookimpl but can not be found in the hookspec
```
Editing the docstrings in `hookspec` module in order to avoid a plugin developer from encountering this error.
=> Update Docstring in Hookspec Module

conda/plugins/__init__.py, conda/plugins/hookspec.py, conda/plugins/types.py, conda/plugins/virtual_packages/archspec.py, conda/plugins/virtual_packages/cuda.py, conda/plugins/virtual_packages/linux.py, conda/plugins/virtual_packages/osx.py, conda/plugins/virtual_packages/windows.py, docs/source/dev-guide/plugins/subcommands.rst, docs/source/dev-guide/plugins/virtual_packages.rst, tests/plugins/test_subcommands.py, tests/plugins/test_virtual_packages.py
POC of internal discussion.
Moving `conda.models.plugins` to `conda.plugins.types` for stricter domain organization and to avoid adding more confusion to `conda.models`.
My intention with the import rules of `conda/plugins/__init__.py` is to expose everything necessary to make a plugin. The plugin implementations (e.g., `conda.plugins.virtual_pacakges`) should never be sideloaded by importing `conda.plugins`.
=> Move `conda.models.plugins` to `conda.plugins.types`

conda/models/match_spec.py, news/12062-fix-name-overwrite, tests/models/test_match_spec.py
Letting [name=...] overwrite the name specified outside of brackets in MatchSpecs allows for confusing cases where it seems one package will be installed but, in reality, another one is installed.
It's worth noting that this is a minor change to MatchSpec behavior.  We have no indication that this behavior is relied upon anywhere but its worth keeping in mind.  We should be confident that we aren't negatively impacting anyone before merging this PR.
=> Prevent [name=...] from overwriting name specified outside of brackets

conda/api.py, conda/base/context.py, conda/cli/install.py, conda/cli/main_remove.py, conda/core/solve.py, conda/plan.py, conda/plugins/__init__.py, conda/plugins/hookspec.py, conda/plugins/manager.py, conda/testing/helpers.py, conda_env/installers/conda.py, docs/source/conf.py, docs/source/dev-guide/plugins/index.rst, docs/source/dev-guide/plugins/manager.rst, docs/source/dev-guide/plugins/solvers.rst, tests/core/test_solve.py, tests/models/test_prefix_graph.py, tests/plugins/test_solvers.py, tests/test_exceptions.py, tests/test_info.py
As a follow up to @jaimergp's comment in https://github.com/conda/conda/pull/11993#pullrequestreview-1177196553 this deprecates `conda.core.solve._get_solver_class` in favor of a method of the `CondaPluginManager`.
=> Move `conda.core.solve._get_solver_class` to `CondaPluginManager.get_solver_backend`

conda/base/context.py, conda/cli/main_info.py, conda/exports.py
First introduced in conda 4.2 and updated in 4.3, conda introduced a private conda environment (`_conda` and `_conda_` respectively). This special env appears to have been a special local testing environment prior developers of conda used. This private env is undocumented, no longer in use, and adds an undesired complexity so we will deprecate it.
Xref: https://github.com/conda/conda-build/pull/4629
=> Deprecate private conda env

conda/base/context.py, tests/plugins/test_solvers.py
Updates the call of the user_agent staticmethod to be done on the class, not the instance, as incorrectly introduced in https://github.com/conda/conda/commit/ba7d9bc1b1516a48b2579ebb0d068986469280c3#diff-b088be378fc4d3c8240b5a24fd9d51409bb64226eb874be18a10eafadec79f78L850-R849.
Fix #12103
=> Don’t instantiate the solver backend for getting the user-agent.

tests/cli/test_main_notices.py
For this test, it's not actually necessary for us to even run the install command. We just want to check whether the notices are running as we expect them to.
So, instead of relying on the fixture that runs `conda-build` under the covers, we've removed it and instead just mock out the install function.
Fix #12092.
=> Fixes slow running test in the `tests/cli/test_main_notices.py` file

conda/core/index.py, conda/plugins/hookspec.py, conda/plugins/types.py, conda/plugins/virtual_packages/archspec.py, conda/plugins/virtual_packages/cuda.py, conda/plugins/virtual_packages/linux.py, conda/plugins/virtual_packages/osx.py, conda/plugins/virtual_packages/windows.py, news/12148-restore-default-virtual-packages, tests/core/test_index.py, tests/plugins/test_manager.py, tests/plugins/test_virtual_packages.py
While publishing the latest `conda` release for conda-forge we encountered solver issues when the CI used `conda=22.11.0`. Particularly, the issues were seen when building Python 3.11 variants.
During those builds solving for the test environment failed since `responses` is a test requirement in the `conda-feedstock`. `responses` requires `pysocks` has only been recently (before a Python 3.11 variant of it would have been built) converted to a `noarch: python` package that depends on `__unix`/`__win` in https://github.com/conda-forge/pysocks-feedstock/pull/20 .
Turns out, `conda=22.11.0` does not create virtual packages for `__unix` and `__win`.
ref: https://github.com/conda-forge/admin-requests/pull/523
=> Fix missing __unix virtual package in 22.11

.pre-commit-config.yaml
We recently ran into these errors while running pre-commit:
https://github.com/akaihola/darker/issues/412
This pull request version pins black when using darker to avoid this.
=> Fixes a compatibility bug with darker and black

conda/plugins/hookspec.py
The current solver plugin API example is missing the `logging` import and a few other lines. One thing to troubleshoot is the how the `"My verbose solver!"` statement does not seem to print out in the terminal.
=> Update solver plugin docstring/example

docs/source/user-guide/tasks/manage-environments.rst, news/11890-env-yml-channel-pkg-docs
Adds documentation requested in #11890.
Documented `channel::package` syntax for dependency specification in a `note:` in the **Sharing an Environment** section of `docs/source/user-guide/tasks/manage-environments.rst`. Also added `news` file, but it may not be needed for a change of this magnitude.
=> Document channel::package syntax for environment.yml files

conda/common/url.py, conda/models/match_spec.py, conda/models/version.py, news/12099-fix-fuzzing-crashes, tests/models/test_match_spec.py, tests/models/test_version.py
Further fuzzing efforts have identified the following cases crashing cases.  More details once I chase them down.
"(-cuda*|*cnumpy==1.0uda|????*cu"
"numpy= " (the trailing space is important here)
"aults::n [channel=ana.conda,versiond=3]"
"a[=)(=b"
Found another while looking at this:
".*!=1.9,^)\$=0"
Interestingly, it only crashes when it is passed to VersionSpec via MatchSpec, not directly.
=> Fix More Crashes in MatchSpec and Version Parsing

docs/source/user-guide/tasks/manage-channels.rst
This pull request removes a reference to conda version 5. As we all know by now, version 5 dead ☠️ and will never happen. Let's clean up our docs to remove any references to it.
I did some basic grepping in the docs directory and this was the only reference I was able to find 🤷‍♂️.
=> Updating docs to remove references to the mythical version 5 🦄

conda/plugins/virtual_packages/cuda.py, news/11667-cuda-detect-in-subprocess
Followed by #11626, see https://github.com/conda/conda/pull/11626#issuecomment-1186553105.
The environment variable `CUDA_VISIBLE_DEVICES` can cause `libcuda.cuInit()` fails (returns non-zero). The CUDA driver detector detects the driver version in the current process. The user-defined environment variable will let it fail.
For example:
- An empty `CUDA_VISIBLE_DEVICES` will cause `libcuda.cuInit()` returns `CUDA_ERROR_NO_DEVICE` (100).
```console
$ CUDA_VISIBLE_DEVICES='' python3 -c 'from conda.plugins.virtual_packages import cuda; print(cuda.cuda_version())'
None
```
- An invalid `CUDA_VISIBLE_DEVICES` will cause `libcuda.cuInit()` returns `CUDA_ERROR_INVALID_DEVICE` (101).
```console
$ CUDA_VISIBLE_DEVICES='0,0' python3 -c 'from conda.plugins.virtual_packages import cuda; …
```
=> Detect CUDA driver version in subprocess

conda/common/io.py, news/12231-lock-json-output
`sys.stdout` isn't threadsafe, leading to corrupted output. Lock while writing json progress bar substitute.
Fix #12225 
Fix #12231
=> lock stdout while writing json progress bar

tests/test-recipes/activate_deactivate_package/meta.yaml
Some versions of conda-build try to call .lower() on the boolean True as if it was a string. But the correct value is "generic".
IIRC this test recipe is duplicated in conda-build? Must we invoke conda-build as part of conda's tests or could we cache them?
Example https://github.com/conda/conda/actions/runs/3949958351/jobs/6761877312#step:7:90
=> correct test recipe

conda/core/link.py, tests/common/test_iterators.py
No need to depend on `toolz`'s `interleave` when `zip` does the job.
Xref https://github.com/conda/conda/issues/11718
=> Replace `toolz.itertoolz.interleave` with `zip`

conda/common/path.py, news/12261-add-downloadable-extensions
Due to the way conda's network stack works today, we can only download certain extensions, otherwise these are stripped or taken to be part of a channel name. We anticipate needing to download `.json.zst` and `.jlap` in the near future; add these. Is otherwise harmless (may prevent users from including these extensions in `/some/channelname.json.zst/osx-64/` for example).
Also, reformat a test with black and pymodernize.
Fix #12261
=> Add .jlap, .json.zst extensions to paths to make them downloadable

tests/test_create.py
A test requires boltons to be absent from defaults but it was added on 23 Jan 2023. Use `--override-channels` to look in the specified channel only, instead. Presumably boltons is in the private version of this test channel, but I'm not a member.
=> modify test to account for boltons in defaults

.github/workflows/tests.yml, dev/linux/integration.sh, dev/linux/unit.sh, dev/macos/integration.sh, dev/macos/unit.sh, dev/windows/integration.bat, dev/windows/unit.bat, docs/source/dev-guide/development-environment.md, setup.cfg, tests/run_tests.sh, tests/test_create.py
I always run tests in the debugger, in vscode, but `--cov` prevents the debugger from working.
Instead, enable coverage in individual test runner scripts, for CI.
=> Move coverage from setup.cfg to ease debugging

conda/plugins/virtual_packages/linux.py, news/12267-conda-override-glibc, tests/plugins/test_virtual_packages.py
=> yield libc virtual package only if libc_version is truthy

conda/base/context.py, news/12309-conda-build-conda, recipe/meta.yaml
conda-build 3.18.3 is from 2019. Remove a check, constrain the minimum conda-build version to be at least 3.18.3.
=> remove check for conda-build that doesn't understand .conda

conda/cli/main_notices.py, conda/notices/cache.py, conda/notices/core.py, tests/cli/test_main_notices.py
Fix for this issue:
- https://github.com/conda/conda/issues/12310
=> Channel Notices doesn't handle i/o errors

conda/core/subdir_data.py, news/remove-track-features-index, tests/core/test_subdir_data.py
AFAICT this has been broken for years, and no one has missed it.
Retain empty properties of SubdirData "just in case" (for API reasons)
Ironically, this should fix searching for `track_features` (since we no longer compare against the missing `track` key), it just goes through the compare-matchspec-against-all-packagerecord path like any other MatchSpec that doesn't specify an exact `name` 
Fix #12319 
Fixes unreleased search-by-packagerecord bug.
=> remove unused _track_features_index optimization

conda/shell/conda.xsh, news/12344-passthrough-version-help-xonsh
Fixes #12324 
xref xonsh/xonsh#5038
The argparser in `conda.xsh` was a bit too eager, so even though there's a function for passing through unparsed arguments, we were never reaching it.
=> Xonsh: allow --help and --version passthrough in conda.xsh

tests/models/test_prefix_graph.py
This test can fail because the channel decides to include its full URL (did we have another channel with almost the same name in some in-memory cache?)
Be more robust against that case.
=> improve reliability of test_prefix_graph

conda/cli/conda_argparse.py, news/12378-add-info-about-conda-remove-in-conda-CLI-help
Resolves #12358 
`conda remove -n <env-name> --all` command can be used to delete environments. This is not mentioned in the conda CLI help (`conda --help`). However it is mentioned in `conda remove` CLI help (`conda remove --help`). 
Because the main `conda` CLI help only mentions that `remove` command is used to remove packages from an environment, it is unintuitive that it could also be used to remove the environment itself. 
Moreover the CLI help doesn't mention any other command to remove environments (eg. `conda env remove`). 
Whether `conda env remove` (and other `conda env` commands) should be listed on CLI help is a part of the [ongoing discussion about collapsing `conda env` into `conda`](https://github.com/conda/conda/issues/11633).
While that discussion continues in the …
=> Add info about `conda remove -n <env-name> --all`  in conda CLI help

docs/source/user-guide/concepts/channels.rst, docs/source/user-guide/tasks/manage-channels.rst
Changing some raw hypertext URLs into embedded links + a few wording changes. See below for un-embedded links:
=> Create embedded links on docs pages

.github/workflows/tests.yml, tests/test_resolve.py
Two unit-tests splits for OSX. Will save us ~6 minutes of setup time since we avoid running the third split. Since the integration tests are much slower, a bigger unit tests run won't hold anything up.
=> use 2 unit test splits for osx, to reduce concurrency

setup.cfg
`--cov-report term-missing` is the per-file missing coverage information at the end of our test runs.
We already interact with coverage through much more useful reports like the codecov website or through `coverage html`, or by downloading the coverage data and doing other reporting outside the github actions log. So this report is just something annoying to scroll past when looking for a test failure. Remove it.
=> remove --cov-report term-missing from setup.cfg

dev/linux/unit.sh, news/12446-init-conda-after-installing-requirements
When setting up to run the unit tests initialize conda only after the requirements are installed since installing requirements may itself install conda undoing any initialization.
=> Init conda after installing requirements in tests

.pre-commit-config.yaml, news/12466-speedup-pre-commit
This removes pylint and bandit from pre-commit, as both are slow and their feedback is anyway already ignored, due to running with exit-zero.
This locally reduces the pre-commit runtime from ~43sec to 2.9sec and thus makes it possible to run pre-commit in a loop during local development to constantly provide feedback / style the code.
This partially resolves https://github.com/conda/conda/issues/12445 (removing more hooks does not make anything significant faster.... the move to ruff for more speed can be done via a separate PR).
=> Speedup pre-commit by factor 15

conda/cli/conda_argparse.py, news/12436-drop-37-support, setup.py, tests/cli/test_cli_install.py, tests/test_create.py
Follow up to #12436.
- adds news
- updates metadata
- updates tests to not use Python 3.7 anymore 
=> Tweaks for dropping Python 3.7 support.

recipe/meta.yaml
Follow up to https://github.com/conda/conda/pull/12453
The canary build in failed in https://github.com/conda/conda/actions/runs/4405872161/jobs/7719078532#step:3:704 with:
```
Adding in variants from /home/runner/work/conda/conda/recipe/conda_build_config.yaml
Error: bad character '>=' in package version dependency 'boltons'
Perhaps you meant 'boltons >=23.0.0'
```
=> Fix typo in recipe.

conda/gateways/connection/__init__.py, conda/gateways/repodata/__init__.py, news/12487-ChunkedEncodingError
Closes #12196
This happens very rarely, but after enough CI runs you get one. I wonder if we should catch the [base `RequestException` class](https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/) entirely instead of this reduced subset?
=> catch `ChunkedEncodingError` too

conda/gateways/disk/__init__.py, news/12490-mkdir-p-sudo-safe-race
This function suffers from [race conditions](https://github.com/conda/conda-libmamba-solver/actions/runs/4420840267/jobs/7751017355#step:5:870) so we need to catch that exception:
```
_____________________________ test_clean_tarballs ______________________________
File "/opt/conda-src/tests/cli/test_main_clean.py", line 109, in test_clean_tarballs
with make_temp_env(pkg):
File "/opt/conda/lib/python3.10/contextlib.py", line 135, in __enter__
return next(self.gen)
File "/opt/conda-src/conda/testing/integration.py", line 326, in make_temp_env
run_command(Commands.CREATE, prefix, *packages, **kwargs)
File "/opt/conda-src/conda/testing/integration.py", line 287, in run_command
result = do_call(args, p)
File "/opt/conda-src/conda/cli/conda_argparse.py", line …
```
=> catch and ignore existence errors in `mkdir_p_sudo_safe`

tests/test_create.py
Since Python 3.11 is now available on defaults the `test_create.py::test_install_update_deps_only_deps_flags` test started failing. Easy correction by removing version pinning.
Found via #12509 in https://github.com/conda/conda/actions/runs/4475317036/jobs/7864628287?pr=12509#step:3:288
=> Remove Python version pinning for correct test results

conda/gateways/repodata/jlap/fetch.py
Line split to satisfy linter missed f-prefix
=> Make split line f-string

conda/core/subdir_data.py, news/conda-index-fix
conda-index calls this method with one argument (the freshly generated index data). Restore default parameter.
This affects standalone conda-index; legacy conda-build index passes a string to a related method.
=> Restore default argument for `SubdirData` method used by `conda-index`.

conda_env/specs/binstar.py, news/12495-reenable-binstar-tests, setup.cfg, tests/conda_env/specs/test_binstar.py
The `tests/conda_env/specs/test_binstar.py` tests were unittest style and broken. This converts them into pytest tests and fixes them. Also updated `conda_env.specs.binstar.BinstarSpec` to use `functools.cached_property` instead of custom implementation.
Xref #11321
=> Update & reenable binstar tests

tests/gateways/test_jlap.py
This test is meant to check a case that I was concerned about getting wrong.
1. Download repodata
2. Cache expires after 30 seconds
3. Will the cache "stay expired", checking "304 Not Modified" every time after the original expiration? Or will it add another 30 seconds and correctly check no more frequently than once every 30 seconds?
=> Test that cache revalidate updates ttl

.github/workflows/tests.yml, dev/linux/setup.sh, dev/macos/setup.sh, dev/windows/setup.bat, news/12524-minio-pin
Needed by https://github.com/conda/conda-libmamba-solver/pull/159, which fixes a few tests in `conda-libmamba-solver`. This PR exposes a `MINIO_RELEASE` environment variable, which defaults to `minio` if not set. By specifying `archive/minio.RELEASE.<timestamp>` you can install a different version than latest.
=> Provide a way to pin `minio` in CI

.github/workflows/images.yml, dev/linux/setup.sh
Linux images are newly failing because curl is missing. Not sure why since curl is still listed as a supported software: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md.
=> Install missing curl for Linux images

conda/gateways/repodata/jlap/__init__.py
conda.gateways.repodata.jlap wasn't packaged by setup.py, since it was using a search algorithm that looked for a missing `__init__.py`. Although init is no longer needed by Python since a long time ago, the packaging tool still wants it.
This will be detected in the usual way, instead of manually adding the module to setup.py's list of auto-detected ones.
=> add __init__.py for conda.gateways.repodata.jlap

setup.cfg
This linter rule enforces a docstring style
`"""Single line comments"""`
instead of the (was) very common in our codebase
```
"""
Single line comments
"""
```
Ignore this rule to ease development.
=> Ignore comment style D200

conda/trust/signature_verification.py, news/12639-warn-missing-sig-url-base
Generate a warning, rather than an info-level message, if the user has enabled metadata signature verification (via `extra_safety_checks`) but has _not_ configured a [required] value for `signing_metadata_url_base`. This avoids the situation where signature verification seems to mysteriously not happen if the user is not running `conda` using in a mode where INFO and lower priority log messages are displayed.
=> Warn about misconfiguration when signature verification is enabled

conda/core/subdir_data.py
The [PR where the `read_mod_and_etag()` function was originally marked for deprecation](https://github.com/conda/conda/pull/12090) had [this comment](https://github.com/conda/conda/pull/12090/files#r1119254480) which pointed to a later deprecation date (which matches with the deprecation schedule we are following overall per [CEP 9](https://github.com/conda-incubator/ceps/blob/main/cep-9.md) policy).
=> Update deprecation version to reflect when function was deprecated

conda/core/subdir_data.py
Sorry for the spam here! I updated the versions [previously on another pull request](https://github.com/conda/conda/pull/12656) but these numbers were incorrect. This should now properly comply with [CEP 9](https://github.com/conda-incubator/ceps/blob/main/cep-9.md).
=> Correct the deprecation versions on `read_mod_and_etag()` function

tests/cli/test_common.py
If `always_yes` gets set prior to running tests then tests will start to unexpectedly fail. This removes this uncertainty.
Seeks to resolve testing issue found in https://github.com/conda/conda/pull/12670
=> Remove potential `test_confirm_*` uncertainty with `always_yes` being set

conda/core/subdir_data.py, conda/gateways/repodata/__init__.py, conda/gateways/repodata/jlap/fetch.py, news/12669-parametrize-cache-keys, tests/gateways/test_jlap.py, tests/gateways/test_repodata_gateway.py
This is extracted from #12556 to simplify the other PR.
Move some strings into constants to make it easier to rename certain cache metadata keys / extension.
Some logging improvements.
Fixes #12669 
Fixes #12572
=> rename `.state.json` to `.info.json` to track draft CEP

conda/gateways/repodata/jlap/fetch.py
At first I thought it would be more conservative to keep the hash key names the same, but the other PR addressing #12669 changed the whole filename. Change those key names to represent the hash algorithm used. [The draft CEP is here as a PR against the conda/ceps repository.](https://github.com/conda-incubator/ceps/pull/48)
The nominal hash and actual hash are used to track jlap changes. The nominal hash comes from the upstream file, hashed as formatted on the server. We look for those hashes in the `.jlap` changelog. The actual hash is our on-disk hash since we do not format the saved json exactly the same as the server; instead, we format it in a more compact way.
=> name hash algorithm in keys to better track draft CEP

conda/testing/helpers.py, conda/testing/integration.py
The deprecation message is wrong. The new `conda.testing.run` fixture was renamed to `conda.testing.conda_cli`.
=> `conda.testing.run` was renamed to `conda.testing.conda_cli`

conda/testing/integration.py, news/12676-deprecate-get_conda_list_tuple, tests/test_priority.py
Encourage using the conda API instead of parsing the CLI for tests.
Part of the effort to remove references to `conda.testing.integration.run_command` since its now marked as pending deprecation (see #12592).
=> Deprecate `conda.testing.integration.get_conda_list_tuple`

conda/testing/integration.py, news/12678-deprecate-temp_chdir
This helper function is unused in conda tests and is better served by pytest's `monkeypatch.chdir` fixture.
=> Deprecate `conda.testing.integration.temp_chdir`

conda/testing/__init__.py, news/12677-deprecate-encode_for_env_var
The `str`/`bytes` check done here is unnecessary and likely a Python 2 remnant.
=> Deprecate `conda.testing.encode_for_env_var`

.github/workflows/tests.yml
Changes canary builds to always occur, irrespective of "success".
Resolves #12686
=> Always build canary when pushed to main/feature/release

.github/workflows/tests.yml, conda/core/subdir_data.py
Fix #12689 by recreating cache_dir any time we look it up, removing memoization.
I counted and this was only called 12 times when defaults and conda-forge are in the search.
=> remove cache_dir memoization to improve unit tests reliability

news/12517-update-test_main_rename, tests/cli/test_main_rename.py
A number of changes occurred here:
- Converts all constants into randomized values returned by fixtures
- Converted `unittest.mock` to `mocker` fixtures
- Eliminated subprocess `list_envs` implementation in favor of calling `conda.core.envs_manager.list_all_known_prefixes`
- Added type hinting
- Converted all fixtures to function scoped to eliminate potentially fragile extra cleanup phase for select tests
- uses the new `conda_cli`, `tmp_env`, and `path_factory` fixtures
=> Remove `test_main_rename.py` customizations in favor of existing functions/fixtures

tests/requirements.txt, tests/test_create.py
Constrain `cryptography` to `<41.0.0` so it'll work with `conda-content-trust`. Also tossed in a line sort for good measure.
Xref https://github.com/conda/conda-content-trust/issues/56
=> `conda-content-trust` is incompatible with `cryptography=41.0.0`

conda/plugins/subcommands/doctor/cli.py, news/12725-deprecate-get_prefix, tests/plugins/subcommands/doctor/test_cli.py
`conda.plugins.subcommands.doctor.cli.get_prefix` duplicates existing functionality that is solved by doing one of the following:
```python
from conda.base.context import context, determine_target_prefix
args = <argparse parsing>
prefix = determine_target_prefix(context, args)
context.__init__(argparse_args=args)
prefix = context.target_prefix
```
=> Deprecate `conda.plugins.subcommands.doctor.cli.get_prefix`

conda/base/context.py, news/12701-deprecate-context-root_dir, tests/conda_env/test_cli.py, tests/test_install.py
We already prefer `context.root_prefix`, no need to keep this alias around.
=> Deprecate `context.root_dir`

.github/workflows/tests.yml
Durations weren't being included in the uploaded artifact bundle (see `gh run download --dir ./artifacts/ --pattern '*-all' 5191498809`). Environment variables aren't expanded in the globbing patterns so we need to use GitHub [expressions](https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-env-context) instead.
=> Ensure durations are included in uploaded artifacts

conda/auxlib/packaging.py, news/12762-distutils-deprecation, pyproject.toml, recipe/meta.yaml, tests/core/test_initialize.py, tests/requirements.txt
This removes imports from distutils that can be replaced with setuptools imports, following the guidance in the [migration guide](https://peps.python.org/pep-0632/#migration-advice).
Also bumps up to [setuptools 60.0.0](https://setuptools.pypa.io/en/latest/history.html#v60-0-0) since that's when "Setuptools once again makes its local copy of distutils the default. To override, set SETUPTOOLS_USE_DISTUTILS=stdlib".
Fix #11136.
=> Fix distutils imports for upcoming deprecation in Python 3.12.

.github/workflows/durations.yml, .github/workflows/tests.yml
Two changes here:
- `workflow_dispatch` also needs the repo to be cloned for https://github.com/dorny/paths-filter to work
- use a PAT token + `push_to_fork` when creating the duration update PRs such that our workflows run on the generated PR (see https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092)
Xref https://github.com/conda/conda/pull/12778
=> Clone if not a PR for `dorny/paths-filter` & add PAT token so `durations.yml` PRs run workflows

conda/cli/python_api.py, news/12796-deprecate-python_api
For testing purposes we now have the `conda_cli` fixture that we prefer to use. Otherwise this interface is for downstream projects that wish to programmatically interact with conda and offers an "API" when there isn't a clean and easy to use one in place.
Is this something we can afford to deprecate?
=> Mark `conda.cli.python_api` for deprecation

conda/testing/integration.py, tests/conda_env/test_create.py
Remove `dotupdate` logger references. From the CHANGELOG these were last mentioned in `conda 3.18.0` from 2015.
=> Remove legacy `dotupdate` logger references

conda/gateways/repodata/__init__.py
I know this is may seem like a nitpick.  But if a network administrator has blocked `repo.anaconda.com` but _not_ `www.anaconda.com`, these instructions may not actually be helpful. Consider the exchange:
USER: I was having trouble using conda, and the error message said that I should check to see if www.anaconda.com is blocked.
SYSADMIN:  nope, neither anaconda.com nor www.anaconda.com are on our block list. You should file a bug report with the conda folks, it's not our fault.
USER: hmm, OK, thanks.
=> Substitute "repo.anaconda.com" for "www.anaconda.com" in http 000 msg

docs/source/user-guide/install/macos.rst
Miniconda pkg installers may skip the "Destination Select" page during the installation process, which can cause the installation to fail.
This PR contains an advisory with a workaround until the problem is fixed.
=> Add advisory for Miniconda pkg installers

conda/cli/conda_argparse.py, conda/plugins/hookspec.py, conda/plugins/manager.py, conda/plugins/types.py, conda_env/cli/main.py, docs/source/dev-guide/plugins/post_commands.rst, docs/source/dev-guide/plugins/pre_commands.rst, news/12712-pre-command-plugin-hook, news/12758-post-command-plugin-hook, tests/plugins/test_post_command.py, tests/plugins/test_pre_command.py
Since we haven't solved the [inconsistency](https://github.com/conda/conda/pull/12814) of builtin subcommands passing a parsed `Namespace` and plugin subcommands passing an iterable of strings (i.e., `sys.argv`) this removes passing in the args into the pre/post command until we can properly identify a safe path forward.
=> Remove arguments/`sys.argv` from pre/post_command actions

conda/plugins/manager.py, news/12869-canonical-names, tests/plugins/data/test-plugin/test_plugin-1.0.dist-info/entry_points.txt, tests/plugins/data/test-plugin/test_plugin/blocked.py, tests/plugins/data/test-plugin/test_plugin/importerror.py, tests/plugins/data/test-plugin/test_plugin/success.py, tests/plugins/test_manager.py
This changes how entry point plugins are registered. Instead of using the entry point name as the plugin name we use the canonical name (this is creates more consistency with how first-party plugins are loaded).
This is inspired by the spoofing concerns raised while implementing `--no-plugins` (https://github.com/conda/conda/pull/12824).
=> Modify plugin loading to only use canonical names

tests/test_priority.py
Cherry picking the `test_priority.py` parametrization changes from https://github.com/conda/conda/pull/12680 into a standalone change.
=> Parametrize `test_priority.py`

conda/gateways/connection/adapters/s3.py, news/lazy-load-boto3
Address #12549 (partial).
On my machine using the scalene profiler:
```
. dev/start.sh -p 3.10
conda install scalene
echo "import conda.__main__" > con.py
python3 -m scalene con.py
```
`import boto3` takes about 350-450ms if boto3 is installed.
Instead, only import when s3 channels are actually used. If the user happens to have boto3 installed at all in their base environment, but doesn't use s3 channels, this should speed things up.
=> lazy-load boto3 to save ~400ms startup time

conda/deprecations.py, news/sys-getframe-inspect-stack
We only use a single frame, so use `sys._getframe` instead of `inspect.stack()`.
=> replace inspect.stack() with sys._getframe() to save ~170ms -> ~90ms

conda/gateways/repodata/jlap/interface.py, news/12731-jlap-respect-ssl-verify, tests/conftest.py, tests/fixtures_jlap.py, tests/gateways/test_jlap.py
Fix  #12731 
adhoc ssl context in test is a bit slow to create and showed an ssl error when I had mixed defaults+conda-forge in my development environment.
=> jlap: disable warning when not context.ssl_verify

tests/test_activate.py
The `test_dash_basic_integration` has repeatedly been slow on our conda-forge based CI, due to the way it installs a package from there (and making repodata fetching/parsing an issue). We should probably refactor that integration test at some point to just install a local package instead.
=> Increase timeout for activation test on conda-forge.

conda/testing/gateways/fixtures.py, news/12986-fix-S3-bucket-name, tests/gateways/test_connection.py
A fix for #12989. A recent change to MinIO added validations to ensure the bucket name conforms to AWS S3 bucket naming rules (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html). The fix is to use a valid bucket name (dashes instead of underscores). Thanks go to @travishathaway for identifying the fix.
=> Fix `test_s3_server` failure

conda/base/context.py, conda/cli/conda_argparse.py, conda/gateways/repodata/lock.py, news/12920-lock-default, tests/gateways/test_repodata_lock.py
TODO figure out what to do with `--experimental=lock`.  The intention would be to keep all `--experimental=` options forever to not break configs as unknown ones create errors in the argument parser, but it might not be necessary to retain them in the command line help.
Fix #12920
=> Lock repodata cache by default

conda/common/io.py, conda/core/package_cache_data.py, news/12982-no-progress-bars-in-logs
As discussed in the Refinement session, async tqdm bars can make some [CI logs too long](https://github.com/conda/constructor/actions/runs/5799411468/job/15719353263#step:3:286) and makes reading these harder. In this PR I check whether `sys.stdout` is a TTY (like the `Spinner()` class does, and decide whether to create progress bars or not. Some extra care has been taking to adjust the output a bit so it doesn't look like it's hung.
Example output: [long-log.txt](https://github.com/conda/conda/files/12294913/long-log.txt)
cc @dholth
=> Do not show download bars in non interactive runs

conda/cli/find_commands.py, news/13035-faster-find-commands
Closes #13033.
On WSL, the entire Windows PATH is inherited, and calling `isfile` (specifically, `os.stat`) across the filesystem boundary is extremely slow. Delaying the check until after pattern matching speeds things up considerably. (30s -> 1s on my machine.)
I've checked on the plain Windows side, and this appears to speed things up there as well (~900ms -> ~400ms).
=> Speed up find_commands() on WSL

conda/gateways/connection/adapters/ftp.py, news/13013-remove-cgi
Fix #13013
I can't imagine that conda ever needed to STOR files to ftp? It certainly doesn't show up in the tests.
What's the best way to deprecate this?
We could import cgi in the naughty functions, deprecate those and avoid the annoying import-time cgi warning.
=> remove cgi import

conda/cli/find_commands.py, news/find-commands-scandir
Fixes #13033, #13067
The original fix from PR #13035 is already in the main branch but not in the 23.7.x branch. This fix improves on #13035 by also removing the `os.path.isfile()` call.
In general, we should always use scandir(); I didn't notice any equally problematic listdir()/stat() pairs on a quick search through the conda source.
=> use scandir() in find_commands.py to avoid stat() calls against 23.7.x branch

conda/cli/find_commands.py, news/13062-find-commands-permission-error, tests/cli/test_find_commands.py
While we check whether a path is a directory we don't also check whether the user has read access resulting in PermissionError if any paths are restricted.
Resolves https://github.com/conda/conda/issues/13058
Target `23.7.x` instead of `main`, supersedes #13062
=> 23.7.x find commands permission error

tests/gateways/test_connection.py
Discovered in https://github.com/conda/conda/pull/13062#discussion_r1316066996:
> With the addition of new tests above the testing order was shuffled and exposed incorrect context mocking in this unrelated test, see https://github.com/conda/conda/actions/runs/6079217031/job/16498615642#step:8:909
> 
> ...
> 
> The failure can be replicated on main with the following test order:
> 
> ```
> pytest \
>     "tests/gateways/test_connection.py::test_get_session_with_channel_settings_no_handler" \
>     "tests/gateways/test_jlap.py::test_jlap_fetch" \
>     "tests/gateways/test_jlap.py::test_jlap_fetch_file" \
>     "tests/gateways/test_jlap.py::test_download_and_hash" \
>     "tests/gateways/test_jlap.py::test_jlap_cache_clock[True]"
> ```
=> Fix context mocking for CondaSession test

conda/cli/main_config.py, news/13076-json-sort-pathlib, tests/cli/test_main_config.py
See https://github.com/conda/conda/pull/13076
=> [23.7.x backport] Fix key sorting for `json.dumps` in `conda config` (#13076)

conda/cli/find_commands.py, news/13062-find-commands-permission-error, tests/cli/test_find_commands.py
See https://github.com/conda/conda/pull/13086#discussion_r1321992688
=> Catch `NotADirectoryError`

conda/base/constants.py, news/13095-wasm-platforms
This adds two new platforms to conda's list of known platforms, to unblock some of the [experimental work happening on emscripten-forge](https://github.com/emscripten-forge/recipes/issues/293). Names are derived from what CPython and Rust have chosen to use.
=> Add emscripten-wasm32 and wasi-wasm32 platforms to known platforms

conda/cli/main_remove.py, news/13019-conda-remove-all-json, tests/cli/test_subcommands.py
Fix https://github.com/conda/conda/issues/13019
Print "Remove all packages in environment" ~~to stderr to not pollute the json output~~ only when `--json` isn't used.
=> Fix conda remove all json

tests/data/conda_format_repo/linux-64/current_repodata.json, tests/data/conda_format_repo/linux-64/repodata.json, tests/data/conda_format_repo/osx-64/current_repodata.json, tests/data/conda_format_repo/osx-64/repodata.json, tests/data/conda_format_repo/win-32/current_repodata.json, tests/data/conda_format_repo/win-32/repodata.json, tests/data/conda_format_repo/win-64/current_repodata.json, tests/data/conda_format_repo/win-64/repodata.json
Some of the test suite repository checksums were incorrect, matching the .tar.bz2 versions of those packages. This makes it impossible to install those `.conda`-format packages in tests. Fixed by running conda-index and preserving the packages that are only in index.json but not on disk used for solver tests.
=> reindex test repository, fixing checksums

conda/gateways/repodata/__init__.py, tests/gateways/test_jlap.py
Follow-up on #13056. Is it better to use log.warning() over warnings.warn()?
=> prefer log.warning() in conda.gateways.repodata

docs/source/user-guide/configuration/use-condarc.rst
Since recently, the filename that can be used in `$CONDARC` is limited. Before, any file was accepted.
=> Clarify content of $CONDARC

conda/cli/conda_argparse.py, conda/common/_os/linux.py, conda/core/portability.py, conda/gateways/disk/create.py, conda/misc.py, conda/models/enums.py, conda/testing/__init__.py, tests/core/test_solve.py, tests/gateways/test_repodata_lock.py, tests/test_misc.py
Consistently use the `on_linux`, `on_mac`, and `on_win` constants. Removed some remaining Python 2.7 fallback codes.
=> Enforce `on_linux`, `on_mac`, and `on_win` usage and remove some Python 2.7 code

pyproject.toml, tests/test_activate.py
Yet another attempt to resolve flaky activation tests (see https://github.com/conda/conda/pull/13170).
Xref https://github.com/conda/conda/pull/13181
=> Addressing flaky `pexpect` parsing

conda/exports.py, news/13194-deprecate-fetch_index
Mark `conda.exports.fetch_index` for deprecation in favor of `conda.core.index.fetch_index`.
Xref #13192
=> Deprecate `conda.exports.fetch_index`

conda/exports.py, conda/models/dist.py, conda/models/match_spec.py, news/13193-deprecate-IndexRecord, tests/test_plan.py
Xref https://github.com/conda/conda/issues/13192
=> Deprecate `conda.models.dist.IndexRecord`

conda/cli/conda_argparse.py, conda/cli/main_mock_activate.py, conda/cli/main_mock_deactivate.py, news/13191-add-activate-to-help, tests/test_activate.py
Add two mock entries to the configure_parser_init() so the `activate` and `deactivate` shell commands are displayed in the --help.
Before:
```
$ conda --help
...
commands:
The following built-in and plugins subcommands are available.
COMMAND
clean             Remove unused packages and caches.
compare           Compare packages between conda environments.
config            Modify configuration values in .condarc.
content-trust     See `conda content-trust --help`.
create            Create a new conda environment from a list of specified packages.
doctor            Display a health report for your environment.
env               See `conda env --help`.
info              Display information about current conda install.
init              Initialize conda for shell interaction.
install …
```
=> Add (de)activate to --help command list

conda/base/context.py, news/context-fetch-threads
Would always be the default of 5 even if `CONDA_DEFAULT_THREADS` was set. IIRC I was also unable to set `fetch_threads` in `~/.condarc`?
What is the correct precedence? I think when default threads is overridden, then all other thread counts must be set or else they equal default threads. Otherwise the individual tunables should win out.
We could try to preserve a distinction between 0 (use DummyExecutor, do not use threading at all), 1 (use a single real Thread), and None (pick a default based on testing or core count/system resources). The current code doesn't seem well suited for that.
=> Fix CONDA_FETCH_THREADS parameter

dev/linux/integration.sh, dev/linux/unit.sh, dev/macos/integration.sh, dev/macos/unit.sh
The Linux and macOS tests are not properly detecting duration files:
https://github.com/conda/conda/actions/runs/6709237086/job/18231881358?pr=13246#step:3:158
https://github.com/conda/conda/actions/runs/6709237086/job/18231877310?pr=13246#step:3:91
=> Fix missing envvar for durations file

tests/test_create.py, tests/test_export.py
libmamba-1.5.3 corrected certain known issues resulting in tests marked as `xfail(strict=True)` starting to fail. We need to correct this before being able to merge `23.10.x` back into `main` (https://github.com/conda/conda/pull/13286).
=> Adjustments for libmamba-1.5.3 fixes

tests/cli/__init__.py, tests/cli/conftest.py
Followup to https://github.com/conda/conda/pull/13291
Fixtures need to be defined in the `conftest.py` (not `__init__.py`) to be discoverable for tests within that submodule.
Explicitly targeting the `forward-23.10.0` branch so we can confirm this works for `23.10.x`.
I have tested this locally by defining the following test in `tests/cli/test_subcommands.py`:
```
def test_logging_level():
assert logging.getLogger("urllib3.connectionpool").getEffectiveLevel() == logging.ERROR
```
This test passes after moving the fixture to `conftest.py`.
=> Move `urllib3_logger_error` to `conftest.py`

tests/cli/test_subcommands.py, tests/test_export.py
These xfails were part of 23.10 before we cut conda-libmamba-solver 23.11. These are obsolete with the latest batch of releases (incl. libmambapy 1.5.3).
=> Remove outdated test xfails that are now xpass related to the conda-libmamba-solver release

conda/_vendor/cpuinfo/__init__.py, conda/base/context.py, news/13313-deprecate-cpuinfo
=> Deprecate `conda._vendor.cpuinfo`

tests/test_create.py, tests/test_misc.py
Comes from https://github.com/conda/conda-libmamba-solver/pull/370
- Apparently https://github.com/conda/conda-libmamba-solver/commit/671b9c1bbb8d7c4d4e237cac17ad2cd3f5870aa1 fixed this test so it's now passing and making CI fail in `conda/conda-libmamba-solver`.
- Under some circumstances, a `PackageCacheData` entry can have a null `url` field which breaks a test.
=> Allow `test_install_features` to xpass and other test patches

conda/_vendor/distro.py, conda/base/context.py, news/13317-distro, pyproject.toml, recipe/meta.yaml
=> Deprecate `conda._vendor.distro` in favor of `distro`.

tests/conda_env/test_cli.py
https://github.com/conda/conda/pull/12984 results in many tests running twice, potentially on the same runner and sequentially. This causes such tests to fail if they, e.g., leave behind a statically named environment.
Combine `env_name_1` and `env_name_2` fixtures into a new (and simpler) `env1` fixture.
Remove unused `escape_for_winpath` and `remove_env_file`.
=> Fix failing tests due to env name collisions

conda/testing/helpers.py
Part of the (obsessive) research with non-determinism at https://github.com/conda/conda-libmamba-solver/issues/317.
I don't think this changes anything in that issue, but since it doesn't hurt I guess we can just have it. This is only part of our testing infra, so no news needed.
=> Sort JSON output in temporary test channels

tests/test_create.py
As part of the Python 3.12 build out, pip was re-released as `23.3` (not `23.3.1`). This causes an inconsistency between classic and libmamba with the former choosing `23.3.1` and the latter choosing `23.3`.
<details>
<summary><code>conda create -n scratch --solver=classic jinja2=3.0.1 --dry-run</code></summary>
```
bzip2              pkgs/main/osx-arm64::bzip2-1.0.8-h620ffc9_4
ca-certificates    pkgs/main/osx-arm64::ca-certificates-2023.08.22-hca03da5_0
jinja2             pkgs/main/noarch::jinja2-3.0.1-pyhd3eb1b0_0
libffi             pkgs/main/osx-arm64::libffi-3.4.4-hca03da5_0
markupsafe         pkgs/main/osx-arm64::markupsafe-2.1.1-py311h80987f9_0
ncurses            pkgs/main/osx-arm64::ncurses-6.4-h313beb8_0
openssl            pkgs/main/osx-arm64::openssl-3.0.12-h1a28f6b_0
pip …
```
=> Fix `test_install_update_deps_only_deps_flags`

conda/plan.py, news/13357-conda-plan
- Fixes https://github.com/conda/conda-libmamba-solver/issues/393
- Fixes https://github.com/conda/conda-libmamba-solver/issues/386
Thanks to all the research done by @mbargull:
We need to use `reset_context` instead of `reset_context_default` to prevent he latter from clearing configurations coming from `.condarc` files (see https://github.com/conda/conda-libmamba-solver/issues/393 for details). We also need `callback` instead of `stack_callback`, because:
> 1. conda.base.context.ContextStack is broken
>     (pop/replace don't call self.apply).
> 2. conda.plan is the only consumer of ContextStack
>     => we know nothing else adds to the stack => no need for it.
> 3. We know always use default search_path => no need for distinctions.
=> Use `callback=reset_context` in `conda.plan`

README.md, news/13343-conda-update-docs
Add update instructions to the README and include instructions for updates in stages.
If the existing `conda` version is too far behind the newest one, a direct update isn't always possible. Documenting this use case will hopefully help users update to the newest version successfully.
=> Add conda update instructions to README

conda/testing/__init__.py, tests/test_create.py
Sometimes we expect conda_cli to raise an exception but we also wish to inspect the stdout/stderr. Currently that requires extra work:
```python
def test_foo(conda_cli: CondaCLIFixture, capsys: CaptureFixture):
with pytest.raises(DryRunExit):
conda_cli("create", "--name=foo", "--dry-run")
stdout, stderr = capsys.readouterr()
```
With the change here we can instead do:
```python
def test_foo(conda_cli: CondaCLIFixture):
stdout, stderr, code = conda_cli("create", "--name=foo", "--dry-run", catch=DryRunExit)
```
=> Add `raises` kwarg to `conda_cli`

docs/source/dev-guide/plugins/health_checks.rst, docs/source/dev-guide/plugins/index.rst
This doesn't show up in the docs because it was missing in a toctree.
=> Show conda doctor health checks in plugin docs.

conda/testing/__init__.py, tests/test_create.py
xref: https://github.com/conda/conda/issues/13292
I decided to just delete the test, "test_noarch_python_package_reinstall_on_pyver_change" because it does not make sense to have around any more. It is probably very seldom that users are actually switching major Python versions and this test is very slow to run.
=> Refactoring tests for `test_create.py`

docs/source/user-guide/concepts/packages.rst, docs/source/user-guide/getting-started.rst, docs/source/user-guide/tasks/manage-environments.rst
This might also need to be checked on the docs.anaconda.com side, to make sure the links correctly redirect for all the older versions of the conda docs. Especially for high traffic pages like the getting started guide!
I also noted that the 404 page on https://docs.anaconda.com/anaconda/install/ doesn't render for me in Safari, but that can't be fixed here.
=> Fix deep links to Anaconda docs.

conda/activate.py, conda/base/context.py, conda/cli/main_config.py, conda/cli/main_package.py, conda/common/compat.py, conda/common/configuration.py, conda/common/io.py, conda/core/initialize.py, conda/core/link.py, conda/core/solve.py, conda/exports.py, conda/gateways/connection/session.py, conda/gateways/disk/create.py, conda/gateways/disk/delete.py, conda/gateways/subprocess.py, conda/models/match_spec.py, conda/models/package_info.py, conda/models/version.py, conda/resolve.py, conda/testing/integration.py, conda_env/env.py, conda_env/specs/binstar.py, news/13433-re-enable-pyupgrade-via-ruff, pyproject.toml, tests/core/test_initialize.py, tests/core/test_solve.py, tests/gateways/disk/test_permissions.py, tests/test_create.py
#13272 replaced black + pyupgrade via ruff format, but forgot to actually enable the pyupgrade rules for ruff.
This PR enables pyupgrade via ruff again and applies it.
=> Re-enable pyupgrade via ruff

conda/env/cli/__init__.py, tests/cli/test_env.py, tests/env/test_env.py
Followup to #13168
Missed updating a few HTTP urls pointing to the old `tests/conda_env` path.
And remove empty `conda.env.cli` submodule.
=> Correct HTTP path to `conda_env` test data and remove empty `conda.env.cli` submodule

conda/testing/helpers.py
This is needed for https://github.com/conda/conda-libmamba-solver/pull/414, which identifies a bug in how we export synthetic repodata to disk. `PackageRecord.timestamp` returns a `float` in seconds, but the JSON repodata should have an `int` in milliseconds. `TimestampField` has the necessary logic but it's not active by default; we are simply flipping that `in_dump` value so `PackageRecord.dump()` includes it.
=> ensure `PackageRecord.timestamp` is dumped in milliseconds

conda/gateways/repodata/__init__.py, news/repodata-lock-api
Small change originating from https://github.com/conda/conda/tree/13120-jlap-benchmark
Add `self.lock()` as a context manager instead of two-step open/lock.
=> Improve repodata lock API

tests/test_create.py
With https://github.com/conda/conda-libmamba-solver/pull/423, conda-libmamba-solver will now load `pkgs_dirs` when invoked in offline mode. Update the test to reflect so.
=> update `test_offline_with_empty_index_cache` for libmamba

conda/core/package_cache_data.py, conda/testing/__init__.py, conda/testing/integration.py, news/13511-tmp_pkgs_dir, tests/cli/test_main_clean.py, tests/core/test_package_cache_data.py, tests/test_create.py
Alternative solution to issue first identified in in https://github.com/conda/conda-libmamba-solver/pull/423#issuecomment-1898149457 and then https://github.com/conda/conda-libmamba-solver/pull/426.
Cherry picked from https://github.com/conda/conda/pull/13162 for easier review (and so this can be merged sooner).
Adds a new fixture `tmp_pkgs_dir` that mocks `context.pkgs_dirs` to only return our temporary cache.
=> Introducing `tmp_pkgs_dir` fixture

conda/gateways/repodata/__init__.py, news/no-cache-control, tests/gateways/test_repodata_gateway.py
I noticed this while using conda-build. Probably this is mainly an issue with older cache that contained the "save cache-control as None" bug, that we have also fixed by not writing bad cache state.
=> allow None for cache-control header, interpret as 0

CHANGELOG.md, conda/base/context.py, conda/cli/helpers.py, conda/gateways/repodata/__init__.py, tests/gateways/test_jlap.py
Use NULL in argparse default value to avoid argparse overriding config file or environment variable.
Fix #13528
=> Set `--use-repodata-zst` argument as `NULL`, rename `no_repodata_zst` to `use_repodata_zst`

docs/source/user-guide/concepts/conda-plugins.rst, pyproject.toml, recipe/meta.yaml
Add zstandard as a runtime dependency (was transitively included via conda-package-handling / streaming). Used to fetch repodata.
=> add zstandard as a run dependency

.github/workflows/builds-review.yaml, .github/workflows/tests.yml
Now that conda 24.1.0 has been released with Python 3.12 support we shouldn't need the `--no-test` argument for our canary builds anymore.
=> Remove `--no-test` from canary builds

conda/cli/main_rename.py, news/13565-conda-can-rename-while-inactive
Fixes https://github.com/conda/conda/issues/11850
=> Enable `conda rename` to not throw a `TypeError` when conda is not activated

conda/auxlib/compat.py, conda/base/context.py, conda/cli/main.py, conda/common/constants.py, conda/deprecations.py, conda/gateways/logging.py, news/13568-import-activate-perf, tests/test_deprecations.py
Avoid some imports to speed up `conda activate`.
Fixes gh-13567.
| `python`<br />`=3.8.18`,<br />`ruamel.yaml`<br />`=0.16.12` | `python`<br />`=3.11.7`,<br />`ruamel.yaml`<br />`=0.16.12` | `python`<br />`=3.8.18`,<br />`ruamel.yaml` <br /> `=0.18.5` | `python`<br />`=3.11.7`,<br />`ruamel.yaml`<br />`=0.18.5` | `python`<br />`=3.8.18`,<br />`ruamel.yaml` <br /> `=0.18.6` | `python`<br />`=3.11.7`,<br />`ruamel.yaml`<br />`=0.18.6` | changes |
|-------|-------|-------|-------|-------|-------|-------|
| 0.089 | 0.093 | 0.093 | 0.098 | 0.090 | 0.95 | base commit 59af01b from `main` |
| 0.084 | 0.088 | 0.089 | 0.093 | | | `Avoid costly .gateways.logging import for activate` |
| 0.086 | 0.091 | 0.091 | 0.096 | | | `Avoid costly argparse import for activate` |
| 0.086 | 0.090 | 0.090 | 0.095 …
=> Optimize import time for `conda activate`

conda/gateways/repodata/jlap/fetch.py, news/13558-bad-zst-fallback, tests/core/test_solve.py, tests/gateways/test_jlap.py
=> Catch ZstdError in jlap/repodata.json.zst handling

conda/gateways/repodata/jlap/fetch.py, news/13573-skip-zst-on-4xx
"Mark format as unavailable if code is in the 400's" 
This is about how it will look, but I feel this logic is not correct on the first commit. Do we need more than True/False? Should we show a different error if the /request/ type was `GET` or `Partial GET`?
Fix #13573
=> change retry logic for 400 <= status < 500

conda/exception_handler.py, news/13531-keyboardinterrupt-traceback
=> Pass traceback, not str, to exception formatter.

tests/cli/test_main_remove.py, tests/test_solvers.py
In https://github.com/conda/conda-libmamba-solver/pull/435, support for the use of wildcards with the `remove` command is added to the libmamba solver. The accompanying test, however, is not specific to the libmamba solver, but rather can be applied to any solver. In the spirit of moving towards a compliance suite of tests, this PR attempts to upstream the test into `conda`.
=> Add wildcard `conda remove` test

pyproject.toml
We wish to dismiss messages like the following from PRs:
Xref https://github.com/conda/conda-build/pull/5186
=> Ignore `TYPE_CHECKING` imports in coverage reports

conda/cli/install.py, news/13611-report-revisions
`conda install --revision <idx>` doesn't report any progress until the result is obtained. This led me to thinking that it was stuck and didn't work. I'm adding the same Spinners we have for the normal solver operation.
=> Report progress while installing from --revision

conda/auxlib/logz.py, news/13628-fix-auxlib-stringify-contenxt_max_len
This addresses the excess resource usage observed in gh-13541.
Essentially, the whole `repodata.json` is parsed via `requests.Response.json` and then dumped into a formatted string -- with both parts allocating multiple GB in RAM for large channels like `conda-forge`.
All this happens in a context only for (intended) debug logging output which is meant to constrain the log message length (and in turn memory usage); the proposed changes just apply the intended size constraints.
(It only handles the severe run time impact but doesn't fix the underlying cause for gh-13541.)
- ~~[ ] Add / update outdated documentation?~~
=> Fix auxlib.logz.stringify excess memory allocation

docs/source/dev-guide/plugins/settings.rst
Fixes a broken link in the settings plugin hook documentation.
=> Fixing broken link in settings plugin documentation

docs/requirements.txt
`boltons` is missing as a docs requirement, which is making documentation pages not render correctly (see screenshots below for examples):
_stable (this is what the docs should look like)_
_latest (currently broken, will be fixed by this PR)_
=> Add `boltons` to `requirements.txt` file for conda docs

MANIFEST.in, news/13684-remove-setuptools-remainings, recipe/meta.yaml
conda once was once packaged by setuptools + wheel extension.
#12509 did the switch to hatch, which has its own wheel builder: https://github.com/pypa/hatch/blob/master/backend/src/hatchling/builders/wheel.py#L160
Thus the wheel package (containing the setuptools wheel extension) and the MANIFEST.in file (describes what setuptools should include) can be removed. The hatch file selection is not based on the MANIFEST.in, see https://hatch.pypa.io/1.9/plugins/builder/wheel/#default-file-selection
=> Remove unused setuptools remainings

.github/TEST_FAILURE_REPORT_TEMPLATE.md, .github/workflows/tests.yml, conda/testing/fixtures.py, tests/cli/test_env.py, tests/cli/test_main_remove.py
Adds an environment variable to control the solvers exported by the fixture. It expects a comma separated list of strings (e.g. `libmamba,classic`).
<details>
<summary>Timings in main</summary>
Integration tests for Windows & Linux take almost 1h for each job if the default channel is conda-forge.
| Windows Integration 1 | `main` |
|-----------------------|--------|
| tests/cli/test_env.py::test_conda_env_create_http[classic] | 526.82s call |
| tests/cli/test_main_remove.py::test_remove_globbed_package_names[classic] | 282.98s call |
| tests/test_create.py::test_dont_remove_conda_2[classic] | 257.13s call |
| tests/cli/test_env.py::test_create_valid_env_with_conda_and_pip_json_output[classic] | 208.85s call |
| tests/test_create.py::test_conda_pip_interop_pip_clobbers_conda[classic] | …
=> Do not run solver=classic tests in PRs

conda/activate.py
Creating a copy of `os.environ` is expensive to do when it doesn't serve any purpose.
Split out from https://github.com/conda/conda/pull/13620
=> Remove `os.environ` copy from `conda.activate._Activator`

conda/activate.py, news/13720-deprecate-activate-testing-helpers, tests/test_activate.py
Deprecating redundant helper functions:
- `conda.activate._Activator.add_export_unset_vars`, use `conda.activate._Activator.get_export_unset_vars` instead
- `conda.activate.JSONFormatMixin.get_scripts_export_unset_vars`, use `conda.activate._Activator.get_export_unset_vars` instead
Deprecate unused keyword argument:
- `conda.activate._Activator._get_path_dirs(extra_library_bin)`
Move testing helper function to test_activate.py:
- `conda.activate._Activator.get_scripts_export_unset_vars`, for testing only
Split out from https://github.com/conda/conda/pull/13620
=> Deprecate redundant helper functions and move testing helper function to test suite

tests/test_activate.py
Using `monkeypatch.setenv` results in less nesting/code complexity.
Split from https://github.com/conda/conda/pull/13620
=> Replace `env_var`/`env_vars` in `test_activate.py` with `monkeypatch.setenv`

tests/test_activate.py
The `skipif` markers for whether a `bash` flavored `test_activate.py` test can run is overly verbose. This creates reusable markers for easy usage.
<table>
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td>
```python
@pytest.mark.skipif(
bash_unsupported(),
reason=bash_unsupported_because(),
)
def test_foo(...):
...
```
</td>
<td>
```python
@skip_unsupported_bash
def test_foo(...):
...
```
</td>
</tr>
<tr>
<td>
```python
@pytest.mark.skipif(
bash_unsupported_win(),
reason=bash_unsupported_win_because(),
)
def test_bar(...):
...
```
</td>
<td>
```python
@skip_unsupported_posix_path
def test_bar(...):
...
```
</td>
</tr>
</table>
Split from https://github.com/conda/conda/pull/13620
=> Simplify bash unsupported markers

conda/cli/install.py, conda/cli/main_create.py, conda/cli/main_install.py, conda/cli/main_update.py, news/13751-deprecate-mkdir
There are two ways to create a new environment by listing the packages to install:
1. `conda create ...` (recommended and documented)
2. `conda install --mkdir ...` (not recommended and undocumented)
Here we remove `--mkdir` in favor of the more explicit `conda create`.
Originally introduced in `conda 2.3` (see https://github.com/conda/conda/commit/ad37b47cc1cdd98fad44f937cb3c84eda73a0723)
=> Deprecate `-m`/`--mkdir` from `conda install`

tests/test_activate.py
Almost every test in `test_activate.py` uses the `reset_environ` fixture. Furthermore there's nothing wrong with the remaining tests to also use the fixture to clear out any conda related environment variables prior to running a test.
Split out from https://github.com/conda/conda/pull/13620
=> Make `reset_environ` an `autouse` fixture

tests/test_activate.py
Both `CONDA_SHLVL` and `CONDA_PREFIX` are cleared by `reset_environ`:
https://github.com/conda/conda/blob/32ea42b9e0b8037ff4c59277738295f2b48553c9/tests/test_activate.py#L162-L172
So these `monkeypatch.setenv` calls are redundant and can be removed.
=> Remove redundant `monkeypatch.setenv`

conda/deprecations.py
If modules are loaded (e.g. lazily loaded modules) while iterating over `sys.modules` a `RuntimeError` is thrown. We avoid this by creating a copy of the module.
Resolves https://github.com/conda/conda/issues/13754
=> Avoid `RuntimeError` in module detection

tests/fixtures_jlap.py, tests/gateways/test_connection.py
=> Adding test for "Accept-Ranges: none" scenario with partial downloads

conda/base/context.py, conda/common/_logic.py, conda/core/package_cache_data.py, conda/core/path_actions.py, conda/core/solve.py, conda/gateways/disk/__init__.py, conda/gateways/disk/create.py, conda/gateways/disk/delete.py, conda/gateways/disk/permissions.py, conda/gateways/disk/test.py, conda/gateways/disk/update.py, conda/gateways/logging.py, conda/gateways/subprocess.py, conda/plan.py, news/13732-log-trace
This is a long-standing issue that prevents `conda` from being used as a library. We can't test `SubdirData` in isolation unless we first call `conda.gateways.logging.initialize_logging` which, among other things, patches `logger.Logger` to have a new method `.trace()` which essentially does `Logger.log(5, ...)`.
I recommend we deprecate it and stop using it. This is the first step to allow easier testability / library usage in other projects.
=> Stop using `log.trace(...)`

tests/plugins/test_manager.py
The recent `pluggy 1.5.0` release corrected an issue first introduced in `pluggy 1.0.0` where when plugins are disabled `plugin_manager.get_plugins()` returns `{None}` instead of the expected `set()`. See https://github.com/pytest-dev/pluggy/pull/481.
=> Fix `pluggy 1.5.0` failure in tests

.github/workflows/tests.yml
See https://github.com/conda-incubator/setup-miniconda/issues/344.
Explicitly using macos-13 to ensure we do use Intel runners for osx-64 package building.
We will need https://github.com/conda-incubator/setup-miniconda/pull/345 to work around issues with the underlying conda-build action.
=> Explicitly use macos-13 for macOS Intel runners

.github/workflows/tests.yml
We've recently had errors like `Error: Codecov token not found. Please provide Codecov token with -t flag.` in test outputs and we should simply set the token we have explicitly. E.g. https://github.com/conda/conda/actions/runs/8835632377/job/24288470874#step:11:38
=> Pass `CODECOV_TOKEN` to codecov GitHub Action step.

conda/cli/install.py, conda/misc.py, conda/plan.py, news/12421-deprecate-conda.plan, tests/test_plan.py
Moves functions still in use (to where they are used):
- `conda.plan._get_best_prec_match` → `conda.misc._get_best_prec_match`
- `conda.plan.revert_actions` → `conda.cli.install.revert_actions`
Deprecates unused functions:
- `conda.plan.print_dists`
- `conda.plan.display_actions`
- `conda.plan.add_unlink`
- `conda.plan.add_defaults_to_specs`
- `conda.plan.execute_actions`
- `conda.plan._plan_from_actions`
- `conda.plan._inject_UNLINKLINKTRANSACTION`
- `conda.plan._handle_menuinst`
- `conda.plan.install_actions`
- `conda.plan.get_blank_actions`
- `conda.plan` as an entrypoint
Extends #13869
Resolves https://github.com/conda/conda/issues/12421
=> Deprecate `conda.plan`

tests/core/test_subdir_data.py, tests/gateways/test_connection.py, tests/test_create.py
`make_temp_env` has been [deprecated since 24.1.0](https://github.com/conda/conda/pull/13511).
Cherry picked from #12771
=> Removing remaining usage of deprecated `make_temp_env`

conda/cli/main_remove.py
Hello! I noticed a typo on [this page](https://conda.io/projects/conda/en/latest/commands/remove.html) and wanted to submit a quick fix for it. For the 3,000+ times `environment` shows up in the code base, I think this is literally the only time it's spelled wrong, which is amazing.
=> Small typo fix

tests/cli/test_main_info.py, tests/conftest.py
Testing for the upcoming `conda info --all` deprecation in favor of `conda info --verbose`.
Split from #12771
=> Fix `conda info --all` tests to reflect deprecation

conda/cli/install.py, conda/cli/main_config.py, conda/exceptions.py, tests/cli/test_config.py, tests/cli/test_main_config.py
`main_config` previously defined a god-function (and still does). This made it difficult to programmatically interact with the `conda config` functionality.
Here we extract individual components from the god-function (e.g., `get_key`, `set_key`, `remove_item`, `remove_key`, `read_rc`, `write_rc`, `set_keys`). These can then be easily called from other parts of conda as well as from the god-function.
Cherry picked from https://github.com/conda/conda/pull/12771
=> Refactor `main_config` into a modular API

docs/source/user-guide/configuration/settings.rst, news/13935-doc-truststore
On  #13075 I submitted a contribution to use the operating system certificate store. It got merged some months ago.
While the introduced feature had tests and basic docs it did not appear in the user guide.
This pull request just aims to complete the previous pull request adding a paragraph to the user guide.
I think it is relevant because for many corporate users behind an SSL proxy the `ssl_verify: truststore` option will make configuration and certificate management easier.
=> Document ssl_verify: truststore

conda/cli/main_list.py, news/13936-list-auth, tests/cli/test_main_list.py
I noticed that some of my `conda-meta/*.json` files have auth details in them. `conda list --explicit` will happily include the auth details in the URL by default IN PLAIN TEXT. For a file that is meant to be shared, I think that default option is too big of a security risk so in this PR:
- I changed the default behaviour so it does NOT print auth details.
- I add an `--auth` flag to `conda list` to opt-in including auth details (in case this is used internally with additional security measurements in place).
=> `conda list --explicit` should not include auth details by default

conda/core/envs_manager.py, conda/core/link.py, conda/core/path_actions.py, conda/core/prefix_data.py, conda/core/solve.py, conda/exception_handler.py, conda/gateways/disk/__init__.py, conda/gateways/disk/delete.py, conda/gateways/disk/permissions.py, conda/gateways/logging.py, conda/gateways/repodata/__init__.py, conda/gateways/repodata/jlap/fetch.py, conda/misc.py, conda/trust/signature_verification.py, conda/utils.py, news/13963-warn-to-warning, tests/common/test_io.py, tests/core/test_envs_manager.py, tests/test_create.py
This replaces calls to `logger.warn` with `logger.warning`. The former has been deprecated since Python 3.3 and generates `DeprecationWarning`s that can make output particularly in debugging and testing more noisy than necessary.
Sibling to conda/conda-build#5364.
As this is a purely internal change, I don't thing any of the following items apply.
However, it does remove the hack in gateways.logging to suppress the deprecation warnings.
Does that need special consideration?
@jezdez noted that the same issue is present in other repos in the ecosystem.
They may be addressed in a similar manner and in detail are the following:
=> Replace logger.warn w/ logger.warning

docs/source/index.rst
Since there are now M1-M4 available and Apple uses "Apple Silicon" themselves. Also move Apple Silicon before Intel chips now that there are no more Intel macs released.
=> Update download links to use "Apple Silicon"

conda/gateways/logging.py, news/13939-mask-token-logs
We currently obtain `TypeError` for calls like this:
```python
log.debug("My template message: %s", {"key": "value", "another": "valuable"}
```
because `TokenURLFilter` iterates over the dict and accidentally turns it into a 2-tuple. By the time the `%` template processes it, it doesn't have enough placeholders.
Instead, let's render the message first, and _then_ we process it for tokens.
=> Fix token filter in logging so it doesn't choke on iterable arguments

conda/activate.py, conda/base/context.py, news/13943-envvars-force-uppercase, tests/test_activate.py
resolves #13713 
Please also check #13904 and #13938 to see the other possible solutions for the linked issue.
This PR adds an `envvars_force_uppercase` flag. 
This flag defaults to `True` thereby justifying the current behavior of `conda` (i.e. uppercasing all environment variables).
When this flag is set to False, `conda` will only save preserved case variable names. 
The plan is to deprecate this flag (and therefore the uppercasing behavior) in the future.
=> Implement a `envvars_force_uppercase` flag defaulting to True

conda/base/constants.py, conda/base/context.py, news/13975-disallow-characters-windows
Closes https://github.com/conda/conda/issues/12558
These characters are problematic in Windows activation.
=> Disallow additional characters in prefix names for Windows

tests/test_activate.py
This was already part of https://github.com/conda/conda/pull/13784, but I'm going to need it for a clean conda-libmamba-solver 24.7 release.
The problem here is that [pytest supports conditions as strings in the `skipif`](https://docs.pytest.org/en/stable/reference/reference.html#pytest-mark-skipif-ref). If we simply pass a string (hoping it'll be truthy), you'll meet [this error](https://github.com/conda/conda-libmamba-solver/actions/runs/9857580438/job/27216989443):
```
ERROR tests/test_activate.py::test_activate_deactivate_modify_path[bash] - Failed: Error evaluating 'skipif' condition
bash: something went wrong while running bash, output:
b''
^
SyntaxError: invalid syntax
```
The fix is to convert it to an explicit `bool`.
=> Fix pytest issue: use bool explicitly to avoid unparsable condition string

conda/gateways/connection/download.py, news/13969-hash-case, tests/test_fetch.py
`rattler` returns `sha256` with uppercase alpha characters. Python's `hashlib.hexdigest()` returns it with lowercase. Either works and both are ok since SHA256 should be case insensitive. We just need to make our comparisons insensitive too.
=> Checksum comparisons should be case insensitive - use bytes directly

conda/plugins/manager.py, news/13846-debug-plugin-exceptions
Closes https://github.com/conda/conda/issues/13742
This is the only way I came up with. Not too clean but not horrible either, I think?
We cannot always pass `exc_info` because that will muddle the warnings with the traceback. Instead we only do it depending on the verbosity. With `-vv` (INFO) you'll get the traceback:
```
Error while loading conda entry point: conda-libmamba-solver (name 'AAAY' is not defined)
File "/workspaces/conda/conda/plugins/manager.py", line 140, in load_entrypoints
plugin = entry_point.load()
^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.12/importlib/__init__.py", …
```
=> report traceback on plugin loading for certain verbosities

conda/shell/conda.xsh, news/14047-update-xonsh-support
Added support xonsh >= [0.18.0](https://github.com/xonsh/xonsh/releases/tag/0.18.0)
=> Update conda.xsh: support xonsh >= 0.18.0

tests/test_plan.py
Replace `env_var` usage in `tests/test_plan.py` with `monkeypatch.setenv`.
The largest change is very superficial, changing unindented multiline strings into `"\n".join(...)` multiline strings instead for better code indentation.
Xref #14095
=> `test_plan.py`: Replace `env_var` with `monkeypatch.setenv`

tests/test_fetch.py
Replace `env_var` usage in `tests/test_fetch.py` with `monkeypatch.setenv`.
Xref #14095
=> `test_fetch.py`: Replace `env_var` with `monkeypatch.setenv`

conda/exports.py, conda/gateways/disk/delete.py, news/14094-cleanup-conda.gateways.disk.delete, tests/gateways/disk/test_delete.py
`conda.gateways.disk.delete` has evolved extensively in the past leaving old code and legacy arguments that are no longer in use. Removed and deprecated as applicable.
=> Remove & deprecated unused args/helpers from `conda.gateways.disk.delete`

conda/testing/__init__.py, news/14093-deprecate-make_temp_envs_dir, tests/env/test_create.py, tests/env/test_env.py, tests/env/utils.py
Implement a new fixture, `tmp_envs_dir`, mirroring the `tmp_pkgs_dir` fixture to replace `make_temp_envs_dir` which required additional manual setup.
=> Deprecate `tests.env.utils.make_temp_envs_dir`

conda/activate.py, conda/common/path.py, conda/utils.py, news/14068-path-identity, tests/common/test_path.py, tests/test_activate.py, tests/test_utils.py
Move `conda.activate.path_identity` to `conda.common.path.path_identity` (marking original as deprecated). Mark `conda.utils.path_identity` as deprecated in favor of the updated `conda.common.path.path_identity`.
Split from https://github.com/conda/conda/pull/14029
=> Move `path_identity` to `conda.common.path`

tests/test_exceptions.py
Replace `env_var` usage in `tests/test_exceptions.py` with `monkeypatch.setenv`.
The largest change is very superficial, changing unindented multiline strings into `"\n".join(...)` multiline strings instead for better code indentation.
Xref #14095
=> `test_exceptions.py`: Replace `env_var` with `monkeypatch.setenv`

recipe/meta.yaml
Follow-up to #14077 (af37e285909afe068cdad7e9c8481d915e9d5a19) which removed the `appdirs` dependency, which now triggers an import error that prevents canary builds from successfully building. See https://github.com/conda/conda/actions/runs/10298401199/job/28503483287 for more details.
Refs #14077.
=> Add `platformdirs` to host section in recipe to fix canary builds

conda/activate.py, conda/base/constants.py, conda/common/compat.py, conda/common/io.py, news/14144-deprecate-unused-compat, tests/common/test_compat.py, tests/test_activate.py
Deprecates:
- Deprecate `conda.activate.ensure_binary`
- Deprecate `conda.activate.ensure_fs_path_encoding`
- Deprecate `conda.common.compat.six_with_metaclass`
- Deprecate `conda.common.compat.open`
- Deprecate `conda.common.compat.ensure_unicode`
- Deprecate `conda.common.compat.ensure_fs_path_encoding`
- Deprecate `conda.common.compat.FILESYSTEM_ENCODING`
=> Deprecate unused compat functions

dev/start
While recreating my devenv I discovered a minor bug in the start script. If the miniconda installer was already downloaded the if clause would fail with the following error:
```
./dev/start:202: parse error: condition expected: =
```
We correct the issue by inverting the conditional check.
=> Fix miniconda downloading in `. ./dev/start`

conda/cli/main_remove.py, news/14173-update-main-remove-and-env-export-test, tests/cli/test_env.py
While working on [Alias `conda env remove` command to `conda remove --all` # 13977](https://github.com/conda/conda/pull/13977) I came across a mysterious test failure in `tests/cli/test_env.py::test_env_export_json`. It appeared that the `conda env export` command was previously able to access a deleted environment (when using the unaliased `conda env remove`), which showed that `conda env remove` was not as robust as `conda remove` (this has been reported in #11092).
This PR:
- updates `main_remove.py` to no longer remove empty parent directories when deleting environments, since this could lead to some unpleasant surprises for a user's conda setup
- edits `tests/cli/test_env.py::test_env_export_json` to use the `path_factory` fixture, which removes the need for invoking the `conda env …
=> Fix `test_env_export_json` test and update `main_remove.py` to not delete parent empty directories

conda/common/path.py, news/14189-deprecate-private-environment
Found two more private conda environment references that are not in use. Marking as deprecated.
=> Deprecate unused private env helper functions

conda/base/context.py, conda/common/path.py, conda/core/initialize.py, conda/core/link.py, conda/core/path_actions.py, conda/testing/integration.py, news/14188-BIN_DIRECTORY, tests/core/test_initialize.py, tests/core/test_path_actions.py, tests/test_create.py
We previously offered a `get_bin_directory_short_path()` which evaluated to `Scripts` on Windows and `bin` on Unix. This is better suited as a constant. We opt to move `conda.testing.integration.BIN_DIRECTORY` to `conda.common.path.BIN_DIRECTORY` and deprecate `conda.common.path.get_bin_directory_short_path` in favor of this constant.
=> Deprecate `get_bin_directory_short_path()` in favor of `BIN_DIRECTORY`

pyproject.toml, tests/requirements-ci.txt
While debugging an ABI issue in `conda-build`'s test suite we found that `xdoctest` hasn't actually been testing anything for us since `pytest` by default only crawls the `tests` directory and not the source code itself.
Since it hasn't been doing anything for us we might as well just remove it and evaluate adding it back in a future effort.
Xref https://github.com/conda/conda-build/pull/5471
=> Remove `xdoctest`

conda/cli/install.py, conda/cli/main_search.py, conda/common/io.py, conda/core/link.py, conda/core/solve.py, conda/env/installers/pip.py, conda/notices/fetch.py, conda/plugins/reporter_backends/console.py, conda/plugins/reporter_backends/json.py, conda/plugins/types.py, conda/reporters.py, news/14206-spinner-support-reporter-backends, tests/cli/test_main_search.py, tests/plugins/reporter_backends/test_console.py, tests/plugins/reporter_backends/test_json.py, tests/plugins/test_post_solves.py, tests/plugins/test_pre_solves.py
xref: #13775 
This pull request makes it so that the "Spinner" component can be switched out via the `reporter_backends` plugin hook.
=> Make Spinner configurable via reporter backends plugin hook

.github/CODEOWNERS
This moves the repo to the new smaller scope "conda-maintainers" team. See #13526 for more details.
=> Transition to new conda-maintainers team.

README.md, docs/source/user-guide/concepts/environments.rst, docs/source/user-guide/getting-started.rst, docs/source/user-guide/install/index.rst, docs/source/user-guide/install/linux.rst, docs/source/user-guide/install/macos.rst, docs/source/user-guide/install/windows.rst
The main changes is the update of the link for miniforge, now pointing to the relevant part of the conda-forge website rather than the GitHub repository.
I am also adding a reference to miniforge in the Readme.
=> Add references to miniforge in Readme and update links to miniforge in documentation.

conda/base/context.py
The following code block will always evaluate to `use_only_tar_bz2 = False` so we can remove it (plus none of our subcommands supports providing a `--use-only-tar-bz2` flag anyhow):
https://github.com/conda/conda/blob/8ba894077c7ddfbcc4e258dc4cefcd1fae5a460d/conda/base/context.py#L972-L975
=> Remove no-op `context.use_only_tar_bz2` logic

tests/base/test_context.py
Replace `env_var` usage in `tests/base/test_context.py with `monkeypatch.setenv`.
Xref https://github.com/conda/conda/issues/14095
=> `test_context`: Replace `env_var`/`env_vars` with `monkeypatch.setenv`

conda/activate.py, conda/cli/conda_argparse.py, conda/cli/main_commands.py, conda/cli/main_mock_activate.py, conda/cli/main_mock_deactivate.py, conda/shell/condabin/Conda.psm1, conda/shell/etc/fish/conf.d/conda.fish, docs/source/commands/commands.rst, news/14215-move-commands-subcommand, tests/cli/test_find_commands.py, tests/cli/test_main_commands.py
The `commands` subcommand is a tab-completion helper function and has long been hidden within the activation code as `conda shell.posix commands`. There is no need for this as the command produces entirely OS and shell agnostic output (a newline delimited list of available subcommands).
=> Deprecate `conda shell.posix commands` in favor of `conda commands`

conda/base/constants.py, conda/base/context.py, conda/cli/install.py, conda/cli/main_config.py, conda/core/subdir_data.py, conda/testing/notices/fixtures.py, news/14227-nodefaults, tests/base/test_context.py, tests/cli/test_config.py, tests/core/test_subdir_data.py, tests/notices/test_core.py
- Closes https://github.com/conda/conda/issues/14178
- Closes https://github.com/conda/conda/issues/12356
=> Leave `context.channels` empty by default

conda/base/context.py, conda/core/index.py, conda/exceptions.py, docs/source/user-guide/configuration/settings.rst, news/14176-denylist_channels-config, tests/base/test_context.py, tests/core/test_index.py
This adds a `denylist_channels` config option, which complements the already existing `allowlist_channels` config option.
Fix #14176.
=>  Add `denylist_channels` config option.

tests/cli/test_main_commands.py
While working on CLS tests (https://github.com/conda/conda-libmamba-solver/pull/524, https://github.com/conda/conda-libmamba-solver/pull/529) I've found that the recently added `test_commands` test does a poor job of handling test environments with additional conda plugins installed (e.g. `conda-build`).
=> Use plugin manager to get subcommands for `tests/cli/test_main_commands.py::test_commands`

.github/workflows/tests.yml, tests/plugins/test_subcommands.py
Fixes a broken test assertion that is currently make builds on the main branch fail.
=> Fixing broken test assertion for `tests.plugins.test_subcommands:test_help` (24.9.x)

.github/workflows/tests.yml, tests/plugins/test_subcommands.py
Fixes a broken test assertion that is currently make builds on the main branch fail.
=> Fixing broken test assertion for `tests.plugins.test_subcommands:test_help`

conda/gateways/disk/read.py, news/14317-pypi-names
Closes https://github.com/conda/conda/issues/14310
Not sure why we would want the conda name (or how that's obtained to begin with!) instead of the original Python name. This is causing the reproducibility problem seen in the linked issue.
=> `PrefixData(pip_interop_enabled=True)`: use Python name for non-conda packages

conda/models/match_spec.py
Closes https://github.com/conda/conda/issues/14328.
This presence of the "s" right next to "`class:`MatchSpec`" caused a formatting issue in the automated docs. Plus, the sentence was a little difficult to parse. This change removes the plural and hopefully makes things a bit more clear.
- ~[ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?~
=> Updated sentence for formatting issue and clarity

conda/misc.py, news/14338-deprecate-rel_path
=> Deprecate unused `conda.misc.rel_path`

conda/deprecations.py, news/14359-update-deprecated.action, tests/test_deprecations.py
Resolves https://github.com/conda/conda/issues/14355
Every positional argument in the conda CLI is either required or defaults to `None` or `[]`, so [checking to see if `values` exists](https://github.com/conda/conda/pull/14359/files#diff-55373dab266c863a6f3a85e6ed1700a8e532ca7c027f6650093e18fd0cb66c4dR229) avoids the activation of an unnecessary deprecation warning.
=> Update `deprecated.action()` to account for positional arguments with no value specified

.github/workflows/tests.yml, news/14375-fix-coverage-upload
The upload-artifact action excludes hidden files since version 4.4.0 by default.
This removes the `.coverage` file from the upload despite it being listed explicitly.
To remedy this, this PR sets the `include-hidden-files` input on the relevant upload-artifact uses in the tests workflow.
Fixes #14374.
=> Fix `.coverage` upload to codecov.

.github/workflows/tests.yml
A follow-up PR related to https://github.com/conda/conda/pull/14387
Xref https://github.com/conda/conda-build/pull/5537
Builds are failing (see example [here](https://github.com/conda/conda-build/actions/runs/11842587199/job/33001566121#step:4:44)) due to [`check_output()`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) returning a bytes object instead of a string; per discussion with @kenodegard , I've added `text=True` so that a `str` will be returned, and also a `.strip()` to avoid any potential extra whitespace.
=> Update `check_output()` call in `tests.yml`

conda/base/context.py, conda/cli/helpers.py, conda/cli/main_search.py, conda/core/index.py, conda/core/subdir_data.py, news/14405-bugfix-for-denylist-channels, tests/base/test_context.py, tests/cli/test_all_commands.py, tests/core/test_index.py, tests/models/test_channel.py, tests/test_create.py
=> `24.11.x` Fixes `denylist_channels` channel bug 🐛

tests/cli/test_conda_argparse.py, tests/test_create.py
- Fix subcommand sorting test introduced for compatibility with Python 3.12. This was introduced in #14402.
- Fix dependency drift in integration test. Previously discovered and fixed in 24.11.x in #14431.
=> Fix failing tests in main

.github/workflows/tests.yml, conda/testing/fixtures.py, news/14475-pythonpath, tests/test_install.py, tests/test_shell.py
Observed in https://github.com/conda/conda/pull/14170. 
`tests/test_shell.py::test_stacking` and `tests/test_install.py::test_windows_entry_point` rely on calls to `conda` subprocesses executed via the entry point (e.g. `$PREFIX/bin/conda`). As per the Python docs, this way of running a script only adds the parent directory of the script to `sys.path`, _instead_ of the working directory (which is added when we call `python` prompt, `python -c "some code"` or `python -m module`).
The different `sys.path` without the working directory misses our cloned `conda` copy, finding the "production" copy (e.g. latest release as installed in the test environmetn). We are not overwriting that one with `pip install` in CI for reasons related to shell initialization, IIRC.
Anyway, the fix is to set …
=> CI: Set PYTHONPATH=CONDA_SOURCE_ROOT

.github/workflows/tests.yml
`conda-build` is changing the default package format from `.tar.bz2` to `.conda`. The old `canary-release` action did not account for `.conda` packages and needs updating to handle this format for uploads.
Xref https://github.com/conda/actions/pull/250
Xref https://github.com/conda/actions/pull/251
=> Bump `canary-release`

tests/data/pkg_cache/__init__.py, tests/requirements-ci.txt
`setuptools 75.4.0` dropped their vendored `importlib_resources` in favor of the stdlib `importlib.resources` which is available since Python 3.9.
This change only impacts the test suite and has no impact on older conda versions so we opt to not include a news snippet.
=> Install `importlib_resources` for Python < 3.12

tests/test_create.py
Recent testing has shown the `tests/test_create.py::test_json_create_install_update_remove` test to be very flaky on Linux ARM and results in the test failing something like 90% of the time. The failure occurs when under network connection retries which are printed to stderr. So the proposed change is to stop testing for `assert not stderr`.
=> Ignore flaky stderr checks

conda/cli/main_env.py, news/14600-remove-configure_parser-None
Remove `conda.cli.main_env.configure_parser`'s support for passing in `sub_parsers=None` as used in `conda_env.cli.main` which has now been removed, see https://github.com/conda/conda/pull/14564.
Xref https://github.com/conda/conda/issues/14560
=> Remove `conda.cli.main_env.configure_parser(sub_parsers=None)`

tests/requirements-ci.txt
We have these packages in defaults now as well. The test matrix will correctly select to either install from defaults or conda-forge, which hopefully should prevent further bleeding over of branches.
- ~[ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda/blob/main/news/TEMPLATE)) for the next release's release notes?~
=> Install `pytest-split` and `pytest-xprocess` from defaults.

conda/testing/integration.py, news/14669-remove-running_a_python_capable_of_unicode_subprocessing
Xref https://github.com/conda/conda/issues/14560
Last deprecation to remove for `conda 25.3`.
=> Remove `conda.testing.integration.running_a_python_capable_of_unicode_subprocessing`

conda/core/link.py, news/144727-variant-install-report, tests/cli/test_main_install.py, tests/core/test_link.py
Fixes https://github.com/conda/conda/issues/13797
This PR adds a "REVISED" section the cli change report. A "REVISED" package is one where the version and channel and build number is the same, but the build variant has changed. 
For example, this might happen when updating the python version for an environment.
Previously, this would produce the result
```
$ conda create -n test-13797 python=3.10 numpy --yes
. . .
$ conda install -n test-13797 python=3.12
. . .
The following packages will be UPDATED:
python                         3.10.16-he725a3c_1_cpython --> 3.12.9-h9e4cc4f_1_cpython 
python_abi                                   3.10-6_cp310 --> 3.12-6_cp312 
The following packages will be DOWNGRADED:
numpy                               2.2.4-py310hefbff90_0 --> 2.2.4-py312h72c5963_0 …
```
=> Report package variant installation as a "REVISED" package (opposed to "DOWNGRADED")

conda/exports.py
Fix issue where `conda.exports.ANYTHING` would always return `None`.
Caught while testing `conda 25.9.x`.
=> Fix `conda.exports.__getattr__`

docs/environment.yml, news/15289_Bump_conda-libmamba-solver_from_24.11.0_to_25.4.0, pyproject.toml, recipe/meta.yaml, tests/requirements.txt
In Conda 25.9.0, some deprecated functionality that earlier versions of conda-libmamba-solver used was removed. While conda-libmamba-solver updated its logic and released 25.4.0, Conda kept the older lower bound of 24.11. As a result users could update Conda, but still get the older conda-libmamba-solver. This would lead to issues running Conda after. To fix this, bump the lower bounds of conda-libmamba-solver in Conda.
<hr>
Fixes https://github.com/conda/conda/issues/15287
=> Bump conda-libmamba-solver from 24.11.0 to 25.4.0
